//	HYPE.documents["Garmin_Cycling_rich_rotate_320x480adaptive_apr26_new"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l =
        "../resources/Garmin_Cycling",
      f = "Garmin_Cycling_rich_rotate_320x480adaptive_apr26_new",
      g = "garmincyclingrichrotate320x480adaptiveapr26new_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      true == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "gotomap",
        source:
          "function(hypeDocument, element, event) {\t\twindow.gotomap();\t\n\t\n}",
        identifier: "118",
      },
      {
        name: "openDSA_Link",
        source:
          "function(hypeDocument, element, event) {\twindow._hyb_ssp.openDSALink();\n\twindow._hyb_creative_sdk && window._hyb_creative_sdk.registerCustomBanner1Event();\t\n}",
        identifier: "847",
      },
      {
        name: "close",
        source:
          "function(hypeDocument, element, event) {_hyb_ssp.in_image_close();\n}",
        identifier: "848",
      },
      {
        name: "action1",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action1();\n}",
        identifier: "904",
      },
      {
        name: "action2",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action2();\n}",
        identifier: "905",
      },
      {
        name: "action3",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action3();\n}",
        identifier: "906",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        10: { p: 1, n: "prod_2.png", g: "724", t: "@1x" },
        2: { p: 1, n: "geo.png", g: "624", t: "@1x" },
        15: { p: 1, n: "prod_2_r.png", g: "875", t: "@1x" },
        "-2": { n: "blank.gif" },
        3: { p: 1, n: "b_elipse.svg", g: "707", t: "image/svg+xml" },
        11: { p: 1, n: "prod_1_r.png", g: "732", t: "@1x" },
        4: { p: 1, n: "b_arrow.svg", g: "709", t: "image/svg+xml" },
        5: { p: 1, n: "geo_icon.svg", g: "754", t: "image/svg+xml" },
        12: { p: 1, n: "prod_1.png", g: "726", t: "@1x" },
        6: { p: 1, n: "photo_1.jpg", g: "602", t: "@1x" },
        13: { p: 1, n: "prod_2_2.png", g: "730", t: "@1x" },
        7: { p: 1, n: "photo_2.jpg", g: "600", t: "@1x" },
        "-1": { n: "PIE.htc" },
        0: { p: 1, n: "garmin_logo.svg", g: "606", t: "image/svg+xml" },
        8: { p: 1, n: "photo_3.jpg", g: "598", t: "@1x" },
        14: { p: 1, n: "prod_1_l.png", g: "734", t: "@1x" },
        1: { p: 1, n: "CTA.svg", g: "608", t: "image/svg+xml" },
        9: { p: 1, n: "prod_3.png", g: "722", t: "@1x" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "SCENE", o: "1", X: [0] }],
      [
        {
          o: "3",
          A: {
            a: [
              {
                i: 0.66666669,
                b: "kTimelineDefaultIdentifier",
                p: 9,
                symbolOid: "2",
              },
            ],
          },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#00293F",
          L: [],
          bY: 1,
          d: 320,
          U: {
            912: { V: { "Main Timeline": "965" }, W: "965", n: "icon" },
            934: { V: { "Main Timeline": "966" }, W: "966", n: "cta_line" },
          },
          T: {
            882: {
              q: false,
              z: 1,
              i: "882",
              n: "right_a",
              a: [
                { f: "c", y: 0, z: 0.15, i: "cR", e: 1.1, s: 1, o: "940" },
                { f: "c", y: 0, z: 0.15, i: "cQ", e: 1.1, s: 1, o: "940" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 1.1, o: "940" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 1.1, o: "940" },
                { y: 1, i: "cR", s: 1, z: 0, o: "940", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "940", f: "c" },
              ],
              f: 30,
              b: [],
            },
            706: {
              q: false,
              z: 3,
              i: "706",
              n: "slider",
              a: [
                { f: "c", y: 0, z: 1, i: "e", e: 0, s: 1, o: "926" },
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 1,
                  i: "ActionHandler",
                  e: { a: [{ p: 7, b: "706", symbolOid: "2" }] },
                  s: { a: [{ p: 7, b: "706", symbolOid: "2" }] },
                  o: "706",
                },
                { y: 0, i: "cY", s: "1", z: 0, o: "958", f: "c" },
                { f: "c", y: 0, z: 2.15, i: "cQ", e: 0.8, s: 1, o: "957" },
                { f: "c", y: 0, z: 2.15, i: "cR", e: 0.8, s: 1, o: "957" },
                { f: "c", y: 0, z: 2.15, i: "cQ", e: 0.8, s: 1, o: "956" },
                { f: "c", y: 0, z: 2.15, i: "cR", e: 0.8, s: 1, o: "956" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 1, s: 0.8, o: "945" },
                { f: "c", y: 0, z: 2.15, i: "cQ", e: 0.8, s: 1, o: "955" },
                { f: "c", y: 0, z: 2.15, i: "cR", e: 0.8, s: 1, o: "955" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 0, s: 1, o: "955" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 0, s: 1, o: "956" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 0, s: 1, o: "957" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 0.8, o: "951" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "951" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 0.8, o: "952" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "952" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 0.8, o: "953" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "953" },
                { f: "c", y: 0.15, z: 0.15, i: "e", e: 1, s: 0, o: "951" },
                { f: "c", y: 0.15, z: 0.15, i: "e", e: 1, s: 0, o: "952" },
                { f: "c", y: 0.15, z: 0.15, i: "e", e: 1, s: 0, o: "953" },
                { f: "c", y: 0.15, z: 1.15, i: "e", e: 1, s: 1, o: "945" },
                { f: "c", y: 0.15, z: 2, i: "e", e: 0, s: 0, o: "955" },
                { f: "c", y: 0.15, z: 2, i: "e", e: 0, s: 0, o: "956" },
                { f: "c", y: 0.15, z: 2, i: "e", e: 0, s: 0, o: "957" },
                { f: "c", y: 0.29, z: 1, i: "e", e: 0, s: 1, o: "928" },
                {
                  f: "c",
                  p: 2,
                  y: 1,
                  z: 1,
                  i: "ActionHandler",
                  e: { a: [{ p: 7, b: "706", symbolOid: "2" }] },
                  s: { a: [{ p: 7, b: "706", symbolOid: "2" }] },
                  o: "706",
                },
                { y: 1, i: "cR", s: 1, z: 0, o: "951", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "951", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "952", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "952", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "953", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "953", f: "c" },
                { f: "c", y: 1, z: 0.15, i: "e", e: 0, s: 1, o: "951" },
                { f: "c", y: 1, z: 0.15, i: "e", e: 0, s: 1, o: "952" },
                { f: "c", y: 1, z: 0.15, i: "e", e: 0, s: 1, o: "953" },
                { y: 1, i: "e", s: 0, z: 0, o: "926", f: "c" },
                { f: "c", y: 1.15, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "963" },
                { f: "c", y: 1.15, z: 0.15, i: "cR", e: 1, s: 0.8, o: "963" },
                { f: "c", y: 1.15, z: 0.15, i: "e", e: 1, s: 0, o: "963" },
                { y: 1.15, i: "e", s: 0, z: 0, o: "951", f: "c" },
                { y: 1.15, i: "e", s: 0, z: 0, o: "952", f: "c" },
                { y: 1.15, i: "e", s: 0, z: 0, o: "953", f: "c" },
                { f: "c", y: 1.29, z: 1, i: "e", e: 0, s: 1, o: "927" },
                { y: 1.29, i: "e", s: 0, z: 0, o: "928", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0.29,
                  i: "ActionHandler",
                  e: { a: [{ i: 0, b: "706", p: 9, symbolOid: "2" }] },
                  s: { a: [{ p: 7, b: "706", symbolOid: "2" }] },
                  o: "706",
                },
                { y: 2, i: "cQ", s: 1, z: 0, o: "963", f: "c" },
                { y: 2, i: "cR", s: 1, z: 0, o: "963", f: "c" },
                { f: "c", y: 2, z: 0.15, i: "e", e: 0, s: 1, o: "963" },
                { f: "c", y: 2, z: 0.15, i: "e", e: 0.8, s: 1, o: "945" },
                { f: "c", y: 2.15, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "957" },
                { f: "c", y: 2.15, z: 0.15, i: "cR", e: 1, s: 0.8, o: "957" },
                { f: "c", y: 2.15, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "956" },
                { f: "c", y: 2.15, z: 0.15, i: "cR", e: 1, s: 0.8, o: "956" },
                { f: "c", y: 2.15, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "955" },
                { f: "c", y: 2.15, z: 0.15, i: "cR", e: 1, s: 0.8, o: "955" },
                { f: "c", y: 2.15, z: 0.15, i: "e", e: 1, s: 0, o: "955" },
                { f: "c", y: 2.15, z: 0.15, i: "e", e: 1, s: 0, o: "956" },
                { f: "c", y: 2.15, z: 0.15, i: "e", e: 1, s: 0, o: "957" },
                { y: 2.15, i: "e", s: 0, z: 0, o: "963", f: "c" },
                { y: 2.15, i: "e", s: 0.8, z: 0, o: "945", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2.29,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ i: 0, b: "706", p: 9, symbolOid: "2" }] },
                  o: "706",
                },
                { y: 2.29, i: "e", s: 0, z: 0, o: "927", f: "c" },
                { y: 3, i: "cQ", s: 1, z: 0, o: "957", f: "c" },
                { y: 3, i: "cR", s: 1, z: 0, o: "957", f: "c" },
                { y: 3, i: "cQ", s: 1, z: 0, o: "956", f: "c" },
                { y: 3, i: "cR", s: 1, z: 0, o: "956", f: "c" },
                { y: 3, i: "cQ", s: 1, z: 0, o: "955", f: "c" },
                { y: 3, i: "cR", s: 1, z: 0, o: "955", f: "c" },
                { y: 3, i: "e", s: 1, z: 0, o: "955", f: "c" },
                { y: 3, i: "e", s: 1, z: 0, o: "956", f: "c" },
                { y: 3, i: "e", s: 1, z: 0, o: "957", f: "c" },
              ],
              f: 30,
              b: [],
            },
            966: {
              c: "934",
              q: false,
              z: 2.15,
              i: "966",
              a: [
                { f: "c", y: 0, z: 0.15, i: "e", e: 1, s: 0, o: "936" },
                { f: "c", y: 0.15, z: 1, i: "dN", e: 1, s: 0, o: "936" },
                { f: "c", y: 0.15, z: 1, i: "e", e: 1, s: 1, o: "936" },
                { y: 1.15, i: "dN", s: 1, z: 0, o: "936", f: "c" },
                { f: "c", y: 1.15, z: 0.15, i: "e", e: 0, s: 1, o: "936" },
                { y: 2, i: "e", s: 0, z: 0, o: "936", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "966", p: 3, z: false, symbolOid: "877" }] },
                  o: "966",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            881: {
              q: false,
              z: 1,
              i: "881",
              n: "left_a",
              a: [
                { f: "c", y: 0, z: 0.15, i: "cQ", e: 1.1, s: 1, o: "944" },
                { f: "c", y: 0, z: 0.15, i: "cR", e: 1.1, s: 1, o: "944" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 1.1, o: "944" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 1.1, o: "944" },
                { y: 1, i: "cR", s: 1, z: 0, o: "944", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "944", f: "c" },
              ],
              f: 30,
              b: [],
            },
            705: {
              q: false,
              z: 3,
              i: "705",
              n: "timer",
              a: [
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      { i: 0, b: "705", p: 9, symbolOid: "2" },
                      { b: "706", p: 8, z: false, symbolOid: "2", J: true },
                    ],
                  },
                  o: "705",
                },
              ],
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 10,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "v", y: 0, z: 2.2, i: "aY", e: 10, s: -10, o: "932" },
                { f: "v", y: 0, z: 2.2, i: "a", e: 10, s: -10, o: "932" },
                { f: "v", y: 0, z: 1.1, i: "b", e: -11, s: -6, o: "932" },
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 1,
                  i: "ActionHandler",
                  e: { a: [{ b: "706", p: 3, z: false, symbolOid: "2" }] },
                  s: { a: [{ b: "705", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "945" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "959" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "959" },
                { y: 0, i: "cY", s: "0", z: 0, o: "918", f: "c" },
                { y: 0, i: "cY", s: "0", z: 0, o: "919", f: "c" },
                { f: "v", y: 0, z: 2.2, i: "a", e: 10, s: -10, o: "948" },
                { f: "v", y: 0, z: 2.2, i: "aY", e: 10, s: -10, o: "948" },
                { f: "v", y: 0, z: 1.1, i: "b", e: -11, s: -6, o: "948" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "958" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "960" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "960" },
                { y: 0, i: "cY", s: "0", z: 0, o: "916", f: "c" },
                { f: "c", y: 0, z: 1, i: "b", e: -10, s: 24, o: "959" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "961" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "961" },
                { f: "v", y: 0, z: 2.2, i: "aY", e: 10, s: -10, o: "922" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "941" },
                { f: "c", y: 0, z: 1, i: "b", e: -10, s: 24, o: "960" },
                { f: "c", y: 0, z: 1, i: "b", e: -7.793, s: 24, o: "961" },
                {
                  f: "c",
                  p: 2,
                  y: 1,
                  z: 5.2,
                  i: "ActionHandler",
                  e: {
                    a: [
                      {
                        i: 1.33333337,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                    ],
                  },
                  s: { a: [{ b: "706", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 1, i: "e", s: 1, z: 0, o: "958", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "959", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "959", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "960", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "960", f: "c" },
                { y: 1, i: "e", s: 1, z: 0, o: "945", f: "c" },
                { y: 1, i: "b", s: -10, z: 0, o: "959", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "961", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "961", f: "c" },
                { y: 1, i: "e", s: 1, z: 0, o: "941", f: "c" },
                { y: 1, i: "b", s: -10, z: 0, o: "960", f: "c" },
                { y: 1, i: "b", s: -7.793, z: 0, o: "961", f: "c" },
                { f: "v", y: 1.1, z: 2.2, i: "bR", e: -10, s: 10, o: "922" },
                { f: "v", y: 1.1, z: 2.2, i: "bR", e: -34, s: -14, o: "948" },
                { f: "v", y: 1.1, z: 2.2, i: "bR", e: -10, s: 10, o: "932" },
                { f: "v", y: 1.1, z: 2.2, i: "b", e: 9, s: -11, o: "948" },
                { f: "v", y: 1.1, z: 2.2, i: "b", e: 9, s: -11, o: "932" },
                { f: "v", y: 2.2, z: 2.2, i: "a", e: -10, s: 10, o: "932" },
                { f: "v", y: 2.2, z: 2.2, i: "a", e: -10, s: 10, o: "948" },
                { f: "v", y: 2.2, z: 2.2, i: "aY", e: -10, s: 10, o: "948" },
                { f: "v", y: 2.2, z: 2.2, i: "aY", e: -10, s: 10, o: "932" },
                { f: "v", y: 2.2, z: 2.2, i: "aY", e: -10, s: 10, o: "922" },
                { f: "v", y: 4, z: 2.2, i: "bR", e: -14, s: -34, o: "948" },
                { f: "v", y: 4, z: 2.2, i: "bR", e: 10, s: -10, o: "922" },
                { f: "v", y: 4, z: 2.2, i: "bR", e: 10, s: -10, o: "932" },
                { f: "v", y: 4, z: 2.2, i: "b", e: -11, s: 9, o: "948" },
                { f: "v", y: 4, z: 2.2, i: "b", e: -11, s: 9, o: "932" },
                { f: "v", y: 5.1, z: 2.2, i: "a", e: 10, s: -10, o: "932" },
                { f: "v", y: 5.1, z: 2.2, i: "a", e: 10, s: -10, o: "948" },
                { f: "v", y: 5.1, z: 2.2, i: "aY", e: 10, s: -10, o: "948" },
                { f: "v", y: 5.1, z: 2.2, i: "aY", e: 10, s: -10, o: "932" },
                { f: "v", y: 5.1, z: 2.2, i: "aY", e: 10, s: -10, o: "922" },
                {
                  f: "c",
                  p: 2,
                  y: 6.2,
                  z: 3.1,
                  i: "ActionHandler",
                  e: {
                    a: [
                      {
                        i: 1,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                    ],
                  },
                  s: {
                    a: [
                      {
                        i: 1.33333337,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 6.2, i: "bR", s: -14, z: 0, o: "948", f: "c" },
                { y: 6.2, i: "bR", s: 10, z: 0, o: "932", f: "c" },
                { y: 6.2, i: "bR", s: 10, z: 0, o: "922", f: "c" },
                { y: 6.2, i: "b", s: -11, z: 0, o: "948", f: "c" },
                { y: 6.2, i: "b", s: -11, z: 0, o: "932", f: "c" },
                { y: 8, i: "a", s: 10, z: 0, o: "932", f: "c" },
                { y: 8, i: "a", s: 10, z: 0, o: "948", f: "c" },
                { y: 8, i: "aY", s: 10, z: 0, o: "948", f: "c" },
                { y: 8, i: "aY", s: 10, z: 0, o: "932", f: "c" },
                { y: 8, i: "aY", s: 10, z: 0, o: "922", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 10,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      {
                        i: 1,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
              ],
              f: 30,
              b: [
                {
                  D: 3.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "965",
                },
                {
                  D: 2.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 1.1,
                  b: "966",
                },
              ],
            },
            965: {
              c: "912",
              q: false,
              z: 3.15,
              i: "965",
              a: [
                { f: "y", y: 0, z: 1.15, i: "aY", e: 360, s: 0, o: "913" },
                { y: 1.15, i: "aY", s: 360, z: 0, o: "913", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "965", p: 3, z: false, symbolOid: "609" }] },
                  o: "965",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "924",
            "960",
            "956",
            "961",
            "957",
            "959",
            "955",
            "922",
            "931",
            "921",
            "958",
            "954",
            "951",
            "950",
            "926",
            "925",
            "952",
            "953",
            "917",
            "916",
            "907",
            "920",
            "948",
            "932",
            "929",
            "923",
            "963",
            "962",
            "949",
            "928",
            "927",
            "918",
            "946",
            "945",
            "944",
            "939",
            "919",
            "942",
            "941",
            "940",
            "947",
            "943",
            "930",
            "936",
            "935",
            "934",
            "938",
            "933",
            "937",
            "910",
            "915",
            "911",
            "909",
            "908",
            "964",
            "912",
            "913",
            "914",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            939: {
              h: "606",
              p: "no-repeat",
              x: "visible",
              a: 112.805,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 12,
              bF: "932",
              b: 160,
              d: 33,
              k: "div",
              c: 97,
            },
            960: {
              bR: 0,
              h: "734",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 24,
              j: "absolute",
              r: "inline",
              bF: "958",
              z: 2,
              dB: "img",
              d: 188.333,
              k: "div",
              cQ: 0.8,
              e: 1,
              c: 194.333,
              cR: 0.8,
            },
            947: {
              h: "709",
              p: "no-repeat",
              x: "visible",
              a: 8,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "945",
              b: 6,
              d: 17,
              k: "div",
              c: 15,
            },
            954: {
              x: "visible",
              a: -36.9757,
              b: -33.6245,
              j: "absolute",
              r: "inline",
              c: 323,
              k: "div",
              z: 1,
              d: 194.874,
              bF: "949",
              cQ: 0.95,
              cR: 0.95,
            },
            912: {
              cN: "none",
              x: "visible",
              a: 11,
              cA: false,
              b: 8,
              j: "absolute",
              r: "inline",
              c: 43,
              k: "div",
              z: 1,
              d: 38,
              bF: "911",
              cQ: 1,
              aP: "auto",
              bY: 1,
              bZ: 180,
              bX: false,
              cR: 1,
              cV: [],
            },
            961: {
              bR: 0,
              h: "726",
              p: "no-repeat",
              x: "visible",
              a: 62.5417,
              q: "100% 100%",
              b: 24,
              j: "absolute",
              r: "inline",
              bF: "958",
              z: 3,
              dB: "img",
              d: 192.667,
              k: "div",
              cQ: 0.8,
              e: 1,
              c: 203.333,
              cR: 0.8,
            },
            948: {
              bR: -14,
              x: "visible",
              tY: 0.15,
              a: -10,
              b: -6,
              j: "absolute",
              r: "inline",
              bF: "921",
              z: 8,
              k: "div",
              d: 480,
              c: 320,
              aY: -10,
              e: 1,
              tX: 0.5,
            },
            920: {
              aD: {
                a: [{ b: "640", p: 8, z: false, symbolOid: "2", J: true }],
              },
              x: "hidden",
              a: 0,
              bS: 383,
              b: 0,
              j: "absolute",
              z: 9,
              k: "div",
              c: 320,
              d: 480,
              cQ: 1,
              aC: {
                a: [
                  {
                    b: "kTimelineDefaultIdentifier",
                    p: 8,
                    z: true,
                    symbolOid: "2",
                    J: false,
                  },
                ],
              },
              cR: 1,
            },
            955: {
              bR: 0,
              h: "732",
              p: "no-repeat",
              x: "visible",
              a: 121,
              q: "100% 100%",
              b: -10,
              j: "absolute",
              r: "inline",
              bF: "954",
              z: 1,
              dB: "img",
              d: 188.333,
              k: "div",
              cQ: 1,
              e: 0,
              c: 202,
              cR: 1,
            },
            913: {
              h: "754",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: 2,
              j: "absolute",
              r: "inline",
              bF: "912",
              z: 4,
              dB: "img",
              d: 35,
              k: "div",
              aY: 0,
              cQ: 1,
              c: 28,
              cR: 1,
            },
            962: {
              x: "visible",
              k: "div",
              c: 233.667,
              d: 151,
              z: 2,
              a: 7.56599,
              j: "absolute",
              bF: "949",
              b: -13.4175,
            },
            949: {
              x: "visible",
              k: "div",
              c: 238,
              d: 403,
              z: 11,
              a: 33.434,
              j: "absolute",
              bF: "948",
              b: 26.4175,
            },
            914: {
              aU: 8,
              G: "#000",
              c: 100,
              aV: 8,
              r: "inline",
              d: 9,
              s: "Montserrat",
              t: 16,
              Y: 4,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "700",
              i: "distance",
              w: "300 m",
              bF: "911",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 2,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 48,
              b: 31,
            },
            921: {
              x: "visible",
              a: 0,
              b: -6,
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "920",
              k: "div",
              d: 480,
              c: 320,
              cQ: 0.95,
              aY: 0,
              e: 1,
              cR: 0.95,
            },
            956: {
              bR: 0,
              h: "734",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: -10,
              j: "absolute",
              r: "inline",
              bF: "954",
              z: 2,
              dB: "img",
              d: 188.333,
              k: "div",
              cQ: 1,
              e: 0,
              c: 194.333,
              cR: 1,
            },
            907: {
              c: 318,
              bS: 63,
              d: 478,
              I: "Solid",
              r: "inline",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              aP: "auto",
              M: 1,
              N: 1,
              A: "#ECECEC",
              j: "absolute",
              x: "visible",
              B: "#ECECEC",
              O: 1,
              P: 1,
              C: "#ECECEC",
              z: 33,
              k: "div",
              D: "#ECECEC",
              cN: "none",
              a: 0,
              b: 0,
            },
            963: {
              bR: 0,
              h: "722",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: -5,
              j: "absolute",
              r: "inline",
              bF: "962",
              z: 1,
              dB: "img",
              d: 151,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 233.667,
              cR: 0.8,
            },
            957: {
              bR: 0,
              h: "726",
              p: "no-repeat",
              x: "visible",
              a: 62.5417,
              q: "100% 100%",
              b: -7.793,
              j: "absolute",
              r: "inline",
              bF: "954",
              z: 3,
              dB: "img",
              d: 192.667,
              k: "div",
              cQ: 1,
              e: 0,
              c: 203.333,
              cR: 1,
            },
            908: {
              x: "hidden",
              b: 427,
              k: "div",
              aL: 15,
              c: 320,
              d: 53,
              z: 10,
              a: 0,
              bS: 31,
              j: "absolute",
              aK: 15,
            },
            915: {
              aU: 8,
              G: "#000",
              c: 164,
              aV: 8,
              r: "inline",
              d: 28,
              s: "Montserrat",
              X: 0,
              t: 10,
              Y: 12,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "500",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">Adgar Park West - budynek A\nAl. Jerozolimskie 181, Warszawa\n</div>',
              bF: "911",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 3,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 48,
              b: -3,
            },
            922: {
              bR: 10,
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              bF: "921",
              z: 4,
              r: "inline",
              cY: "0",
              d: 480,
              k: "div",
              aY: -10,
              e: 1,
              c: 320,
            },
            964: {
              p: "no-repeat",
              c: 280,
              q: "100% 100%",
              bS: 13,
              d: 55,
              r: "none",
              cQ: 1,
              gg: "1",
              cR: 1,
              h: "624",
              bF: "920",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 8,
              Q: 10,
              R: "rgba(0, 0, 0, 0.143)",
              S: 0,
              a: 20.0243,
              T: 0,
              b: 425.376,
            },
            958: {
              x: "visible",
              a: -36.9757,
              b: -33.6245,
              j: "absolute",
              bF: "949",
              z: 8,
              r: "inline",
              cY: "0",
              d: 194.874,
              k: "div",
              cQ: 0.95,
              e: 0,
              c: 323,
              cR: 0.95,
            },
            909: {
              c: 320,
              bS: 319,
              d: 53,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#FFF",
              L: "Solid",
              M: 0,
              bF: "908",
              N: 0,
              A: "#ECECEC",
              j: "absolute",
              x: "visible",
              B: "#ECECEC",
              P: 0,
              O: 0,
              C: "#ECECEC",
              z: 1,
              k: "div",
              D: "#ECECEC",
              aK: 0,
              a: 0,
              aL: 0,
              b: 0,
            },
            916: {
              c: 318,
              bS: 63,
              d: 478,
              r: "inline",
              cY: "0",
              e: 0,
              J: "Solid",
              I: "Solid",
              K: "Solid",
              g: "#E8EBED",
              L: "Solid",
              aP: "pointer",
              M: 1,
              w: "",
              N: 1,
              A: "#B3B3B3",
              j: "absolute",
              x: "visible",
              B: "#B3B3B3",
              P: 1,
              O: 1,
              C: "#B3B3B3",
              z: 57,
              dB: "button",
              D: "#B3B3B3",
              aA: {
                a: [
                  { p: 4, h: "118" },
                  { p: 4, h: "906" },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            923: {
              c: 240,
              d: 400,
              r: "inline",
              e: 1,
              gg: "1",
              bF: "922",
              aI: 10,
              j: "absolute",
              x: "hidden",
              k: "div",
              aJ: 10,
              Q: 10,
              z: 2,
              aK: 10,
              R: "rgba(0, 0, 0, 0.152)",
              S: 0,
              a: 40,
              aL: 10,
              T: 0,
              b: 16,
            },
            930: {
              c: 328,
              d: 121,
              r: "inline",
              I: "Solid",
              J: "Solid",
              f: 0,
              K: "Solid",
              L: "Solid",
              aX: 0,
              M: 0,
              aY: 0,
              bF: "923",
              N: 0,
              A: "#ECECEC",
              x: "visible",
              j: "absolute",
              B: "#ECECEC",
              O: 0,
              P: 0,
              C: "#ECECEC",
              z: 9,
              l: 0,
              D: "#ECECEC",
              m: "#000",
              k: "div",
              n: "rgba(255, 255, 255, 0.000)",
              a: -53,
              b: 300,
            },
            959: {
              bR: 0,
              h: "732",
              p: "no-repeat",
              x: "visible",
              a: 121,
              q: "100% 100%",
              b: 24,
              j: "absolute",
              r: "inline",
              bF: "958",
              z: 1,
              dB: "img",
              d: 188.333,
              k: "div",
              cQ: 0.8,
              e: 1,
              c: 202,
              cR: 0.8,
            },
            917: {
              cN: "none",
              x: "visible",
              bS: 383,
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 58,
              d: 480,
              aP: "auto",
              e: 1,
            },
            924: {
              x: "visible",
              k: "div",
              c: 525,
              d: 495,
              z: 1,
              a: -190,
              j: "absolute",
              bF: "923",
              b: -72,
            },
            931: {
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              r: "none",
              c: 320,
              k: "div",
              z: 3,
              d: 480,
              bF: "921",
              aY: 0,
              e: 1,
            },
            918: {
              c: 53,
              d: 53,
              I: "None",
              cY: "0",
              e: 0,
              J: "None",
              K: "None",
              g: "#00BABE",
              L: "None",
              aP: "pointer",
              M: 0,
              bF: "917",
              N: 0,
              A: "#B3B3B3",
              x: "visible",
              j: "absolute",
              B: "#B3B3B3",
              P: 0,
              O: 0,
              C: "#B3B3B3",
              z: 1,
              dB: "button",
              D: "#B3B3B3",
              aA: {
                a: [
                  { b: "706", p: 8, z: true, symbolOid: "2", J: false },
                  { b: "705", p: 3, z: false, symbolOid: "2" },
                  { p: 4, h: "905" },
                  { b: "881", p: 3, z: false, symbolOid: "2" },
                ],
              },
              k: "div",
              a: 0,
              b: 155,
            },
            925: {
              h: "602",
              p: "no-repeat",
              x: "visible",
              a: 181,
              q: "100% 100%",
              b: 49,
              j: "absolute",
              r: "inline",
              bF: "924",
              z: 1,
              dB: "img",
              d: 476,
              k: "div",
              cQ: 1,
              e: 1,
              c: 299,
              cR: 1,
            },
            932: {
              bR: 10,
              x: "visible",
              tY: 0.5,
              a: -10,
              b: -6,
              j: "absolute",
              r: "inline",
              bF: "921",
              z: 7,
              k: "div",
              d: 480,
              c: 320,
              aY: -10,
              e: 1,
              tX: 0.5,
            },
            933: {
              Q: 7,
              x: "visible",
              R: "rgba(0, 0, 0, 0.095)",
              a: 107,
              b: 377,
              S: 0,
              bF: "932",
              z: 13,
              T: 0,
              j: "absolute",
              d: 29,
              k: "div",
              c: 96,
              gg: "1",
            },
            940: {
              x: "visible",
              cQ: 1,
              k: "div",
              cR: 1,
              c: 28,
              d: 28,
              z: 9,
              a: 292,
              bF: "921",
              j: "absolute",
              b: 170,
            },
            919: {
              c: 57,
              d: 53,
              I: "None",
              cY: "0",
              e: 0,
              J: "None",
              K: "None",
              g: "#00BABE",
              L: "None",
              aP: "pointer",
              M: 0,
              bF: "917",
              N: 0,
              A: "#B3B3B3",
              x: "visible",
              j: "absolute",
              B: "#B3B3B3",
              P: 0,
              O: 0,
              C: "#B3B3B3",
              z: 2,
              dB: "button",
              D: "#B3B3B3",
              aA: {
                a: [
                  { b: "706", p: 8, z: false, symbolOid: "2", J: false },
                  { b: "705", p: 3, z: false, symbolOid: "2" },
                  { p: 4, h: "904" },
                  { b: "882", p: 3, z: false, symbolOid: "2" },
                ],
              },
              k: "div",
              a: 263,
              b: 155,
            },
            926: {
              h: "602",
              p: "no-repeat",
              x: "visible",
              a: 181,
              q: "100% 100%",
              b: 49,
              j: "absolute",
              r: "inline",
              bF: "924",
              z: 6,
              dB: "img",
              d: 476,
              k: "div",
              cQ: 1,
              e: 1,
              c: 299,
              cR: 1,
            },
            927: {
              h: "598",
              p: "no-repeat",
              x: "visible",
              a: 95,
              q: "100% 100%",
              b: 172,
              j: "absolute",
              r: "inline",
              bF: "924",
              z: 2,
              dB: "img",
              d: 300,
              k: "div",
              cQ: 1,
              e: 1,
              c: 430,
              cR: 1,
            },
            934: {
              x: "visible",
              a: -37,
              cA: false,
              b: -10,
              j: "absolute",
              bF: "933",
              c: 168,
              k: "div",
              bY: 1,
              d: 50,
              z: 3,
              bX: false,
              e: 1,
              bZ: 180,
              cV: [],
            },
            941: {
              x: "visible",
              k: "div",
              c: 28,
              d: 28,
              z: 1,
              e: 0,
              a: 0,
              j: "absolute",
              bF: "940",
              b: 0,
            },
            928: {
              h: "600",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 170,
              j: "absolute",
              r: "inline",
              bF: "924",
              z: 3,
              dB: "img",
              d: 325,
              k: "div",
              cQ: 1,
              e: 1,
              c: 463,
              cR: 1,
            },
            935: {
              x: "visible",
              k: "div",
              c: 168,
              d: 50,
              z: 2,
              a: 0,
              j: "absolute",
              bF: "934",
              b: 0,
            },
            942: {
              h: "707",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "941",
              b: 0,
              d: 28,
              k: "div",
              c: 28,
            },
            929: {
              c: 328,
              d: 135,
              r: "inline",
              I: "Solid",
              J: "Solid",
              f: 0,
              K: "Solid",
              g: "#FFF",
              aX: 0,
              L: "Solid",
              M: 0,
              aY: 0,
              bF: "923",
              N: 0,
              A: "#ECECEC",
              x: "visible",
              j: "absolute",
              B: "#ECECEC",
              P: 0,
              O: 0,
              C: "#ECECEC",
              z: 10,
              k: "div",
              D: "#ECECEC",
              a: -27,
              b: 0,
            },
            936: {
              dF: "round",
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              dG: "round",
              bF: "935",
              dC: {
                path: [
                  [3, 3, 3, 3, 165, 3, 165, 3],
                  [165, 3, 165, 3, 165, 47, 165, 47],
                  [165, 47, 165, 47, 3, 47, 3, 47],
                  [3, 47, 3, 47, 3, 3, 3, 3],
                ],
                closed: true,
              },
              z: 1,
              d: 50,
              k: "div",
              cQ: 0.6,
              e: 0,
              dD: 3,
              c: 168,
              cR: 0.7,
              dE: "#FFF",
              dN: 0,
            },
            943: {
              h: "709",
              p: "no-repeat",
              x: "visible",
              a: 8,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "941",
              b: 6,
              d: 17,
              k: "div",
              c: 15,
            },
            950: {
              x: "visible",
              a: -15.9757,
              b: -30.6245,
              j: "absolute",
              r: "inline",
              c: 279.333,
              k: "div",
              z: 4,
              d: 173.54,
              bF: "949",
              cQ: 0.95,
              cR: 0.95,
            },
            951: {
              bR: 0,
              h: "730",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: -7,
              j: "absolute",
              r: "inline",
              bF: "950",
              z: 1,
              dB: "img",
              d: 165.333,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 165.333,
              cR: 0.8,
            },
            937: {
              x: "hidden",
              k: "div",
              c: 88,
              d: 21,
              z: 1,
              a: 2.43401,
              j: "absolute",
              bF: "933",
              b: 4.41748,
            },
            944: {
              x: "visible",
              a: 1,
              b: 170,
              j: "absolute",
              r: "inline",
              z: 10,
              k: "div",
              bF: "921",
              d: 28,
              c: 28,
              cQ: 1,
              aY: 180,
              cR: 1,
            },
            952: {
              bR: 0,
              h: "724",
              p: "no-repeat",
              x: "visible",
              a: 57.5417,
              q: "100% 100%",
              b: -1.793,
              j: "absolute",
              r: "inline",
              bF: "950",
              z: 3,
              dB: "img",
              d: 165.333,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 165.333,
              cR: 0.8,
            },
            910: {
              cN: "none",
              x: "visible",
              bS: 31,
              a: 0,
              b: 417,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 11,
              d: 63,
              aP: "auto",
              e: 1,
            },
            938: {
              h: "608",
              p: "no-repeat",
              x: "visible",
              a: -2.43401,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "937",
              b: -4.41748,
              d: 29,
              k: "div",
              c: 96,
            },
            945: {
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              bF: "944",
              c: 28,
              k: "div",
              z: 1,
              d: 28,
              cQ: 1,
              e: 0,
              cR: 1,
            },
            946: {
              h: "707",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "945",
              b: 0,
              d: 28,
              k: "div",
              c: 28,
            },
            953: {
              bR: 0,
              h: "875",
              p: "no-repeat",
              x: "visible",
              a: 115,
              q: "100% 100%",
              b: -7,
              j: "absolute",
              r: "inline",
              bF: "950",
              z: 4,
              dB: "img",
              d: 165.5,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 165.5,
              cR: 0.8,
            },
            911: {
              x: "visible",
              bF: "910",
              k: "div",
              c: 320,
              d: 52,
              z: 4,
              a: 0,
              bS: 383,
              j: "absolute",
              b: 10,
            },
          },
        },
      ],
      {},
      h,
      {
        v: { p: 0, q: [[0, 0, 0.455, 0.03, 0.515, 0.955, 1, 1]] },
        y: { p: 0, q: [[0, 0, 0.445, 0.05, 0.55, 0.95, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
