//	HYPE.documents["Tchibo_family_RichMedia_320x480_final"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/Tchibo",
      f = "Tchibo_family_RichMedia_320x480_final",
      g = "tchibofamilyrichmedia320x480final_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/tchibofamilyrichmedia320x480final_hype_generated_script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "Click",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.click();\n\t\n}",
        identifier: "65",
      },
      {
        name: "volumeUp",
        source:
          'function(hypeDocument, element, event) {\tvar video = hypeDocument.getElementById("videom");\n\tvideo.volume = 0.5;\n\tvideo.muted = true;\t\t\n}',
        identifier: "75",
      },
      {
        name: "sound",
        source:
          'function(hypeDocument, element, event) {\t\n\tvar video = hypeDocument.getElementById("videom");\n\tvar krest = hypeDocument.getElementById("krestm");\n\tvar on = hypeDocument.getElementById("onm");\n\t\n\t\n\tif (video.muted) {\n\t\tvideo.muted = false;\n\t\tkrest.style.display = "none";\n\t\ton.style.display = "block";\n\t\tregisterUnMuteEvent();\n\t} else {\n\t\tvideo.muted = true;\n\t\tkrest.style.display = "block";\n\t\ton.style.display = "none";\n\t\tregisterMuteEvent();\n\t}\n\t\n\treturn false;\n\t\t\t\n}',
        identifier: "76",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        "-2": { n: "blank.gif" },
        18: { p: 1, n: "family_photo.jpg", g: "274", t: "@1x" },
        10: { p: 1, n: "MUG.png", g: "156", t: "@1x" },
        11: { p: 1, n: "3.png", g: "265", t: "@1x" },
        0: { p: 1, n: "mute.svg", g: "68", t: "image/svg+xml" },
        12: { p: 1, n: "1.png", g: "269", t: "@1x" },
        1: { p: 1, n: "krest.svg", g: "70", t: "image/svg+xml" },
        2: { p: 1, n: "on.svg", g: "72", t: "image/svg+xml" },
        13: { p: 1, n: "2.png", g: "267", t: "@1x" },
        3: { n: "all_families_16x09_PL.mp4", g: "7", t: "video/mp4" },
        14: { p: 1, n: "mug_no_steam.png", g: "279", t: "@1x" },
        4: { p: 1, n: "btn.svg", g: "29", t: "image/svg+xml" },
        5: { p: 1, n: "logo.svg", g: "158", t: "image/svg+xml" },
        15: { p: 1, n: "dog.jpg", g: "262", t: "@1x" },
        6: { p: 1, n: "head_2.svg", g: "160", t: "image/svg+xml" },
        16: { p: 1, n: "workers.jpg", g: "257", t: "@1x" },
        "-1": { n: "PIE.htc" },
        7: { p: 1, n: "head_1.svg", g: "162", t: "image/svg+xml" },
        8: { p: 1, n: "smokes.png", g: "168", t: "@1x" },
        17: { p: 1, n: "friends.jpg", g: "259", t: "@1x" },
        9: { p: 1, n: "family.svg", g: "164", t: "image/svg+xml" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "main scene", o: "1", X: [0] }],
      [
        {
          o: "3",
          A: { a: [{ p: 4, h: "75" }] },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {
            317: { V: { "Main Timeline": "445" }, W: "445", n: "Video_copy" },
            58: { V: { "Main Timeline": "444" }, W: "444", n: "Video" },
            439: { V: { "Main Timeline": "446" }, W: "446", n: "btn" },
          },
          T: {
            445: {
              b: [],
              c: "317",
              q: false,
              z: 20.2,
              i: "445",
              n: "Main Timeline",
              a: [
                { y: 5.2, p: 1, i: "Video Track", z: 14.3, o: "423", f: "a" },
              ],
              s: "317",
              f: 30,
            },
            446: {
              c: "439",
              q: false,
              z: 1,
              i: "446",
              a: [
                { f: "e", y: 0, z: 0.09, i: "cQ", e: 0.95, s: 1, o: "440" },
                { f: "e", y: 0, z: 0.09, i: "cR", e: 0.95, s: 1, o: "440" },
                { f: "d", y: 0.09, z: 0.08, i: "cR", e: 1, s: 0.95, o: "440" },
                { f: "d", y: 0.09, z: 0.08, i: "cQ", e: 1, s: 0.95, o: "440" },
                { y: 0.17, i: "cR", s: 1, z: 0, o: "440", f: "d" },
                { y: 0.17, i: "cQ", s: 1, z: 0, o: "440", f: "d" },
                {
                  f: "c",
                  p: 2,
                  y: 1,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "446", p: 3, z: false, symbolOid: "46" }] },
                  o: "446",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            220: {
              q: false,
              z: 12,
              i: "220",
              n: "smoke_animation",
              a: [
                { f: "d", y: 0, z: 4, i: "cR", e: 2.5, s: 0.7, o: "391" },
                { f: "d", y: 0, z: 2, i: "e", e: 1, s: 0, o: "391" },
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 10,
                  i: "ActionHandler",
                  e: { a: [{}] },
                  s: { a: [{ i: 2, b: "220", p: 9, symbolOid: "2" }] },
                  o: "220",
                },
                { f: "d", y: 0, z: 4, i: "cR", e: 2.5, s: 0.7, o: "401" },
                { f: "d", y: 0, z: 2, i: "e", e: 1, s: 0, o: "401" },
                { f: "d", y: 0, z: 4, i: "cR", e: 2.5, s: 0.7, o: "380" },
                { f: "d", y: 0, z: 2, i: "e", e: 1, s: 0, o: "380" },
                { f: "d", y: 2, z: 2, i: "e", e: 1, s: 0, o: "392" },
                { f: "d", y: 2, z: 4, i: "cR", e: 2.5, s: 0.7, o: "392" },
                { f: "d", y: 2, z: 4, i: "e", e: 1, s: 0, o: "390" },
                { f: "d", y: 2, z: 8, i: "cR", e: 2.5, s: 0.7, o: "390" },
                { f: "d", y: 2, z: 4, i: "e", e: 1, s: 0, o: "400" },
                { f: "d", y: 2, z: 8, i: "cR", e: 2.5, s: 0.7, o: "400" },
                { f: "d", y: 2, z: 2, i: "e", e: 1, s: 0, o: "396" },
                { f: "d", y: 2, z: 4, i: "cR", e: 2.5, s: 0.7, o: "396" },
                { f: "d", y: 2, z: 4, i: "e", e: 1, s: 0, o: "385" },
                { f: "d", y: 2, z: 8, i: "cR", e: 2.5, s: 0.7, o: "385" },
                { f: "d", y: 2, z: 2, i: "e", e: 1, s: 0, o: "381" },
                { f: "d", y: 2, z: 4, i: "cR", e: 2.5, s: 0.7, o: "381" },
                { f: "d", y: 2, z: 2, i: "e", e: 0, s: 1, o: "391" },
                { f: "d", y: 2, z: 2, i: "e", e: 0, s: 1, o: "401" },
                { f: "d", y: 2, z: 2, i: "e", e: 0, s: 1, o: "380" },
                { f: "d", y: 4, z: 4, i: "cR", e: 2.5, s: 0.7, o: "393" },
                { f: "d", y: 4, z: 4, i: "cR", e: 2.5, s: 0.7, o: "397" },
                { f: "d", y: 4, z: 4, i: "cR", e: 2.5, s: 0.7, o: "382" },
                { f: "d", y: 4, z: 2, i: "e", e: 1, s: 0, o: "393" },
                { y: 4, i: "cR", s: 2.5, z: 0, o: "391", f: "c" },
                { f: "d", y: 4, z: 2, i: "e", e: 1, s: 0, o: "397" },
                { y: 4, i: "cR", s: 2.5, z: 0, o: "401", f: "c" },
                { f: "d", y: 4, z: 2, i: "e", e: 1, s: 0, o: "382" },
                { y: 4, i: "cR", s: 2.5, z: 0, o: "380", f: "c" },
                { f: "d", y: 4, z: 2, i: "e", e: 0, s: 1, o: "392" },
                { f: "d", y: 4, z: 2, i: "e", e: 0, s: 1, o: "396" },
                { f: "d", y: 4, z: 2, i: "e", e: 0, s: 1, o: "381" },
                { y: 4, i: "e", s: 0, z: 0, o: "391", f: "c" },
                { y: 4, i: "e", s: 0, z: 0, o: "401", f: "c" },
                { y: 4, i: "e", s: 0, z: 0, o: "380", f: "c" },
                { f: "d", y: 6, z: 4, i: "cR", e: 2.5, s: 0.7, o: "388" },
                { f: "d", y: 6, z: 4, i: "cR", e: 2.5, s: 0.7, o: "398" },
                { f: "d", y: 6, z: 4, i: "cR", e: 2.5, s: 0.7, o: "383" },
                { y: 6, i: "cR", s: 2.5, z: 0, o: "392", f: "c" },
                { y: 6, i: "cR", s: 2.5, z: 0, o: "396", f: "c" },
                { y: 6, i: "cR", s: 2.5, z: 0, o: "381", f: "c" },
                { f: "d", y: 6, z: 2, i: "e", e: 1, s: 0, o: "388" },
                { f: "d", y: 6, z: 2, i: "e", e: 1, s: 0, o: "398" },
                { f: "d", y: 6, z: 2, i: "e", e: 1, s: 0, o: "383" },
                { f: "d", y: 6, z: 2, i: "e", e: 0, s: 1, o: "393" },
                { f: "d", y: 6, z: 4, i: "e", e: 0, s: 1, o: "390" },
                { f: "d", y: 6, z: 4, i: "e", e: 0, s: 1, o: "400" },
                { f: "d", y: 6, z: 2, i: "e", e: 0, s: 1, o: "397" },
                { f: "d", y: 6, z: 4, i: "e", e: 0, s: 1, o: "385" },
                { f: "d", y: 6, z: 2, i: "e", e: 0, s: 1, o: "382" },
                { y: 6, i: "e", s: 0, z: 0, o: "392", f: "c" },
                { y: 6, i: "e", s: 0, z: 0, o: "396", f: "c" },
                { y: 6, i: "e", s: 0, z: 0, o: "381", f: "c" },
                { f: "d", y: 8, z: 4, i: "cR", e: 2.5, s: 0.7, o: "389" },
                { f: "d", y: 8, z: 4, i: "cR", e: 2.5, s: 0.7, o: "399" },
                { f: "d", y: 8, z: 4, i: "cR", e: 2.5, s: 0.7, o: "384" },
                { y: 8, i: "cR", s: 2.5, z: 0, o: "393", f: "c" },
                { y: 8, i: "cR", s: 2.5, z: 0, o: "397", f: "c" },
                { y: 8, i: "cR", s: 2.5, z: 0, o: "382", f: "c" },
                { f: "d", y: 8, z: 2, i: "e", e: 1, s: 0, o: "389" },
                { f: "d", y: 8, z: 2, i: "e", e: 1, s: 0, o: "399" },
                { f: "d", y: 8, z: 2, i: "e", e: 1, s: 0, o: "384" },
                { f: "d", y: 8, z: 2, i: "e", e: 0, s: 1, o: "388" },
                { f: "d", y: 8, z: 2, i: "e", e: 0, s: 1, o: "398" },
                { f: "d", y: 8, z: 2, i: "e", e: 0, s: 1, o: "383" },
                { y: 8, i: "e", s: 0, z: 0, o: "393", f: "c" },
                { y: 8, i: "e", s: 0, z: 0, o: "397", f: "c" },
                { y: 8, i: "e", s: 0, z: 0, o: "382", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 10,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ i: 2, b: "220", p: 9, symbolOid: "2" }] },
                  o: "220",
                },
                { y: 10, i: "cR", s: 2.5, z: 0, o: "388", f: "c" },
                { y: 10, i: "cR", s: 2.5, z: 0, o: "390", f: "c" },
                { y: 10, i: "cR", s: 2.5, z: 0, o: "400", f: "c" },
                { y: 10, i: "cR", s: 2.5, z: 0, o: "398", f: "c" },
                { y: 10, i: "cR", s: 2.5, z: 0, o: "385", f: "c" },
                { y: 10, i: "cR", s: 2.5, z: 0, o: "383", f: "c" },
                { f: "d", y: 10, z: 2, i: "e", e: 0, s: 1, o: "389" },
                { f: "d", y: 10, z: 2, i: "e", e: 0, s: 1, o: "399" },
                { f: "d", y: 10, z: 2, i: "e", e: 0, s: 1, o: "384" },
                { y: 10, i: "e", s: 0, z: 0, o: "388", f: "c" },
                { y: 10, i: "e", s: 0, z: 0, o: "390", f: "c" },
                { y: 10, i: "e", s: 0, z: 0, o: "400", f: "c" },
                { y: 10, i: "e", s: 0, z: 0, o: "398", f: "c" },
                { y: 10, i: "e", s: 0, z: 0, o: "385", f: "c" },
                { y: 10, i: "e", s: 0, z: 0, o: "383", f: "c" },
                { y: 12, i: "cR", s: 2.5, z: 0, o: "389", f: "c" },
                { y: 12, i: "cR", s: 2.5, z: 0, o: "399", f: "c" },
                { y: 12, i: "cR", s: 2.5, z: 0, o: "384", f: "c" },
                { y: 12, i: "e", s: 0, z: 0, o: "389", f: "c" },
                { y: 12, i: "e", s: 0, z: 0, o: "399", f: "c" },
                { y: 12, i: "e", s: 0, z: 0, o: "384", f: "c" },
              ],
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 25,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { y: 0, i: "b", s: 0, z: 0, o: "367", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 25,
                  i: "ActionHandler",
                  e: {
                    a: [
                      {
                        i: 17,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                    ],
                  },
                  s: { a: [{ b: "220", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 0, z: 0.15, i: "e", e: 0.5, s: 0, o: "387" },
                { f: "p", y: 0, z: 0.24, i: "cQ", e: 1.1, s: 0.8, o: "409" },
                { f: "p", y: 0, z: 0.24, i: "cR", e: 1.1, s: 0.8, o: "409" },
                { f: "c", y: 0, z: 18.28, i: "cY", e: "1", s: "0", o: "369" },
                { y: 0, i: "b", s: 0, z: 0, o: "421", f: "c" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 0.5, s: 0, o: "395" },
                { y: 0, i: "b", s: 0, z: 0, o: "422", f: "c" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 0.5, s: 0, o: "379" },
                { y: 0, i: "b", s: 0, z: 0, o: "370", f: "c" },
                { f: "c", y: 0, z: 0.18, i: "e", e: 1, s: 0, o: "410" },
                { y: 0, i: "b", s: 0, z: 0, o: "371", f: "c" },
                { y: 0, i: "b", s: 0, z: 0, o: "368", f: "c" },
                { y: 0.15, i: "e", s: 0.5, z: 0, o: "387", f: "c" },
                { y: 0.15, i: "e", s: 0.5, z: 0, o: "395", f: "c" },
                { y: 0.15, i: "e", s: 0.5, z: 0, o: "379", f: "c" },
                { f: "c", y: 0.18, z: 0.15, i: "cR", e: 1, s: 1.1, o: "439" },
                { f: "c", y: 0.18, z: 0.15, i: "cQ", e: 1, s: 1.1, o: "439" },
                { y: 0.18, i: "e", s: 1, z: 0, o: "410", f: "c" },
                { f: "c", y: 0.18, z: 0.15, i: "e", e: 1, s: 0, o: "439" },
                { f: "c", y: 0.24, z: 0.21, i: "cQ", e: 1, s: 1.1, o: "409" },
                { f: "c", y: 0.24, z: 0.21, i: "cR", e: 1, s: 1.1, o: "409" },
                { f: "c", y: 1, z: 1, i: "e", e: 1, s: 0, o: "411" },
                { y: 1.03, i: "cR", s: 1, z: 0, o: "439", f: "c" },
                { y: 1.03, i: "cQ", s: 1, z: 0, o: "439", f: "c" },
                { y: 1.03, i: "e", s: 1, z: 0, o: "439", f: "c" },
                { f: "b", y: 1.15, z: 1, i: "c", e: 288, s: 0, o: "412" },
                { y: 1.15, i: "cQ", s: 1, z: 0, o: "409", f: "c" },
                { y: 1.15, i: "cR", s: 1, z: 0, o: "409", f: "c" },
                { y: 2, i: "e", s: 1, z: 0, o: "411", f: "c" },
                { y: 2.15, i: "c", s: 288, z: 0, o: "412", f: "c" },
                { f: "k", y: 3, z: 1.1, i: "a", e: -30, s: 0, o: "375" },
                { f: "k", y: 3, z: 1.1, i: "aY", e: -90, s: 0, o: "375" },
                { f: "k", y: 3.01, z: 1.1, i: "aY", e: -90, s: 0, o: "402" },
                { f: "p", y: 4.09, z: 1.11, i: "b", e: 60, s: 43, o: "433" },
                { f: "p", y: 4.09, z: 1.11, i: "b", e: 14, s: -3, o: "436" },
                { f: "p", y: 4.09, z: 1.11, i: "b", e: 60, s: 43, o: "353" },
                { f: "p", y: 4.09, z: 1.11, i: "b", e: 14, s: -3, o: "351" },
                { f: "c", y: 4.09, z: 0.01, i: "e", e: 0, s: 1, o: "375" },
                { f: "q", y: 4.1, z: 1.1, i: "a", e: 0, s: 30, o: "349" },
                { f: "q", y: 4.1, z: 1.1, i: "aY", e: 0, s: 90, o: "349" },
                { f: "c", y: 4.1, z: 0.01, i: "a", e: 30, s: -30, o: "375" },
                { f: "c", y: 4.1, z: 0.01, i: "aY", e: 90, s: -90, o: "375" },
                { f: "q", y: 4.1, z: 0.01, i: "e", e: 1, s: 0, o: "349" },
                { f: "c", y: 4.1, z: 0.01, i: "e", e: -0.0, s: 1, o: "402" },
                { y: 4.1, i: "e", s: 0, z: 0, o: "375", f: "c" },
                { y: 4.11, i: "a", s: 30, z: 0, o: "375", f: "q" },
                { f: "c", y: 4.11, z: 0.01, i: "aY", e: 90, s: -90, o: "402" },
                { y: 4.11, i: "aY", s: 90, z: 0, o: "375", f: "q" },
                { f: "c", y: 4.11, z: 1.09, i: "e", e: 1, s: 0, o: "432" },
                { f: "c", y: 4.11, z: 7.21, i: "e", e: 1, s: 1, o: "349" },
                { y: 4.11, i: "e", s: -0.0, z: 0, o: "402", f: "c" },
                { f: "c", y: 4.11, z: 1.09, i: "e", e: 1, s: 0, o: "350" },
                { f: "q", y: 4.12, z: 1.1, i: "aY", e: 0, s: 90, o: "355" },
                { y: 4.12, i: "aY", s: 90, z: 0, o: "402", f: "q" },
                { f: "p", y: 4.12, z: 1.11, i: "b", e: 24, s: 7, o: "434" },
                { f: "p", y: 4.12, z: 1.11, i: "b", e: 24, s: 7, o: "354" },
                { f: "q", y: 4.12, z: 0.01, i: "e", e: 1, s: -0.0, o: "355" },
                { f: "c", y: 4.13, z: 7.19, i: "e", e: 1, s: 1, o: "355" },
                { f: "p", y: 4.19, z: 1.11, i: "b", e: 0, s: -17, o: "435" },
                { f: "p", y: 4.19, z: 1.11, i: "b", e: 0, s: -17, o: "352" },
                { f: "c", y: 5.2, z: 5.03, i: "a", e: 0, s: 0, o: "349" },
                { f: "k", y: 5.2, z: 5.03, i: "aY", e: 0, s: 0, o: "349" },
                { y: 5.2, i: "b", s: 60, z: 0, o: "433", f: "c" },
                { y: 5.2, i: "b", s: 14, z: 0, o: "436", f: "c" },
                { y: 5.2, i: "b", s: 60, z: 0, o: "353", f: "c" },
                { y: 5.2, i: "b", s: 14, z: 0, o: "351", f: "c" },
                { y: 5.2, i: "e", s: 1, z: 0, o: "432", f: "c" },
                { y: 5.2, i: "e", s: 1, z: 0, o: "350", f: "c" },
                { f: "c", y: 5.22, z: 5.01, i: "aY", e: 0, s: 0, o: "355" },
                { y: 5.23, i: "b", s: 24, z: 0, o: "434", f: "c" },
                { y: 5.23, i: "b", s: 24, z: 0, o: "354", f: "c" },
                { y: 6, i: "b", s: 0, z: 0, o: "435", f: "c" },
                { y: 6, i: "b", s: 0, z: 0, o: "352", f: "c" },
                { y: 6.22, i: "a", s: -15, z: 0, o: "367", f: "p" },
                { f: "c", y: 6.22, z: 0.21, i: "e", e: 0, s: 1, o: "367" },
                { y: 7.13, i: "e", s: 0, z: 0, o: "367", f: "c" },
                { f: "c", y: 7.25, z: 7.23, i: "a", e: -14, s: -14, o: "421" },
                { f: "c", y: 7.25, z: 13.23, i: "a", e: -14, s: -14, o: "370" },
                { f: "c", y: 7.25, z: 0.15, i: "a", e: -14, s: -14, o: "368" },
                { y: 8.1, i: "a", s: -14, z: 0, o: "368", f: "c" },
                { f: "c", y: 8.1, z: 0.2, i: "e", e: 0, s: 1, o: "368" },
                { y: 9, i: "e", s: 0, z: 0, o: "368", f: "c" },
                { f: "c", y: 9.12, z: 7.26, i: "a", e: -14, s: -14, o: "420" },
                { f: "c", y: 9.12, z: 13.26, i: "a", e: -14, s: -14, o: "373" },
                { f: "c", y: 9.12, z: 0.18, i: "a", e: -14, s: -14, o: "366" },
                { y: 10, i: "a", s: -14, z: 0, o: "366", f: "c" },
                { f: "c", y: 10, z: 0.21, i: "e", e: 0, s: 1, o: "366" },
                { y: 10.21, i: "e", s: 0, z: 0, o: "366", f: "c" },
                { f: "k", y: 10.23, z: 1.1, i: "aY", e: -90, s: 0, o: "349" },
                { f: "k", y: 10.23, z: 1.1, i: "aY", e: -90, s: 0, o: "355" },
                { f: "k", y: 10.23, z: 1.1, i: "a", e: -30, s: 0, o: "349" },
                { y: 11, i: "a", s: -14, z: 0, o: "419", f: "c" },
                { y: 11, i: "a", s: -14, z: 0, o: "372", f: "c" },
                { y: 11, i: "a", s: -14, z: 0, o: "365", f: "c" },
                { f: "q", y: 12, z: 1.1, i: "aY", e: 0, s: 90, o: "431" },
                { f: "q", y: 12, z: 1.1, i: "a", e: 0, s: 30, o: "431" },
                { f: "q", y: 12, z: 0.01, i: "e", e: 1, s: 0, o: "431" },
                { f: "c", y: 12.01, z: 6.27, i: "e", e: 1, s: 1, o: "431" },
                { f: "q", y: 12.02, z: 1.1, i: "aY", e: 0, s: 90, o: "417" },
                { f: "q", y: 12.02, z: 0.01, i: "e", e: 1, s: -0.0, o: "417" },
                { f: "c", y: 12.02, z: 0.01, i: "e", e: 0, s: 1, o: "349" },
                { f: "c", y: 12.02, z: 0.01, i: "e", e: -0.0, s: 1, o: "355" },
                { f: "c", y: 12.03, z: 6.27, i: "aY", e: 90, s: -90, o: "355" },
                { f: "c", y: 12.03, z: 6.25, i: "aY", e: 90, s: -90, o: "349" },
                { f: "c", y: 12.03, z: 6.25, i: "a", e: 30, s: -30, o: "349" },
                { f: "c", y: 12.03, z: 6.26, i: "e", e: 1, s: 1, o: "417" },
                { f: "c", y: 12.03, z: 6.25, i: "e", e: 0, s: 0, o: "349" },
                {
                  f: "c",
                  y: 12.03,
                  z: 6.27,
                  i: "e",
                  e: -0.0,
                  s: -0.0,
                  o: "355",
                },
                { f: "k", y: 13.1, z: 4.09, i: "aY", e: 0, s: 0, o: "431" },
                { f: "c", y: 13.1, z: 4.09, i: "a", e: 0, s: 0, o: "431" },
                { f: "c", y: 13.12, z: 4.08, i: "aY", e: 0, s: 0, o: "417" },
                { y: 14, i: "a", s: -15, z: 0, o: "422", f: "p" },
                { f: "c", y: 14, z: 0.21, i: "e", e: 0, s: 1, o: "422" },
                { y: 14.21, i: "e", s: 0, z: 0, o: "422", f: "c" },
                { y: 15.18, i: "a", s: -14, z: 0, o: "421", f: "c" },
                { f: "c", y: 15.18, z: 0.2, i: "e", e: 0, s: 1, o: "421" },
                { y: 16.08, i: "e", s: 0, z: 0, o: "421", f: "c" },
                { y: 17.08, i: "a", s: -14, z: 0, o: "420", f: "c" },
                { f: "c", y: 17.08, z: 0.21, i: "e", e: 0, s: 1, o: "420" },
                { f: "k", y: 17.19, z: 1.1, i: "aY", e: -90, s: 0, o: "431" },
                { f: "k", y: 17.19, z: 1.1, i: "a", e: -30, s: 0, o: "431" },
                { f: "k", y: 17.2, z: 1.1, i: "aY", e: -90, s: 0, o: "417" },
                { y: 17.29, i: "e", s: 0, z: 0, o: "420", f: "c" },
                {
                  f: "c",
                  y: 18.28,
                  z: 0.02,
                  i: "cY",
                  e: "0",
                  s: "1",
                  o: "369",
                },
                { f: "q", y: 18.28, z: 1.1, i: "aY", e: 0, s: 90, o: "349" },
                { f: "q", y: 18.28, z: 1.1, i: "a", e: 0, s: 30, o: "349" },
                { f: "c", y: 18.28, z: 0.01, i: "e", e: 0, s: 1, o: "431" },
                { f: "q", y: 18.28, z: 0.01, i: "e", e: 1, s: 0, o: "349" },
                { f: "c", y: 18.29, z: 0.01, i: "aY", e: 90, s: -90, o: "431" },
                { f: "c", y: 18.29, z: 0.01, i: "a", e: 30, s: -30, o: "431" },
                { f: "c", y: 18.29, z: 0.01, i: "e", e: -0.0, s: 1, o: "417" },
                { y: 18.29, i: "e", s: 0, z: 0, o: "431", f: "c" },
                { y: 18.29, i: "e", s: 1, z: 0, o: "349", f: "c" },
                { y: 19, i: "cY", s: "0", z: 0, o: "369", f: "c" },
                { f: "c", y: 19, z: 0.01, i: "aY", e: 90, s: -90, o: "417" },
                { y: 19, i: "aY", s: 90, z: 0, o: "431", f: "q" },
                { f: "q", y: 19, z: 1.1, i: "aY", e: 0, s: 90, o: "355" },
                { y: 19, i: "a", s: 30, z: 0, o: "431", f: "q" },
                { y: 19, i: "e", s: -0.0, z: 0, o: "417", f: "c" },
                { f: "q", y: 19, z: 0.01, i: "e", e: 1, s: -0.0, o: "355" },
                { y: 19.01, i: "aY", s: 90, z: 0, o: "417", f: "q" },
                { y: 19.01, i: "e", s: 1, z: 0, o: "355", f: "c" },
                { y: 20, i: "a", s: -15, z: 0, o: "371", f: "p" },
                { f: "c", y: 20, z: 0.21, i: "e", e: 0, s: 1, o: "371" },
                { y: 20.08, i: "aY", s: 0, z: 0, o: "349", f: "k" },
                { y: 20.08, i: "a", s: 0, z: 0, o: "349", f: "c" },
                { y: 20.1, i: "aY", s: 0, z: 0, o: "355", f: "c" },
                { y: 20.21, i: "e", s: 0, z: 0, o: "371", f: "c" },
                { y: 21.18, i: "a", s: -14, z: 0, o: "370", f: "c" },
                { f: "c", y: 21.18, z: 0.2, i: "e", e: 0, s: 1, o: "370" },
                { y: 22.08, i: "e", s: 0, z: 0, o: "370", f: "c" },
                { y: 23.08, i: "a", s: -14, z: 0, o: "373", f: "c" },
                { f: "c", y: 23.08, z: 0.21, i: "e", e: 0, s: 1, o: "373" },
                { y: 23.29, i: "e", s: 0, z: 0, o: "373", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 25,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      {
                        i: 10.69999981,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
              ],
              f: 30,
              b: [
                {
                  D: 20.2,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "444",
                },
                {
                  D: 1,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0.18,
                  b: "446",
                },
              ],
            },
            444: {
              b: [],
              c: "58",
              q: false,
              z: 20.2,
              i: "444",
              n: "Main Timeline",
              a: [
                { y: 5.2, p: 1, i: "Video Track", z: 14.3, o: "356", f: "a" },
              ],
              s: "58",
              f: 30,
            },
          },
          bZ: 180,
          O: [
            "417",
            "416",
            "349",
            "355",
            "348",
            "402",
            "374",
            "347",
            "437",
            "442",
            "431",
            "375",
            "317",
            "423",
            "430",
            "356",
            "58",
            "363",
            "415",
            "427",
            "429",
            "424",
            "360",
            "362",
            "357",
            "408",
            "405",
            "403",
            "404",
            "426",
            "361",
            "428",
            "358",
            "407",
            "406",
            "425",
            "359",
            "409",
            "378",
            "394",
            "386",
            "410",
            "376",
            "411",
            "412",
            "413",
            "383",
            "381",
            "379",
            "398",
            "396",
            "395",
            "388",
            "392",
            "387",
            "384",
            "382",
            "380",
            "399",
            "397",
            "401",
            "389",
            "393",
            "391",
            "443",
            "422",
            "421",
            "420",
            "419",
            "371",
            "370",
            "373",
            "372",
            "367",
            "368",
            "366",
            "365",
            "418",
            "369",
            "364",
            "385",
            "400",
            "390",
            "377",
            "352",
            "350",
            "435",
            "432",
            "351",
            "436",
            "354",
            "434",
            "353",
            "433",
            "438",
            "414",
            "441",
            "440",
            "439",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            407: {
              h: "72",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 11,
              j: "absolute",
              r: "inline",
              bF: "403",
              cY: "1",
              z: 4,
              d: 13,
              dB: "img",
              cQ: 0.5,
              k: "div",
              c: 8,
              cR: 0.5,
            },
            430: {
              c: 290,
              bS: 18,
              d: 331,
              r: "inline",
              I: "None",
              J: "None",
              K: "None",
              g: "#FFB200",
              L: "None",
              aP: "auto",
              M: 0,
              bF: "417",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 1,
              k: "div",
              D: "#D8DDE4",
              aK: 0,
              cN: "none",
              a: 15,
              b: 16,
            },
            351: {
              h: "267",
              p: "no-repeat",
              x: "visible",
              a: 44,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "350",
              b: -3,
              d: 127.5,
              k: "div",
              c: 119.5,
            },
            415: {
              c: 288,
              bS: 18,
              d: 347,
              r: "inline",
              I: "None",
              J: "None",
              K: "None",
              g: "#FFB200",
              L: "None",
              aP: "auto",
              M: 0,
              bF: "402",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 1,
              k: "div",
              D: "#D8DDE4",
              aK: 0,
              cN: "none",
              a: 16,
              b: 16,
            },
            423: {
              c: 287,
              d: 161,
              cQ: 1.05,
              aO: "0",
              cR: 1.05,
              bE: "7",
              aH: "1",
              aP: "pointer",
              i: "videom",
              bF: "317",
              aQ: "1",
              j: "absolute",
              dA: "1",
              x: "visible",
              aR: "1",
              aA: { a: [{ p: 4, h: "65" }] },
              k: "video",
              dB: "button",
              z: 4,
              a: 0,
              b: 1,
            },
            408: {
              c: 35,
              d: 35,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#181E39",
              L: "Solid",
              aP: "pointer",
              M: 0,
              bF: "403",
              N: 0,
              A: "#1E2B46",
              x: "visible",
              j: "absolute",
              B: "#1E2B46",
              P: 0,
              O: 0,
              C: "#1E2B46",
              z: 5,
              dB: "button",
              D: "#1E2B46",
              aA: { a: [{ p: 4, h: "76" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            431: {
              cN: "none",
              x: "visible",
              a: 30,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 6,
              d: 480,
              bF: "416",
              aY: 90,
              e: 0,
              aP: "auto",
            },
            352: {
              h: "269",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "350",
              b: -17,
              d: 123.5,
              k: "div",
              c: 117.5,
            },
            416: {
              cN: "none",
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 17,
              d: 480,
              bF: "347",
              aP: "auto",
            },
            360: {
              c: 35,
              d: 35,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#181E39",
              L: "Solid",
              aP: "pointer",
              M: 0,
              bF: "357",
              N: 0,
              A: "#1E2B46",
              x: "visible",
              j: "absolute",
              B: "#1E2B46",
              P: 0,
              O: 0,
              C: "#1E2B46",
              z: 5,
              dB: "button",
              D: "#1E2B46",
              aA: { a: [{ p: 4, h: "76" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            424: {
              x: "visible",
              k: "div",
              c: 35,
              aP: "auto",
              cN: "none",
              d: 35,
              z: 5,
              a: 246,
              j: "absolute",
              bF: "317",
              b: 8,
            },
            58: {
              c: 290,
              bS: 343,
              d: 167,
              r: "inline",
              cQ: 1,
              e: 1,
              cA: false,
              cR: 1,
              aP: "auto",
              cS: true,
              cK: { a: [{ b: "444", p: 3, z: false, symbolOid: "58" }] },
              bF: "355",
              j: "absolute",
              x: "hidden",
              cL: "58",
              k: "div",
              cM: true,
              z: 5,
              bX: false,
              cV: [],
              cN: "none",
              bY: 1,
              a: 15,
              bZ: 180,
              b: 15,
            },
            409: {
              x: "visible",
              bS: 343,
              a: 0,
              b: 57,
              j: "absolute",
              bF: "402",
              z: 5,
              r: "inline",
              k: "div",
              d: 107,
              c: 319,
              cQ: 0.8,
              e: 1,
              cR: 0.8,
            },
            353: {
              h: "279",
              p: "no-repeat",
              x: "visible",
              a: 146,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "350",
              b: 43,
              d: 78.5,
              k: "div",
              c: 106.5,
            },
            417: {
              cN: "none",
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 1,
              d: 480,
              bF: "416",
              aY: 90,
              e: -0.0,
              aP: "auto",
            },
            432: {
              x: "visible",
              k: "div",
              c: 252.5,
              d: 141.5,
              z: 1,
              e: 0,
              a: 31,
              j: "absolute",
              bF: "431",
              b: 278,
            },
            361: {
              h: "68",
              p: "no-repeat",
              x: "visible",
              a: 7,
              q: "100% 100%",
              b: 6,
              j: "absolute",
              r: "inline",
              bF: "357",
              z: 2,
              dB: "img",
              d: 23,
              k: "div",
              cQ: 0.5,
              c: 17,
              aP: "pointer",
              cR: 0.5,
              bD: "auto",
            },
            425: {
              h: "70",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 13,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "424",
              dB: "img",
              d: 9,
              i: "krestm",
              cQ: 0.5,
              k: "div",
              c: 8,
              aP: "pointer",
              cR: 0.5,
            },
            440: {
              cN: "none",
              Q: 0,
              x: "visible",
              R: "#000",
              a: 0,
              b: 0,
              j: "absolute",
              bF: "439",
              z: 12,
              T: 0,
              S: 0,
              d: 32,
              k: "div",
              cQ: 1,
              c: 159,
              aP: "auto",
              cR: 1,
              gg: "1",
            },
            433: {
              h: "279",
              p: "no-repeat",
              x: "visible",
              a: 146,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "432",
              b: 43,
              d: 78.5,
              k: "div",
              c: 106.5,
            },
            354: {
              h: "265",
              p: "no-repeat",
              x: "visible",
              a: 113,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "350",
              b: 7,
              d: 108,
              k: "div",
              c: 70,
            },
            418: {
              x: "hidden",
              b: 180,
              k: "div",
              c: 290,
              d: 172,
              z: 2,
              r: "inline",
              a: 15,
              bS: 343,
              j: "absolute",
              bF: "417",
            },
            441: {
              cN: "none",
              h: "29",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "440",
              dB: "img",
              d: 37,
              k: "div",
              cQ: 1,
              c: 149,
              aP: "auto",
              cR: 1,
            },
            362: {
              c: 35,
              d: 35,
              r: "inline",
              I: "Solid",
              cQ: 0.9,
              J: "Solid",
              K: "Solid",
              cR: 0.9,
              g: "#D0001E",
              L: "Solid",
              M: 0,
              bF: "357",
              N: 0,
              A: "#1E2B46",
              x: "visible",
              j: "absolute",
              B: "#1E2B46",
              P: 0,
              O: 0,
              C: "#1E2B46",
              z: 1,
              aJ: 20,
              D: "#1E2B46",
              aK: 20,
              k: "div",
              aI: 20,
              a: 0,
              aL: 20,
              b: 0,
            },
            426: {
              h: "68",
              p: "no-repeat",
              x: "visible",
              a: 7,
              q: "100% 100%",
              b: 6,
              j: "absolute",
              r: "inline",
              bF: "424",
              z: 2,
              dB: "img",
              d: 23,
              k: "div",
              cQ: 0.5,
              c: 17,
              aP: "pointer",
              cR: 0.5,
              bD: "auto",
            },
            347: {
              cN: "none",
              x: "visible",
              a: 0,
              bS: 383,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 6,
              d: 480,
              aP: "auto",
            },
            370: {
              h: "257",
              p: "no-repeat",
              x: "visible",
              a: -14,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "369",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
            434: {
              h: "265",
              p: "no-repeat",
              x: "visible",
              a: 113,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "432",
              b: 7,
              d: 108,
              k: "div",
              c: 70,
            },
            355: {
              cN: "none",
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 1,
              d: 480,
              bF: "348",
              aY: 90,
              e: -0.0,
              aP: "auto",
            },
            419: {
              h: "274",
              p: "no-repeat",
              x: "visible",
              a: -14,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "418",
              b: 0,
              d: 171.123,
              k: "div",
              c: 320,
            },
            442: {
              c: 320,
              bS: 18,
              d: 480,
              r: "inline",
              I: "None",
              J: "None",
              K: "None",
              g: "#782573",
              L: "None",
              aP: "auto",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 1,
              k: "div",
              D: "#D8DDE4",
              aK: 0,
              cN: "none",
              a: 0,
              b: 0,
            },
            363: {
              c: 290,
              bS: 18,
              d: 331,
              r: "inline",
              I: "None",
              J: "None",
              K: "None",
              g: "#FFB200",
              L: "None",
              aP: "auto",
              M: 0,
              bF: "355",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 1,
              k: "div",
              D: "#D8DDE4",
              aK: 0,
              cN: "none",
              a: 15,
              b: 16,
            },
            427: {
              c: 35,
              d: 35,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#181E39",
              L: "Solid",
              aP: "pointer",
              M: 0,
              bF: "424",
              N: 0,
              A: "#1E2B46",
              x: "visible",
              j: "absolute",
              B: "#1E2B46",
              P: 0,
              O: 0,
              C: "#1E2B46",
              z: 5,
              dB: "button",
              D: "#1E2B46",
              aA: { a: [{ p: 4, h: "76" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            348: {
              cN: "none",
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 16,
              d: 480,
              bF: "347",
              aP: "auto",
            },
            371: {
              h: "262",
              p: "no-repeat",
              x: "visible",
              a: -15,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "369",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
            435: {
              h: "269",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "432",
              b: -17,
              d: 123.5,
              k: "div",
              c: 117.5,
            },
            356: {
              c: 287,
              d: 161,
              cQ: 1.05,
              aO: "0",
              cR: 1.05,
              bE: "7",
              aH: "1",
              aP: "pointer",
              i: "videom",
              bF: "58",
              aQ: "1",
              j: "absolute",
              dA: "1",
              x: "visible",
              aR: "1",
              aA: { a: [{ p: 4, h: "65" }] },
              k: "video",
              dB: "button",
              z: 4,
              a: 0,
              b: 1,
            },
            443: {
              c: 320,
              bS: 287,
              d: 300,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#FF9300",
              L: "Solid",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 7,
              dB: "button",
              D: "#D8DDE4",
              aA: { a: [{ p: 4, h: "65" }] },
              k: "div",
              a: 0,
              b: 180,
            },
            364: {
              x: "hidden",
              b: 180,
              k: "div",
              c: 290,
              d: 172,
              z: 2,
              r: "inline",
              a: 15,
              bS: 343,
              j: "absolute",
              bF: "355",
            },
            428: {
              h: "72",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 11,
              j: "absolute",
              r: "inline",
              bF: "424",
              cY: "1",
              z: 4,
              d: 13,
              dB: "img",
              i: "onm",
              cQ: 0.5,
              k: "div",
              c: 8,
              cR: 0.5,
            },
            349: {
              cN: "none",
              x: "visible",
              a: 30,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 6,
              d: 480,
              bF: "348",
              aY: 90,
              e: 0,
              aP: "auto",
            },
            372: {
              h: "274",
              p: "no-repeat",
              x: "visible",
              a: -14,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "369",
              b: 0,
              d: 171.123,
              k: "div",
              c: 320,
            },
            436: {
              h: "267",
              p: "no-repeat",
              x: "visible",
              a: 44,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "432",
              b: -3,
              d: 127.5,
              k: "div",
              c: 119.5,
            },
            357: {
              x: "visible",
              k: "div",
              c: 35,
              aP: "auto",
              cN: "none",
              d: 35,
              z: 5,
              a: 246,
              j: "absolute",
              bF: "58",
              b: 8,
            },
            380: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "379",
              b: 0,
              z: 2,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            365: {
              h: "274",
              p: "no-repeat",
              x: "visible",
              a: -14,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "364",
              b: 0,
              d: 171.123,
              k: "div",
              c: 320,
            },
            429: {
              c: 35,
              d: 35,
              r: "inline",
              I: "Solid",
              cQ: 0.9,
              J: "Solid",
              K: "Solid",
              cR: 0.9,
              g: "#D0001E",
              L: "Solid",
              M: 0,
              bF: "424",
              N: 0,
              A: "#1E2B46",
              x: "visible",
              j: "absolute",
              B: "#1E2B46",
              P: 0,
              O: 0,
              C: "#1E2B46",
              z: 1,
              aJ: 20,
              D: "#1E2B46",
              aK: 20,
              k: "div",
              aI: 20,
              a: 0,
              aL: 20,
              b: 0,
            },
            373: {
              h: "259",
              p: "no-repeat",
              x: "visible",
              a: -14,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "369",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
            437: {
              c: 320,
              bS: 319,
              d: 480,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#00F900",
              L: "Solid",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 5,
              dB: "button",
              D: "#D8DDE4",
              aA: { a: [{ p: 4, h: "65" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            358: {
              h: "72",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 11,
              j: "absolute",
              r: "inline",
              bF: "357",
              cY: "1",
              z: 4,
              d: 13,
              dB: "img",
              i: "onm",
              cQ: 0.5,
              k: "div",
              c: 8,
              cR: 0.5,
            },
            381: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 0,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "379",
              b: 0,
              z: 4,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            366: {
              h: "259",
              p: "no-repeat",
              x: "visible",
              a: -14,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "364",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
            374: {
              cN: "none",
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 319,
              k: "div",
              z: 14,
              d: 480,
              bF: "347",
              aP: "auto",
            },
            438: {
              cN: "none",
              x: "visible",
              a: 0,
              bS: 351,
              b: 367,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 4,
              d: 113,
              aP: "auto",
            },
            359: {
              h: "70",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 13,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "357",
              dB: "img",
              d: 9,
              i: "krestm",
              cQ: 0.5,
              k: "div",
              c: 8,
              aP: "pointer",
              cR: 0.5,
            },
            382: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "379",
              b: 0,
              z: 5,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            367: {
              h: "262",
              p: "no-repeat",
              x: "visible",
              a: -15,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "364",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
            390: {
              p: "no-repeat",
              tY: 1,
              b: 29,
              q: "100% 100%",
              c: 65,
              d: 144,
              r: "inline",
              e: 0.6,
              cQ: 1,
              cR: 1,
              h: "168",
              aY: 180,
              bF: "387",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 1,
              tX: 0.5,
              a: 33,
              bR: 0,
            },
            375: {
              cN: "none",
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 319,
              k: "div",
              z: 4,
              d: 480,
              bF: "374",
              aY: 0,
              e: 1,
              aP: "auto",
            },
            439: {
              bZ: 180,
              c: 159,
              bS: 383,
              d: 32,
              cQ: 1.1,
              e: 0,
              gg: "1",
              cA: false,
              cR: 1.1,
              aP: "auto",
              bF: "438",
              j: "absolute",
              x: "visible",
              k: "div",
              bX: false,
              Q: 10,
              z: 1,
              R: "rgba(0, 0, 0, 0.147)",
              cN: "none",
              bY: 1,
              S: -4,
              a: 80,
              cV: [],
              T: 4,
              b: 62,
            },
            383: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 0,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "379",
              b: 0,
              z: 6,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0.99791011,
              k: "div",
              c: 119,
              cR: 1.30023101,
              tX: 0.5,
            },
            368: {
              h: "257",
              p: "no-repeat",
              x: "visible",
              a: -14,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "364",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
            391: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "387",
              b: 0,
              z: 2,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            376: {
              cN: "none",
              x: "visible",
              a: 0,
              bS: 343,
              b: 111,
              j: "absolute",
              r: "inline",
              c: 319,
              k: "div",
              z: 2,
              d: 313,
              bF: "375",
              aP: "auto",
            },
            384: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "379",
              b: 0,
              z: 7,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0.0020898859,
              k: "div",
              c: 119,
              cR: 0.7010396,
              tX: 0.5,
            },
            369: {
              x: "hidden",
              bS: 343,
              a: 15,
              b: 180,
              j: "absolute",
              cY: "0",
              bF: "355",
              k: "div",
              z: 3,
              d: 172,
              r: "inline",
              c: 290,
              e: 1,
            },
            392: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 0,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "387",
              b: 0,
              z: 4,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            377: {
              h: "156",
              p: "no-repeat",
              x: "visible",
              a: 27,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "376",
              b: 150,
              d: 156,
              k: "div",
              c: 213,
            },
            385: {
              p: "no-repeat",
              tY: 1,
              b: 29,
              q: "100% 100%",
              c: 65,
              d: 144,
              r: "inline",
              e: 0.6,
              cQ: 1,
              cR: 1,
              h: "168",
              aY: 180,
              bF: "379",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 1,
              tX: 0.5,
              a: 33,
              bR: 0,
            },
            393: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "387",
              b: 0,
              z: 5,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            378: {
              c: 249,
              d: 325,
              r: "inline",
              e: 1,
              cQ: 0.55,
              gg: "0",
              f: 0,
              cR: 0.55,
              aY: 0,
              bF: "376",
              j: "absolute",
              x: "visible",
              k: "div",
              Q: 0,
              z: 4,
              R: "#000",
              S: 0,
              a: -3,
              T: 0,
              b: -49,
            },
            386: {
              c: 249,
              d: 325,
              r: "inline",
              e: 1,
              cQ: 0.55,
              gg: "0",
              f: 0,
              cR: 0.55,
              aY: 0,
              bF: "376",
              j: "absolute",
              x: "visible",
              k: "div",
              Q: 0,
              z: 2,
              R: "#000",
              S: 0,
              a: -3,
              T: 0,
              b: -49,
            },
            394: {
              c: 249,
              d: 325,
              r: "inline",
              e: 1,
              cQ: 0.55,
              gg: "0",
              f: 0,
              cR: 0.55,
              aY: 0,
              bF: "376",
              j: "absolute",
              x: "visible",
              k: "div",
              Q: 0,
              z: 3,
              R: "#000",
              S: 0,
              a: -3,
              T: 0,
              b: -49,
            },
            379: {
              x: "visible",
              tY: 0.8,
              a: 54,
              b: 110,
              j: "absolute",
              bF: "378",
              gW: 7,
              z: 2,
              k: "div",
              d: 183,
              c: 129,
              cQ: 2,
              bL: 1.31341912,
              e: 0,
              cR: 1.30769231,
              tX: 0.5,
            },
            387: {
              x: "visible",
              tY: 0.8,
              a: 54,
              b: 110,
              j: "absolute",
              bF: "386",
              gW: 7,
              z: 2,
              k: "div",
              d: 183,
              c: 129,
              cQ: 2,
              bL: 1.31341912,
              e: 0,
              cR: 1.30769231,
              tX: 0.5,
            },
            395: {
              x: "visible",
              tY: 0.8,
              a: 54,
              b: 110,
              j: "absolute",
              bF: "394",
              gW: 7,
              z: 2,
              k: "div",
              d: 183,
              c: 129,
              cQ: 2,
              bL: 1.31341912,
              e: 0,
              cR: 1.30769231,
              tX: 0.5,
            },
            388: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 0,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "387",
              b: 0,
              z: 6,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0.99791011,
              k: "div",
              c: 119,
              cR: 1.30023101,
              tX: 0.5,
            },
            400: {
              p: "no-repeat",
              tY: 1,
              b: 29,
              q: "100% 100%",
              c: 65,
              d: 144,
              r: "inline",
              e: 0.6,
              cQ: 1,
              cR: 1,
              h: "168",
              aY: 180,
              bF: "395",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 1,
              tX: 0.5,
              a: 33,
              bR: 0,
            },
            396: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 0,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "395",
              b: 0,
              z: 4,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            389: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "387",
              b: 0,
              z: 7,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0.0020898859,
              k: "div",
              c: 119,
              cR: 0.7010396,
              tX: 0.5,
            },
            401: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "395",
              b: 0,
              z: 2,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            397: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "395",
              b: 0,
              z: 5,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 119,
              cR: 2.5,
              tX: 0.5,
            },
            402: {
              cN: "none",
              x: "visible",
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 2,
              d: 480,
              bF: "374",
              aY: 0,
              e: 1,
              aP: "auto",
            },
            398: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 0,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "395",
              b: 0,
              z: 6,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0.99791011,
              k: "div",
              c: 119,
              cR: 1.30023101,
              tX: 0.5,
            },
            410: {
              h: "162",
              p: "no-repeat",
              x: "visible",
              a: 71,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "409",
              dB: "img",
              d: 65,
              k: "div",
              c: 177,
              e: 0,
            },
            403: {
              cN: "none",
              x: "visible",
              a: 253,
              b: 28,
              j: "absolute",
              r: "none",
              c: 35,
              k: "div",
              z: 7,
              d: 35,
              bF: "402",
              aP: "auto",
            },
            399: {
              h: "168",
              p: "no-repeat",
              tY: 1,
              a: 10,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "395",
              b: 0,
              z: 7,
              d: 183,
              dB: "img",
              cQ: 1,
              e: 0.0020898859,
              k: "div",
              c: 119,
              cR: 0.7010396,
              tX: 0.5,
            },
            411: {
              h: "160",
              p: "no-repeat",
              x: "visible",
              a: 113,
              q: "100% 100%",
              b: 81,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "409",
              dB: "img",
              d: 19,
              k: "div",
              c: 93,
              e: 0,
            },
            317: {
              cS: true,
              x: "hidden",
              a: 15,
              cA: false,
              b: 14,
              j: "absolute",
              r: "inline",
              c: 290,
              k: "div",
              z: 4,
              cL: "317",
              d: 167,
              bF: "417",
              bY: 1,
              bZ: 180,
              cM: true,
              bX: false,
              cK: { a: [{ b: "445", p: 3, z: false, symbolOid: "58" }] },
              cV: [],
            },
            404: {
              h: "68",
              p: "no-repeat",
              x: "visible",
              a: 7,
              q: "100% 100%",
              b: 6,
              j: "absolute",
              r: "inline",
              bF: "403",
              z: 2,
              dB: "img",
              d: 23,
              k: "div",
              cQ: 0.5,
              c: 17,
              aP: "pointer",
              cR: 0.5,
              bD: "auto",
            },
            412: {
              x: "hidden",
              k: "div",
              c: 0,
              d: 93,
              z: 3,
              a: 16,
              j: "absolute",
              bF: "402",
              b: 164,
            },
            420: {
              h: "259",
              p: "no-repeat",
              x: "visible",
              a: -14,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "418",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
            405: {
              c: 35,
              d: 35,
              r: "inline",
              I: "Solid",
              cQ: 0.9,
              J: "Solid",
              K: "Solid",
              cR: 0.9,
              g: "#D0001E",
              L: "Solid",
              M: 0,
              bF: "403",
              N: 0,
              A: "#1E2B46",
              x: "visible",
              j: "absolute",
              B: "#1E2B46",
              P: 0,
              O: 0,
              C: "#1E2B46",
              z: 1,
              aJ: 20,
              D: "#1E2B46",
              aK: 20,
              k: "div",
              aI: 20,
              a: 0,
              aL: 20,
              b: 0,
            },
            413: {
              h: "164",
              p: "no-repeat",
              x: "visible",
              a: 46,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "412",
              b: 0,
              d: 93,
              k: "div",
              c: 196,
            },
            421: {
              h: "257",
              p: "no-repeat",
              x: "visible",
              a: -14,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "418",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
            406: {
              h: "70",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 13,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "403",
              dB: "img",
              d: 9,
              k: "div",
              cQ: 0.5,
              c: 8,
              aP: "pointer",
              cR: 0.5,
            },
            350: {
              x: "visible",
              k: "div",
              c: 252.5,
              d: 141.5,
              z: 1,
              e: 0,
              a: 31,
              j: "absolute",
              bF: "349",
              b: 278,
            },
            414: {
              h: "158",
              p: "no-repeat",
              x: "visible",
              a: 184,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "402",
              b: 377,
              d: 31,
              k: "div",
              c: 99,
            },
            422: {
              h: "262",
              p: "no-repeat",
              x: "visible",
              a: -15,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "418",
              dB: "img",
              d: 171.123,
              k: "div",
              c: 320,
              e: 1,
            },
          },
        },
      ],
      {
        317: ["423", "424", "425", "426", "427", "428", "429"],
        58: ["356", "357", "358", "359", "360", "361", "362"],
      },
      h,
      {
        k: { p: 0, q: [[0, 0, 0.895, 0.03, 0.685, 0.22, 1, 1]] },
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
