(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/LaRoche_Posay_Tinder",
      f = "La_Roche_Posay_320x480_Tiner_Man_adaptive",
      g = "larocheposay320x480tinermanadaptive_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotosite();\n\n}",
        identifier: "39",
      },
      {
        name: "action1",
        source:
          "function(hypeDocument, element, event) {\t\n\t\nwindow.action1();\n}",
        identifier: "288",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        10: { p: 1, n: "bg_sun.jpg", g: "22", t: "@1x" },
        2: { p: 1, n: "text1_2.svg", g: "190", t: "image/svg+xml" },
        15: {
          n: "lrp-suncare-uvair_studioai_textureflying.mp4",
          g: "295",
          t: "video/mp4",
        },
        "-2": { n: "blank.gif" },
        3: { p: 1, n: "text1_1.svg", g: "192", t: "image/svg+xml" },
        11: { p: 1, n: "BUBBLES.jpg", g: "20", t: "@1x" },
        4: { p: 1, n: "buble_.png", g: "194", t: "@1x" },
        5: { p: 1, n: "text2_1.svg", g: "34", t: "image/svg+xml" },
        12: { p: 1, n: "t2_2.svg", g: "289", t: "image/svg+xml" },
        6: { p: 1, n: "text2_2.svg", g: "32", t: "image/svg+xml" },
        13: { p: 1, n: "dis.png", g: "18", t: "@1x" },
        7: { p: 1, n: "prod_2.png", g: "196", t: "@1x" },
        "-1": { n: "PIE.htc" },
        0: { p: 1, n: "logo_.svg", g: "16", t: "image/svg+xml" },
        8: { p: 1, n: "text3_1.svg", g: "30", t: "image/svg+xml" },
        14: { p: 1, n: "man_.webp", g: "185", t: "@1x" },
        1: { p: 1, n: "logos.svg", g: "188", t: "image/svg+xml" },
        9: { p: 1, n: "text3_2.svg", g: "28", t: "image/svg+xml" },
      },
      l,
      [
        "<style>\n    @font-face {\n        font-family: 'GothamProBold';\n        src:url('${Fonts}/futuratot-bol-webfont.ttf') format('truetype'),\n    }\n</style>",
        "<style>\n    @font-face {\n        font-family: 'Gotham';\n        src: url('${Fonts}/futuratot-bol-webfont.eot?#iefix') format('embedded-opentype'),\n                }\n</style>",
      ],
      e,
      [{ n: "Untitled Scene", o: "1", X: [0] }],
      [
        {
          o: "3",
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {},
          T: {
            153: {
              q: false,
              z: 6,
              i: "153",
              n: "pulse",
              a: [
                {
                  f: "c",
                  p: 2,
                  y: 6,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "153", p: 3, z: false, symbolOid: "2" }] },
                  o: "153",
                },
              ],
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              j: {
                3: [[388, 275, 388, 275, 388, 275, 388, 275]],
                1: [[215, 311, 215, 311, 215, 311, 215, 311]],
                4: [
                  [388, 275, 388, 275, 367, 221, 322, 249],
                  [322, 249, 248, 295, 161, 265, 161, 265],
                ],
                2: [
                  [215, 311, 215, 311, 283, 333, 322, 324],
                  [322, 324, 369, 315, 388, 275, 388, 275],
                ],
                0: [
                  [224, 422, 224, 422, 242, 400, 236, 379],
                  [236, 379, 230, 358, 198, 353, 198, 340],
                  [198, 340, 198, 319, 215, 311, 215, 311],
                ],
              },
              q: false,
              z: 17.15,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "309" },
                { f: "p", y: 0, z: 1, i: "b", e: 55, s: 144, o: "309" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "305" },
                { f: "c", y: 0, z: 1, i: "a", e: 20, s: -270, o: "305" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "305" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "318" },
                { y: 0, i: "b", s: 73, z: 0, o: "305", f: "c" },
                { f: "c", y: 0, z: 1.16, i: "cQ", e: 1, s: 0.8, o: "322" },
                { f: "c", y: 0, z: 1.16, i: "cR", e: 1, s: 0.8, o: "322" },
                { f: "c", y: 0, z: 1.16, i: "a", e: 84, s: 320, o: "322" },
                { f: "c", y: 0, z: 2.12, i: "e", e: 1, s: 0, o: "313" },
                { f: "p", y: 0, z: 1.16, i: "b", e: 158, s: 158, o: "322" },
                { f: "c", y: 0, z: 2.12, i: "cQ", e: 0.6, s: 0.4, o: "313" },
                { f: "c", y: 0, z: 2.12, i: "cR", e: 0.6, s: 0.4, o: "313" },
                {
                  o: "313",
                  y: 0,
                  z: 2.12,
                  i: "a",
                  e: 103.75,
                  a: "0",
                  f: "q",
                  s: 112.75,
                },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "305" },
                {
                  o: "313",
                  y: 0,
                  z: 2.12,
                  i: "b",
                  e: 180,
                  a: "0",
                  f: "q",
                  s: 291,
                },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "319" },
                { f: "c", y: 0, z: 1.16, i: "e", e: 1, s: 0, o: "322" },
                { f: "c", y: 1, z: 3.04, i: "cQ", e: 1, s: 1, o: "305" },
                { f: "c", y: 1, z: 3.04, i: "cR", e: 1, s: 1, o: "305" },
                { f: "c", y: 1, z: 3.04, i: "a", e: 20, s: 20, o: "305" },
                { y: 1, i: "b", s: 55, z: 0, o: "309", f: "c" },
                { f: "c", y: 1, z: 2.1, i: "e", e: 1, s: 1, o: "318" },
                { f: "c", y: 1, z: 1, i: "e", e: 1, s: 0, o: "310" },
                { f: "c", y: 1, z: 3.04, i: "e", e: 1, s: 1, o: "305" },
                { f: "c", y: 1, z: 2.1, i: "e", e: 1, s: 1, o: "319" },
                { f: "c", y: 1, z: 2.17, i: "e", e: 1, s: 1, o: "309" },
                { f: "c", y: 1.16, z: 2.26, i: "cQ", e: 1, s: 1, o: "322" },
                { f: "c", y: 1.16, z: 2.26, i: "cR", e: 1, s: 1, o: "322" },
                { f: "c", y: 1.16, z: 2.26, i: "a", e: 84, s: 84, o: "322" },
                { f: "c", y: 1.16, z: 2.26, i: "b", e: 158, s: 158, o: "322" },
                { f: "c", y: 1.16, z: 2.26, i: "e", e: 1, s: 1, o: "322" },
                { f: "c", y: 2, z: 2.27, i: "e", e: 1, s: 1, o: "310" },
                { f: "c", y: 2.12, z: 6.03, i: "cQ", e: 0.6, s: 0.6, o: "313" },
                { f: "c", y: 2.12, z: 6.03, i: "cR", e: 0.6, s: 0.6, o: "313" },
                {
                  o: "313",
                  y: 2.12,
                  z: 1.18,
                  i: "a",
                  e: 103.75,
                  a: "1",
                  f: "c",
                  s: 103.75,
                },
                {
                  o: "313",
                  y: 2.12,
                  z: 1.18,
                  i: "b",
                  e: 180,
                  a: "1",
                  f: "c",
                  s: 180,
                },
                { f: "c", y: 2.12, z: 1.18, i: "e", e: 1, s: 1, o: "313" },
                { f: "c", y: 3.1, z: 1, i: "e", e: 0, s: 1, o: "318" },
                { f: "c", y: 3.1, z: 1, i: "e", e: 0, s: 1, o: "319" },
                { f: "q", y: 3.17, z: 2, i: "cR", e: 1, s: 1.3, o: "301" },
                { f: "q", y: 3.17, z: 2, i: "cQ", e: 1, s: 1.3, o: "301" },
                { f: "c", y: 3.17, z: 2, i: "e", e: 1, s: 0, o: "301" },
                { f: "c", y: 3.17, z: 2, i: "e", e: 0, s: 1, o: "309" },
                { f: "c", y: 3.2, z: 0.3, i: "e", e: 1, s: 0, o: "320" },
                {
                  o: "313",
                  y: 4,
                  z: 2,
                  i: "a",
                  e: 276.75,
                  a: "2",
                  f: "c",
                  s: 103.75,
                },
                {
                  o: "313",
                  y: 4,
                  z: 2,
                  i: "b",
                  e: 144,
                  a: "2",
                  f: "c",
                  s: 180,
                },
                { f: "c", y: 4, z: 2, i: "e", e: 0, s: 1, o: "313" },
                { f: "c", y: 4.04, z: 1.08, i: "cQ", e: 0.8, s: 1, o: "305" },
                { f: "c", y: 4.04, z: 1.08, i: "cR", e: 0.8, s: 1, o: "305" },
                { f: "c", y: 4.04, z: 1.08, i: "a", e: 144, s: 20, o: "305" },
                { f: "c", y: 4.04, z: 1.08, i: "e", e: 0, s: 1, o: "305" },
                { y: 4.1, i: "e", s: 0, z: 0, o: "318", f: "c" },
                { y: 4.1, i: "e", s: 0, z: 0, o: "319", f: "c" },
                { f: "c", y: 4.12, z: 1.08, i: "cR", e: 1, s: 1, o: "322" },
                { f: "c", y: 4.12, z: 1.08, i: "a", e: 331, s: 84, o: "322" },
                { f: "c", y: 4.12, z: 1.08, i: "b", e: 158, s: 158, o: "322" },
                { f: "c", y: 4.12, z: 1.08, i: "cQ", e: 1, s: 1, o: "322" },
                { f: "c", y: 4.12, z: 1.08, i: "e", e: 0, s: 1, o: "322" },
                { f: "c", y: 4.17, z: 1.08, i: "b", e: 46, s: 46, o: "324" },
                { f: "c", y: 4.17, z: 1.08, i: "cR", e: 1, s: 0.8, o: "324" },
                { f: "c", y: 4.17, z: 1.08, i: "a", e: 195, s: 342, o: "324" },
                { f: "c", y: 4.17, z: 1.08, i: "cQ", e: 1, s: 0.8, o: "324" },
                { f: "c", y: 4.17, z: 1.08, i: "e", e: 1, s: 0, o: "324" },
                { f: "c", y: 4.2, z: 11.25, i: "e", e: 1, s: 1, o: "320" },
                { f: "c", y: 4.27, z: 1, i: "e", e: 0, s: 1, o: "310" },
                { f: "q", y: 5, z: 4.07, i: "a", e: 52, s: 52, o: "314" },
                { f: "q", y: 5, z: 4.07, i: "b", e: 162, s: 140, o: "314" },
                { f: "c", y: 5, z: 1.08, i: "cQ", e: 1, s: 0.8, o: "304" },
                { f: "c", y: 5, z: 1.08, i: "cR", e: 1, s: 0.8, o: "304" },
                { f: "c", y: 5, z: 1.08, i: "a", e: 21, s: -212, o: "304" },
                { f: "c", y: 5, z: 1.08, i: "b", e: 90, s: 90, o: "304" },
                { f: "q", y: 5, z: 1.25, i: "e", e: 1, s: 0, o: "314" },
                { f: "c", y: 5, z: 1.08, i: "e", e: 1, s: 0, o: "304" },
                { y: 5.12, i: "cQ", s: 0.8, z: 0, o: "305", f: "c" },
                { y: 5.12, i: "cR", s: 0.8, z: 0, o: "305", f: "c" },
                { y: 5.12, i: "a", s: 144, z: 0, o: "305", f: "c" },
                { y: 5.12, i: "e", s: 0, z: 0, o: "305", f: "c" },
                { y: 5.17, i: "cR", s: 1, z: 0, o: "301", f: "c" },
                { y: 5.17, i: "cQ", s: 1, z: 0, o: "301", f: "c" },
                { f: "c", y: 5.17, z: 10.28, i: "e", e: 1, s: 1, o: "301" },
                { y: 5.17, i: "e", s: 0, z: 0, o: "309", f: "c" },
                { y: 5.2, i: "b", s: 158, z: 0, o: "322", f: "c" },
                { y: 5.2, i: "a", s: 331, z: 0, o: "322", f: "c" },
                { y: 5.2, i: "cQ", s: 1, z: 0, o: "322", f: "c" },
                { y: 5.2, i: "cR", s: 1, z: 0, o: "322", f: "c" },
                { y: 5.2, i: "e", s: 0, z: 0, o: "322", f: "c" },
                { y: 5.25, i: "b", s: 46, z: 0, o: "324", f: "c" },
                { f: "c", y: 5.25, z: 2.09, i: "cR", e: 1, s: 1, o: "324" },
                { y: 5.25, i: "a", s: 195, z: 0, o: "324", f: "c" },
                { f: "c", y: 5.25, z: 2.09, i: "cQ", e: 1, s: 1, o: "324" },
                { f: "c", y: 5.25, z: 2.09, i: "e", e: 1, s: 1, o: "324" },
                { y: 5.27, i: "e", s: 0, z: 0, o: "310", f: "c" },
                {
                  o: "313",
                  y: 6,
                  z: 2.15,
                  i: "b",
                  e: 144,
                  a: "3",
                  f: "c",
                  s: 144,
                },
                {
                  o: "313",
                  y: 6,
                  z: 2.15,
                  i: "a",
                  e: 276.75,
                  a: "3",
                  f: "c",
                  s: 276.75,
                },
                { f: "c", y: 6, z: 2.15, i: "e", e: 0, s: 0, o: "313" },
                { f: "c", y: 6.08, z: 1.16, i: "cQ", e: 1, s: 1, o: "304" },
                { f: "c", y: 6.08, z: 1.16, i: "cR", e: 1, s: 1, o: "304" },
                { y: 6.08, i: "b", s: 90, z: 0, o: "304", f: "c" },
                { y: 6.08, i: "a", s: 21, z: 0, o: "304", f: "c" },
                { f: "c", y: 6.08, z: 1.16, i: "e", e: 1, s: 1, o: "304" },
                { f: "c", y: 6.25, z: 1.07, i: "e", e: 1, s: 1, o: "314" },
                { f: "q", y: 7.15, z: 2, i: "cR", e: 1, s: 1.3, o: "299" },
                { f: "q", y: 7.15, z: 2, i: "cQ", e: 1, s: 1.3, o: "299" },
                { f: "c", y: 7.15, z: 2, i: "e", e: 1, s: 0, o: "299" },
                { f: "v", y: 7.24, z: 1.1, i: "cR", e: 0.8, s: 1, o: "304" },
                { f: "v", y: 7.24, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "304" },
                { f: "c", y: 7.24, z: 1.1, i: "e", e: 0, s: 1, o: "304" },
                { f: "c", y: 8.02, z: 1.05, i: "e", e: 0, s: 1, o: "314" },
                {
                  f: "h",
                  y: 8.04,
                  z: 1.2,
                  i: "cQ",
                  e: 1,
                  s: 0.79214318,
                  o: "306",
                },
                {
                  f: "h",
                  y: 8.04,
                  z: 1.2,
                  i: "cR",
                  e: 1,
                  s: 0.79214318,
                  o: "306",
                },
                { f: "v", y: 8.04, z: 1.1, i: "cR", e: 0.8, s: 1, o: "324" },
                { f: "v", y: 8.04, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "324" },
                { f: "c", y: 8.04, z: 1.2, i: "e", e: 1, s: 0, o: "306" },
                { f: "c", y: 8.04, z: 1.1, i: "e", e: 0, s: 1, o: "324" },
                {
                  o: "313",
                  y: 8.15,
                  z: 2.01,
                  i: "b",
                  e: 134,
                  a: "4",
                  f: "q",
                  s: 144,
                },
                {
                  o: "313",
                  y: 8.15,
                  z: 2.01,
                  i: "a",
                  e: 49.75,
                  a: "4",
                  f: "q",
                  s: 276.75,
                },
                { f: "q", y: 8.15, z: 2.01, i: "cQ", e: 0.9, s: 0.6, o: "313" },
                { f: "q", y: 8.15, z: 2.01, i: "cR", e: 0.9, s: 0.6, o: "313" },
                { f: "q", y: 8.15, z: 2.01, i: "e", e: 1, s: 0, o: "313" },
                {
                  f: "h",
                  y: 8.24,
                  z: 1.2,
                  i: "cR",
                  e: 1,
                  s: 0.79715879,
                  o: "323",
                },
                {
                  f: "h",
                  y: 8.24,
                  z: 1.2,
                  i: "cQ",
                  e: 1,
                  s: 0.79715879,
                  o: "323",
                },
                { f: "c", y: 8.24, z: 1.2, i: "e", e: 1, s: 0, o: "323" },
                { y: 9.04, i: "cQ", s: 0.8, z: 0, o: "304", f: "c" },
                { y: 9.04, i: "cR", s: 0.8, z: 0, o: "304", f: "c" },
                { y: 9.04, i: "e", s: 0, z: 0, o: "304", f: "c" },
                { y: 9.07, i: "b", s: 162, z: 0, o: "314", f: "c" },
                { y: 9.07, i: "a", s: 52, z: 0, o: "314", f: "c" },
                { y: 9.07, i: "e", s: 0, z: 0, o: "314", f: "c" },
                { y: 9.14, i: "cR", s: 0.8, z: 0, o: "324", f: "c" },
                { y: 9.14, i: "cQ", s: 0.8, z: 0, o: "324", f: "c" },
                { y: 9.14, i: "e", s: 0, z: 0, o: "324", f: "c" },
                { y: 9.15, i: "cR", s: 1, z: 0, o: "299", f: "c" },
                { y: 9.15, i: "cQ", s: 1, z: 0, o: "299", f: "c" },
                { f: "c", y: 9.15, z: 7, i: "e", e: 1, s: 1, o: "299" },
                { f: "c", y: 9.24, z: 1.17, i: "cR", e: 1, s: 1, o: "306" },
                { f: "c", y: 9.24, z: 1.17, i: "cQ", e: 1, s: 1, o: "306" },
                { f: "c", y: 9.24, z: 1.17, i: "e", e: 1, s: 1, o: "306" },
                { f: "c", y: 10, z: 2, i: "cQ", e: 1, s: 0.8, o: "325" },
                { f: "c", y: 10, z: 2, i: "cR", e: 1, s: 0.8, o: "325" },
                { y: 10, p: 1, i: "Video Track", z: 6.13, o: "325", f: "c" },
                { f: "c", y: 10.14, z: 1.05, i: "cR", e: 1, s: 1, o: "323" },
                { f: "c", y: 10.14, z: 1.05, i: "cQ", e: 1, s: 1, o: "323" },
                { f: "c", y: 10.14, z: 1.05, i: "e", e: 1, s: 1, o: "323" },
                { y: 10.16, i: "b", s: 134, z: 0, o: "313", f: "c" },
                { y: 10.16, i: "a", s: 49.75, z: 0, o: "313", f: "c" },
                { y: 10.16, i: "cQ", s: 0.9, z: 0, o: "313", f: "c" },
                { y: 10.16, i: "cR", s: 0.9, z: 0, o: "313", f: "c" },
                { f: "c", y: 10.16, z: 4.14, i: "e", e: 1, s: 1, o: "313" },
                { f: "c", y: 11, z: 1.22, i: "e", e: 1, s: 0, o: "325" },
                {
                  f: "c",
                  y: 11.11,
                  z: 1,
                  i: "cR",
                  e: 0.79715879,
                  s: 1,
                  o: "306",
                },
                {
                  f: "c",
                  y: 11.11,
                  z: 1,
                  i: "cQ",
                  e: 0.79715879,
                  s: 1,
                  o: "306",
                },
                { f: "c", y: 11.11, z: 1, i: "e", e: 0, s: 1, o: "306" },
                {
                  f: "c",
                  y: 11.19,
                  z: 1,
                  i: "cQ",
                  e: 0.79715879,
                  s: 1,
                  o: "323",
                },
                {
                  f: "c",
                  y: 11.19,
                  z: 1,
                  i: "cR",
                  e: 0.79715879,
                  s: 1,
                  o: "323",
                },
                { f: "c", y: 11.19, z: 1, i: "e", e: 0, s: 1, o: "323" },
                { y: 12, i: "cQ", s: 1, z: 0, o: "325", f: "c" },
                { y: 12, i: "cR", s: 1, z: 0, o: "325", f: "c" },
                {
                  f: "h",
                  y: 12,
                  z: 1.2,
                  i: "cR",
                  e: 1,
                  s: 0.79214318,
                  o: "315",
                },
                {
                  f: "h",
                  y: 12,
                  z: 1.2,
                  i: "cQ",
                  e: 1,
                  s: 0.79214318,
                  o: "315",
                },
                { f: "c", y: 12, z: 1.2, i: "e", e: 1, s: 0, o: "315" },
                { y: 12.11, i: "cR", s: 0.79715879, z: 0, o: "306", f: "c" },
                { y: 12.11, i: "cQ", s: 0.79715879, z: 0, o: "306", f: "c" },
                { y: 12.11, i: "e", s: 0, z: 0, o: "306", f: "c" },
                { y: 12.19, i: "cR", s: 0.79715879, z: 0, o: "323", f: "c" },
                { y: 12.19, i: "cQ", s: 0.79715879, z: 0, o: "323", f: "c" },
                { y: 12.19, i: "e", s: 0, z: 0, o: "323", f: "c" },
                { f: "c", y: 12.22, z: 3.23, i: "e", e: 1, s: 1, o: "325" },
                { y: 13.2, i: "cR", s: 1, z: 0, o: "315", f: "c" },
                { y: 13.2, i: "cQ", s: 1, z: 0, o: "315", f: "c" },
                { f: "c", y: 13.2, z: 2.25, i: "e", e: 1, s: 1, o: "315" },
                { f: "c", y: 15, z: 1, i: "e", e: 0, s: 1, o: "313" },
                { y: 16, i: "e", s: 0, z: 0, o: "313", f: "c" },
                { f: "c", y: 16.15, z: 0.28, i: "e", e: 0, s: 1, o: "325" },
                { f: "c", y: 16.15, z: 1, i: "e", e: 0, s: 1, o: "320" },
                { f: "c", y: 16.15, z: 1, i: "e", e: 0, s: 1, o: "315" },
                { f: "c", y: 16.15, z: 1, i: "e", e: 0, s: 1, o: "301" },
                { f: "c", y: 16.15, z: 1, i: "e", e: 0, s: 1, o: "299" },
                { y: 17.13, i: "e", s: 0, z: 0, o: "325", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 17.15,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      {
                        i: 0,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 17.15, i: "e", s: 0, z: 0, o: "320", f: "c" },
                { y: 17.15, i: "e", s: 0, z: 0, o: "315", f: "c" },
                { y: 17.15, i: "e", s: 0, z: 0, o: "301", f: "c" },
                { y: 17.15, i: "e", s: 0, z: 0, o: "299", f: "c" },
              ],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "318",
            "325",
            "301",
            "299",
            "308",
            "326",
            "316",
            "311",
            "302",
            "303",
            "319",
            "317",
            "312",
            "307",
            "300",
            "298",
            "320",
            "309",
            "305",
            "304",
            "306",
            "313",
            "314",
            "322",
            "321",
            "315",
            "310",
            "323",
            "324",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            302: {
              x: "visible",
              k: "div",
              c: 320,
              d: 228,
              z: 32,
              r: "inline",
              a: 0,
              bS: 371,
              j: "absolute",
              b: 0,
            },
            323: {
              h: "28",
              p: "no-repeat",
              x: "visible",
              a: 96,
              q: "100% 100%",
              b: 32,
              j: "absolute",
              r: "inline",
              bF: "321",
              z: 7,
              dB: "img",
              d: 43,
              k: "div",
              cQ: 0.79715879,
              e: 0,
              c: 203,
              cR: 0.79715879,
            },
            315: {
              h: "289",
              p: "no-repeat",
              x: "visible",
              a: 28,
              q: "100% 100%",
              b: 409,
              j: "absolute",
              r: "inline",
              bF: "312",
              z: 15,
              dB: "img",
              d: 12,
              k: "div",
              cQ: 0.79214318,
              e: 0,
              c: 263,
              cR: 0.79214318,
            },
            307: {
              x: "visible",
              k: "div",
              c: 322,
              d: 480,
              z: 2,
              a: -1,
              bS: 63,
              j: "absolute",
              b: 0,
            },
            311: {
              c: 320,
              bS: 319,
              d: 480,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              k: "div",
              O: 1,
              C: "#D8DDE4",
              z: 39,
              P: 1,
              D: "#D8DDE4",
              a: -1,
              b: -1,
            },
            303: {
              x: "visible",
              k: "div",
              c: 320,
              d: 145,
              z: 31,
              r: "inline",
              a: 0,
              bS: 374,
              j: "absolute",
              b: 0,
            },
            324: {
              h: "32",
              p: "no-repeat",
              x: "visible",
              a: 342,
              q: "100% 100%",
              b: 46,
              j: "absolute",
              r: "inline",
              bF: "321",
              z: 8,
              dB: "img",
              d: 7,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 98,
              cR: 0.8,
            },
            316: {
              c: 320,
              bS: 319,
              d: 480,
              I: "None",
              e: 0,
              J: "None",
              K: "None",
              g: "#E8EBED",
              L: "None",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 40,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "39" },
                  { p: 4, h: "288" },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            308: {
              x: "visible",
              bF: "307",
              k: "div",
              c: 454,
              d: 480,
              z: 1,
              a: -131,
              bS: 447,
              j: "absolute",
              b: 0,
            },
            320: {
              h: "16",
              p: "no-repeat",
              x: "visible",
              a: 106,
              q: "100% 100%",
              b: 15,
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "317",
              dB: "img",
              d: 29,
              k: "div",
              c: 110,
              e: 0,
            },
            312: {
              x: "visible",
              bS: 383,
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              z: 19,
              k: "div",
              c: 320,
              d: 480,
              cQ: 1,
              e: 1,
              cR: 1,
            },
            304: {
              p: "no-repeat",
              c: 217,
              q: "100% 100%",
              d: 102,
              r: "inline",
              cQ: 0.8,
              s: "GothamProBold",
              e: 0,
              cR: 0.8,
              u: "normal",
              h: "34",
              v: "normal",
              w: "",
              bF: "303",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 3,
              a: -212,
              b: 90,
            },
            298: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 1,
              a: 0,
              bS: 447,
              j: "absolute",
              b: 0,
            },
            317: {
              x: "visible",
              k: "div",
              c: 320,
              d: 129,
              z: 30,
              r: "inline",
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            309: {
              h: "185",
              p: "no-repeat",
              x: "visible",
              a: 13,
              q: "100% 100%",
              bS: 191,
              j: "absolute",
              bF: "308",
              r: "inline",
              b: 144,
              z: 1,
              d: 425.333,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 547,
              cR: 1,
            },
            300: {
              c: 320,
              bS: 319,
              d: 480,
              I: "None",
              e: 0.85,
              J: "None",
              K: "None",
              L: "None",
              M: 0,
              bF: "298",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              l: 0,
              D: "#D8DDE4",
              m: "#51B1E6",
              k: "div",
              n: "#007CC1",
              a: 0,
              b: 0,
            },
            325: {
              dA: true,
              aR: true,
              x: "visible",
              a: 0,
              bE: "295",
              b: -79,
              j: "absolute",
              bF: "326",
              z: 1,
              aO: false,
              k: "video",
              d: 592,
              c: 333,
              cQ: 0.8,
              e: 0,
              cR: 0.8,
              aQ: false,
              aH: true,
            },
            321: {
              x: "visible",
              k: "div",
              c: 320,
              d: 107,
              z: 24,
              r: "inline",
              a: 0,
              bS: 347,
              j: "absolute",
              b: 373,
            },
            313: {
              h: "194",
              p: "no-repeat",
              tY: 0.5,
              a: 112.75,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "312",
              b: 291,
              z: 9,
              d: 262,
              dB: "img",
              cQ: 0.4,
              e: 0,
              k: "div",
              c: 222.5,
              cR: 0.4,
              tX: 0.5,
            },
            305: {
              h: "192",
              p: "no-repeat",
              x: "visible",
              a: -270,
              q: "100% 100%",
              b: 73,
              j: "absolute",
              r: "inline",
              bF: "303",
              z: 4,
              dB: "img",
              d: 60,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 280,
              cR: 0.8,
            },
            299: {
              h: "22",
              p: "no-repeat",
              x: "visible",
              a: -9,
              q: "100% 100%",
              b: -15,
              j: "absolute",
              r: "inline",
              cP: "blendmode-soft-light",
              bF: "298",
              z: 3,
              d: 507,
              dB: "img",
              cQ: 1.3,
              e: 0,
              k: "div",
              c: 338,
              cR: 1.3,
            },
            318: {
              c: 5690,
              d: 166,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#FFF",
              L: "Solid",
              M: 0,
              bF: "317",
              N: 0,
              A: "#D8DDE4",
              x: "visible",
              j: "absolute",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 5,
              k: "div",
              D: "#D8DDE4",
              a: -4644,
              b: -105,
            },
            326: {
              x: "hidden",
              k: "div",
              c: 333,
              d: 480,
              z: 10,
              a: -7,
              j: "absolute",
              bF: "312",
              b: 0,
            },
            301: {
              h: "20",
              p: "no-repeat",
              x: "visible",
              a: -10,
              q: "100% 100%",
              b: -15,
              j: "absolute",
              r: "inline",
              cP: "blendmode-luminosity",
              bF: "298",
              z: 4,
              d: 509,
              dB: "img",
              cQ: 1.3,
              e: 0,
              k: "div",
              c: 339,
              cR: 1.3,
            },
            322: {
              h: "190",
              p: "no-repeat",
              x: "visible",
              a: 320,
              q: "100% 100%",
              b: 158,
              j: "absolute",
              r: "inline",
              bF: "302",
              z: 3,
              dB: "img",
              d: 65,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 219,
              cR: 0.8,
            },
            314: {
              h: "196",
              p: "no-repeat",
              x: "visible",
              a: 52,
              q: "100% 100%",
              b: 140,
              j: "absolute",
              r: "inline",
              bF: "312",
              z: 14,
              dB: "img",
              d: 261,
              k: "div",
              cQ: 1,
              e: 0,
              c: 222,
              cR: 1,
            },
            306: {
              h: "30",
              p: "no-repeat",
              x: "visible",
              a: 28,
              q: "100% 100%",
              b: 86,
              j: "absolute",
              r: "inline",
              bF: "303",
              z: 2,
              dB: "img",
              d: 45,
              k: "div",
              cQ: 0.79214318,
              e: 0,
              c: 203,
              cR: 0.79214318,
            },
            319: {
              h: "188",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 2,
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "317",
              dB: "img",
              d: 55,
              k: "div",
              c: 320,
              e: 0,
            },
            310: {
              h: "18",
              p: "no-repeat",
              x: "visible",
              a: 72,
              q: "100% 100%",
              b: 34,
              j: "absolute",
              r: "inline",
              bF: "321",
              z: 6,
              dB: "img",
              d: 53,
              k: "div",
              cQ: 1,
              e: 0,
              c: 241,
              cR: 1,
            },
          },
        },
      ],
      {},
      h,
      {
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
        h: { p: 0, q: [[0, 0, 0.175, 0.885, 0.32, 1.25, 1, 1]] },
        v: { p: 0, q: [[0, 0, 0.455, 0.03, 0.515, 0.955, 1, 1]] },
      },
      null,
      false,
      true,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
