(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/LaRochePosay",
      f = "La_Roche_Posay_320x480_weather_trigger",
      g = "larocheposay320x480weathertrigger_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/larocheposay320x480weathertrigger_hype_generated_script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "blendmodes",
        source:
          "function(hypeDocument, element, event) {\t\n\tvar blendmodes = ['color', 'color-burn', 'color-dodge', 'darken', 'difference', 'exclusion', 'hard-light', 'hue', 'lighten', 'luminosity', 'multiply', 'normal', 'overlay', 'saturation', 'screen', 'soft-light'];\n\twhile (blendmodes.length) {\n\t\tvar blendmode = blendmodes.pop();\n\t\tvar nodes = element.querySelectorAll('.blendmode-'+blendmode);\n\t\tfor (i = 0; i < nodes.length; ++i) {\n\t\t\tnodes[i].parentNode.style.mixBlendMode = blendmode;\n\t\t}\n\t}\n}",
        identifier: "7",
      },
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotosite();\n\n}",
        identifier: "39",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        9: { n: "movie.mp4", g: "57", t: "video/mp4" },
        10: { p: 1, n: "bg_sun.jpg", g: "22", t: "@1x" },
        11: { p: 1, n: "BUBBLES.jpg", g: "20", t: "@1x" },
        0: { p: 1, n: "product_.png", g: "10", t: "@1x" },
        12: { p: 1, n: "bubbles_3.png", g: "97", t: "@1x" },
        1: { p: 1, n: "movie_text.svg", g: "12", t: "image/svg+xml" },
        2: { p: 1, n: "logo_.svg", g: "16", t: "image/svg+xml" },
        13: { p: 1, n: "bubbles_2.png", g: "99", t: "@1x" },
        3: { p: 1, n: "dis.svg", g: "18", t: "image/svg+xml" },
        14: { p: 1, n: "bubbles_1.png", g: "101", t: "@1x" },
        4: { p: 1, n: "2_3t.svg", g: "26", t: "image/svg+xml" },
        5: { p: 1, n: "2_2t.svg", g: "28", t: "image/svg+xml" },
        15: { p: 1, n: "pink.png", g: "24", t: "@1x" },
        6: { p: 1, n: "2_1t.svg", g: "30", t: "image/svg+xml" },
        16: { p: 1, n: "blue_top.png", g: "147", t: "@1x" },
        7: { p: 1, n: "1_2t.svg", g: "32", t: "image/svg+xml" },
        "-1": { n: "PIE.htc" },
        8: { p: 1, n: "1_1t.svg", g: "34", t: "image/svg+xml" },
        17: { p: 1, n: "blue_top%20copy.png", g: "149", t: "@1x" },
        "-2": { n: "blank.gif" },
      },
      l,
      [
        "<style>\n    @font-face {\n        font-family: 'GothamProBold';\n        src:url('${Fonts}/futuratot-bol-webfont.ttf') format('truetype'),\n    }\n</style>",
        "<style>\n    @font-face {\n        font-family: 'Gotham';\n        src: url('${Fonts}/futuratot-bol-webfont.eot?#iefix') format('embedded-opentype'),\n                }\n</style>",
      ],
      e,
      [
        { n: "Untitled Scene", o: "1", X: [0] },
        { n: "Untitled Scene Copy", o: "161", X: [1] },
      ],
      [
        {
          o: "3",
          A: { a: [{ p: 4, h: "7" }] },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {
            235: { V: { "Main Timeline": "242" }, W: "242", n: "bubbles_2" },
            239: { V: { "Main Timeline": "244" }, W: "244", n: "bubbles_1" },
            59: { V: { "Main Timeline": "241" }, W: "241", n: "movie" },
            237: { V: { "Main Timeline": "243" }, W: "243", n: "bubbles 3" },
          },
          T: {
            244: {
              c: "239",
              q: false,
              z: 4,
              i: "244",
              a: [
                { f: "c", y: 0, z: 2, i: "cQ", e: 1.05, s: 1, o: "240" },
                { f: "c", y: 0, z: 2, i: "cR", e: 1.05, s: 1, o: "240" },
                { f: "c", y: 2, z: 2, i: "cQ", e: 1, s: 1.05, o: "240" },
                { f: "c", y: 2, z: 2, i: "cR", e: 1, s: 1.05, o: "240" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "244", p: 3, z: false, symbolOid: "142" }] },
                  o: "244",
                },
                { y: 4, i: "cQ", s: 1, z: 0, o: "240", f: "c" },
                { y: 4, i: "cR", s: 1, z: 0, o: "240", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            243: {
              c: "237",
              q: false,
              z: 3,
              i: "243",
              a: [
                { f: "c", y: 0, z: 1.19, i: "b", e: -11, s: 0, o: "238" },
                { f: "c", y: 1.19, z: 1.11, i: "b", e: 0, s: -11, o: "238" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "243", p: 3, z: false, symbolOid: "103" }] },
                  o: "243",
                },
                { y: 3, i: "b", s: 0, z: 0, o: "238", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            153: {
              q: false,
              z: 6,
              i: "153",
              n: "pulse",
              a: [
                { f: "c", y: 0, z: 1, i: "cQ", e: 1.05, s: 1, o: "209" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1.05, s: 1, o: "209" },
                { f: "c", y: 0, z: 2, i: "b", e: 140, s: 62, o: "217" },
                { f: "c", y: 0, z: 2, i: "e", e: 1, s: 0, o: "219" },
                { f: "c", y: 0, z: 2, i: "b", e: 0, s: -34, o: "219" },
                { f: "c", y: 0.08, z: 2, i: "e", e: 1, s: 0, o: "218" },
                { f: "c", y: 0.08, z: 2, i: "b", e: 0, s: -34, o: "218" },
                { f: "c", y: 0.2, z: 2, i: "e", e: 1, s: 0, o: "220" },
                { f: "c", y: 0.2, z: 2, i: "b", e: 0, s: -34, o: "220" },
                { f: "c", y: 1, z: 1, i: "cR", e: 1, s: 1.05, o: "209" },
                { f: "c", y: 1, z: 1, i: "cQ", e: 1, s: 1.05, o: "209" },
                { f: "c", y: 2, z: 2, i: "cR", e: 1, s: 1, o: "209" },
                { f: "c", y: 2, z: 2, i: "cQ", e: 1, s: 1, o: "209" },
                { f: "c", y: 2, z: 2.23, i: "e", e: 1, s: 1, o: "219" },
                { y: 2, i: "b", s: 140, z: 0, o: "217", f: "c" },
                { y: 2, i: "b", s: 0, z: 0, o: "219", f: "c" },
                { f: "c", y: 2.08, z: 2.06, i: "e", e: 1, s: 1, o: "218" },
                { y: 2.08, i: "b", s: 0, z: 0, o: "218", f: "c" },
                { f: "c", y: 2.2, z: 1.1, i: "e", e: 1, s: 1, o: "220" },
                { y: 2.2, i: "b", s: 0, z: 0, o: "220", f: "c" },
                { f: "c", y: 4, z: 1, i: "cR", e: 1.05, s: 1, o: "209" },
                { f: "c", y: 4, z: 1, i: "cQ", e: 1.05, s: 1, o: "209" },
                { f: "c", y: 4, z: 1.06, i: "e", e: 0, s: 1, o: "220" },
                { f: "c", y: 4.14, z: 1.06, i: "e", e: 0, s: 1, o: "218" },
                { f: "c", y: 4.23, z: 1.06, i: "e", e: 0, s: 1, o: "219" },
                { f: "c", y: 5, z: 1, i: "cR", e: 1, s: 1.05, o: "209" },
                { f: "c", y: 5, z: 1, i: "cQ", e: 1, s: 1.05, o: "209" },
                { y: 5.06, i: "e", s: 0, z: 0, o: "220", f: "c" },
                { y: 5.2, i: "e", s: 0, z: 0, o: "218", f: "c" },
                { y: 5.29, i: "e", s: 0, z: 0, o: "219", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 6,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "153", p: 3, z: false, symbolOid: "2" }] },
                  o: "153",
                },
                { y: 6, i: "cR", s: 1, z: 0, o: "209", f: "c" },
                { y: 6, i: "cQ", s: 1, z: 0, o: "209", f: "c" },
              ],
              f: 30,
              b: [],
            },
            241: {
              b: [],
              c: "59",
              q: false,
              z: 7.2,
              i: "241",
              n: "Main Timeline",
              a: [{ y: 0, p: 1, i: "Video Track", z: 7.2, o: "212", f: "c" }],
              s: "59",
              f: 30,
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 15.29,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "59" },
                { f: "p", y: 0, z: 1, i: "b", e: -89, s: 0, o: "59" },
                { f: "c", y: 0, z: 1, i: "a", e: 160, s: 284, o: "226" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "226" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "226" },
                { f: "c", y: 0, z: 1.16, i: "c", e: 219, s: 18, o: "222" },
                { f: "c", y: 0, z: 1.16, i: "d", e: 65, s: 10, o: "222" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "226" },
                { f: "c", y: 0, z: 1.16, i: "a", e: 0, s: -197, o: "222" },
                { f: "c", y: 0, z: 1.16, i: "cQ", e: 1, s: 0.8, o: "222" },
                { f: "c", y: 0, z: 1.16, i: "cR", e: 1, s: 0.8, o: "222" },
                { f: "p", y: 0, z: 1.16, i: "b", e: 0, s: 27, o: "222" },
                { f: "c", y: 0, z: 1.16, i: "e", e: 1, s: 0, o: "222" },
                { y: 1, i: "b", s: -89, z: 0, o: "59", f: "c" },
                { f: "c", y: 1, z: 2.07, i: "cQ", e: 1, s: 1, o: "226" },
                { f: "c", y: 1, z: 2.07, i: "cR", e: 1, s: 1, o: "226" },
                { f: "c", y: 1, z: 2.07, i: "a", e: 160, s: 160, o: "226" },
                { f: "c", y: 1, z: 2, i: "e", e: 1, s: 1, o: "59" },
                { f: "c", y: 1, z: 2.07, i: "e", e: 1, s: 1, o: "226" },
                { f: "c", y: 1.16, z: 1.29, i: "c", e: 219, s: 219, o: "222" },
                { f: "c", y: 1.16, z: 1.29, i: "d", e: 65, s: 65, o: "222" },
                { f: "c", y: 1.16, z: 1.29, i: "cR", e: 1, s: 1, o: "222" },
                { f: "c", y: 1.16, z: 1.29, i: "a", e: 0, s: 0, o: "222" },
                { f: "c", y: 1.16, z: 1.29, i: "cQ", e: 1, s: 1, o: "222" },
                { f: "c", y: 1.16, z: 1.29, i: "b", e: 0, s: 0, o: "222" },
                { f: "c", y: 1.16, z: 1.29, i: "e", e: 1, s: 1, o: "222" },
                { f: "q", y: 3, z: 2, i: "cR", e: 1, s: 1.3, o: "231" },
                { f: "q", y: 3, z: 2, i: "cQ", e: 1, s: 1.3, o: "231" },
                { f: "c", y: 3, z: 2, i: "e", e: 1, s: 0, o: "231" },
                { f: "c", y: 3, z: 2, i: "e", e: 0, s: 1, o: "59" },
                { f: "c", y: 3.07, z: 1.08, i: "b", e: 90, s: 90, o: "213" },
                { f: "c", y: 3.07, z: 1.08, i: "a", e: 21, s: -212, o: "213" },
                { f: "c", y: 3.07, z: 1.08, i: "cR", e: 1, s: 0.8, o: "213" },
                { f: "c", y: 3.07, z: 1.08, i: "cQ", e: 1, s: 0.8, o: "213" },
                { f: "c", y: 3.07, z: 1.08, i: "a", e: 284, s: 160, o: "226" },
                { f: "c", y: 3.07, z: 1.08, i: "cR", e: 0.8, s: 1, o: "226" },
                { f: "c", y: 3.07, z: 1.08, i: "cQ", e: 0.8, s: 1, o: "226" },
                { f: "c", y: 3.07, z: 0.3, i: "e", e: 1, s: 0, o: "234" },
                { f: "c", y: 3.07, z: 1.08, i: "e", e: 1, s: 0, o: "213" },
                { f: "c", y: 3.07, z: 1.08, i: "e", e: 0, s: 1, o: "226" },
                { f: "c", y: 3.15, z: 1.08, i: "c", e: 18, s: 219, o: "222" },
                { f: "c", y: 3.15, z: 1.08, i: "d", e: 10, s: 65, o: "222" },
                { f: "c", y: 3.15, z: 1.08, i: "b", e: 382, s: 382, o: "211" },
                { f: "c", y: 3.15, z: 1.08, i: "a", e: 160, s: 307, o: "211" },
                { f: "c", y: 3.15, z: 1.08, i: "b", e: 27, s: 0, o: "222" },
                { f: "c", y: 3.15, z: 1.08, i: "cR", e: 1, s: 0.8, o: "211" },
                { f: "c", y: 3.15, z: 1.08, i: "cQ", e: 1, s: 0.8, o: "211" },
                { f: "c", y: 3.15, z: 1.08, i: "a", e: -197, s: 0, o: "222" },
                { f: "c", y: 3.15, z: 1.08, i: "cR", e: 0.8, s: 1, o: "222" },
                { f: "c", y: 3.15, z: 1.08, i: "cQ", e: 0.8, s: 1, o: "222" },
                { f: "c", y: 3.15, z: 1.08, i: "e", e: 1, s: 0, o: "211" },
                { f: "c", y: 3.15, z: 1.08, i: "e", e: 0, s: 1, o: "222" },
                { f: "c", y: 4.07, z: 2.23, i: "e", e: 1, s: 1, o: "234" },
                { y: 4.15, i: "b", s: 90, z: 0, o: "213", f: "c" },
                { y: 4.15, i: "a", s: 21, z: 0, o: "213", f: "c" },
                { f: "c", y: 4.15, z: 2.27, i: "cR", e: 1, s: 1, o: "213" },
                { f: "c", y: 4.15, z: 2.27, i: "cQ", e: 1, s: 1, o: "213" },
                { y: 4.15, i: "a", s: 284, z: 0, o: "226", f: "c" },
                { y: 4.15, i: "cR", s: 0.8, z: 0, o: "226", f: "c" },
                { y: 4.15, i: "cQ", s: 0.8, z: 0, o: "226", f: "c" },
                { f: "c", y: 4.15, z: 2.27, i: "e", e: 1, s: 1, o: "213" },
                { y: 4.15, i: "e", s: 0, z: 0, o: "226", f: "c" },
                { y: 4.23, i: "c", s: 18, z: 0, o: "222", f: "c" },
                { y: 4.23, i: "d", s: 10, z: 0, o: "222", f: "c" },
                { y: 4.23, i: "b", s: 382, z: 0, o: "211", f: "c" },
                { y: 4.23, i: "b", s: 27, z: 0, o: "222", f: "p" },
                { y: 4.23, i: "a", s: 160, z: 0, o: "211", f: "c" },
                { f: "c", y: 4.23, z: 2.29, i: "cR", e: 1, s: 1, o: "211" },
                { f: "c", y: 4.23, z: 2.29, i: "cQ", e: 1, s: 1, o: "211" },
                { y: 4.23, i: "a", s: -197, z: 0, o: "222", f: "c" },
                { y: 4.23, i: "cR", s: 0.8, z: 0, o: "222", f: "c" },
                { y: 4.23, i: "cQ", s: 0.8, z: 0, o: "222", f: "c" },
                { f: "c", y: 4.23, z: 2.29, i: "e", e: 1, s: 1, o: "211" },
                { y: 4.23, i: "e", s: 0, z: 0, o: "222", f: "c" },
                { y: 5, i: "cR", s: 1, z: 0, o: "231", f: "c" },
                { y: 5, i: "cQ", s: 1, z: 0, o: "231", f: "c" },
                { y: 5, i: "e", s: 1, z: 0, o: "231", f: "c" },
                { y: 5, i: "e", s: 0, z: 0, o: "59", f: "c" },
                { f: "c", y: 7, z: 2, i: "b", e: 140, s: 62, o: "217" },
                { f: "q", y: 7, z: 2, i: "cQ", e: 1, s: 1.3, o: "232" },
                { f: "q", y: 7, z: 2, i: "cR", e: 1, s: 1.3, o: "232" },
                { f: "c", y: 7, z: 2, i: "e", e: 1, s: 0, o: "232" },
                { f: "c", y: 7, z: 1, i: "e", e: 0, s: 1, o: "234" },
                { f: "v", y: 7.12, z: 1.1, i: "cR", e: 0.8, s: 1, o: "213" },
                { f: "v", y: 7.12, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "213" },
                { f: "c", y: 7.12, z: 1.1, i: "e", e: 0, s: 1, o: "213" },
                { f: "c", y: 7.22, z: 2, i: "b", e: 0, s: -34, o: "219" },
                { f: "h", y: 7.22, z: 1.2, i: "cR", e: 1, s: 0.8, o: "208" },
                { f: "h", y: 7.22, z: 1.2, i: "cQ", e: 1, s: 0.8, o: "208" },
                { f: "v", y: 7.22, z: 1.1, i: "cR", e: 0.8, s: 1, o: "211" },
                { f: "v", y: 7.22, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "211" },
                { f: "c", y: 7.22, z: 2, i: "e", e: 1, s: 0, o: "219" },
                { f: "c", y: 7.22, z: 1.2, i: "e", e: 1, s: 0, o: "208" },
                { f: "c", y: 7.22, z: 1.1, i: "e", e: 0, s: 1, o: "211" },
                { f: "c", y: 8, z: 2, i: "b", e: 0, s: -34, o: "218" },
                { f: "c", y: 8, z: 2, i: "e", e: 1, s: 0, o: "218" },
                { y: 8, i: "e", s: 0, z: 0, o: "234", f: "c" },
                { f: "h", y: 8.08, z: 1.2, i: "cQ", e: 1, s: 0.8, o: "214" },
                { f: "h", y: 8.08, z: 1.2, i: "cR", e: 1, s: 0.8, o: "214" },
                { f: "c", y: 8.08, z: 1.2, i: "e", e: 1, s: 0, o: "214" },
                { f: "c", y: 8.12, z: 2, i: "b", e: 0, s: -34, o: "220" },
                { f: "h", y: 8.12, z: 1.2, i: "cR", e: 1, s: 0.8, o: "216" },
                { f: "h", y: 8.12, z: 1.2, i: "cQ", e: 1, s: 0.8, o: "216" },
                { f: "c", y: 8.12, z: 2, i: "e", e: 1, s: 0, o: "220" },
                { f: "c", y: 8.12, z: 1.2, i: "e", e: 1, s: 0, o: "216" },
                { y: 8.22, i: "cR", s: 0.8, z: 0, o: "213", f: "c" },
                { y: 8.22, i: "cQ", s: 0.8, z: 0, o: "213", f: "c" },
                { y: 8.22, i: "e", s: 0, z: 0, o: "213", f: "c" },
                { f: "q", y: 8.28, z: 1, i: "c", e: 90, s: 0, o: "209" },
                { y: 9, i: "b", s: 140, z: 0, o: "217", f: "c" },
                { y: 9, i: "cR", s: 1, z: 0, o: "232", f: "c" },
                { y: 9, i: "cQ", s: 1, z: 0, o: "232", f: "c" },
                { y: 9, i: "e", s: 1, z: 0, o: "232", f: "c" },
                { y: 9.02, i: "cR", s: 0.8, z: 0, o: "211", f: "c" },
                { y: 9.02, i: "cQ", s: 0.8, z: 0, o: "211", f: "c" },
                { y: 9.02, i: "e", s: 0, z: 0, o: "211", f: "c" },
                { y: 9.12, i: "cR", s: 1, z: 0, o: "208", f: "c" },
                { y: 9.12, i: "cQ", s: 1, z: 0, o: "208", f: "c" },
                { y: 9.12, i: "e", s: 1, z: 0, o: "208", f: "c" },
                { y: 9.22, i: "b", s: 0, z: 0, o: "219", f: "c" },
                { f: "c", y: 9.22, z: 5.01, i: "e", e: 1, s: 1, o: "219" },
                { y: 9.28, i: "c", s: 90, z: 0, o: "209", f: "c" },
                { y: 9.28, i: "cQ", s: 1, z: 0, o: "214", f: "c" },
                { y: 9.28, i: "cR", s: 1, z: 0, o: "214", f: "c" },
                { y: 9.28, i: "e", s: 1, z: 0, o: "214", f: "c" },
                { y: 10, i: "b", s: 0, z: 0, o: "218", f: "c" },
                { f: "c", y: 10, z: 4.14, i: "e", e: 1, s: 1, o: "218" },
                { y: 10.02, i: "cR", s: 1, z: 0, o: "216", f: "c" },
                { y: 10.02, i: "cQ", s: 1, z: 0, o: "216", f: "c" },
                { y: 10.02, i: "e", s: 1, z: 0, o: "216", f: "c" },
                { y: 10.12, i: "b", s: 0, z: 0, o: "220", f: "c" },
                { f: "c", y: 10.12, z: 3.18, i: "e", e: 1, s: 1, o: "220" },
                { f: "c", y: 10.12, z: 1, i: "e", e: 1, s: 0, o: "215" },
                { f: "c", y: 11.12, z: 1, i: "cQ", e: 1.05, s: 1, o: "209" },
                { f: "c", y: 11.12, z: 1, i: "cR", e: 1.05, s: 1, o: "209" },
                { y: 11.12, i: "e", s: 1, z: 0, o: "215", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 12,
                  z: 1.29,
                  i: "ActionHandler",
                  e: { a: [{ b: "153", p: 3, z: false, symbolOid: "2" }] },
                  s: { a: [{ d: 1, p: 1, g: 2, e: "161" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 12.12, z: 1, i: "cR", e: 1, s: 1.05, o: "209" },
                { f: "c", y: 12.12, z: 1, i: "cQ", e: 1, s: 1.05, o: "209" },
                { y: 13.12, i: "cQ", s: 1, z: 0, o: "209", f: "c" },
                { y: 13.12, i: "cR", s: 1, z: 0, o: "209", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 13.29,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "153", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 14, z: 1.06, i: "e", e: 0, s: 1, o: "220" },
                { f: "c", y: 14.14, z: 1.06, i: "e", e: 0, s: 1, o: "218" },
                { f: "c", y: 14.23, z: 1.06, i: "e", e: 0, s: 1, o: "219" },
                { y: 15.06, i: "e", s: 0, z: 0, o: "220", f: "c" },
                { y: 15.2, i: "e", s: 0, z: 0, o: "218", f: "c" },
                { y: 15.29, i: "e", s: 0, z: 0, o: "219", f: "c" },
              ],
              f: 30,
              b: [
                {
                  D: 7.2,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "241",
                },
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 4,
                  b: "242",
                },
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 4,
                  b: "243",
                },
                {
                  D: 4,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 4,
                  b: "244",
                },
              ],
            },
            242: {
              c: "235",
              q: false,
              z: 3,
              i: "242",
              a: [
                { f: "c", y: 0, z: 1.17, i: "b", e: 15, s: 0, o: "236" },
                { f: "c", y: 1.17, z: 1.13, i: "b", e: 0, s: 15, o: "236" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "242", p: 3, z: false, symbolOid: "139" }] },
                  o: "242",
                },
                { y: 3, i: "b", s: 0, z: 0, o: "236", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "232",
            "231",
            "206",
            "205",
            "224",
            "212",
            "59",
            "207",
            "233",
            "230",
            "225",
            "219",
            "220",
            "218",
            "226",
            "217",
            "227",
            "229",
            "213",
            "208",
            "228",
            "240",
            "239",
            "234",
            "216",
            "238",
            "237",
            "236",
            "235",
            "210",
            "209",
            "214",
            "221",
            "211",
            "222",
            "223",
            "215",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            231: {
              h: "20",
              p: "no-repeat",
              x: "visible",
              a: -10,
              q: "100% 100%",
              b: -15,
              j: "absolute",
              r: "inline",
              cP: "blendmode-luminosity",
              bF: "230",
              z: 2,
              d: 509,
              dB: "img",
              cQ: 1.3,
              e: 0,
              k: "div",
              c: 339,
              cR: 1.3,
            },
            239: {
              x: "visible",
              cA: false,
              a: 0,
              b: 0,
              j: "absolute",
              bF: "234",
              c: 256,
              k: "div",
              bY: 1,
              d: 228,
              z: 3,
              bX: false,
              bZ: 180,
              cV: [],
            },
            207: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 16,
              r: "inline",
              a: 0,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            226: {
              x: "visible",
              a: 284,
              bS: 356,
              b: 34,
              j: "absolute",
              bF: "224",
              z: 2,
              k: "div",
              c: 160,
              d: 99,
              cQ: 0.8,
              e: 0,
              cR: 0.8,
            },
            213: {
              p: "no-repeat",
              c: 236,
              q: "100% 100%",
              d: 55,
              r: "inline",
              cQ: 0.8,
              s: "GothamProBold",
              e: 0,
              cR: 0.8,
              u: "normal",
              h: "34",
              v: "normal",
              w: "",
              bF: "207",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 6,
              a: -212,
              b: 90,
            },
            232: {
              h: "22",
              p: "no-repeat",
              x: "visible",
              a: -9,
              q: "100% 100%",
              b: -15,
              j: "absolute",
              r: "inline",
              cP: "blendmode-soft-light",
              bF: "230",
              z: 4,
              d: 507,
              dB: "img",
              cQ: 1.3,
              e: 0,
              k: "div",
              c: 338,
              cR: 1.3,
            },
            208: {
              h: "30",
              p: "no-repeat",
              x: "visible",
              a: 28,
              q: "100% 100%",
              b: 86,
              j: "absolute",
              r: "inline",
              bF: "207",
              z: 21,
              dB: "img",
              d: 47,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 199,
              cR: 0.8,
            },
            227: {
              aU: 8,
              G: "#FFF",
              c: 44,
              aV: 8,
              r: "inline",
              d: 20,
              s: "Futura,Verdana,sans-serif",
              t: 36,
              Y: 0,
              u: "normal",
              Z: "break-word",
              v: "bold",
              i: "temp",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">30</div>',
              bF: "226",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 2,
              aS: 8,
              aT: 8,
              a: 27,
              b: 30,
            },
            214: {
              h: "26",
              p: "no-repeat",
              x: "visible",
              a: 21,
              q: "100% 100%",
              b: 346,
              j: "absolute",
              r: "inline",
              bF: "207",
              z: 19,
              dB: "img",
              d: 66,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 173,
              cR: 0.8,
            },
            233: {
              c: 320,
              bS: 319,
              d: 480,
              I: "None",
              e: 0.85,
              J: "None",
              K: "None",
              L: "None",
              M: 0,
              bF: "230",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              l: 0,
              D: "#D8DDE4",
              m: "#51B1E6",
              k: "div",
              n: "#007CC1",
              a: 0,
              b: 0,
            },
            209: {
              x: "hidden",
              cQ: 1,
              k: "div",
              cR: 1,
              c: 0,
              d: 95,
              z: 16,
              a: 203,
              bF: "207",
              j: "absolute",
              b: 331,
            },
            220: {
              h: "149",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: -34,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "217",
              dB: "img",
              d: 79,
              k: "div",
              c: 214.333,
              e: 0,
            },
            228: {
              aU: 8,
              G: "#FFF",
              c: 80,
              aV: 8,
              r: "inline",
              d: 30,
              s: "Futura,Verdana,sans-serif",
              t: 16,
              Y: 0,
              Z: "break-word",
              i: "text",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">\u0421\u043e\u043d\u044f\u0447\u043d\u043e</div>',
              bF: "226",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 1,
              aS: 8,
              aT: 8,
              a: 30,
              F: "right",
              b: 52,
            },
            215: {
              h: "18",
              p: "no-repeat",
              x: "visible",
              a: 21,
              q: "100% 100%",
              b: 448,
              j: "absolute",
              r: "inline",
              z: 8,
              bF: "207",
              dB: "img",
              d: 14,
              k: "div",
              c: 278,
              e: 0,
            },
            234: {
              x: "visible",
              k: "div",
              c: 323,
              d: 265,
              z: 3,
              e: 0,
              a: -3,
              j: "absolute",
              bF: "230",
              b: 145,
            },
            221: {
              x: "visible",
              k: "div",
              c: 320,
              d: 107,
              z: 17,
              a: 0,
              bS: 351,
              j: "absolute",
              b: 373,
            },
            229: {
              aU: 8,
              G: "#FFF",
              c: 45,
              aV: 8,
              r: "inline",
              d: 20,
              s: "Helvetica,Arial,Sans-Serif",
              t: 36,
              Y: 0,
              u: "normal",
              Z: "break-word",
              v: "bold",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">\u00b0C</div>',
              bF: "226",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 3,
              aS: 8,
              aT: 8,
              a: 78,
              b: 30,
            },
            240: {
              h: "101",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 14,
              bF: "239",
              dB: "img",
              d: 228,
              k: "div",
              cQ: 1,
              c: 256,
              cR: 1,
            },
            216: {
              h: "28",
              p: "no-repeat",
              x: "visible",
              a: 103,
              q: "100% 100%",
              b: 266,
              j: "absolute",
              r: "inline",
              bF: "207",
              z: 20,
              dB: "img",
              d: 49,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 196,
              cR: 0.8,
            },
            235: {
              x: "visible",
              cA: false,
              a: 132,
              b: 173,
              j: "absolute",
              bF: "234",
              c: 103,
              k: "div",
              bY: 1,
              d: 92,
              z: 2,
              bX: false,
              bZ: 180,
              cV: [],
            },
            222: {
              x: "hidden",
              a: -197,
              bS: 100,
              b: 27,
              j: "absolute",
              bF: "221",
              z: 1,
              k: "div",
              c: 18,
              d: 10,
              cQ: 0.8,
              e: 0,
              cR: 0.8,
            },
            217: {
              x: "visible",
              k: "div",
              c: 216,
              d: 140,
              z: 22,
              e: 1,
              a: 20,
              j: "absolute",
              bF: "207",
              b: 62,
            },
            236: {
              h: "99",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 12,
              bF: "235",
              b: 0,
              d: 92,
              k: "div",
              c: 103,
            },
            223: {
              h: "12",
              p: "no-repeat",
              x: "visible",
              a: 16,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "222",
              z: 1,
              dB: "img",
              d: 55,
              k: "div",
              cQ: 1,
              e: 1,
              c: 201,
              cR: 1,
            },
            210: {
              h: "10",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "209",
              b: 0,
              d: 95,
              k: "div",
              c: 90,
            },
            218: {
              h: "147",
              p: "no-repeat",
              x: "visible",
              a: 7,
              q: "100% 100%",
              b: -34,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "217",
              dB: "img",
              d: 134,
              k: "div",
              c: 215,
              e: 0,
            },
            237: {
              x: "visible",
              cA: false,
              a: 187,
              b: 121,
              j: "absolute",
              bF: "234",
              c: 136,
              k: "div",
              bY: 1,
              d: 104,
              z: 1,
              bX: false,
              bZ: 180,
              cV: [],
            },
            205: {
              c: 320,
              bS: 319,
              d: 480,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              k: "div",
              O: 1,
              C: "#D8DDE4",
              z: 28,
              P: 1,
              D: "#D8DDE4",
              a: -1,
              b: -1,
            },
            224: {
              x: "visible",
              k: "div",
              c: 320,
              d: 129,
              z: 22,
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            211: {
              h: "32",
              p: "no-repeat",
              x: "visible",
              a: 307,
              q: "100% 100%",
              b: 382,
              j: "absolute",
              r: "inline",
              bF: "207",
              z: 5,
              dB: "img",
              d: 69,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 144,
              cR: 0.8,
            },
            219: {
              h: "24",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: -34,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "217",
              dB: "img",
              d: 140,
              k: "div",
              c: 216,
              e: 0,
            },
            230: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 1,
              a: 0,
              bS: 447,
              j: "absolute",
              b: 0,
            },
            238: {
              h: "97",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 10,
              bF: "237",
              b: 0,
              d: 104,
              k: "div",
              c: 136,
            },
            206: {
              c: 320,
              bS: 319,
              d: 480,
              I: "None",
              e: 0,
              J: "None",
              K: "None",
              g: "#E8EBED",
              L: "None",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 29,
              dB: "button",
              D: "#D8DDE4",
              aA: { a: [{ p: 4, h: "39" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            59: {
              cS: true,
              x: "visible",
              a: 0,
              cA: false,
              b: 0,
              j: "absolute",
              bF: "207",
              c: 320,
              k: "div",
              z: 4,
              cL: "59",
              d: 569,
              bY: 1,
              e: 0,
              bZ: 180,
              cM: true,
              bX: false,
              cK: { a: [{ p: 3, b: "241", z: false }] },
              cV: [],
            },
            225: {
              h: "16",
              p: "no-repeat",
              x: "visible",
              a: 106,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "224",
              b: 15,
              d: 29,
              k: "div",
              c: 110,
            },
            212: {
              aR: "0",
              x: "visible",
              bE: "57",
              a: 0,
              b: 0,
              j: "absolute",
              bF: "59",
              z: 5,
              aO: false,
              k: "video",
              d: 569,
              c: 320,
              aQ: "0",
              aH: "1",
            },
          },
        },
        {
          o: "197",
          A: { a: [{ p: 4, h: "7" }] },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {
            267: { V: { "Main Timeline": "281" }, W: "281", n: "bubbles_1" },
            265: { V: { "Main Timeline": "280" }, W: "280", n: "bubbles 3" },
            59: { V: { "Main Timeline": "241" }, W: "241", n: "movie" },
            269: { V: { "Main Timeline": "282" }, W: "282", n: "bubbles_2" },
          },
          T: {
            196: {
              q: false,
              z: 6,
              i: "196",
              n: "pulse",
              a: [
                { f: "c", y: 0, z: 1, i: "cQ", e: 1.05, s: 1, o: "248" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1.05, s: 1, o: "248" },
                { f: "c", y: 0, z: 2, i: "b", e: 140, s: 62, o: "252" },
                { f: "c", y: 0, z: 2, i: "e", e: 1, s: 0, o: "253" },
                { f: "c", y: 0, z: 2, i: "b", e: 0, s: -34, o: "253" },
                { f: "c", y: 0.08, z: 2, i: "e", e: 1, s: 0, o: "254" },
                { f: "c", y: 0.08, z: 2, i: "b", e: 0, s: -34, o: "254" },
                { f: "c", y: 0.2, z: 2, i: "e", e: 1, s: 0, o: "255" },
                { f: "c", y: 0.2, z: 2, i: "b", e: 0, s: -34, o: "255" },
                { f: "c", y: 1, z: 1, i: "cR", e: 1, s: 1.05, o: "248" },
                { f: "c", y: 1, z: 1, i: "cQ", e: 1, s: 1.05, o: "248" },
                { f: "c", y: 2, z: 2, i: "cR", e: 1, s: 1, o: "248" },
                { f: "c", y: 2, z: 2, i: "cQ", e: 1, s: 1, o: "248" },
                { f: "c", y: 2, z: 2.23, i: "e", e: 1, s: 1, o: "253" },
                { y: 2, i: "b", s: 140, z: 0, o: "252", f: "c" },
                { y: 2, i: "b", s: 0, z: 0, o: "253", f: "c" },
                { f: "c", y: 2.08, z: 2.06, i: "e", e: 1, s: 1, o: "254" },
                { y: 2.08, i: "b", s: 0, z: 0, o: "254", f: "c" },
                { f: "c", y: 2.2, z: 1.1, i: "e", e: 1, s: 1, o: "255" },
                { y: 2.2, i: "b", s: 0, z: 0, o: "255", f: "c" },
                { f: "c", y: 4, z: 1, i: "cR", e: 1.05, s: 1, o: "248" },
                { f: "c", y: 4, z: 1, i: "cQ", e: 1.05, s: 1, o: "248" },
                { f: "c", y: 4, z: 1.06, i: "e", e: 0, s: 1, o: "255" },
                { f: "c", y: 4.14, z: 1.06, i: "e", e: 0, s: 1, o: "254" },
                { f: "c", y: 4.23, z: 1.06, i: "e", e: 0, s: 1, o: "253" },
                { f: "c", y: 5, z: 1, i: "cR", e: 1, s: 1.05, o: "248" },
                { f: "c", y: 5, z: 1, i: "cQ", e: 1, s: 1.05, o: "248" },
                { y: 5.06, i: "e", s: 0, z: 0, o: "255", f: "c" },
                { y: 5.2, i: "e", s: 0, z: 0, o: "254", f: "c" },
                { y: 5.29, i: "e", s: 0, z: 0, o: "253", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 6,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "196", p: 3, z: false, symbolOid: "2" }] },
                  o: "196",
                },
                { y: 6, i: "cR", s: 1, z: 0, o: "248", f: "c" },
                { y: 6, i: "cQ", s: 1, z: 0, o: "248", f: "c" },
              ],
              f: 30,
              b: [],
            },
            280: {
              c: "265",
              q: false,
              z: 3,
              i: "280",
              a: [
                { f: "c", y: 0, z: 1.19, i: "b", e: -11, s: 0, o: "266" },
                { f: "c", y: 1.19, z: 1.11, i: "b", e: 0, s: -11, o: "266" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "280", p: 3, z: false, symbolOid: "103" }] },
                  o: "280",
                },
                { y: 3, i: "b", s: 0, z: 0, o: "266", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            281: {
              c: "267",
              q: false,
              z: 4,
              i: "281",
              a: [
                { f: "c", y: 0, z: 2, i: "cQ", e: 1.05, s: 1, o: "268" },
                { f: "c", y: 0, z: 2, i: "cR", e: 1.05, s: 1, o: "268" },
                { f: "c", y: 2, z: 2, i: "cQ", e: 1, s: 1.05, o: "268" },
                { f: "c", y: 2, z: 2, i: "cR", e: 1, s: 1.05, o: "268" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "281", p: 3, z: false, symbolOid: "142" }] },
                  o: "281",
                },
                { y: 4, i: "cQ", s: 1, z: 0, o: "268", f: "c" },
                { y: 4, i: "cR", s: 1, z: 0, o: "268", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 15.29,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "59" },
                { f: "p", y: 0, z: 1, i: "b", e: -89, s: 0, o: "59" },
                { f: "c", y: 0, z: 1, i: "a", e: 160, s: 284, o: "276" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "276" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "276" },
                { f: "c", y: 0, z: 1.16, i: "c", e: 219, s: 18, o: "261" },
                { f: "c", y: 0, z: 1.16, i: "d", e: 65, s: 10, o: "261" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "276" },
                { f: "c", y: 0, z: 1.16, i: "a", e: 0, s: -197, o: "261" },
                { f: "c", y: 0, z: 1.16, i: "cQ", e: 1, s: 0.8, o: "261" },
                { f: "c", y: 0, z: 1.16, i: "cR", e: 1, s: 0.8, o: "261" },
                { f: "p", y: 0, z: 1.16, i: "b", e: 0, s: 27, o: "261" },
                { f: "c", y: 0, z: 1.16, i: "e", e: 1, s: 0, o: "261" },
                { y: 1, i: "b", s: -89, z: 0, o: "59", f: "c" },
                { f: "c", y: 1, z: 2.07, i: "cQ", e: 1, s: 1, o: "276" },
                { f: "c", y: 1, z: 2.07, i: "cR", e: 1, s: 1, o: "276" },
                { f: "c", y: 1, z: 2.07, i: "a", e: 160, s: 160, o: "276" },
                { f: "c", y: 1, z: 2, i: "e", e: 1, s: 1, o: "59" },
                { f: "c", y: 1, z: 2.07, i: "e", e: 1, s: 1, o: "276" },
                { f: "c", y: 1.16, z: 1.29, i: "c", e: 219, s: 219, o: "261" },
                { f: "c", y: 1.16, z: 1.29, i: "d", e: 65, s: 65, o: "261" },
                { f: "c", y: 1.16, z: 1.29, i: "cR", e: 1, s: 1, o: "261" },
                { f: "c", y: 1.16, z: 1.29, i: "a", e: 0, s: 0, o: "261" },
                { f: "c", y: 1.16, z: 1.29, i: "cQ", e: 1, s: 1, o: "261" },
                { f: "c", y: 1.16, z: 1.29, i: "b", e: 0, s: 0, o: "261" },
                { f: "c", y: 1.16, z: 1.29, i: "e", e: 1, s: 1, o: "261" },
                { f: "q", y: 3, z: 2, i: "cR", e: 1, s: 1.3, o: "272" },
                { f: "q", y: 3, z: 2, i: "cQ", e: 1, s: 1.3, o: "272" },
                { f: "c", y: 3, z: 2, i: "e", e: 1, s: 0, o: "272" },
                { f: "c", y: 3, z: 2, i: "e", e: 0, s: 1, o: "59" },
                { f: "c", y: 3.07, z: 1.08, i: "b", e: 90, s: 90, o: "258" },
                { f: "c", y: 3.07, z: 1.08, i: "a", e: 21, s: -212, o: "258" },
                { f: "c", y: 3.07, z: 1.08, i: "cR", e: 1, s: 0.8, o: "258" },
                { f: "c", y: 3.07, z: 1.08, i: "cQ", e: 1, s: 0.8, o: "258" },
                { f: "c", y: 3.07, z: 1.08, i: "a", e: 284, s: 160, o: "276" },
                { f: "c", y: 3.07, z: 1.08, i: "cR", e: 0.8, s: 1, o: "276" },
                { f: "c", y: 3.07, z: 1.08, i: "cQ", e: 0.8, s: 1, o: "276" },
                { f: "c", y: 3.07, z: 0.3, i: "e", e: 1, s: 0, o: "264" },
                { f: "c", y: 3.07, z: 1.08, i: "e", e: 1, s: 0, o: "258" },
                { f: "c", y: 3.07, z: 1.08, i: "e", e: 0, s: 1, o: "276" },
                { f: "c", y: 3.15, z: 1.08, i: "c", e: 18, s: 219, o: "261" },
                { f: "c", y: 3.15, z: 1.08, i: "d", e: 10, s: 65, o: "261" },
                { f: "c", y: 3.15, z: 1.08, i: "b", e: 382, s: 382, o: "257" },
                { f: "c", y: 3.15, z: 1.08, i: "a", e: 160, s: 307, o: "257" },
                { f: "c", y: 3.15, z: 1.08, i: "b", e: 27, s: 0, o: "261" },
                { f: "c", y: 3.15, z: 1.08, i: "cR", e: 1, s: 0.8, o: "257" },
                { f: "c", y: 3.15, z: 1.08, i: "cQ", e: 1, s: 0.8, o: "257" },
                { f: "c", y: 3.15, z: 1.08, i: "a", e: -197, s: 0, o: "261" },
                { f: "c", y: 3.15, z: 1.08, i: "cR", e: 0.8, s: 1, o: "261" },
                { f: "c", y: 3.15, z: 1.08, i: "cQ", e: 0.8, s: 1, o: "261" },
                { f: "c", y: 3.15, z: 1.08, i: "e", e: 1, s: 0, o: "257" },
                { f: "c", y: 3.15, z: 1.08, i: "e", e: 0, s: 1, o: "261" },
                { f: "c", y: 4.07, z: 2.23, i: "e", e: 1, s: 1, o: "264" },
                { y: 4.15, i: "b", s: 90, z: 0, o: "258", f: "c" },
                { y: 4.15, i: "a", s: 21, z: 0, o: "258", f: "c" },
                { f: "c", y: 4.15, z: 2.27, i: "cR", e: 1, s: 1, o: "258" },
                { f: "c", y: 4.15, z: 2.27, i: "cQ", e: 1, s: 1, o: "258" },
                { y: 4.15, i: "a", s: 284, z: 0, o: "276", f: "c" },
                { y: 4.15, i: "cR", s: 0.8, z: 0, o: "276", f: "c" },
                { y: 4.15, i: "cQ", s: 0.8, z: 0, o: "276", f: "c" },
                { f: "c", y: 4.15, z: 2.27, i: "e", e: 1, s: 1, o: "258" },
                { y: 4.15, i: "e", s: 0, z: 0, o: "276", f: "c" },
                { y: 4.23, i: "c", s: 18, z: 0, o: "261", f: "c" },
                { y: 4.23, i: "d", s: 10, z: 0, o: "261", f: "c" },
                { y: 4.23, i: "b", s: 382, z: 0, o: "257", f: "c" },
                { y: 4.23, i: "b", s: 27, z: 0, o: "261", f: "p" },
                { y: 4.23, i: "a", s: 160, z: 0, o: "257", f: "c" },
                { f: "c", y: 4.23, z: 2.29, i: "cR", e: 1, s: 1, o: "257" },
                { f: "c", y: 4.23, z: 2.29, i: "cQ", e: 1, s: 1, o: "257" },
                { y: 4.23, i: "a", s: -197, z: 0, o: "261", f: "c" },
                { y: 4.23, i: "cR", s: 0.8, z: 0, o: "261", f: "c" },
                { y: 4.23, i: "cQ", s: 0.8, z: 0, o: "261", f: "c" },
                { f: "c", y: 4.23, z: 2.29, i: "e", e: 1, s: 1, o: "257" },
                { y: 4.23, i: "e", s: 0, z: 0, o: "261", f: "c" },
                { y: 5, i: "cR", s: 1, z: 0, o: "272", f: "c" },
                { y: 5, i: "cQ", s: 1, z: 0, o: "272", f: "c" },
                { y: 5, i: "e", s: 1, z: 0, o: "272", f: "c" },
                { y: 5, i: "e", s: 0, z: 0, o: "59", f: "c" },
                { f: "c", y: 7, z: 2, i: "b", e: 140, s: 62, o: "252" },
                { f: "q", y: 7, z: 2, i: "cQ", e: 1, s: 1.3, o: "273" },
                { f: "q", y: 7, z: 2, i: "cR", e: 1, s: 1.3, o: "273" },
                { f: "c", y: 7, z: 2, i: "e", e: 1, s: 0, o: "273" },
                { f: "c", y: 7, z: 1, i: "e", e: 0, s: 1, o: "264" },
                { f: "v", y: 7.12, z: 1.1, i: "cR", e: 0.8, s: 1, o: "258" },
                { f: "v", y: 7.12, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "258" },
                { f: "c", y: 7.12, z: 1.1, i: "e", e: 0, s: 1, o: "258" },
                { f: "c", y: 7.22, z: 2, i: "b", e: 0, s: -34, o: "253" },
                { f: "h", y: 7.22, z: 1.2, i: "cR", e: 1, s: 0.8, o: "256" },
                { f: "h", y: 7.22, z: 1.2, i: "cQ", e: 1, s: 0.8, o: "256" },
                { f: "v", y: 7.22, z: 1.1, i: "cR", e: 0.8, s: 1, o: "257" },
                { f: "v", y: 7.22, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "257" },
                { f: "c", y: 7.22, z: 2, i: "e", e: 1, s: 0, o: "253" },
                { f: "c", y: 7.22, z: 1.2, i: "e", e: 1, s: 0, o: "256" },
                { f: "c", y: 7.22, z: 1.1, i: "e", e: 0, s: 1, o: "257" },
                { f: "c", y: 8, z: 2, i: "b", e: 0, s: -34, o: "254" },
                { f: "c", y: 8, z: 2, i: "e", e: 1, s: 0, o: "254" },
                { y: 8, i: "e", s: 0, z: 0, o: "264", f: "c" },
                { f: "h", y: 8.08, z: 1.2, i: "cQ", e: 1, s: 0.8, o: "259" },
                { f: "h", y: 8.08, z: 1.2, i: "cR", e: 1, s: 0.8, o: "259" },
                { f: "c", y: 8.08, z: 1.2, i: "e", e: 1, s: 0, o: "259" },
                { f: "c", y: 8.12, z: 2, i: "b", e: 0, s: -34, o: "255" },
                { f: "h", y: 8.12, z: 1.2, i: "cR", e: 1, s: 0.8, o: "250" },
                { f: "h", y: 8.12, z: 1.2, i: "cQ", e: 1, s: 0.8, o: "250" },
                { f: "c", y: 8.12, z: 2, i: "e", e: 1, s: 0, o: "255" },
                { f: "c", y: 8.12, z: 1.2, i: "e", e: 1, s: 0, o: "250" },
                { y: 8.22, i: "cR", s: 0.8, z: 0, o: "258", f: "c" },
                { y: 8.22, i: "cQ", s: 0.8, z: 0, o: "258", f: "c" },
                { y: 8.22, i: "e", s: 0, z: 0, o: "258", f: "c" },
                { f: "q", y: 8.28, z: 1, i: "c", e: 90, s: 0, o: "248" },
                { y: 9, i: "b", s: 140, z: 0, o: "252", f: "c" },
                { y: 9, i: "cR", s: 1, z: 0, o: "273", f: "c" },
                { y: 9, i: "cQ", s: 1, z: 0, o: "273", f: "c" },
                { y: 9, i: "e", s: 1, z: 0, o: "273", f: "c" },
                { y: 9.02, i: "cR", s: 0.8, z: 0, o: "257", f: "c" },
                { y: 9.02, i: "cQ", s: 0.8, z: 0, o: "257", f: "c" },
                { y: 9.02, i: "e", s: 0, z: 0, o: "257", f: "c" },
                { y: 9.12, i: "cR", s: 1, z: 0, o: "256", f: "c" },
                { y: 9.12, i: "cQ", s: 1, z: 0, o: "256", f: "c" },
                { y: 9.12, i: "e", s: 1, z: 0, o: "256", f: "c" },
                { y: 9.22, i: "b", s: 0, z: 0, o: "253", f: "c" },
                { f: "c", y: 9.22, z: 5.01, i: "e", e: 1, s: 1, o: "253" },
                { y: 9.28, i: "c", s: 90, z: 0, o: "248", f: "c" },
                { y: 9.28, i: "cQ", s: 1, z: 0, o: "259", f: "c" },
                { y: 9.28, i: "cR", s: 1, z: 0, o: "259", f: "c" },
                { y: 9.28, i: "e", s: 1, z: 0, o: "259", f: "c" },
                { y: 10, i: "b", s: 0, z: 0, o: "254", f: "c" },
                { f: "c", y: 10, z: 4.14, i: "e", e: 1, s: 1, o: "254" },
                { y: 10.02, i: "cR", s: 1, z: 0, o: "250", f: "c" },
                { y: 10.02, i: "cQ", s: 1, z: 0, o: "250", f: "c" },
                { y: 10.02, i: "e", s: 1, z: 0, o: "250", f: "c" },
                { y: 10.12, i: "b", s: 0, z: 0, o: "255", f: "c" },
                { f: "c", y: 10.12, z: 3.18, i: "e", e: 1, s: 1, o: "255" },
                { f: "c", y: 10.12, z: 1, i: "e", e: 1, s: 0, o: "251" },
                { f: "c", y: 11.12, z: 1, i: "cQ", e: 1.05, s: 1, o: "248" },
                { f: "c", y: 11.12, z: 1, i: "cR", e: 1.05, s: 1, o: "248" },
                { y: 11.12, i: "e", s: 1, z: 0, o: "251", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 12,
                  z: 1.29,
                  i: "ActionHandler",
                  e: { a: [{ b: "153", p: 3, z: false, symbolOid: "2" }] },
                  s: { a: [{ d: 1, p: 1, g: 2, e: "1" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 12.12, z: 1, i: "cR", e: 1, s: 1.05, o: "248" },
                { f: "c", y: 12.12, z: 1, i: "cQ", e: 1, s: 1.05, o: "248" },
                { y: 13.12, i: "cQ", s: 1, z: 0, o: "248", f: "c" },
                { y: 13.12, i: "cR", s: 1, z: 0, o: "248", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 13.29,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "196", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 14, z: 1.06, i: "e", e: 0, s: 1, o: "255" },
                { f: "c", y: 14.14, z: 1.06, i: "e", e: 0, s: 1, o: "254" },
                { f: "c", y: 14.23, z: 1.06, i: "e", e: 0, s: 1, o: "253" },
                { y: 15.06, i: "e", s: 0, z: 0, o: "255", f: "c" },
                { y: 15.2, i: "e", s: 0, z: 0, o: "254", f: "c" },
                { y: 15.29, i: "e", s: 0, z: 0, o: "253", f: "c" },
              ],
              f: 30,
              b: [
                {
                  D: 7.2,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "241",
                },
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 4,
                  b: "282",
                },
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 4,
                  b: "280",
                },
                {
                  D: 4,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 4,
                  b: "281",
                },
              ],
            },
            241: {
              b: [],
              c: "59",
              q: false,
              z: 7.2,
              i: "241",
              n: "Main Timeline",
              a: [{ y: 0, p: 1, i: "Video Track", z: 7.2, o: "212", f: "c" }],
              s: "59",
              f: 30,
            },
            282: {
              c: "269",
              q: false,
              z: 3,
              i: "282",
              a: [
                { f: "c", y: 0, z: 1.17, i: "b", e: 15, s: 0, o: "270" },
                { f: "c", y: 1.17, z: 1.13, i: "b", e: 0, s: 15, o: "270" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "282", p: 3, z: false, symbolOid: "139" }] },
                  o: "282",
                },
                { y: 3, i: "b", s: 0, z: 0, o: "270", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "212",
            "59",
            "273",
            "272",
            "246",
            "245",
            "274",
            "247",
            "271",
            "263",
            "275",
            "276",
            "278",
            "279",
            "258",
            "256",
            "277",
            "253",
            "252",
            "255",
            "254",
            "268",
            "267",
            "264",
            "250",
            "266",
            "265",
            "270",
            "269",
            "249",
            "248",
            "259",
            "260",
            "257",
            "261",
            "262",
            "251",
          ],
          n: "Untitled Layout",
          _: 1,
          v: {
            250: {
              h: "28",
              p: "no-repeat",
              x: "visible",
              a: 103,
              q: "100% 100%",
              b: 266,
              j: "absolute",
              r: "inline",
              bF: "247",
              z: 20,
              dB: "img",
              d: 49,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 196,
              cR: 0.8,
            },
            258: {
              p: "no-repeat",
              c: 236,
              q: "100% 100%",
              d: 55,
              r: "inline",
              cQ: 0.8,
              s: "GothamProBold",
              e: 0,
              cR: 0.8,
              u: "normal",
              h: "34",
              v: "normal",
              w: "",
              bF: "247",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 6,
              a: -212,
              b: 90,
            },
            277: {
              aU: 8,
              G: "#FFF",
              c: 80,
              aV: 8,
              r: "inline",
              d: 30,
              s: "Futura,Verdana,sans-serif",
              t: 16,
              Y: 0,
              Z: "break-word",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">\u0421\u043e\u043d\u044f\u0447\u043d\u043e</div>',
              bF: "276",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 1,
              aS: 8,
              aT: 8,
              a: 30,
              F: "right",
              b: 52,
            },
            245: {
              c: 320,
              bS: 319,
              d: 480,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              k: "div",
              O: 1,
              C: "#D8DDE4",
              z: 28,
              P: 1,
              D: "#D8DDE4",
              a: -1,
              b: -1,
            },
            264: {
              x: "visible",
              k: "div",
              c: 323,
              d: 265,
              z: 3,
              e: 0,
              a: -3,
              j: "absolute",
              bF: "263",
              b: 145,
            },
            251: {
              h: "18",
              p: "no-repeat",
              x: "visible",
              a: 21,
              q: "100% 100%",
              b: 448,
              j: "absolute",
              r: "inline",
              z: 8,
              bF: "247",
              dB: "img",
              d: 14,
              k: "div",
              c: 278,
              e: 0,
            },
            259: {
              h: "26",
              p: "no-repeat",
              x: "visible",
              a: 21,
              q: "100% 100%",
              b: 346,
              j: "absolute",
              r: "inline",
              bF: "247",
              z: 19,
              dB: "img",
              d: 66,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 173,
              cR: 0.8,
            },
            270: {
              h: "99",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 12,
              bF: "269",
              b: 0,
              d: 92,
              k: "div",
              c: 103,
            },
            278: {
              aU: 8,
              G: "#FFF",
              c: 44,
              aV: 8,
              r: "inline",
              d: 20,
              s: "Futura,Verdana,sans-serif",
              t: 36,
              Y: 0,
              u: "normal",
              Z: "break-word",
              v: "bold",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">30</div>',
              bF: "276",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 2,
              aS: 8,
              aT: 8,
              a: 27,
              b: 30,
            },
            246: {
              c: 320,
              bS: 319,
              d: 480,
              I: "None",
              e: 0,
              J: "None",
              K: "None",
              g: "#E8EBED",
              L: "None",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 29,
              dB: "button",
              D: "#D8DDE4",
              aA: { a: [{ p: 4, h: "39" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            265: {
              x: "visible",
              cA: false,
              a: 187,
              b: 121,
              j: "absolute",
              bF: "264",
              c: 136,
              k: "div",
              bY: 1,
              d: 104,
              z: 1,
              bX: false,
              bZ: 180,
              cV: [],
            },
            252: {
              x: "visible",
              k: "div",
              c: 216,
              d: 140,
              z: 22,
              e: 1,
              a: 20,
              j: "absolute",
              bF: "247",
              b: 62,
            },
            271: {
              c: 320,
              bS: 319,
              d: 480,
              I: "None",
              e: 0.85,
              J: "None",
              K: "None",
              L: "None",
              M: 0,
              bF: "263",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              l: 0,
              D: "#D8DDE4",
              m: "#51B1E6",
              k: "div",
              n: "#007CC1",
              a: 0,
              b: 0,
            },
            279: {
              aU: 8,
              G: "#FFF",
              c: 45,
              aV: 8,
              r: "inline",
              d: 20,
              s: "Helvetica,Arial,Sans-Serif",
              t: 36,
              Y: 0,
              u: "normal",
              Z: "break-word",
              v: "bold",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">\u00b0C</div>',
              bF: "276",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 3,
              aS: 8,
              aT: 8,
              a: 78,
              b: 30,
            },
            247: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 16,
              r: "inline",
              a: 0,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            266: {
              h: "97",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 10,
              bF: "265",
              b: 0,
              d: 104,
              k: "div",
              c: 136,
            },
            253: {
              h: "24",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: -34,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "252",
              dB: "img",
              d: 140,
              k: "div",
              c: 216,
              e: 0,
            },
            272: {
              h: "20",
              p: "no-repeat",
              x: "visible",
              a: -10,
              q: "100% 100%",
              b: -15,
              j: "absolute",
              r: "inline",
              cP: "blendmode-luminosity",
              bF: "263",
              z: 2,
              d: 509,
              dB: "img",
              cQ: 1.3,
              e: 0,
              k: "div",
              c: 339,
              cR: 1.3,
            },
            248: {
              x: "hidden",
              cQ: 1,
              k: "div",
              cR: 1,
              c: 0,
              d: 95,
              z: 16,
              a: 203,
              bF: "247",
              j: "absolute",
              b: 331,
            },
            267: {
              x: "visible",
              cA: false,
              a: 0,
              b: 0,
              j: "absolute",
              bF: "264",
              c: 256,
              k: "div",
              bY: 1,
              d: 228,
              z: 3,
              bX: false,
              bZ: 180,
              cV: [],
            },
            254: {
              h: "147",
              p: "no-repeat",
              x: "visible",
              a: 7,
              q: "100% 100%",
              b: -34,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "252",
              dB: "img",
              d: 134,
              k: "div",
              c: 215,
              e: 0,
            },
            273: {
              h: "22",
              p: "no-repeat",
              x: "visible",
              a: -9,
              q: "100% 100%",
              b: -15,
              j: "absolute",
              r: "inline",
              cP: "blendmode-soft-light",
              bF: "263",
              z: 4,
              d: 507,
              dB: "img",
              cQ: 1.3,
              e: 0,
              k: "div",
              c: 338,
              cR: 1.3,
            },
            249: {
              h: "10",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "248",
              b: 0,
              d: 95,
              k: "div",
              c: 90,
            },
            260: {
              x: "visible",
              k: "div",
              c: 320,
              d: 107,
              z: 17,
              a: 0,
              bS: 351,
              j: "absolute",
              b: 373,
            },
            268: {
              h: "101",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 14,
              bF: "267",
              dB: "img",
              d: 228,
              k: "div",
              cQ: 1,
              c: 256,
              cR: 1,
            },
            255: {
              h: "149",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: -34,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "252",
              dB: "img",
              d: 79,
              k: "div",
              c: 214.333,
              e: 0,
            },
            274: {
              x: "visible",
              k: "div",
              c: 320,
              d: 129,
              z: 22,
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            261: {
              x: "hidden",
              a: -197,
              bS: 100,
              b: 27,
              j: "absolute",
              bF: "260",
              z: 1,
              k: "div",
              c: 18,
              d: 10,
              cQ: 0.8,
              e: 0,
              cR: 0.8,
            },
            269: {
              x: "visible",
              cA: false,
              a: 132,
              b: 173,
              j: "absolute",
              bF: "264",
              c: 103,
              k: "div",
              bY: 1,
              d: 92,
              z: 2,
              bX: false,
              bZ: 180,
              cV: [],
            },
            256: {
              h: "30",
              p: "no-repeat",
              x: "visible",
              a: 28,
              q: "100% 100%",
              b: 86,
              j: "absolute",
              r: "inline",
              bF: "247",
              z: 21,
              dB: "img",
              d: 47,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 199,
              cR: 0.8,
            },
            275: {
              h: "16",
              p: "no-repeat",
              x: "visible",
              a: 106,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "274",
              b: 15,
              d: 29,
              k: "div",
              c: 110,
            },
            262: {
              h: "12",
              p: "no-repeat",
              x: "visible",
              a: 16,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "261",
              z: 1,
              dB: "img",
              d: 55,
              k: "div",
              cQ: 1,
              e: 1,
              c: 201,
              cR: 1,
            },
            59: {
              cS: true,
              x: "visible",
              a: 0,
              cA: false,
              b: 0,
              j: "absolute",
              bF: "247",
              c: 320,
              k: "div",
              z: 4,
              cL: "59",
              d: 569,
              bY: 1,
              e: 0,
              bZ: 180,
              cM: true,
              bX: false,
              cK: { a: [{ p: 3, b: "241", z: false }] },
              cV: [],
            },
            257: {
              h: "32",
              p: "no-repeat",
              x: "visible",
              a: 307,
              q: "100% 100%",
              b: 382,
              j: "absolute",
              r: "inline",
              bF: "247",
              z: 5,
              dB: "img",
              d: 69,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 144,
              cR: 0.8,
            },
            276: {
              x: "visible",
              a: 284,
              bS: 356,
              b: 34,
              j: "absolute",
              bF: "274",
              z: 2,
              k: "div",
              c: 160,
              d: 99,
              cQ: 0.8,
              e: 0,
              cR: 0.8,
            },
            212: {
              aR: "0",
              x: "visible",
              bE: "57",
              a: 0,
              b: 0,
              j: "absolute",
              bF: "59",
              z: 5,
              aO: false,
              k: "video",
              d: 569,
              c: 320,
              cM: true,
              aQ: "0",
              aH: "1",
            },
            263: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 1,
              a: 0,
              bS: 447,
              j: "absolute",
              b: 0,
            },
          },
        },
      ],
      { 59: ["212"] },
      h,
      {
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
        h: { p: 0, q: [[0, 0, 0.175, 0.885, 0.32, 1.25, 1, 1]] },
        v: { p: 0, q: [[0, 0, 0.455, 0.03, 0.515, 0.955, 1, 1]] },
      },
      null,
      false,
      true,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
