//	HYPE.documents["New_Balance_Cards_RichMedia_320x480"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resorces/NewBalance",
      f = "New_Balance_Cards_RichMedia_320x480",
      g = "newbalancecardsrichmedia320x480_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "Click",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.click();\n\t\n}",
        identifier: "65",
      },
      {
        name: "volumeUp",
        source:
          'function(hypeDocument, element, event) {\tvar video = hypeDocument.getElementById("videom");\n\tvideo.volume = 0.5;\n\tvideo.muted = true;\t\t\n}',
        identifier: "75",
      },
      {
        name: "sound",
        source:
          'function(hypeDocument, element, event) {\t\n\tvar video = hypeDocument.getElementById("videom");\n\tvar krest = hypeDocument.getElementById("krestm");\n\tvar on = hypeDocument.getElementById("onm");\n\t\n\t\n\tif (video.muted) {\n\t\tvideo.muted = false;\n\t\tkrest.style.display = "none";\n\t\ton.style.display = "block";\n\t\tregisterUnMuteEvent();\n\t} else {\n\t\tvideo.muted = true;\n\t\tkrest.style.display = "block";\n\t\ton.style.display = "none";\n\t\tregisterMuteEvent();\n\t}\n\t\n\treturn false;\n\t\t\t\n}',
        identifier: "76",
      },
      {
        name: "Click",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.click();\n\t\n}",
        identifier: "202",
      },
      {
        name: "sound",
        source:
          'function(hypeDocument, element, event) {\t\n\tvar video = hypeDocument.getElementById("videom");\n\tvar krest = hypeDocument.getElementById("krestm");\n\tvar on = hypeDocument.getElementById("onm");\n\t\n\t\n\tif (video.muted) {\n\t\tvideo.muted = false;\n\t\tkrest.style.display = "none";\n\t\ton.style.display = "block";\n\t\tregisterUnMuteEvent();\n\t} else {\n\t\tvideo.muted = true;\n\t\tkrest.style.display = "block";\n\t\ton.style.display = "none";\n\t\tregisterMuteEvent();\n\t}\n\t\n\treturn false;\n\t\t\t\n}',
        identifier: "203",
      },
      {
        name: "action5",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action5();\n}",
        identifier: "376",
      },
      {
        name: "action6",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action6();\n}",
        identifier: "377",
      },
      {
        name: "action7",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action7();\n}",
        identifier: "378",
      },
      {
        name: "action8",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action8();\n}",
        identifier: "379",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        3: { p: 1, n: "on-1.svg", g: "190", t: "image/svg+xml" },
        12: { p: 1, n: "p_2_2x.png", g: "265", t: "@2x" },
        21: { p: 1, n: "cucumber02.png", g: "410", t: "@1x" },
        4: { p: 1, n: "krest-1.svg", g: "192", t: "image/svg+xml" },
        30: { p: 1, n: "nb_logo.svg", g: "497", t: "image/svg+xml" },
        13: { p: 1, n: "p_1_2x.png", g: "271", t: "@2x" },
        5: { p: 1, n: "mute-1.svg", g: "193", t: "image/svg+xml" },
        22: { p: 1, n: "cucumber01.png", g: "413", t: "@1x" },
        6: { p: 1, n: "fog.png", g: "204", t: "@1x" },
        31: { p: 1, n: "info.svg", g: "405", t: "image/svg+xml" },
        14: { p: 1, n: "p_3_2x.png", g: "274", t: "@2x" },
        7: { p: 1, n: "btn_bg.svg", g: "207", t: "image/svg+xml" },
        23: { p: 1, n: "olive02.png", g: "416", t: "@1x" },
        32: { p: 1, n: "hand.svg", g: "398", t: "image/svg+xml" },
        15: { p: 1, n: "f_3_2x.png", g: "280", t: "@2x" },
        8: { p: 1, n: "btn_txt.svg", g: "208", t: "image/svg+xml" },
        24: { p: 1, n: "cucumber03.png", g: "419", t: "@1x" },
        9: { n: "video_nb-1.mp4", g: "191", t: "video/mp4" },
        33: { p: 1, n: "dis3.svg", g: "527", t: "image/svg+xml" },
        16: { p: 1, n: "f_1_2x.png", g: "283", t: "@2x" },
        25: { p: 1, n: "olive01.png", g: "422", t: "@1x" },
        34: { p: 1, n: "dis2.svg", g: "529", t: "image/svg+xml" },
        17: { p: 1, n: "f_2_2x.png", g: "286", t: "@2x" },
        26: { p: 1, n: "olive03.png", g: "425", t: "@1x" },
        35: { p: 1, n: "dis.svg", g: "531", t: "image/svg+xml" },
        18: { p: 1, n: "f_4_2x.png", g: "289", t: "@2x" },
        27: { p: 1, n: "1.png", g: "401", t: "@1x" },
        36: { p: 1, n: "10_w.svg", g: "533", t: "image/svg+xml" },
        19: { p: 1, n: "p_4_2x.png", g: "292", t: "@2x" },
        28: { p: 1, n: "2.png", g: "404", t: "@1x" },
        "-1": { n: "PIE.htc" },
        37: { p: 1, n: "10_b.svg", g: "535", t: "image/svg+xml" },
        29: { p: 1, n: "3.png", g: "406", t: "@1x" },
        "-2": { n: "blank.gif" },
        10: { p: 1, n: "SALE.svg", g: "239", t: "image/svg+xml" },
        0: { p: 1, n: "bg.jpg", g: "153", t: "@1x" },
        1: { p: 1, n: "sparkle.png", g: "180", t: "@1x" },
        11: { p: 1, n: "arrow.svg", g: "241", t: "image/svg+xml" },
        2: { p: 1, n: "logo_Michael.png", g: "184", t: "@1x" },
        20: { p: 1, n: "icon.svg", g: "277", t: "image/svg+xml" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "main scene", o: "1", X: [0] }],
      [
        {
          o: "3",
          A: { a: [{ p: 4, h: "75" }] },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {
            589: { V: { "Main Timeline": "604" }, W: "604", n: "arrow" },
            569: { V: { "Main Timeline": "603" }, W: "603", n: "icon" },
            594: { V: { "Main Timeline": "605" }, W: "605", n: "sticker" },
            194: { V: { "Main Timeline": "602" }, W: "602", n: "Video" },
          },
          T: {
            603: {
              c: "569",
              q: false,
              z: 3.15,
              i: "603",
              a: [
                { f: "y", y: 0, z: 1.15, i: "aY", e: 360, s: 0, o: "570" },
                { y: 1.15, i: "aY", s: 360, z: 0, o: "570", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "603", p: 3, z: false, symbolOid: "609" }] },
                  o: "603",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            602: {
              b: [],
              c: "194",
              q: false,
              z: 15,
              i: "602",
              n: "Main Timeline",
              a: [{ y: 0, p: 1, i: "Video Track", z: 14.3, o: "557", f: "c" }],
              s: "194",
              f: 30,
            },
            605: {
              c: "594",
              q: false,
              z: 4,
              i: "605",
              a: [
                { f: "c", y: 0, z: 1, i: "e", e: 0, s: 1, o: "597" },
                { f: "c", y: 0, z: 1, i: "g", e: "#FFF", s: "#000", o: "595" },
                { f: "c", y: 0, z: 0.15, i: "cQ", e: 1.05, s: 1, o: "598" },
                { f: "c", y: 0, z: 0.15, i: "cR", e: 1.05, s: 1, o: "598" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 1.05, o: "598" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 1.05, o: "598" },
                { f: "c", y: 1, z: 1, i: "e", e: 0, s: 0, o: "597" },
                { f: "c", y: 1, z: 1, i: "g", e: "#FFF", s: "#FFF", o: "595" },
                { f: "c", y: 1, z: 1, i: "cR", e: 1, s: 1, o: "598" },
                { f: "c", y: 1, z: 1, i: "cQ", e: 1, s: 1, o: "598" },
                { f: "c", y: 2, z: 1, i: "e", e: 1, s: 0, o: "597" },
                { f: "c", y: 2, z: 1, i: "g", e: "#000", s: "#FFF", o: "595" },
                { f: "c", y: 2, z: 0.15, i: "cR", e: 1.05, s: 1, o: "598" },
                { f: "c", y: 2, z: 0.15, i: "cQ", e: 1.05, s: 1, o: "598" },
                { f: "c", y: 2.15, z: 0.15, i: "cR", e: 1, s: 1.05, o: "598" },
                { f: "c", y: 2.15, z: 0.15, i: "cQ", e: 1, s: 1.05, o: "598" },
                { y: 3, i: "e", s: 1, z: 0, o: "597", f: "c" },
                { y: 3, i: "g", s: "#000", z: 0, o: "595", f: "c" },
                { y: 3, i: "cR", s: 1, z: 0, o: "598", f: "c" },
                { y: 3, i: "cQ", s: 1, z: 0, o: "598", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "605", p: 3, z: false, symbolOid: "538" }] },
                  o: "605",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            513: {
              q: false,
              z: 7,
              i: "513",
              n: "info",
              a: [
                { f: "c", y: 0, z: 0.18, i: "cQ", e: 1, s: 1.4, o: "588" },
                { f: "c", y: 0, z: 1, i: "f", e: 0, s: 0, o: "588" },
                { f: "c", y: 0, z: 0.18, i: "cR", e: 1, s: 1.4, o: "588" },
                { f: "c", y: 0, z: 0.18, i: "e", e: 1, s: 0, o: "588" },
                { f: "c", y: 0, z: 0.18, i: "e", e: 1, s: 0, o: "587" },
                { y: 0.18, i: "cQ", s: 1, z: 0, o: "588", f: "c" },
                { y: 0.18, i: "cR", s: 1, z: 0, o: "588", f: "c" },
                { f: "c", y: 0.18, z: 2.25, i: "e", e: 1, s: 1, o: "588" },
                { f: "c", y: 0.18, z: 2.25, i: "e", e: 1, s: 1, o: "587" },
                { f: "q", y: 1, z: 1, i: "a", e: 79, s: 57, o: "588" },
                { f: "q", y: 1, z: 1, i: "b", e: 7, s: 21, o: "588" },
                { f: "q", y: 1, z: 1, i: "f", e: 80, s: 0, o: "588" },
                { f: "c", y: 2, z: 1, i: "a", e: 57, s: 79, o: "588" },
                { f: "c", y: 2, z: 1, i: "b", e: 21, s: 7, o: "588" },
                { f: "c", y: 2, z: 1, i: "f", e: 0, s: 80, o: "588" },
                { y: 3, i: "a", s: 57, z: 0, o: "588", f: "c" },
                { y: 3, i: "b", s: 21, z: 0, o: "588", f: "c" },
                { y: 3, i: "f", s: 0, z: 0, o: "588", f: "c" },
                { f: "c", y: 3.13, z: 0.17, i: "e", e: 0, s: 1, o: "587" },
                { f: "c", y: 3.13, z: 0.18, i: "e", e: 0, s: 1, o: "588" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "513", p: 3, z: false, symbolOid: "2" }] },
                  o: "513",
                },
                { y: 4, i: "e", s: 0, z: 0, o: "587", f: "c" },
                { y: 4.01, i: "e", s: 0, z: 0, o: "588", f: "c" },
                { f: "c", y: 6, z: 1, i: "e", e: 0, s: 1, o: "586" },
                { f: "c", y: 6, z: 1, i: "cQ", e: 0.6, s: 0.8, o: "586" },
                { f: "c", y: 6, z: 1, i: "cR", e: 0.6, s: 0.8, o: "586" },
                { y: 7, i: "e", s: 0, z: 0, o: "586", f: "c" },
                { y: 7, i: "cQ", s: 0.6, z: 0, o: "586", f: "c" },
                { y: 7, i: "cR", s: 0.6, z: 0, o: "586", f: "c" },
              ],
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 15,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "c", y: 0, z: 0.15, i: "e", e: 1, s: 0, o: "194" },
                { f: "c", y: 0, z: 15, i: "cY", e: "1", s: "0", o: "574" },
                { f: "p", y: 0, z: 1, i: "a", e: 154, s: 141, o: "589" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "589" },
                { f: "p", y: 0, z: 1, i: "cQ", e: 0.9, s: 0.7, o: "589" },
                { f: "p", y: 0, z: 1, i: "cR", e: 0.9, s: 0.7, o: "589" },
                { y: 0, i: "cY", s: "1", z: 0, o: "600", f: "c" },
                { y: 0, i: "cY", s: "1", z: 0, o: "599", f: "c" },
                { y: 0.15, i: "e", s: 1, z: 0, o: "194", f: "c" },
                { y: 1, i: "cQ", s: 0.9, z: 0, o: "589", f: "c" },
                { y: 1, i: "e", s: 1, z: 0, o: "589", f: "c" },
                { y: 1, i: "a", s: 154, z: 0, o: "589", f: "c" },
                { y: 1, i: "cR", s: 0.9, z: 0, o: "589", f: "c" },
                { f: "p", y: 6, z: 1, i: "aL", e: 30, s: 0, o: "194" },
                { f: "p", y: 6, z: 1, i: "aJ", e: 30, s: 0, o: "194" },
                { f: "p", y: 6, z: 1, i: "b", e: 495, s: 39, o: "194" },
                { f: "p", y: 6, z: 1, i: "aK", e: 30, s: 0, o: "194" },
                { f: "p", y: 6, z: 1, i: "aI", e: 30, s: 0, o: "194" },
                { f: "c", y: 6, z: 0.06, i: "e", e: 0, s: 1, o: "575" },
                { f: "c", y: 6, z: 2, i: "b", e: -88, s: 250, o: "577" },
                { f: "c", y: 6, z: 2, i: "e", e: 1, s: 0, o: "577" },
                { f: "q", y: 6, z: 1, i: "cQ", e: 0.9, s: 0.7, o: "594" },
                { f: "q", y: 6, z: 1, i: "cR", e: 0.9, s: 0.7, o: "594" },
                { f: "c", y: 6, z: 1, i: "e", e: 1, s: 0, o: "594" },
                { f: "q", y: 6.06, z: 1.09, i: "cR", e: 1, s: 1.2, o: "584" },
                { f: "c", y: 6.06, z: 1.09, i: "e", e: 1, s: 0, o: "584" },
                { f: "q", y: 6.06, z: 1.09, i: "cQ", e: 1, s: 1.2, o: "584" },
                { f: "s", y: 6.06, z: 1.16, i: "b", e: 198, s: 104, o: "580" },
                { f: "s", y: 6.06, z: 1.16, i: "b", e: 198, s: 104, o: "583" },
                { y: 6.06, i: "e", s: 0, z: 0, o: "575", f: "c" },
                { f: "c", y: 6.12, z: 1.09, i: "b", e: 182, s: 622, o: "579" },
                { f: "c", y: 6.12, z: 1.09, i: "b", e: 182, s: 622, o: "582" },
                { f: "c", y: 6.16, z: 1.08, i: "b", e: 167, s: 622, o: "581" },
                { f: "c", y: 6.16, z: 1.08, i: "b", e: 167, s: 622, o: "578" },
                { y: 7, i: "cR", s: 0.9, z: 0, o: "594", f: "c" },
                { y: 7, i: "cQ", s: 0.9, z: 0, o: "594", f: "c" },
                { y: 7, i: "aL", s: 30, z: 0, o: "194", f: "c" },
                { y: 7, i: "b", s: 495, z: 0, o: "194", f: "c" },
                { y: 7, i: "aI", s: 30, z: 0, o: "194", f: "c" },
                { y: 7, i: "aJ", s: 30, z: 0, o: "194", f: "c" },
                { y: 7, i: "aK", s: 30, z: 0, o: "194", f: "c" },
                { y: 7, i: "e", s: 1, z: 0, o: "594", f: "c" },
                { f: "c", y: 7.15, z: 1.15, i: "e", e: 1, s: 0, o: "593" },
                { y: 7.15, i: "cQ", s: 1, z: 0, o: "584", f: "c" },
                { y: 7.15, i: "cR", s: 1, z: 0, o: "584", f: "c" },
                { y: 7.15, i: "e", s: 1, z: 0, o: "584", f: "c" },
                { y: 7.21, i: "b", s: 182, z: 0, o: "579", f: "d" },
                { y: 7.21, i: "b", s: 182, z: 0, o: "582", f: "d" },
                { y: 7.22, i: "b", s: 198, z: 0, o: "580", f: "d" },
                { y: 7.22, i: "b", s: 198, z: 0, o: "583", f: "d" },
                { y: 7.24, i: "b", s: 167, z: 0, o: "581", f: "d" },
                { y: 7.24, i: "b", s: 167, z: 0, o: "578", f: "d" },
                {
                  f: "c",
                  p: 2,
                  y: 8,
                  z: 1.01,
                  i: "ActionHandler",
                  e: {
                    a: [{ b: "509", p: 8, z: false, symbolOid: "2", J: false }],
                  },
                  s: { a: [{ b: "513", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 8, i: "b", s: -88, z: 0, o: "577", f: "c" },
                { y: 8, i: "e", s: 1, z: 0, o: "577", f: "c" },
                { y: 9, i: "e", s: 1, z: 0, o: "593", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 9.01,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [{ b: "509", p: 8, z: false, symbolOid: "2", J: false }],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 15, i: "cY", s: "1", z: 0, o: "574", f: "c" },
              ],
              f: 30,
              b: [
                {
                  D: 15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "602",
                },
                {
                  D: 3.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "603",
                },
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 1,
                  b: "604",
                },
                {
                  D: 4,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 6.06,
                  b: "605",
                },
              ],
            },
            604: {
              c: "589",
              q: false,
              z: 3,
              i: "604",
              a: [
                { f: "c", y: 0, z: 1, i: "cQ", e: 0.7, s: 0.9, o: "590" },
                { f: "c", y: 0, z: 1, i: "cR", e: 0.7, s: 0.9, o: "590" },
                { f: "c", y: 0, z: 1, i: "a", e: -16, s: 1, o: "590" },
                { f: "c", y: 1, z: 1, i: "cR", e: 0.9, s: 0.7, o: "590" },
                { f: "c", y: 1, z: 1, i: "cQ", e: 0.9, s: 0.7, o: "590" },
                { f: "c", y: 1, z: 1, i: "a", e: 1, s: -16, o: "590" },
                { y: 2, i: "cR", s: 0.9, z: 0, o: "590", f: "c" },
                { y: 2, i: "cQ", s: 0.9, z: 0, o: "590", f: "c" },
                { y: 2, i: "a", s: 1, z: 0, o: "590", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "604", p: 3, z: false, symbolOid: "524" }] },
                  o: "604",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            509: {
              q: false,
              z: 6.14,
              i: "509",
              n: "cards_3",
              a: [
                { f: "c", y: 0, z: 1.07, i: "b", e: 198, s: 198, o: "583" },
                { f: "c", y: 0, z: 1.07, i: "f", e: 30, s: 0, o: "583" },
                { f: "c", y: 0, z: 1.07, i: "a", e: 393, s: 33, o: "583" },
                { f: "c", y: 0, z: 1.07, i: "cY", e: "0", s: "1", o: "580" },
                { f: "c", y: 0, z: 1.07, i: "b", e: 198, s: 198, o: "578" },
                { f: "c", y: 0, z: 1.07, i: "f", e: 30, s: 0, o: "578" },
                { f: "c", y: 0, z: 1.07, i: "a", e: 393, s: 33, o: "578" },
                { f: "c", y: 0, z: 1, i: "e", e: 0, s: 1, o: "593" },
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 3,
                  i: "ActionHandler",
                  e: { a: [{ p: 7, b: "509", symbolOid: "2" }] },
                  s: { a: [{ p: 7, b: "509", symbolOid: "2" }] },
                  o: "509",
                },
                { f: "c", y: 0, z: 1, i: "cY", e: "1", s: "0", o: "599" },
                { f: "c", y: 0, z: 3, i: "cY", e: "0", s: "1", o: "600" },
                { f: "c", y: 0.2, z: 1.05, i: "b", e: 197, s: 182, o: "582" },
                { f: "c", y: 0.22, z: 1.05, i: "a", e: 33, s: 33, o: "581" },
                { f: "c", y: 0.22, z: 1.05, i: "b", e: 182, s: 167, o: "581" },
                { f: "c", y: 1, z: 1, i: "e", e: 1, s: 0, o: "592" },
                { y: 1, i: "e", s: 0, z: 0, o: "593", f: "c" },
                { y: 1, i: "cY", s: "1", z: 0, o: "599", f: "c" },
                { f: "c", y: 1.07, z: 0.02, i: "e", e: 0, s: 1, o: "583" },
                { f: "c", y: 1.07, z: 1.05, i: "b", e: 167, s: 198, o: "580" },
                { f: "c", y: 1.07, z: 1.07, i: "f", e: 0, s: 30, o: "580" },
                { f: "c", y: 1.07, z: 1.07, i: "a", e: 33, s: 393, o: "580" },
                { f: "c", y: 1.07, z: 0.02, i: "e", e: 0, s: 1, o: "578" },
                { y: 1.07, i: "f", s: 30, z: 0, o: "583", f: "c" },
                { y: 1.07, i: "a", s: 393, z: 0, o: "583", f: "c" },
                { y: 1.07, i: "b", s: 198, z: 0, o: "583", f: "c" },
                { y: 1.07, i: "cY", s: "0", z: 0, o: "580", f: "c" },
                { y: 1.07, i: "f", s: 30, z: 0, o: "578", f: "c" },
                { y: 1.07, i: "a", s: 393, z: 0, o: "578", f: "c" },
                { y: 1.07, i: "b", s: 198, z: 0, o: "578", f: "c" },
                { y: 1.09, i: "e", s: 0, z: 0, o: "583", f: "c" },
                { y: 1.09, i: "e", s: 0, z: 0, o: "578", f: "c" },
                { f: "c", y: 1.25, z: 2.05, i: "b", e: 197, s: 197, o: "582" },
                { y: 1.27, i: "a", s: 33, z: 0, o: "581", f: "c" },
                { f: "c", y: 1.27, z: 2.25, i: "b", e: 182, s: 182, o: "581" },
                { f: "c", y: 2, z: 2, i: "e", e: 1, s: 1, o: "592" },
                { f: "c", y: 2.12, z: 2.25, i: "b", e: 167, s: 167, o: "580" },
                { y: 2.14, i: "f", s: 0, z: 0, o: "580", f: "c" },
                { y: 2.14, i: "a", s: 33, z: 0, o: "580", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 3.11,
                  i: "ActionHandler",
                  e: { a: [{ i: 6, b: "513", p: 9, symbolOid: "2" }] },
                  s: { a: [{ p: 7, b: "509", symbolOid: "2" }] },
                  o: "509",
                },
                { f: "c", y: 3, z: 2, i: "cY", e: "1", s: "0", o: "600" },
                { f: "c", y: 4, z: 1.07, i: "f", e: 30, s: 0, o: "582" },
                { f: "c", y: 4, z: 1.07, i: "a", e: 393, s: 33, o: "582" },
                { f: "c", y: 4, z: 1.07, i: "cY", e: "0", s: "1", o: "579" },
                { f: "c", y: 4, z: 1.07, i: "b", e: 283, s: 197, o: "582" },
                { f: "c", y: 4, z: 1, i: "e", e: 0, s: 1, o: "592" },
                { f: "c", y: 4.22, z: 1.04, i: "b", e: 197, s: 182, o: "581" },
                { f: "c", y: 5, z: 1, i: "e", e: 1, s: 0, o: "591" },
                { y: 5, i: "cY", s: "1", z: 0, o: "600", f: "c" },
                { y: 5, i: "e", s: 0, z: 0, o: "592", f: "c" },
                { f: "c", y: 5.07, z: 0.02, i: "e", e: 0, s: 1, o: "582" },
                { f: "c", y: 5.07, z: 1.07, i: "b", e: 167, s: 283, o: "579" },
                { f: "c", y: 5.07, z: 1.07, i: "a", e: 33, s: 393, o: "579" },
                { f: "c", y: 5.07, z: 1.07, i: "f", e: 0, s: 30, o: "579" },
                { y: 5.07, i: "f", s: 30, z: 0, o: "582", f: "c" },
                { y: 5.07, i: "a", s: 393, z: 0, o: "582", f: "c" },
                { y: 5.07, i: "cY", s: "0", z: 0, o: "579", f: "c" },
                { f: "c", y: 5.07, z: 1.04, i: "b", e: 182, s: 167, o: "580" },
                { y: 5.07, i: "b", s: 283, z: 0, o: "582", f: "c" },
                { y: 5.09, i: "e", s: 0, z: 0, o: "582", f: "c" },
                { y: 5.26, i: "b", s: 197, z: 0, o: "581", f: "c" },
                { y: 6, i: "e", s: 1, z: 0, o: "591", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 6.11,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ i: 6, b: "513", p: 9, symbolOid: "2" }] },
                  o: "509",
                },
                { y: 6.11, i: "b", s: 182, z: 0, o: "580", f: "c" },
                { y: 6.14, i: "b", s: 167, z: 0, o: "579", f: "c" },
                { y: 6.14, i: "a", s: 33, z: 0, o: "579", f: "c" },
                { y: 6.14, i: "f", s: 0, z: 0, o: "579", f: "c" },
              ],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "577",
            "585",
            "576",
            "554",
            "599",
            "600",
            "601",
            "555",
            "556",
            "584",
            "595",
            "598",
            "594",
            "581",
            "578",
            "582",
            "579",
            "597",
            "596",
            "583",
            "580",
            "586",
            "588",
            "587",
            "568",
            "567",
            "575",
            "574",
            "564",
            "593",
            "591",
            "592",
            "590",
            "589",
            "566",
            "565",
            "572",
            "573",
            "569",
            "570",
            "571",
            "557",
            "194",
            "560",
            "562",
            "558",
            "559",
            "561",
            "563",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            588: {
              p: "no-repeat",
              b: 21,
              c: 43,
              q: "100% 100%",
              d: 44,
              r: "inline",
              e: 0,
              cQ: 1,
              f: 0,
              cR: 1,
              aP: "auto",
              h: "398",
              aY: 0,
              bF: "586",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 2,
              cN: "none",
              tX: 0.71,
              a: 57,
              tY: 0.66,
            },
            556: {
              p: "no-repeat",
              c: 320,
              q: "100% 100%",
              bS: 18,
              d: 480,
              r: "inline",
              I: "None",
              J: "None",
              K: "None",
              L: "None",
              aP: "auto",
              h: "153",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              k: "div",
              D: "#D8DDE4",
              aK: 0,
              cN: "none",
              a: 0,
              b: 0,
            },
            575: {
              cN: "none",
              x: "visible",
              a: 116,
              b: 2,
              j: "absolute",
              bF: "568",
              c: 197,
              k: "div",
              z: 1,
              d: 55,
              aP: "auto",
              e: 1,
            },
            594: {
              x: "visible",
              a: 205,
              cA: false,
              b: 65,
              j: "absolute",
              bF: "585",
              c: 100,
              k: "div",
              z: 1,
              d: 100,
              bY: 1,
              cQ: 0.7,
              e: 0,
              bZ: 180,
              bX: false,
              cV: [],
              cR: 0.7,
            },
            562: {
              c: 35,
              d: 35,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#A60303",
              L: "Solid",
              M: 0,
              bF: "558",
              N: 0,
              A: "#1E2B46",
              x: "visible",
              j: "absolute",
              B: "#1E2B46",
              P: 0,
              O: 0,
              C: "#1E2B46",
              z: 1,
              aJ: 20,
              D: "#1E2B46",
              aK: 20,
              k: "div",
              aI: 20,
              a: 0,
              aL: 20,
              b: 0,
            },
            581: {
              p: "no-repeat",
              c: 232,
              q: "100% 100%",
              bS: 13,
              d: 232,
              r: "inline",
              cQ: 1,
              e: 1,
              f: 0,
              cR: 1,
              aP: "auto",
              h: "406",
              bF: "577",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 12,
              cN: "none",
              a: 33,
              b: 622,
            },
            589: {
              x: "visible",
              a: 141,
              cA: false,
              b: 17,
              j: "absolute",
              bF: "575",
              c: 32,
              k: "div",
              z: 2,
              d: 22,
              bY: 1,
              cQ: 0.7,
              e: 0,
              bZ: 180,
              bX: false,
              cV: [],
              cR: 0.7,
            },
            557: {
              c: 496,
              d: 279,
              cQ: 1.05,
              aO: "0",
              cR: 1.05,
              bE: "191",
              aH: "1",
              aP: "pointer",
              i: "videom",
              bF: "194",
              aQ: false,
              j: "absolute",
              dA: "1",
              x: "visible",
              aR: "1",
              aA: { a: [{ p: 4, h: "202" }] },
              k: "video",
              dB: "button",
              z: 4,
              a: -104,
              b: 5,
            },
            576: {
              cN: "none",
              x: "visible",
              a: 0,
              bS: 383,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 12,
              d: 480,
              bF: "554",
              aP: "auto",
            },
            595: {
              c: 100,
              d: 100,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#000",
              L: "Solid",
              M: 0,
              bF: "598",
              N: 0,
              A: "#D8DDE4",
              x: "visible",
              j: "absolute",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 1,
              aJ: "50%",
              D: "#D8DDE4",
              aK: "50%",
              k: "div",
              aI: "50%",
              a: 0,
              aL: "50%",
              b: 0,
            },
            563: {
              h: "192",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 13,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "558",
              dB: "img",
              d: 9,
              i: "krestm",
              cQ: 0.5,
              k: "div",
              c: 8,
              aP: "pointer",
              cR: 0.5,
            },
            582: {
              p: "no-repeat",
              c: 232,
              q: "100% 100%",
              bS: 13,
              d: 232,
              r: "inline",
              cQ: 1,
              e: 1,
              f: 0,
              cR: 1,
              aP: "auto",
              h: "404",
              bF: "577",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 13,
              cN: "none",
              a: 33,
              b: 622,
            },
            558: {
              x: "visible",
              k: "div",
              c: 35,
              aP: "auto",
              cN: "none",
              d: 35,
              z: 5,
              a: 246,
              j: "absolute",
              bF: "194",
              b: 8,
            },
            577: {
              cN: "none",
              x: "visible",
              bS: 383,
              a: 10,
              b: 250,
              j: "absolute",
              bF: "576",
              z: 2,
              r: "inline",
              k: "div",
              d: 481,
              c: 300,
              cQ: 1,
              e: 0,
              aP: "auto",
              f: 0,
              cR: 1,
            },
            596: {
              h: "535",
              p: "no-repeat",
              x: "visible",
              a: 11,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "598",
              b: 30,
              d: 40,
              k: "div",
              c: 77,
            },
            564: {
              h: "239",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "575",
              b: 13,
              d: 30,
              k: "div",
              c: 94,
            },
            583: {
              p: "no-repeat",
              c: 232,
              q: "100% 100%",
              bS: 13,
              d: 232,
              r: "inline",
              e: 1,
              cQ: 1,
              gg: "1",
              f: 0,
              BDbL: 0,
              cR: 1,
              aP: "auto",
              h: "401",
              bF: "577",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 14,
              Q: 0,
              R: "#000",
              cN: "none",
              S: 0,
              a: 33,
              T: 0,
              b: 104,
            },
            559: {
              h: "193",
              p: "no-repeat",
              x: "visible",
              a: 7,
              q: "100% 100%",
              b: 6,
              j: "absolute",
              r: "inline",
              bF: "558",
              z: 2,
              dB: "img",
              d: 23,
              k: "div",
              cQ: 0.5,
              c: 17,
              aP: "pointer",
              cR: 0.5,
              bD: "auto",
            },
            570: {
              h: "277",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: 2,
              j: "absolute",
              r: "inline",
              bF: "569",
              z: 5,
              dB: "img",
              d: 35,
              k: "div",
              aY: 0,
              cQ: 1,
              c: 28,
              cR: 1,
            },
            578: {
              p: "no-repeat",
              c: 232,
              q: "100% 100%",
              bS: 13,
              d: 232,
              r: "inline",
              cY: "1",
              e: 1,
              cQ: 1,
              f: 30,
              cR: 1,
              aP: "auto",
              h: "406",
              bF: "577",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 5,
              cN: "none",
              a: 33,
              b: 622,
            },
            194: {
              c: 290,
              bS: 343,
              d: 291,
              cQ: 1.1,
              e: 0,
              cA: false,
              cR: 1.1,
              aP: "auto",
              cS: true,
              cK: { a: [{ b: "602", p: 3, z: false, symbolOid: "58" }] },
              bF: "554",
              aI: 0,
              j: "absolute",
              x: "hidden",
              cL: "194",
              k: "div",
              aJ: 0,
              cM: true,
              z: 13,
              bX: false,
              aK: 0,
              cV: [],
              cN: "none",
              bY: 1,
              a: 16,
              aL: 0,
              bZ: 180,
              b: 39,
            },
            597: {
              h: "533",
              p: "no-repeat",
              x: "visible",
              a: 11,
              q: "100% 100%",
              b: 30,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "598",
              dB: "img",
              d: 40,
              k: "div",
              c: 77,
              e: 1,
            },
            565: {
              cN: "none",
              x: "hidden",
              bS: 31,
              a: 0,
              b: 411,
              j: "absolute",
              bF: "554",
              z: 14,
              r: "inline",
              k: "div",
              d: 69,
              aK: 30,
              c: 320,
              e: 1,
              aP: "auto",
              aL: 30,
            },
            584: {
              p: "no-repeat",
              c: 90,
              q: "100% 100%",
              d: 49,
              r: "inline",
              cQ: 1.2,
              e: 0,
              f: 0,
              cR: 1.2,
              aP: "auto",
              h: "497",
              bF: "585",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 5,
              cN: "none",
              a: 115,
              b: 16,
            },
            571: {
              aU: 8,
              G: "#FFF",
              c: 100,
              aV: 8,
              r: "inline",
              d: 9,
              s: "Montserrat",
              t: 18,
              Y: 4,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "700",
              w: "300 m",
              bF: "568",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 6,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 75,
              b: 105,
            },
            579: {
              p: "no-repeat",
              c: 232,
              q: "100% 100%",
              bS: 13,
              d: 232,
              r: "inline",
              cY: "1",
              cQ: 1,
              f: 30,
              cR: 1,
              aP: "auto",
              h: "404",
              bF: "577",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 6,
              cN: "none",
              a: 33,
              b: 622,
            },
            590: {
              h: "241",
              p: "no-repeat",
              tY: 0.5,
              a: 1,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "589",
              b: 1,
              z: 3,
              d: 22,
              dB: "img",
              cQ: 0.9,
              e: 1,
              k: "div",
              c: 32,
              cR: 0.9,
              tX: 0,
            },
            598: {
              x: "visible",
              cQ: 1,
              k: "div",
              cR: 1,
              c: 100,
              d: 100,
              z: 2,
              a: 0,
              bF: "594",
              j: "absolute",
              b: 0,
            },
            566: {
              c: 320,
              bS: 319,
              d: 69,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#A60303",
              L: "Solid",
              M: 0,
              bF: "565",
              N: 0,
              A: "#ECECEC",
              j: "absolute",
              x: "visible",
              B: "#ECECEC",
              P: 0,
              O: 0,
              C: "#ECECEC",
              z: 1,
              k: "div",
              D: "#ECECEC",
              aK: 0,
              a: 0,
              aL: 0,
              b: 0,
            },
            585: {
              x: "visible",
              k: "div",
              c: 320,
              aP: "auto",
              cN: "none",
              d: 63,
              z: 20,
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            572: {
              aU: 8,
              G: "#FFF",
              c: 204,
              aV: 8,
              r: "inline",
              d: 28,
              s: "Montserrat",
              X: 0,
              t: 12,
              Y: 15,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "500",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">New Balance - Galeria Kaskada\nal. Niepodleg\u0142o\u015bci 36, poziom +1\n</div>',
              bF: "568",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 7,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 75,
              b: 63,
            },
            591: {
              h: "527",
              p: "no-repeat",
              x: "visible",
              a: 48,
              q: "100% 100%",
              b: 368,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "576",
              dB: "img",
              d: 14,
              k: "div",
              c: 223,
              e: 0,
            },
            599: {
              c: 320,
              bS: 18,
              d: 480,
              I: "Solid",
              cY: "1",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#241011",
              L: "Solid",
              aP: "pointer",
              M: 0,
              bF: "601",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 2,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "376" },
                  { b: "509", p: 8, z: false, symbolOid: "2", J: false },
                  { i: 6, b: "513", p: 9, symbolOid: "2" },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            567: {
              cN: "none",
              x: "visible",
              bS: 31,
              a: 0,
              b: 346,
              j: "absolute",
              bF: "554",
              c: 320,
              k: "div",
              z: 15,
              d: 134,
              r: "inline",
              e: 1,
              aP: "auto",
            },
            586: {
              cN: "none",
              x: "visible",
              a: 176,
              b: 141,
              j: "absolute",
              r: "inline",
              z: 6,
              k: "div",
              bF: "585",
              d: 91,
              c: 137,
              cQ: 0.8,
              e: 1,
              aP: "auto",
              cR: 0.8,
            },
            554: {
              x: "visible",
              k: "div",
              c: 320,
              aP: "auto",
              cN: "none",
              d: 480,
              z: 8,
              a: 0,
              bS: 18,
              j: "absolute",
              b: 0,
            },
            600: {
              c: 320,
              bS: 18,
              d: 480,
              I: "Solid",
              cY: "1",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#241011",
              L: "Solid",
              aP: "pointer",
              M: 0,
              bF: "601",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 1,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "377" },
                  { b: "509", p: 8, z: false, symbolOid: "2", J: false },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            573: {
              c: 51,
              d: 51,
              I: "Solid",
              e: 1,
              J: "Solid",
              K: "Solid",
              g: "#FFF",
              L: "Solid",
              M: 0,
              bF: "569",
              N: 0,
              A: "#D8DDE4",
              x: "visible",
              j: "absolute",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 4,
              aJ: "50%",
              D: "#D8DDE4",
              aK: "50%",
              k: "div",
              aI: "50%",
              a: -4,
              aL: "50%",
              b: -6,
            },
            592: {
              h: "529",
              p: "no-repeat",
              x: "visible",
              a: 58,
              q: "100% 100%",
              b: 368,
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "576",
              dB: "img",
              d: 14,
              k: "div",
              c: 204,
              e: 0,
            },
            560: {
              c: 35,
              d: 35,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#181E39",
              L: "Solid",
              aP: "pointer",
              M: 0,
              bF: "558",
              N: 0,
              A: "#1E2B46",
              x: "visible",
              j: "absolute",
              B: "#1E2B46",
              P: 0,
              O: 0,
              C: "#1E2B46",
              z: 5,
              dB: "button",
              D: "#1E2B46",
              aA: { a: [{ p: 4, h: "203" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            568: {
              cN: "none",
              x: "visible",
              a: 0,
              bS: 383,
              b: 0,
              j: "absolute",
              bF: "567",
              c: 320,
              k: "div",
              z: 4,
              d: 134,
              aP: "auto",
            },
            587: {
              cN: "none",
              h: "405",
              p: "no-repeat",
              x: "visible",
              a: 10,
              q: "100% 100%",
              b: 71,
              j: "absolute",
              r: "inline",
              bF: "586",
              z: 1,
              dB: "img",
              d: 26,
              k: "div",
              cQ: 1,
              e: 0,
              c: 117,
              aP: "auto",
              cR: 1,
            },
            555: {
              c: 320,
              bS: 18,
              d: 480,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#241011",
              L: "Solid",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 2,
              dB: "button",
              D: "#D8DDE4",
              aA: { a: [{ p: 4, h: "65" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            601: {
              x: "visible",
              k: "div",
              c: 320,
              aP: "auto",
              cN: "none",
              d: 480,
              z: 3,
              a: 0,
              bS: 319,
              j: "absolute",
              b: 0,
            },
            574: {
              c: 56,
              d: 55,
              I: "Solid",
              cY: "0",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#A60303",
              L: "Solid",
              aP: "pointer",
              M: 0,
              bF: "575",
              N: 0,
              A: "#D8DDE4",
              x: "visible",
              j: "absolute",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 4,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "379" },
                  {
                    i: 6,
                    b: "kTimelineDefaultIdentifier",
                    p: 9,
                    symbolOid: "2",
                  },
                ],
              },
              k: "div",
              a: 141,
              b: 0,
            },
            593: {
              h: "531",
              p: "no-repeat",
              x: "visible",
              a: 27,
              q: "100% 100%",
              b: 368,
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "576",
              dB: "img",
              d: 15,
              k: "div",
              c: 265,
              e: 0,
            },
            561: {
              h: "190",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 11,
              j: "absolute",
              r: "inline",
              bF: "558",
              cY: "1",
              z: 4,
              d: 13,
              dB: "img",
              i: "onm",
              cQ: 0.5,
              k: "div",
              c: 8,
              cR: 0.5,
            },
            569: {
              cN: "none",
              x: "visible",
              a: 21,
              cA: false,
              b: 81,
              j: "absolute",
              r: "inline",
              c: 43,
              k: "div",
              z: 5,
              d: 38,
              bF: "568",
              cQ: 1,
              aP: "auto",
              bY: 1,
              bZ: 180,
              bX: false,
              cR: 1,
              cV: [],
            },
            580: {
              p: "no-repeat",
              c: 232,
              q: "100% 100%",
              bS: 13,
              d: 232,
              r: "inline",
              cY: "1",
              e: 1,
              cQ: 1,
              gg: "1",
              f: 30,
              BDbL: 0,
              cR: 1,
              aP: "auto",
              h: "401",
              bF: "577",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 7,
              Q: 0,
              R: "#000",
              cN: "none",
              S: 0,
              a: 33,
              T: 0,
              b: 104,
            },
          },
        },
      ],
      { 194: ["557", "558", "559", "560", "561", "562", "563"] },
      h,
      {
        y: { p: 0, q: [[0, 0, 0.445, 0.05, 0.55, 0.95, 1, 1]] },
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        s: { p: 0, q: [[0, 0, 0.39, 0.575, 0.565, 1, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
