(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/Azarro",
      f = "Azarro_rich_320x480_line_3_1_web_copy",
      g = "azarrorich320x480line31webcopy_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/azarrorich320x480line31webcopy_hype_generated_script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "action1",
        source:
          "function(hypeDocument, element, event) {\t\n\t\n\twindow.action1();\n}",
        identifier: "100",
      },
      {
        name: "action2",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action2();\n}",
        identifier: "101",
      },
      {
        name: "action3",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action3();\n}",
        identifier: "102",
      },
      {
        name: "action4",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action4();\n}",
        identifier: "103",
      },
      {
        name: "snow",
        source:
          'function(hypeDocument, element, event) {\tsnowFall.snow(document.getElementsByClassName("enclosed")[0],{round : true, flakeCount : 30, minSpeed : 1, maxSpeed : 4, minSize : 1, maxSize : 4} );\t\n//enclosed - \u044d\u0442\u043e \u0438\u043c\u044f \u0437\u0430\u0434\u0430\u0435\u043c \u043a\u0430\u043a\u043e\u043c\u0443-\u043d\u0438\u0431\u0443\u0434\u044c \u043e\u0431\u044c\u0435\u043a\u0442\u0443 (\u043f\u0430\u043f\u043a\u0430 \u0438\u043b\u0438 \u043f\u0440\u044f\u043c\u043e\u0443\u0433\u043e\u043b\u044c\u043d\u0438\u043a), \u0432 \u0440\u0430\u043c\u043a\u0430\u0445 \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u0443\u0434\u0435\u0442 \u043f\u043e\u043a\u0430\u0437\u0430\u043d \u0441\u043d\u0435\u0433\t\n//\u0444\u0443\u043d\u043a\u0446\u0438\u044e snow \u043d\u0435 \u0437\u0430\u0431\u044b\u0432\u0430\u0442\u044c \u0437\u0430\u043f\u0443\u0441\u043a\u0430\u0442\u044c \u043f\u0440\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0435 \u0441\u0446\u0435\u043d\u044b\n\tsnowFall.snow(document.getElementsByClassName("enclosed1")[0],{round : true, flakeCount : 30, minSpeed : 1, maxSpeed : 4, minSize : 1, maxSize : 4} );\t\n//enclosed1 - \u044d\u0442\u043e \u0438\u043c\u044f \u043e\u0431\u044a\u0435\u043a\u0442\u0430 \u043d\u0430 \u0434\u0440\u0443\u0433\u043e\u0439 \u0441\u0446\u0435\u043d\u0435\n}',
        identifier: "107",
      },
      {
        name: "activateGift",
        source:
          'function(hypeDocument, element, event) {\t    var giftName = element.id; // or hardcode "gift_1" etc. if you prefer\n\n    // Mark gift as activated\n    window.giftStatus[giftName] = true;\n\n    // Check if all 4 gifts are activated\n    if (window.giftStatus.gift_1 &&\n        window.giftStatus.gift_2 &&\n        window.giftStatus.gift_3 &&\n        window.giftStatus.gift_4) {\n\n        // Delay scene change by 1.09 seconds\n        setTimeout(function() {\n            hypeDocument.showSceneNamed("Final_new", hypeDocument.kSceneTransitionCrossfade, 1.0);\n        }, 1200); // 1090 milliseconds\n}\n\t\n}',
        identifier: "167",
      },
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\twindow.gotosite();\n        \t\n        \t\n\t\n}",
        identifier: "359",
      },
      {
        name: "reverse_timer",
        source:
          "function(hypeDocument, element, event) {\n    if (window._hyb_ssp) {\n        window._hyb_ssp.initTimer();\n    } else {\n        setTimeout(() => reverse_timer(hypeDocument, element, event), 200);\n    }\n\t\n}",
        identifier: "536",
      },
      {
        name: "initTimer_rich",
        source:
          'function(hypeDocument, element, event) {\t\n\tcountDownTimer("24/12/2025 23:59", "days", "hours", "minutes", "seconds");\n\n    function countDownTimer(\n      dt,\n      daysElementId,\n      hoursElementId,\n      minutesElementId,\n      secondsElementId\n    ) {\n      const [endDay, endMonth, endYear] = dt.split(" ")[0].split("/");\n      const endDate = `${endMonth}/${endDay}/${endYear} ${convertTimeTo12hourFormat(\n        dt.split(" ")[1]\n      )}`;\n      const end = new Date(endDate);\n\n      let _second = 1000;\n      let _minute = _second * 60;\n      let _hour = _minute * 60;\n      let _day = _hour * 24;\n      let timer;\n\n      function showRemaining() {\n        let days, hours, minutes, seconds;\n        const now = new Date();\n        let distance = end - now;\n        if (distance < 0) {\n          clearInterval(timer);\n          document.getElementById(daysElementId).innerHTML = 0;\n          document.getElementById(hoursElementId).innerHTML = 0;\n          document.getElementById(minutesElementId).innerHTML = 0;\n          document.getElementById(secondsElementId).innerHTML = 0;\n\n          return;\n        }\n\n        days = Math.floor(distance / _day);\n        hours = Math.floor((distance % _day) / _hour);\n        minutes = Math.floor((distance % _hour) / _minute);\n        seconds = Math.floor((distance % _minute) / _second);\n\n        console.log(days, hours, minutes);\n\n        document.getElementById(daysElementId).innerHTML = days;\n        document.getElementById(hoursElementId).innerHTML = hours;\n        document.getElementById(minutesElementId).innerHTML =\n          minutes;\n        document.getElementById(secondsElementId).innerHTML =\n          seconds;\n      }\n\n      timer = setInterval(showRemaining, 1000);\n    }\n\n    function convertTimeTo12hourFormat(time) {\n      time = time\n        .toString()\n        .match(/^([01]\\d|2[0-3])(:)([0-5]\\d)(:[0-5]\\d)?$/) || [time];\n\n      if (time.length > 1) {\n        time = time.slice(1);\n        time[5] = +time[0] < 12 ? " AM" : " PM";\n        time[0] = +time[0] % 12 || 12;\n      }\n      return time.join("");\n    }\n\n}',
        identifier: "573",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        3: { p: 1, n: "ellipse.svg", g: "432", t: "image/svg+xml" },
        12: { p: 1, n: "godzin.svg", g: "551", t: "image/svg+xml" },
        21: { p: 1, n: "rossmann_logo-1.png", g: "581", t: "@1x" },
        4: { p: 1, n: "glitter.png", g: "435", t: "@1x" },
        30: { p: 1, n: "parfume2.png", g: "517", t: "@1x" },
        13: { p: 1, n: "dni.svg", g: "553", t: "image/svg+xml" },
        5: { p: 1, n: "timer_text.svg", g: "505", t: "image/svg+xml" },
        22: { p: 1, n: "lid_2.png", g: "582", t: "@1x" },
        6: { p: 1, n: "timer_board.svg", g: "507", t: "image/svg+xml" },
        31: { p: 1, n: "parfume4-1.png", g: "586", t: "@1x" },
        14: { p: 1, n: "bg_original.jpg", g: "5", t: "@1x" },
        7: { p: 1, n: "lights_.png", g: "521", t: "@1x" },
        23: { p: 1, n: "text_2_bottom.svg", g: "584", t: "image/svg+xml" },
        32: { p: 1, n: "parfume4.png", g: "513", t: "@1x" },
        15: { p: 1, n: "logo_.png", g: "173", t: "@1x" },
        8: { p: 1, n: "button_.svg", g: "523", t: "image/svg+xml" },
        24: { p: 1, n: "ref_320x480.jpg", g: "585", t: "@1x" },
        9: { p: 1, n: "320x480.jpg", g: "525", t: "@1x" },
        16: { p: 1, n: "bottom_2.png", g: "576", t: "@1x" },
        25: { p: 1, n: "texts_2_top.svg", g: "587", t: "image/svg+xml" },
        17: { p: 1, n: "bg_original-1.jpg", g: "577", t: "@1x" },
        26: { p: 1, n: "parfume5.png", g: "511", t: "@1x" },
        18: { p: 1, n: "logo_-1.png", g: "578", t: "@1x" },
        27: { p: 1, n: "parfume1.png", g: "519", t: "@1x" },
        19: { p: 1, n: "outer_2.png", g: "579", t: "@1x" },
        28: { p: 1, n: "parfume3.png", g: "515", t: "@1x" },
        "-1": { n: "PIE.htc" },
        29: { p: 1, n: "parfume2-1.png", g: "583", t: "@1x" },
        "-2": { n: "blank.gif" },
        10: { p: 1, n: "text_.svg", g: "18", t: "image/svg+xml" },
        0: { p: 1, n: "rossmann_logo.png", g: "10", t: "@1x" },
        1: { n: "snowfall.min.js" },
        11: { p: 1, n: "minut.svg", g: "549", t: "image/svg+xml" },
        2: { p: 1, n: "text_bottom.svg", g: "16", t: "image/svg+xml" },
        20: { p: 1, n: "pointer_.svg", g: "580", t: "image/svg+xml" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Lato:700&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [
        { n: "Main", o: "241", X: [0] },
        { n: "Main Copy", o: "592", X: [1] },
      ],
      [
        {
          o: "291",
          A: {
            a: [
              { p: 4, h: "107" },
              { p: 4, h: "573" },
            ],
          },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {},
          T: {
            535: {
              j: {
                0: [
                  [75, 33, 75, 33, 75, -33, 33, -31],
                  [33, -31, -21, -28, -23, 74, -23, 74],
                ],
                1: [
                  [76, 33, 76, 33, 71, -18, 102, -23],
                  [102, -23, 147, -30, 165, 65, 165, 65],
                ],
              },
              q: false,
              z: 22,
              i: "535",
              n: "carousel",
              a: [
                { f: "c", y: 0, z: 0.29, i: "f", e: -27, s: 0, o: "706" },
                {
                  o: "706",
                  y: 0,
                  z: 0.29,
                  i: "a",
                  e: -89,
                  a: "0",
                  f: "c",
                  s: 9,
                },
                {
                  o: "706",
                  y: 0,
                  z: 0.29,
                  i: "b",
                  e: 42,
                  a: "0",
                  f: "c",
                  s: 1,
                },
                { f: "c", y: 0, z: 0.13, i: "e", e: 1, s: 0, o: "704" },
                { f: "c", y: 0, z: 0.19, i: "b", e: -49, s: -33, o: "704" },
                { y: 0, i: "a", s: 192, z: 0, o: "695", f: "c" },
                { f: "c", y: 0.03, z: 0.25, i: "f", e: 34, s: 0, o: "711" },
                {
                  o: "711",
                  y: 0.03,
                  z: 0.25,
                  i: "b",
                  e: 33,
                  a: "1",
                  f: "c",
                  s: 1,
                },
                {
                  o: "711",
                  y: 0.03,
                  z: 0.25,
                  i: "a",
                  e: 99,
                  a: "1",
                  f: "c",
                  s: 10,
                },
                { f: "e", y: 0.07, z: 0.11, i: "b", e: -36, s: -20, o: "709" },
                { f: "e", y: 0.07, z: 0.11, i: "e", e: 1, s: 0, o: "709" },
                { f: "c", y: 0.13, z: 3.17, i: "e", e: 1, s: 1, o: "704" },
                { f: "c", y: 0.18, z: 0.15, i: "b", e: -20, s: -36, o: "709" },
                { f: "c", y: 0.18, z: 1.12, i: "e", e: 1, s: 1, o: "709" },
                { f: "c", y: 0.19, z: 0.11, i: "e", e: 0, s: 1, o: "705" },
                { f: "c", y: 0.19, z: 0.11, i: "e", e: 0, s: 1, o: "703" },
                { f: "c", y: 0.19, z: 0.1, i: "b", e: -33, s: -49, o: "704" },
                { f: "c", y: 0.22, z: 0.11, i: "e", e: 0, s: 1, o: "708" },
                { f: "c", y: 0.22, z: 0.11, i: "e", e: 0, s: 1, o: "710" },
                { f: "c", y: 0.22, z: 0.11, i: "e", e: 0, s: 1, o: "711" },
                { f: "c", y: 0.23, z: 0.07, i: "e", e: 0, s: 1, o: "706" },
                { y: 0.28, i: "f", s: 34, z: 0, o: "711", f: "c" },
                { y: 0.28, i: "a", s: 99, z: 0, o: "711", f: "c" },
                { y: 0.28, i: "b", s: 33, z: 0, o: "711", f: "c" },
                { y: 0.29, i: "f", s: -27, z: 0, o: "706", f: "c" },
                { y: 0.29, i: "a", s: -89, z: 0, o: "706", f: "c" },
                { y: 0.29, i: "b", s: 42, z: 0, o: "706", f: "c" },
                { f: "c", y: 0.29, z: 3.01, i: "b", e: -33, s: -33, o: "704" },
                { y: 1, i: "e", s: 0, z: 0, o: "706", f: "c" },
                { y: 1, i: "e", s: 0, z: 0, o: "705", f: "c" },
                { y: 1, i: "e", s: 0, z: 0, o: "703", f: "c" },
                { y: 1.03, i: "e", s: 0, z: 0, o: "708", f: "c" },
                { y: 1.03, i: "e", s: 0, z: 0, o: "710", f: "c" },
                { y: 1.03, i: "e", s: 0, z: 0, o: "711", f: "c" },
                { f: "e", y: 1.03, z: 0.27, i: "b", e: -20, s: -20, o: "709" },
                { f: "c", y: 2, z: 1, i: "e", e: 1, s: 0, o: "694" },
                { f: "e", y: 2, z: 1, i: "b", e: 63, s: -48, o: "694" },
                { f: "c", y: 2, z: 1, i: "e", e: 0, s: 1, o: "709" },
                { f: "e", y: 2, z: 1, i: "b", e: -9, s: -20, o: "709" },
                { f: "c", y: 3, z: 3, i: "b", e: 63, s: 63, o: "694" },
                { f: "c", y: 3, z: 3, i: "e", e: 1, s: 1, o: "694" },
                { f: "c", y: 3, z: 7, i: "e", e: 0, s: 0, o: "709" },
                { f: "c", y: 3, z: 6.25, i: "b", e: -9, s: -9, o: "709" },
                { f: "c", y: 4, z: 1, i: "e", e: 1, s: 0, o: "696" },
                { f: "c", y: 4, z: 1, i: "b", e: 88, s: -23, o: "696" },
                { f: "c", y: 4, z: 1, i: "e", e: 0, s: 1, o: "704" },
                { f: "c", y: 4, z: 1, i: "b", e: -17, s: -33, o: "704" },
                { f: "c", y: 5, z: 3, i: "e", e: 1, s: 1, o: "696" },
                { f: "c", y: 5, z: 3, i: "b", e: 88, s: 88, o: "696" },
                { f: "c", y: 5, z: 3, i: "e", e: 0, s: 0, o: "704" },
                { f: "c", y: 5, z: 2.25, i: "b", e: -17, s: -17, o: "704" },
                { f: "c", y: 6, z: 1, i: "e", e: 1, s: 0, o: "695" },
                { f: "e", y: 6, z: 1, i: "b", e: 74, s: -36, o: "695" },
                { f: "c", y: 6, z: 1, i: "e", e: 0, s: 1, o: "694" },
                { f: "c", y: 6, z: 1, i: "b", e: 82, s: 63, o: "694" },
                { f: "c", y: 7, z: 3, i: "e", e: 1, s: 1, o: "695" },
                { f: "c", y: 7, z: 3, i: "b", e: 74, s: 74, o: "695" },
                { y: 7, i: "b", s: 82, z: 0, o: "694", f: "c" },
                { y: 7, i: "e", s: 0, z: 0, o: "694", f: "c" },
                { f: "c", y: 7.25, z: 0.05, i: "b", e: -79, s: -17, o: "704" },
                { f: "c", y: 8, z: 1, i: "e", e: 0, s: 1, o: "696" },
                { f: "c", y: 8, z: 1, i: "b", e: 91, s: 88, o: "696" },
                { f: "e", y: 8, z: 1, i: "e", e: 1, s: 0, o: "704" },
                { f: "c", y: 8, z: 1, i: "b", e: -33, s: -79, o: "704" },
                { y: 9, i: "b", s: 91, z: 0, o: "696", f: "c" },
                { y: 9, i: "e", s: 0, z: 0, o: "696", f: "c" },
                { y: 9, i: "e", s: 1, z: 0, o: "704", f: "c" },
                { y: 9, i: "b", s: -33, z: 0, o: "704", f: "c" },
                { f: "c", y: 9.25, z: 0.05, i: "b", e: -61, s: -9, o: "709" },
                { f: "c", y: 10, z: 1, i: "e", e: 0, s: 1, o: "695" },
                { f: "c", y: 10, z: 1, i: "b", e: 86, s: 74, o: "695" },
                { f: "c", y: 10, z: 1, i: "e", e: 1, s: 0, o: "709" },
                { f: "c", y: 10, z: 1, i: "b", e: -20, s: -61, o: "709" },
                { y: 11, i: "b", s: 86, z: 0, o: "695", f: "c" },
                { y: 11, i: "e", s: 0, z: 0, o: "695", f: "c" },
                { y: 11, i: "e", s: 1, z: 0, o: "709", f: "c" },
                { y: 11, i: "b", s: -20, z: 0, o: "709", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 12,
                  z: 10,
                  i: "ActionHandler",
                  e: { a: [{ b: "535", p: 3, z: false, symbolOid: "242" }] },
                  s: { a: [{ i: 2, b: "535", p: 9, symbolOid: "242" }] },
                  o: "535",
                },
                {
                  f: "c",
                  p: 2,
                  y: 22,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "535", p: 3, z: false, symbolOid: "242" }] },
                  o: "535",
                },
              ],
              f: 30,
              b: [],
            },
            574: {
              q: false,
              z: 1.15,
              i: "574",
              n: "pulse",
              a: [
                { f: "c", y: 0, z: 0.15, i: "cQ", e: 0.8, s: 1, o: "675" },
                { f: "c", y: 0, z: 0.15, i: "cR", e: 0.8, s: 1, o: "675" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "675" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 0.8, o: "675" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "675", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "675", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 1.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "574", p: 3, z: false, symbolOid: "242" }] },
                  o: "574",
                },
              ],
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 2.15,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "e", y: 0, z: 1, i: "cQ", e: 1, s: 1.05, o: "679" },
                { f: "e", y: 0, z: 1, i: "cR", e: 1, s: 1.05, o: "679" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "682" },
                { f: "c", y: 0, z: 1, i: "b", e: 57, s: 36, o: "682" },
                { f: "f", y: 0, z: 1, i: "b", e: 121, s: 13, o: "702" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "702" },
                { f: "f", y: 0.11, z: 1, i: "b", e: 116, s: 8, o: "707" },
                { f: "c", y: 0.11, z: 1, i: "e", e: 1, s: 0, o: "707" },
                { f: "c", y: 0.11, z: 1, i: "e", e: 0, s: -1, o: "695" },
                { f: "f", y: 0.11, z: 1, i: "b", e: -36, s: -69, o: "695" },
                { f: "c", y: 0.16, z: 0.3, i: "e", e: 1, s: 0, o: "713" },
                { f: "f", y: 0.16, z: 0.3, i: "b", e: 1, s: -32, o: "713" },
                { f: "c", y: 0.24, z: 0.26, i: "e", e: 1, s: 0, o: "691" },
                { f: "c", y: 1, z: 1, i: "cQ", e: 1, s: 0.8, o: "675" },
                { f: "c", y: 1, z: 1, i: "cR", e: 1, s: 0.8, o: "675" },
                { y: 1, i: "b", s: 121, z: 0, o: "702", f: "c" },
                { y: 1, i: "e", s: 1, z: 0, o: "702", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "679", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "679", f: "c" },
                { y: 1, i: "b", s: 57, z: 0, o: "682", f: "c" },
                { f: "c", y: 1, z: 1, i: "e", e: 1, s: 0, o: "675" },
                { f: "d", y: 1, z: 0.16, i: "b", e: -26, s: -34, o: "677" },
                { f: "c", y: 1, z: 0.26, i: "e", e: 1, s: 0, o: "674" },
                { y: 1, i: "e", s: 1, z: 0, o: "682", f: "c" },
                { f: "d", y: 1, z: 0.16, i: "e", e: 1, s: 0, o: "677" },
                { f: "d", y: 1.07, z: 0.16, i: "b", e: -25, s: -39, o: "676" },
                { f: "d", y: 1.07, z: 0.16, i: "e", e: 1, s: 0, o: "676" },
                { y: 1.11, i: "b", s: 116, z: 0, o: "707", f: "c" },
                { y: 1.11, i: "e", s: 1, z: 0, o: "707", f: "c" },
                { f: "c", y: 1.11, z: 1.04, i: "e", e: 0, s: 0, o: "695" },
                { y: 1.11, i: "b", s: -36, z: 0, o: "695", f: "c" },
                { y: 1.16, i: "e", s: 1, z: 0, o: "713", f: "c" },
                { y: 1.16, i: "b", s: 1, z: 0, o: "713", f: "c" },
                { y: 1.16, i: "b", s: -26, z: 0, o: "677", f: "c" },
                { y: 1.16, i: "e", s: 1, z: 0, o: "677", f: "c" },
                { y: 1.2, i: "e", s: 1, z: 0, o: "691", f: "c" },
                { y: 1.23, i: "b", s: -25, z: 0, o: "676", f: "c" },
                { y: 1.23, i: "e", s: 1, z: 0, o: "676", f: "c" },
                { y: 1.26, i: "e", s: 1, z: 0, o: "674", f: "c" },
                { y: 2, i: "cQ", s: 1, z: 0, o: "675", f: "c" },
                { y: 2, i: "cR", s: 1, z: 0, o: "675", f: "c" },
                { y: 2, i: "e", s: 1, z: 0, o: "675", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2.15,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      { b: "535", p: 3, z: false, symbolOid: "242" },
                      { b: "574", p: 3, z: false, symbolOid: "242" },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 2.15, i: "e", s: 0, z: 0, o: "695", f: "c" },
              ],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "701",
            "697",
            "698",
            "700",
            "678",
            "699",
            "692",
            "681",
            "680",
            "679",
            "691",
            "712",
            "686",
            "682",
            "683",
            "693",
            "713",
            "687",
            "690",
            "684",
            "704",
            "688",
            "685",
            "689",
            "695",
            "696",
            "694",
            "709",
            "707",
            "702",
            "708",
            "703",
            "705",
            "710",
            "711",
            "706",
            "677",
            "676",
            "673",
            "674",
            "675",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            712: {
              h: "513",
              p: "no-repeat",
              x: "visible",
              a: -25,
              q: "100% 100%",
              b: -74,
              j: "absolute",
              r: "none",
              bF: "693",
              z: 3,
              dB: "img",
              d: 300,
              k: "div",
              cQ: 1,
              e: 0,
              c: 292,
              cR: 1,
            },
            685: {
              h: "551",
              p: "no-repeat",
              x: "visible",
              a: 80,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "682",
              b: 82,
              d: 13,
              k: "div",
              c: 35,
            },
            707: {
              x: "visible",
              tY: 0.5,
              a: 182,
              b: 8,
              j: "absolute",
              bF: "693",
              z: 0,
              k: "div",
              c: 143,
              d: 114,
              cQ: 1.2,
              e: 0,
              f: 0,
              cR: 1.2,
              tX: 0.5,
            },
            691: {
              h: "173",
              p: "no-repeat",
              x: "visible",
              a: 143,
              q: "100% 100%",
              b: 11,
              j: "absolute",
              r: "none",
              z: 14,
              bF: "681",
              dB: "img",
              d: 100,
              k: "div",
              c: 177,
              e: 0,
            },
            699: {
              c: 320,
              cP: "enclosed",
              bS: 447,
              d: 480,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 11,
              k: "div",
              D: "#D8DDE4",
              a: 0,
              b: 0,
            },
            713: {
              h: "517",
              p: "no-repeat",
              x: "visible",
              a: 117,
              q: "100% 100%",
              b: -32,
              j: "absolute",
              r: "none",
              bF: "693",
              z: 4,
              dB: "img",
              d: 285.5,
              k: "div",
              cQ: 1,
              e: 0,
              c: 286,
              cR: 1,
            },
            686: {
              h: "507",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "682",
              b: 0,
              d: 107,
              k: "div",
              c: 196,
            },
            700: {
              c: 318,
              bS: 63,
              d: 478,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              aP: "auto",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              k: "div",
              O: 1,
              C: "#D8DDE4",
              z: 16,
              P: 1,
              D: "#D8DDE4",
              cN: "none",
              a: 0,
              b: 0,
            },
            673: {
              x: "visible",
              k: "div",
              c: 320,
              d: 97,
              z: 3,
              e: 1,
              a: 0,
              bS: 351,
              j: "absolute",
              b: 383,
            },
            708: {
              h: "576",
              p: "no-repeat",
              x: "visible",
              a: -5,
              q: "100% 100%",
              b: 20,
              j: "absolute",
              bF: "707",
              r: "inline",
              cY: "0",
              z: 1,
              d: 117.5,
              dB: "img",
              cQ: 1,
              e: 1,
              k: "div",
              c: 159,
              cR: 1,
            },
            692: {
              x: "visible",
              bF: "681",
              k: "div",
              c: 320,
              d: 480,
              z: 3,
              a: 0,
              bS: 127,
              j: "absolute",
              b: 0,
            },
            687: {
              aU: 8,
              G: "#FFF",
              c: 51,
              aV: 8,
              r: "inline",
              d: 0,
              s: "Lato",
              X: 0,
              t: 36,
              Y: 0,
              Z: "break-word",
              v: "700",
              i: "days",
              w: "00",
              bF: "682",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 9,
              aS: 8,
              aT: 8,
              a: 6,
              F: "center",
              b: 54,
            },
            701: {
              h: "173",
              p: "no-repeat",
              x: "visible",
              a: 191,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "681",
              b: -6,
              d: 75,
              k: "div",
              c: 132.75,
            },
            674: {
              h: "10",
              p: "no-repeat",
              x: "visible",
              a: 19,
              q: "100% 100%",
              b: 19,
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "673",
              dB: "img",
              d: 60,
              k: "div",
              c: 122,
              e: 0,
            },
            709: {
              p: "no-repeat",
              b: -20,
              c: 130,
              q: "100% 100%",
              d: 157,
              r: "inline",
              cY: "0",
              e: 0,
              cQ: 1,
              cR: 1,
              h: "586",
              bF: "707",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 2,
              tX: 0.5,
              a: 10,
              tY: 0.53,
            },
            693: {
              x: "visible",
              k: "div",
              c: 355,
              d: 303,
              z: 1,
              a: -28,
              j: "absolute",
              bF: "692",
              b: 96,
            },
            680: {
              h: "5",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "679",
              dB: "img",
              d: 480,
              k: "div",
              cQ: 1,
              c: 320,
              cR: 1,
            },
            688: {
              h: "553",
              p: "no-repeat",
              x: "visible",
              a: 34,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "682",
              b: 82,
              d: 10,
              k: "div",
              c: 16,
            },
            702: {
              x: "visible",
              a: 51,
              b: 13,
              j: "absolute",
              bF: "693",
              z: 1,
              k: "div",
              c: 149,
              d: 114,
              cQ: 1.2,
              aY: 0,
              e: 0,
              f: 0,
              cR: 1.2,
            },
            675: {
              h: "523",
              p: "no-repeat",
              x: "visible",
              a: 174,
              q: "100% 100%",
              b: 31,
              j: "absolute",
              r: "inline",
              bF: "673",
              z: 3,
              dB: "img",
              d: 36,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 124,
              cR: 0.8,
            },
            694: {
              h: "515",
              p: "no-repeat",
              tY: 0.5,
              a: 181,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "693",
              b: -48,
              z: 3,
              d: 206.5,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 165,
              cR: 1,
              tX: 0.5,
            },
            681: {
              x: "visible",
              k: "div",
              c: 320,
              d: 75,
              z: 10,
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            689: {
              h: "549",
              p: "no-repeat",
              x: "visible",
              a: 142,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "682",
              b: 83,
              d: 9,
              k: "div",
              c: 28,
            },
            703: {
              h: "576",
              p: "no-repeat",
              x: "visible",
              a: -5,
              q: "100% 100%",
              b: 20,
              j: "absolute",
              bF: "702",
              r: "inline",
              cY: "0",
              z: 1,
              d: 117.5,
              dB: "img",
              cQ: 1,
              e: 1,
              k: "div",
              c: 159,
              cR: 1,
            },
            676: {
              h: "16",
              p: "no-repeat",
              x: "visible",
              a: 75,
              q: "100% 100%",
              b: -39,
              j: "absolute",
              r: "none",
              bF: "673",
              z: 1,
              dB: "img",
              d: 31,
              k: "div",
              cQ: 1,
              e: 0,
              c: 170,
              cR: 1,
            },
            695: {
              h: "519",
              p: "no-repeat",
              x: "visible",
              a: 192,
              q: "100% 100%",
              b: -69,
              j: "absolute",
              r: "inline",
              bF: "693",
              z: 5,
              dB: "img",
              d: 214,
              k: "div",
              cQ: 1,
              e: -1,
              c: 143,
              cR: 1,
            },
            682: {
              x: "visible",
              b: 36,
              k: "div",
              c: 196,
              d: 107,
              z: 4,
              r: "inline",
              e: 0,
              j: "absolute",
              a: 62,
              bF: "681",
            },
            704: {
              p: "no-repeat",
              b: -33,
              c: 142,
              q: "100% 100%",
              d: 166,
              r: "inline",
              cY: "0",
              e: 0,
              cQ: 1,
              cR: 1,
              h: "583",
              bF: "702",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 2,
              tX: 0.5,
              a: -4,
              tY: 0.54,
            },
            677: {
              h: "18",
              p: "no-repeat",
              x: "visible",
              a: 32,
              q: "100% 100%",
              b: -34,
              j: "absolute",
              r: "inline",
              bF: "673",
              z: 2,
              dB: "img",
              d: 30,
              k: "div",
              cQ: 1,
              e: 0,
              c: 255,
              cR: 1,
            },
            696: {
              h: "511",
              p: "no-repeat",
              tY: 0.5,
              a: 36,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "693",
              b: -23,
              z: 2,
              d: 181,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 191,
              cR: 1,
              tX: 0.5,
            },
            710: {
              h: "579",
              p: "no-repeat",
              x: "visible",
              a: 10,
              q: "100% 100%",
              b: 36,
              j: "absolute",
              bF: "707",
              r: "inline",
              cY: "0",
              z: 4,
              d: 83.5,
              dB: "img",
              cQ: 1,
              e: 1,
              k: "div",
              c: 131,
              cR: 1,
            },
            683: {
              h: "505",
              p: "no-repeat",
              x: "visible",
              a: 38,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 8,
              bF: "682",
              b: 11,
              d: 42,
              k: "div",
              c: 120,
            },
            705: {
              h: "579",
              p: "no-repeat",
              x: "visible",
              a: 10,
              q: "100% 100%",
              b: 36,
              j: "absolute",
              bF: "702",
              r: "inline",
              cY: "0",
              z: 3,
              d: 83.5,
              dB: "img",
              cQ: 1,
              e: 1,
              k: "div",
              c: 131,
              cR: 1,
            },
            678: {
              c: 320,
              bS: 63,
              d: 480,
              I: "Solid",
              e: 1,
              J: "Solid",
              K: "Solid",
              L: "Solid",
              aP: "pointer",
              M: 0,
              w: "",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 12,
              dB: "button",
              D: "#D8DDE4",
              aA: { a: [{ p: 4, h: "359" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            697: {
              h: "521",
              p: "no-repeat",
              x: "visible",
              a: -144,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "681",
              b: 0,
              d: 212,
              k: "div",
              c: 467,
            },
            711: {
              p: "no-repeat",
              b: 0,
              c: 132,
              q: "100% 100%",
              d: 64,
              r: "inline",
              cY: "0",
              e: 1,
              cQ: 1,
              f: 0,
              cR: 1,
              h: "582",
              bF: "707",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 5,
              tX: 0.5,
              a: 10,
              tY: 0.5,
            },
            684: {
              aU: 8,
              G: "#FFF",
              c: 53,
              aV: 8,
              r: "inline",
              d: 0,
              s: "Lato",
              X: 0,
              t: 36,
              Y: 0,
              Z: "break-word",
              v: "700",
              i: "minutes",
              w: "00",
              bF: "682",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 11,
              aS: 8,
              aT: 8,
              a: 120,
              F: "center",
              b: 54,
            },
            706: {
              p: "no-repeat",
              b: 0,
              c: 132,
              q: "100% 100%",
              d: 64,
              r: "inline",
              cY: "0",
              e: 1,
              cQ: 1,
              f: 0,
              cR: 1,
              h: "582",
              bF: "702",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 4,
              tX: 0.5,
              a: 9,
              tY: 0.5,
            },
            679: {
              x: "visible",
              cQ: 1.05,
              k: "div",
              cR: 1.05,
              c: 320,
              d: 480,
              z: 2,
              a: 0,
              bS: 447,
              j: "absolute",
              b: 0,
            },
            690: {
              aU: 8,
              G: "#FFF",
              c: 53,
              aV: 8,
              r: "inline",
              d: 0,
              s: "Lato",
              X: 0,
              t: 36,
              Y: 0,
              Z: "break-word",
              v: "700",
              i: "hours",
              w: "00",
              bF: "682",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 10,
              aS: 8,
              aT: 8,
              a: 65,
              F: "center",
              b: 54,
            },
            698: {
              h: "525",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "none",
              z: 28,
              b: 0,
              k: "div",
              d: 480,
              c: 320,
              e: 0.4,
            },
          },
        },
        {
          o: "630",
          A: {
            a: [
              { p: 4, h: "107" },
              { b: "628", p: 3, z: false, symbolOid: "242" },
            ],
          },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: { 716: { V: { "Main Timeline": "746" }, W: "746", n: "Symbol" } },
          T: {
            629: {
              q: false,
              z: 5,
              i: "629",
              n: "carousel",
              a: [
                { y: 0, i: "cY", s: "1", z: 0, o: "722", f: "c" },
                { y: 0, i: "e", s: 1, z: 0, o: "723", f: "c" },
                { f: "c", y: 0, z: 0.23, i: "b", e: -39, s: -9, o: "723" },
                { f: "c", y: 0, z: 0.23, i: "cR", e: 1.2, s: 1, o: "723" },
                { f: "c", y: 0, z: 0.23, i: "cQ", e: 1.2, s: 1, o: "723" },
                { y: 0, i: "cY", s: "0", z: 0, o: "723", f: "c" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 1, s: 1, o: "729" },
                { y: 0, i: "cY", s: "1", z: 0, o: "725", f: "c" },
                { y: 0, i: "cY", s: "1", z: 0, o: "727", f: "c" },
                { y: 0, i: "cY", s: "1", z: 0, o: "730", f: "c" },
                { y: 0, i: "cY", s: "1", z: 0, o: "728", f: "c" },
                { y: 0, i: "cY", s: "1", z: 0, o: "724", f: "c" },
                { y: 0, i: "cY", s: "1", z: 0, o: "715", f: "c" },
                { f: "c", y: 0, z: 0.15, i: "cY", e: "0", s: "0", o: "729" },
                { y: 0.15, i: "e", s: 1, z: 0, o: "729", f: "c" },
                { y: 0.15, i: "cY", s: "0", z: 0, o: "729", f: "c" },
                { f: "c", y: 0.23, z: 0.22, i: "cQ", e: 1, s: 1.2, o: "723" },
                { f: "c", y: 0.23, z: 0.22, i: "cR", e: 1, s: 1.2, o: "723" },
                { f: "c", y: 0.23, z: 0.22, i: "b", e: -9, s: -39, o: "723" },
                { y: 1.15, i: "cQ", s: 1, z: 0, o: "723", f: "c" },
                { y: 1.15, i: "cR", s: 1, z: 0, o: "723", f: "c" },
                { y: 1.15, i: "b", s: -9, z: 0, o: "723", f: "c" },
                { y: 2, i: "a", s: -29, z: 0, o: "729", f: "c" },
                { f: "c", y: 2, z: 0.23, i: "cQ", e: 1.2, s: 1, o: "729" },
                { f: "c", y: 2, z: 0.23, i: "cR", e: 1.2, s: 1, o: "729" },
                { f: "c", y: 2, z: 0.23, i: "b", e: -92, s: -56, o: "729" },
                { f: "c", y: 2.23, z: 0.22, i: "cQ", e: 1, s: 1.2, o: "729" },
                { f: "c", y: 2.23, z: 0.22, i: "cR", e: 1, s: 1.2, o: "729" },
                { f: "c", y: 2.23, z: 0.22, i: "b", e: -56, s: -92, o: "729" },
                { y: 3.15, i: "cQ", s: 1, z: 0, o: "729", f: "c" },
                { y: 3.15, i: "cR", s: 1, z: 0, o: "729", f: "c" },
                { y: 3.15, i: "b", s: -56, z: 0, o: "729", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 5,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "629", p: 3, z: false, symbolOid: "242" }] },
                  o: "629",
                },
              ],
              f: 30,
              b: [],
            },
            746: {
              c: "716",
              q: false,
              z: 1.15,
              i: "746",
              a: [
                { f: "c", y: 0, z: 0.15, i: "cQ", e: 1.05, s: 1, o: "718" },
                { f: "c", y: 0, z: 0.15, i: "cR", e: 1.05, s: 1, o: "718" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 1.05, o: "718" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 1.05, o: "718" },
                { y: 1, i: "cR", s: 1, z: 0, o: "718", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "718", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 1.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "746", p: 3, z: false, symbolOid: "76" }] },
                  o: "746",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            625: {
              j: {
                4: [
                  [76, 33, 76, 33, 71, -18, 102, -23],
                  [102, -23, 147, -30, 165, 65, 165, 65],
                ],
              },
              q: false,
              z: 1.09,
              i: "625",
              n: "gift_right",
              a: [
                { f: "c", y: 0, z: 0.03, i: "cY", e: "1", s: "0", o: "740" },
                { f: "c", y: 0, z: 0.25, i: "f", e: 34, s: 0, o: "722" },
                {
                  o: "722",
                  y: 0,
                  z: 0.25,
                  i: "a",
                  e: 99,
                  a: "4",
                  f: "c",
                  s: 10,
                },
                {
                  o: "722",
                  y: 0,
                  z: 0.25,
                  i: "b",
                  e: 33,
                  a: "4",
                  f: "c",
                  s: 1,
                },
                { y: 0.03, i: "cY", s: "1", z: 0, o: "740", f: "c" },
                { f: "e", y: 0.04, z: 0.15, i: "e", e: 1, s: 0, o: "723" },
                { f: "e", y: 0.04, z: 0.15, i: "b", e: -79, s: -9, o: "723" },
                { f: "c", y: 0.19, z: 0.11, i: "e", e: 0, s: 1, o: "725" },
                { f: "c", y: 0.19, z: 0.11, i: "e", e: 0, s: 1, o: "724" },
                { f: "c", y: 0.19, z: 0.2, i: "b", e: -9, s: -79, o: "723" },
                { f: "c", y: 0.19, z: 0.11, i: "e", e: 0, s: 1, o: "722" },
                { y: 0.19, i: "e", s: 1, z: 0, o: "723", f: "c" },
                { y: 0.25, i: "f", s: 34, z: 0, o: "722", f: "c" },
                { y: 0.25, i: "a", s: 99, z: 0, o: "722", f: "c" },
                { y: 0.25, i: "b", s: 33, z: 0, o: "722", f: "c" },
                { y: 1, i: "e", s: 0, z: 0, o: "725", f: "c" },
                { y: 1, i: "e", s: 0, z: 0, o: "724", f: "c" },
                { y: 1, i: "e", s: 0, z: 0, o: "722", f: "c" },
                { y: 1.09, i: "b", s: -9, z: 0, o: "723", f: "e" },
              ],
              f: 30,
              b: [],
            },
            628: {
              q: false,
              z: 2,
              i: "628",
              n: "counter",
              a: [
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 0.15,
                  i: "ActionHandler",
                  e: { a: [{ p: 7, b: "372", symbolOid: "242" }] },
                  s: { a: [{ p: 7, b: "628", symbolOid: "242" }] },
                  o: "628",
                },
                {
                  f: "c",
                  p: 2,
                  y: 0.15,
                  z: 1.15,
                  i: "ActionHandler",
                  e: { a: [{ d: 1.1, p: 1, g: 2, e: "453" }] },
                  s: { a: [{ p: 7, b: "628", symbolOid: "242" }] },
                  o: "628",
                },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ d: 1.1, p: 1, g: 2, e: "453" }] },
                  o: "628",
                },
              ],
              f: 30,
              b: [],
            },
            624: {
              j: {
                2: [
                  [232, 139, 232, 139, 235, 127, 144, 128],
                  [144, 128, 65, 129, 69, 136, 69, 136],
                ],
                3: [
                  [69, 136, 69, 136, 74, 169, 96, 175],
                  [96, 175, 103, 177, 147, 145, 160, 145],
                  [160, 145, 169, 146, 192, 165, 205, 173],
                  [205, 173, 215, 179, 231, 140, 231, 140],
                ],
              },
              q: false,
              z: 4,
              i: "624",
              n: "pointer",
              a: [
                { f: "c", y: 0, z: 0.07, i: "e", e: 0, s: 1, o: "719" },
                { f: "c", y: 0, z: 0.06, i: "b", e: 167, s: 178, o: "721" },
                { f: "c", y: 0, z: 0.03, i: "f", e: -4, s: 0, o: "721" },
                { f: "c", y: 0.02, z: 0.06, i: "b", e: 167, s: 178, o: "726" },
                { f: "c", y: 0.02, z: 0.03, i: "f", e: -4, s: 0, o: "726" },
                { f: "c", y: 0.03, z: 0.03, i: "f", e: 4, s: -4, o: "721" },
                { f: "c", y: 0.05, z: 0.03, i: "f", e: 4, s: -4, o: "726" },
                { f: "c", y: 0.06, z: 0.05, i: "b", e: 178, s: 167, o: "721" },
                { f: "c", y: 0.06, z: 0.02, i: "f", e: -4, s: 4, o: "721" },
                {
                  o: "715",
                  y: 0.07,
                  z: 0.16,
                  i: "a",
                  e: -15,
                  a: "2",
                  f: "e",
                  s: 148,
                },
                { f: "c", y: 0.07, z: 1.16, i: "e", e: 0, s: 0, o: "719" },
                {
                  o: "715",
                  y: 0.07,
                  z: 0.16,
                  i: "b",
                  e: 89.5,
                  a: "2",
                  f: "e",
                  s: 92.5,
                },
                { f: "c", y: 0.08, z: 0.05, i: "b", e: 178, s: 167, o: "726" },
                { f: "c", y: 0.08, z: 0.01, i: "f", e: -4, s: 4, o: "726" },
                { f: "c", y: 0.08, z: 0.01, i: "f", e: 4, s: -4, o: "721" },
                { f: "c", y: 0.09, z: 0.02, i: "f", e: 4, s: -4, o: "726" },
                { f: "c", y: 0.09, z: 0.02, i: "f", e: 0, s: 4, o: "721" },
                { y: 0.11, i: "b", s: 178, z: 0, o: "721", f: "c" },
                { f: "c", y: 0.11, z: 0.02, i: "f", e: 0, s: 4, o: "726" },
                { y: 0.11, i: "f", s: 0, z: 0, o: "721", f: "c" },
                { y: 0.13, i: "b", s: 178, z: 0, o: "726", f: "c" },
                { y: 0.13, i: "f", s: 0, z: 0, o: "726", f: "c" },
                {
                  o: "715",
                  y: 0.23,
                  z: 1.04,
                  i: "a",
                  e: 147,
                  a: "3",
                  f: "c",
                  s: -15,
                },
                {
                  o: "715",
                  y: 0.23,
                  z: 1.04,
                  i: "b",
                  e: 93.5,
                  a: "3",
                  f: "c",
                  s: 89.5,
                },
                { f: "c", y: 1.23, z: 0.07, i: "e", e: 1, s: 0, o: "719" },
                { y: 1.27, i: "a", s: 147, z: 0, o: "715", f: "e" },
                { y: 1.27, i: "b", s: 93.5, z: 0, o: "715", f: "e" },
                { y: 2, i: "e", s: 1, z: 0, o: "719", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "624", p: 3, z: false, symbolOid: "2" }] },
                  o: "624",
                },
              ],
              f: 30,
              b: [
                {
                  D: 1.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "746",
                },
              ],
            },
            627: {
              q: false,
              z: 1.15,
              i: "627",
              n: "pointer_end",
              a: [
                { f: "c", y: 0, z: 0.15, i: "e", e: 0, s: 1, o: "716" },
                { y: 0, i: "e", s: 0, z: 0, o: "715", f: "c" },
                { y: 0.15, i: "e", s: 0, z: 0, o: "716", f: "c" },
              ],
              f: 30,
              b: [
                {
                  D: 1.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "746",
                },
              ],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 6.15,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "e", y: 0, z: 1, i: "cQ", e: 1, s: 1.05, o: "737" },
                { f: "e", y: 0, z: 1, i: "cR", e: 1, s: 1.05, o: "737" },
                { f: "c", y: 0.07, z: 1, i: "e", e: 1, s: 0, o: "721" },
                { f: "f", y: 0.07, z: 1, i: "b", e: 178, s: 70, o: "721" },
                { f: "f", y: 0.18, z: 1, i: "b", e: 178, s: 70, o: "726" },
                { f: "c", y: 0.18, z: 1, i: "e", e: 1, s: 0, o: "726" },
                { f: "c", y: 0.24, z: 0.26, i: "e", e: 1, s: 0, o: "744" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "737", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "737", f: "c" },
                { f: "d", y: 1, z: 0.16, i: "b", e: -40, s: -57, o: "734" },
                { f: "d", y: 1, z: 0.16, i: "e", e: 1, s: 0, o: "734" },
                { y: 1.07, i: "b", s: 178, z: 0, o: "721", f: "c" },
                { y: 1.07, i: "e", s: 1, z: 0, o: "721", f: "c" },
                { f: "d", y: 1.07, z: 0.16, i: "b", e: -18, s: -32, o: "736" },
                { f: "d", y: 1.07, z: 0.16, i: "e", e: 1, s: 0, o: "736" },
                { f: "c", y: 1.1, z: 0.26, i: "cR", e: 1, s: 1.1, o: "715" },
                { f: "c", y: 1.1, z: 0.26, i: "cQ", e: 1, s: 1.1, o: "715" },
                { f: "c", y: 1.1, z: 0.26, i: "e", e: 1, s: 0, o: "715" },
                { f: "c", y: 1.1, z: 0.26, i: "e", e: 1, s: 0, o: "735" },
                { y: 1.16, i: "b", s: -40, z: 0, o: "734", f: "c" },
                { y: 1.16, i: "e", s: 1, z: 0, o: "734", f: "c" },
                { y: 1.18, i: "b", s: 178, z: 0, o: "726", f: "c" },
                { y: 1.18, i: "e", s: 1, z: 0, o: "726", f: "c" },
                { y: 1.2, i: "e", s: 1, z: 0, o: "744", f: "c" },
                { y: 1.23, i: "b", s: -18, z: 0, o: "736", f: "c" },
                { y: 1.23, i: "e", s: 1, z: 0, o: "736", f: "c" },
                { y: 2.06, i: "cR", s: 1, z: 0, o: "715", f: "c" },
                { y: 2.06, i: "cQ", s: 1, z: 0, o: "715", f: "c" },
                { f: "c", y: 2.06, z: 2.1, i: "e", e: 1, s: 1, o: "715" },
                { y: 2.06, i: "e", s: 1, z: 0, o: "735", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2.15,
                  z: 2.15,
                  i: "ActionHandler",
                  e: {
                    a: [
                      { b: "286", p: 3, z: false, symbolOid: "2" },
                      { b: "289", p: 3, z: false, symbolOid: "2" },
                      { p: 7, b: "285", symbolOid: "2" },
                    ],
                  },
                  s: { a: [{ b: "624", p: 3, z: false, symbolOid: "242" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 4.16, z: 0.15, i: "e", e: 0, s: 1, o: "716" },
                { f: "c", y: 4.16, z: 0.15, i: "e", e: 0, s: 1, o: "715" },
                {
                  f: "c",
                  p: 2,
                  y: 5,
                  z: 1.15,
                  i: "ActionHandler",
                  e: { a: [{ b: "413", p: 3, z: false, symbolOid: "242" }] },
                  s: {
                    a: [
                      { b: "625", p: 3, z: false, symbolOid: "2" },
                      { b: "626", p: 3, z: false, symbolOid: "2" },
                      { p: 7, b: "624", symbolOid: "2" },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 5.01, i: "e", s: 0, z: 0, o: "716", f: "c" },
                { y: 5.01, i: "e", s: 0, z: 0, o: "715", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 6.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "629", p: 3, z: false, symbolOid: "242" }] },
                  o: "kTimelineDefaultIdentifier",
                },
              ],
              f: 30,
              b: [
                {
                  D: 1.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "746",
                },
              ],
            },
            626: {
              j: {
                5: [
                  [75, 33, 75, 33, 80, -3, 38, -4],
                  [38, -4, 3, -5, -23, 74, -23, 74],
                ],
              },
              q: false,
              z: 1.1,
              i: "626",
              n: "gift_left",
              a: [
                { f: "c", y: 0, z: 0.02, i: "cY", e: "1", s: "0", o: "741" },
                { f: "c", y: 0, z: 0.17, i: "b", e: -94, s: -56, o: "729" },
                { f: "c", y: 0, z: 0.17, i: "e", e: 1, s: 0, o: "729" },
                {
                  o: "727",
                  y: 0,
                  z: 1.09,
                  i: "a",
                  e: -89,
                  a: "5",
                  f: "c",
                  s: 9,
                },
                { f: "c", y: 0, z: 1.09, i: "f", e: -27, s: 0, o: "727" },
                {
                  o: "727",
                  y: 0,
                  z: 1.09,
                  i: "b",
                  e: 42,
                  a: "5",
                  f: "c",
                  s: 1,
                },
                { y: 0.02, i: "cY", s: "1", z: 0, o: "741", f: "c" },
                { y: 0.17, i: "e", s: 1, z: 0, o: "729", f: "c" },
                { f: "c", y: 0.17, z: 0.22, i: "b", e: -56, s: -94, o: "729" },
                { f: "c", y: 1, z: 0.1, i: "e", e: 0, s: 1, o: "728" },
                { f: "c", y: 1, z: 0.1, i: "e", e: 0, s: 1, o: "730" },
                { f: "c", y: 1, z: 0.1, i: "e", e: 0, s: 1, o: "727" },
                { y: 1.09, i: "a", s: -89, z: 0, o: "727", f: "c" },
                { y: 1.09, i: "f", s: -27, z: 0, o: "727", f: "c" },
                { y: 1.09, i: "b", s: 42, z: 0, o: "727", f: "c" },
                { y: 1.09, i: "b", s: -56, z: 0, o: "729", f: "c" },
                { y: 1.1, i: "e", s: 0, z: 0, o: "728", f: "c" },
                { y: 1.1, i: "e", s: 0, z: 0, o: "730", f: "c" },
                { y: 1.1, i: "e", s: 0, z: 0, o: "727", f: "c" },
              ],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "738",
            "737",
            "731",
            "745",
            "739",
            "732",
            "742",
            "743",
            "714",
            "744",
            "720",
            "718",
            "717",
            "716",
            "715",
            "729",
            "719",
            "741",
            "723",
            "740",
            "726",
            "721",
            "722",
            "727",
            "728",
            "725",
            "730",
            "724",
            "734",
            "736",
            "733",
            "735",
          ],
          n: "Untitled Layout",
          _: 1,
          v: {
            739: {
              x: "visible",
              k: "div",
              c: 320,
              aP: "auto",
              cN: "none",
              d: 480,
              z: 15,
              a: 0,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            730: {
              h: "579",
              p: "no-repeat",
              x: "visible",
              a: 10,
              q: "100% 100%",
              b: 36,
              j: "absolute",
              bF: "726",
              r: "inline",
              cY: "0",
              z: 3,
              d: 83.5,
              dB: "img",
              cQ: 1,
              e: 1,
              k: "div",
              c: 131,
              cR: 1,
            },
            722: {
              p: "no-repeat",
              b: 0,
              c: 132,
              q: "100% 100%",
              d: 64,
              r: "inline",
              cY: "0",
              e: 1,
              cQ: 1,
              f: 0,
              cR: 1,
              h: "582",
              bF: "721",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 5,
              tX: 0.5,
              a: 10,
              tY: 0.5,
            },
            714: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 10,
              a: 0,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            743: {
              x: "visible",
              k: "div",
              c: 320,
              d: 75,
              z: 11,
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            735: {
              h: "581",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: 29,
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "733",
              dB: "img",
              d: 60,
              k: "div",
              c: 122,
              e: 0,
            },
            727: {
              p: "no-repeat",
              b: 0,
              c: 132,
              q: "100% 100%",
              d: 64,
              r: "inline",
              cY: "0",
              e: 1,
              cQ: 1,
              f: 0,
              cR: 1,
              h: "582",
              bF: "726",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 4,
              tX: 0.5,
              a: 9,
              tY: 0.5,
            },
            719: {
              x: "hidden",
              k: "div",
              c: 168,
              d: 40,
              z: 3,
              e: 1,
              a: 0,
              j: "absolute",
              bF: "715",
              b: 53,
            },
            731: {
              h: "585",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "none",
              z: 18,
              b: 0,
              k: "div",
              d: 480,
              c: 320,
              e: 0.4269761,
            },
            723: {
              p: "no-repeat",
              b: -9,
              c: 142,
              q: "100% 100%",
              d: 146,
              r: "inline",
              cY: "0",
              e: 0,
              cQ: 1,
              cR: 1,
              h: "586",
              bF: "721",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 3,
              tX: 0.5,
              a: -6,
              tY: 0.53,
            },
            715: {
              x: "visible",
              tY: 0.5,
              a: 148,
              b: 92,
              j: "absolute",
              bF: "714",
              z: 5,
              cY: "0",
              k: "div",
              d: 93,
              c: 168,
              cQ: 1.1,
              e: 0,
              cR: 1.1,
              tX: 0.5,
            },
            744: {
              h: "578",
              p: "no-repeat",
              x: "visible",
              a: 143,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 9,
              bF: "743",
              dB: "img",
              d: 100,
              k: "div",
              c: 177,
              e: 0,
            },
            736: {
              h: "584",
              p: "no-repeat",
              x: "visible",
              a: 66,
              q: "100% 100%",
              b: -32,
              j: "absolute",
              r: "inline",
              bF: "733",
              z: 1,
              dB: "img",
              d: 16,
              k: "div",
              cQ: 1,
              e: 0,
              c: 188,
              cR: 1,
            },
            728: {
              h: "576",
              p: "no-repeat",
              x: "visible",
              a: -5,
              q: "100% 100%",
              b: 20,
              j: "absolute",
              bF: "726",
              r: "inline",
              cY: "0",
              z: 1,
              d: 117.5,
              dB: "img",
              cQ: 1,
              e: 1,
              k: "div",
              c: 159,
              cR: 1,
            },
            740: {
              c: 134,
              bS: 36,
              d: 112,
              r: "inline",
              cY: "0",
              I: "None",
              J: "None",
              K: "None",
              L: "None",
              aP: "pointer",
              M: 0,
              i: "gift_2",
              bF: "739",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 3,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { b: "625", p: 3, z: false, symbolOid: "2" },
                  { p: 4, h: "100" },
                  { p: 7, b: "624", symbolOid: "2" },
                  { b: "627", p: 3, z: false, symbolOid: "2" },
                  { p: 7, b: "kTimelineDefaultIdentifier", symbolOid: "2" },
                  { b: "628", p: 8, z: false, symbolOid: "242", J: false },
                ],
              },
              k: "div",
              a: 160,
              b: 168,
            },
            732: {
              c: 320,
              bS: 63,
              d: 480,
              I: "Solid",
              e: 1,
              J: "Solid",
              K: "Solid",
              L: "Solid",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 13,
              dB: "button",
              D: "#D8DDE4",
              aA: { a: [{ p: 4, h: "359" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            724: {
              h: "579",
              p: "no-repeat",
              x: "visible",
              a: 10,
              q: "100% 100%",
              b: 36,
              j: "absolute",
              bF: "721",
              r: "inline",
              cY: "0",
              z: 4,
              d: 83.5,
              dB: "img",
              cQ: 1,
              e: 1,
              k: "div",
              c: 131,
              cR: 1,
            },
            716: {
              x: "visible",
              a: 0,
              cA: false,
              b: 0,
              j: "absolute",
              bF: "715",
              c: 168,
              k: "div",
              bY: 1,
              d: 53,
              z: 1,
              bX: false,
              e: 1,
              bZ: 180,
              cV: [],
            },
            745: {
              c: 318,
              bS: 63,
              d: 478,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              aP: "auto",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              k: "div",
              O: 1,
              C: "#D8DDE4",
              z: 17,
              P: 1,
              D: "#D8DDE4",
              cN: "none",
              a: 0,
              b: 0,
            },
            737: {
              x: "visible",
              cQ: 1.05,
              k: "div",
              cR: 1.05,
              c: 393,
              d: 549,
              z: 2,
              a: -37,
              bS: 447,
              j: "absolute",
              b: -36,
            },
            729: {
              p: "no-repeat",
              b: -56,
              c: 200,
              q: "100% 100%",
              d: 233.5,
              r: "inline",
              cY: "0",
              e: 0,
              cQ: 1,
              cR: 1,
              h: "583",
              bF: "726",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 2,
              tX: 0.5,
              a: -29,
              tY: 0.54,
            },
            720: {
              h: "580",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: -53,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "719",
              dB: "img",
              d: 79,
              k: "div",
              cQ: 1,
              c: 179,
              cR: 1,
            },
            741: {
              c: 118,
              bS: 36,
              d: 101,
              r: "inline",
              cY: "0",
              I: "None",
              J: "None",
              K: "None",
              L: "None",
              aP: "pointer",
              M: 0,
              i: "gift_3",
              bF: "739",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 2,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "103" },
                  { b: "626", p: 3, z: false, symbolOid: "2" },
                  { p: 7, b: "624", symbolOid: "2" },
                  { b: "627", p: 3, z: false, symbolOid: "2" },
                  { p: 7, b: "kTimelineDefaultIdentifier", symbolOid: "2" },
                  { b: "628", p: 8, z: false, symbolOid: "242", J: false },
                ],
              },
              k: "div",
              a: 26,
              b: 168,
            },
            733: {
              x: "visible",
              k: "div",
              c: 320,
              d: 97,
              z: 3,
              e: 1,
              a: 0,
              bS: 351,
              j: "absolute",
              b: 383,
            },
            725: {
              h: "576",
              p: "no-repeat",
              x: "visible",
              a: -5,
              q: "100% 100%",
              b: 20,
              j: "absolute",
              bF: "721",
              r: "inline",
              cY: "0",
              z: 1,
              d: 117.5,
              dB: "img",
              cQ: 1,
              e: 1,
              k: "div",
              c: 159,
              cR: 1,
            },
            717: {
              x: "hidden",
              k: "div",
              c: 168,
              d: 53,
              z: 2,
              r: "inline",
              a: 0,
              j: "absolute",
              bF: "716",
              b: 0,
            },
            738: {
              h: "577",
              p: "no-repeat",
              x: "visible",
              a: -2,
              q: "100% 100%",
              b: -2,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "737",
              dB: "img",
              d: 614.5,
              k: "div",
              cQ: 1,
              c: 397,
              cR: 1,
            },
            721: {
              x: "visible",
              k: "div",
              c: 132,
              f: 0,
              d: 114,
              z: 2,
              e: 0,
              a: 160,
              j: "absolute",
              bF: "714",
              b: 70,
            },
            742: {
              c: 320,
              cP: "enclosed",
              bS: 447,
              d: 480,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 12,
              k: "div",
              D: "#D8DDE4",
              a: 0,
              b: 0,
            },
            734: {
              h: "587",
              p: "no-repeat",
              x: "visible",
              a: 17,
              q: "100% 100%",
              b: -57,
              j: "absolute",
              r: "inline",
              bF: "733",
              z: 2,
              dB: "img",
              d: 21,
              k: "div",
              cQ: 1,
              e: 0,
              c: 286,
              cR: 1,
            },
            726: {
              x: "visible",
              a: 16,
              b: 70,
              j: "absolute",
              bF: "714",
              c: 132,
              k: "div",
              z: 1,
              d: 114,
              aY: 0,
              e: 0,
              f: 0,
            },
            718: {
              h: "580",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              dP: 0,
              j: "absolute",
              r: "inline",
              bF: "717",
              dO: 0,
              b: 0,
              d: 79,
              z: 1,
              dB: "img",
              dD: 0,
              cQ: 1,
              k: "div",
              c: 179,
              cR: 1,
            },
          },
        },
      ],
      {},
      h,
      {
        f: {
          p: 0,
          q: [
            [0, 0, 0.1971, 0, 0.3391, 0.8944, 0.3636, 1],
            [0.3636, 1, 0.3636, 1, 0.4425, 0.75, 0.5455, 0.75],
            [0.5455, 0.75, 0.6519, 0.75, 0.7273, 1, 0.7273, 1],
            [0.7273, 1, 0.7273, 1, 0.7718, 0.9375, 0.8182, 0.9375],
            [0.8182, 0.9375, 0.8646, 0.9375, 0.9091, 1, 0.9091, 1],
            [0.9091, 1, 0.9091, 1, 0.9294, 0.9844, 0.9546, 0.9844],
            [0.9546, 0.9844, 0.9798, 0.9844, 1, 1, 1, 1],
          ],
        },
      },
      null,
      false,
      true,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
