//	HYPE.documents["Biedronka_320x480_rich_geo_adaptive"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/Biedronka",
      f = "Biedronka_320x480_rich_geo_adaptive",
      g = "biedronka320x480richgeoadaptive_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "../resources/Biedronka/script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotosite();\n}",
        identifier: "9",
      },
      {
        name: "gotomap",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotomap();\n\n}",
        identifier: "747",
      },
      {
        name: "action1",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action1(); \n}",
        identifier: "749",
      },
      {
        name: "action2",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action2(); \n\t\n}",
        identifier: "750",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        10: { p: 1, n: "bug.png", g: "990", t: "@1x" },
        2: { p: 1, n: "dis-1.svg", g: "986", t: "image/svg+xml" },
        "-2": { n: "blank.gif" },
        3: { p: 1, n: "sky.jpg", g: "993", t: "@1x" },
        4: { p: 1, n: "icon-1.svg", g: "62", t: "image/svg+xml" },
        5: { p: 1, n: "cta_t.svg", g: "1003", t: "image/svg+xml" },
        6: { p: 1, n: "wave_top.svg", g: "976", t: "image/svg+xml" },
        7: { p: 1, n: "text_yellow.png", g: "978", t: "@1x" },
        "-1": { n: "PIE.htc" },
        0: { p: 1, n: "logo.svg", g: "980", t: "image/svg+xml" },
        8: { p: 1, n: "bug_bg.png", g: "988", t: "@1x" },
        1: { p: 1, n: "headline.svg", g: "984", t: "image/svg+xml" },
        9: { p: 1, n: "bug_bg_island.png", g: "1044", t: "@1x" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "Untitled Scene", o: "548", X: [0] }],
      [
        {
          o: "550",
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {
            1148: { V: { "Main Timeline": "1169" }, W: "1169", n: "sky" },
            1134: { V: { "Main Timeline": "1167" }, W: "1167", n: "icon" },
            1161: { V: { "Main Timeline": "1172" }, W: "1172", n: "wave" },
            1154: {
              V: { angle: "1171", "Main Timeline": "1170" },
              W: "1170",
              n: "bug",
            },
            1145: { V: { "Main Timeline": "1168" }, W: "1168", n: "wave" },
          },
          T: {
            1172: {
              c: "1161",
              q: false,
              z: 3,
              i: "1172",
              a: [
                { f: "b", y: 0, z: 3, i: "a", e: -448, s: 2, o: "1162" },
                {
                  f: "c",
                  p: 2,
                  y: 2.14,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ i: 0, b: "1172", p: 9, symbolOid: "1020" }] },
                  o: "1172",
                },
                { y: 3, i: "a", s: -448, z: 0, o: "1162", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            1170: {
              c: "1154",
              q: false,
              z: 1.15,
              i: "1170",
              a: [
                { f: "p", y: 0.01, z: 0.22, i: "b", e: 4, s: 2, o: "1155" },
                {
                  f: "c",
                  p: 2,
                  y: 0.01,
                  z: 1.14,
                  i: "ActionHandler",
                  e: {
                    a: [
                      {
                        i: 0,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "1102",
                      },
                    ],
                  },
                  s: { a: [{ b: "1171", p: 3, z: false, symbolOid: "1102" }] },
                  o: "1170",
                },
                { f: "p", y: 0.01, z: 1.14, i: "a", e: -2, s: -2, o: "1155" },
                { f: "c", y: 0.23, z: 0.22, i: "b", e: 2, s: 4, o: "1155" },
                {
                  f: "c",
                  p: 2,
                  y: 1.15,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [{ i: 0.033333335, b: "1170", p: 9, symbolOid: "1102" }],
                  },
                  o: "1170",
                },
                { y: 1.15, i: "a", s: -2, z: 0, o: "1155", f: "c" },
                { y: 1.15, i: "b", s: 2, z: 0, o: "1155", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            1167: {
              c: "1134",
              q: false,
              z: 3.15,
              i: "1167",
              a: [
                { f: "y", y: 0, z: 1.15, i: "aY", e: 360, s: 0, o: "1135" },
                { y: 1.15, i: "aY", s: 360, z: 0, o: "1135", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1167", p: 3, z: false, symbolOid: "609" }] },
                  o: "1167",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            1047: {
              q: false,
              z: 4,
              i: "1047",
              n: "bug",
              a: [
                { f: "b", y: 0, z: 2, i: "b", e: 65, s: 71, o: "1153" },
                { f: "c", y: 0, z: 1.1, i: "d", e: 400, s: 400, o: "1156" },
                { f: "c", y: 0, z: 2.2, i: "c", e: 627, s: 580, o: "1156" },
                { f: "b", y: 0, z: 2, i: "a", e: 215, s: 196, o: "1153" },
                { f: "c", y: 0, z: 2.2, i: "a", e: 46, s: 34, o: "1154" },
                { f: "c", y: 1.1, z: 1.1, i: "d", e: 376, s: 400, o: "1156" },
                { f: "c", y: 2, z: 2, i: "a", e: 196, s: 215, o: "1153" },
                { f: "c", y: 2, z: 2, i: "b", e: 71, s: 65, o: "1153" },
                { f: "c", y: 2.2, z: 1.1, i: "a", e: 34, s: 46, o: "1154" },
                { f: "c", y: 2.2, z: 1.1, i: "c", e: 580, s: 627, o: "1156" },
                { f: "c", y: 2.2, z: 1.1, i: "d", e: 400, s: 376, o: "1156" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1047", p: 3, z: false, symbolOid: "549" }] },
                  o: "1047",
                },
                { y: 4, i: "a", s: 196, z: 0, o: "1153", f: "c" },
                { y: 4, i: "c", s: 580, z: 0, o: "1156", f: "c" },
                { y: 4, i: "b", s: 71, z: 0, o: "1153", f: "c" },
                { y: 4, i: "a", s: 34, z: 0, o: "1154", f: "c" },
                { y: 4, i: "d", s: 400, z: 0, o: "1156", f: "c" },
              ],
              f: 30,
              b: [],
            },
            1171: {
              c: "1154",
              q: false,
              z: 1.15,
              i: "1171",
              a: [
                { f: "c", y: 0, z: 0.23, i: "f", e: -5, s: 0, o: "1155" },
                { f: "c", y: 0.23, z: 0.22, i: "f", e: 0, s: -5, o: "1155" },
                {
                  f: "c",
                  p: 2,
                  y: 1.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1171", p: 3, z: false, symbolOid: "1102" }] },
                  o: "1171",
                },
                { y: 1.15, i: "f", s: 0, z: 0, o: "1155", f: "c" },
              ],
              n: "angle",
              f: 30,
              b: [],
            },
            1168: {
              c: "1145",
              q: false,
              z: 3,
              i: "1168",
              a: [
                { f: "b", y: 0, z: 3, i: "a", e: -448, s: 2, o: "1146" },
                {
                  f: "c",
                  p: 2,
                  y: 2.14,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ i: 0, b: "1168", p: 9, symbolOid: "1020" }] },
                  o: "1168",
                },
                { y: 3, i: "a", s: -448, z: 0, o: "1146", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 17.13,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "q", y: 0, z: 0.15, i: "b", e: 417, s: 461, o: "1158" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 1, s: 0, o: "1158" },
                { f: "h", y: 0, z: 0.24, i: "cQ", e: 1, s: 0.8, o: "1136" },
                { f: "h", y: 0, z: 0.24, i: "cR", e: 1, s: 0.8, o: "1136" },
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      { b: "1029", p: 3, z: false, symbolOid: "549" },
                      { b: "1047", p: 3, z: false, symbolOid: "549" },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 0, z: 0.24, i: "e", e: 1, s: 0, o: "1136" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 1, s: 0, o: "1139" },
                { f: "c", y: 0.1, z: 0.15, i: "e", e: 1, s: 0, o: "1141" },
                {
                  f: "h",
                  y: 0.15,
                  z: 0.24,
                  i: "cQ",
                  e: 1.1,
                  s: 0.7,
                  o: "1130",
                },
                {
                  f: "h",
                  y: 0.15,
                  z: 0.24,
                  i: "cR",
                  e: 1.1,
                  s: 0.7,
                  o: "1130",
                },
                { y: 0.15, i: "b", s: 417, z: 0, o: "1158", f: "c" },
                { f: "c", y: 0.15, z: 0.24, i: "e", e: 1, s: 0, o: "1130" },
                { y: 0.15, i: "e", s: 1, z: 0, o: "1158", f: "c" },
                { y: 0.15, i: "e", s: 1, z: 0, o: "1139", f: "c" },
                { y: 0.24, i: "cR", s: 1, z: 0, o: "1136", f: "c" },
                { y: 0.24, i: "cQ", s: 1, z: 0, o: "1136", f: "c" },
                { f: "c", y: 0.24, z: 0.15, i: "e", e: 1, s: 0, o: "1140" },
                { y: 0.24, i: "e", s: 1, z: 0, o: "1136", f: "c" },
                { y: 0.25, i: "e", s: 1, z: 0, o: "1141", f: "c" },
                { y: 1, i: "a", s: -161, z: 0, o: "1152", f: "c" },
                { f: "c", y: 1, z: 0.15, i: "e", e: 1, s: 0, o: "1137" },
                { f: "c", y: 1.09, z: 0.13, i: "cQ", e: 1, s: 1.1, o: "1130" },
                { f: "c", y: 1.09, z: 0.13, i: "cR", e: 1, s: 1.1, o: "1130" },
                { y: 1.09, i: "e", s: 1, z: 0, o: "1140", f: "c" },
                { y: 1.09, i: "e", s: 1, z: 0, o: "1130", f: "c" },
                { y: 1.15, i: "e", s: 1, z: 0, o: "1137", f: "c" },
                { y: 1.22, i: "cQ", s: 1, z: 0, o: "1130", f: "c" },
                { y: 1.22, i: "cR", s: 1, z: 0, o: "1130", f: "c" },
              ],
              f: 30,
              b: [
                {
                  D: 3.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1167",
                },
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1168",
                },
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1172",
                },
                {
                  D: 17.13,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1169",
                },
                {
                  D: 1.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1170",
                },
              ],
            },
            1029: {
              q: false,
              z: 4,
              i: "1029",
              n: "wave",
              a: [
                { f: "c", y: 0, z: 2, i: "b", e: 187, s: 208, o: "1145" },
                { f: "c", y: 0, z: 2, i: "d", e: 186, s: 165, o: "1144" },
                { f: "c", y: 0, z: 0.12, i: "cQ", e: 1.05, s: 1, o: "1136" },
                { f: "c", y: 0, z: 0.12, i: "cR", e: 1.05, s: 1, o: "1136" },
                { f: "c", y: 0, z: 2, i: "b", e: 207, s: 228, o: "1144" },
                { f: "c", y: 0.12, z: 0.11, i: "cR", e: 1, s: 1.05, o: "1136" },
                { f: "c", y: 0.12, z: 0.11, i: "cQ", e: 1, s: 1.05, o: "1136" },
                { f: "c", y: 0.23, z: 0.11, i: "cR", e: 1.05, s: 1, o: "1130" },
                { f: "c", y: 0.23, z: 0.11, i: "cQ", e: 1.05, s: 1, o: "1130" },
                { y: 0.23, i: "cR", s: 1, z: 0, o: "1136", f: "c" },
                { y: 0.23, i: "cQ", s: 1, z: 0, o: "1136", f: "c" },
                { f: "c", y: 1.04, z: 0.11, i: "cR", e: 1, s: 1.05, o: "1130" },
                { f: "c", y: 1.04, z: 0.11, i: "cQ", e: 1, s: 1.05, o: "1130" },
                { y: 1.15, i: "cR", s: 1, z: 0, o: "1130", f: "c" },
                { y: 1.15, i: "cQ", s: 1, z: 0, o: "1130", f: "c" },
                { f: "c", y: 2, z: 2, i: "d", e: 165, s: 186, o: "1144" },
                { f: "c", y: 2, z: 2, i: "b", e: 228, s: 207, o: "1144" },
                { f: "c", y: 2, z: 2, i: "b", e: 208, s: 187, o: "1145" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1029", p: 3, z: false, symbolOid: "549" }] },
                  o: "1029",
                },
                { y: 4, i: "d", s: 165, z: 0, o: "1144", f: "c" },
                { y: 4, i: "b", s: 228, z: 0, o: "1144", f: "c" },
                { y: 4, i: "b", s: 208, z: 0, o: "1145", f: "c" },
              ],
              f: 30,
              b: [],
            },
            1169: {
              c: "1148",
              q: false,
              z: 17.13,
              i: "1169",
              a: [
                { f: "b", y: 0, z: 7.13, i: "a", e: -125, s: 0, o: "1149" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "1149" },
                { f: "c", y: 1, z: 5, i: "e", e: 1, s: 1, o: "1149" },
                { f: "b", y: 4, z: 7, i: "a", e: -125, s: 0, o: "1150" },
                { f: "b", y: 4, z: 2, i: "e", e: 1, s: 0, o: "1150" },
                { f: "b", y: 6, z: 4, i: "e", e: 1, s: 1, o: "1150" },
                { f: "b", y: 6, z: 1.13, i: "e", e: 0, s: 1, o: "1149" },
                {
                  f: "c",
                  y: 7.13,
                  z: 0.17,
                  i: "a",
                  e: -100,
                  s: -125,
                  o: "1149",
                },
                { f: "c", y: 7.13, z: 0.17, i: "e", e: 0, s: 0, o: "1149" },
                { f: "c", y: 8, z: 3, i: "a", e: -125, s: -100, o: "1149" },
                { y: 8, i: "e", s: 0, z: 0, o: "1149", f: "c" },
                { f: "b", y: 10, z: 7.13, i: "a", e: -125, s: 0, o: "1151" },
                { f: "c", y: 10, z: 1, i: "e", e: 1, s: 0, o: "1151" },
                { f: "c", y: 10, z: 1, i: "e", e: 0, s: 1, o: "1150" },
                {
                  f: "c",
                  p: 2,
                  y: 10.29,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ i: 1, b: "1169", p: 9, symbolOid: "1030" }] },
                  o: "1169",
                },
                { y: 11, i: "a", s: -125, z: 0, o: "1150", f: "c" },
                { y: 11, i: "a", s: -125, z: 0, o: "1149", f: "c" },
                { f: "c", y: 11, z: 5, i: "e", e: 1, s: 1, o: "1151" },
                { y: 11, i: "e", s: 0, z: 0, o: "1150", f: "c" },
                { f: "b", y: 16, z: 1.13, i: "e", e: 0, s: 1, o: "1151" },
                { y: 17.13, i: "a", s: -125, z: 0, o: "1151", f: "c" },
                { y: 17.13, i: "e", s: 0, z: 0, o: "1151", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "1149",
            "1150",
            "1151",
            "1148",
            "1124",
            "1125",
            "1157",
            "1127",
            "1138",
            "1129",
            "1128",
            "1166",
            "1165",
            "1143",
            "1142",
            "1156",
            "1152",
            "1147",
            "1126",
            "1153",
            "1155",
            "1154",
            "1146",
            "1145",
            "1144",
            "1136",
            "1141",
            "1140",
            "1130",
            "1133",
            "1132",
            "1134",
            "1135",
            "1131",
            "1137",
            "1139",
            "1123",
            "1159",
            "1158",
            "1160",
            "1162",
            "1161",
            "1164",
            "1163",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            1126: {
              w: "",
              h: "984",
              p: "no-repeat",
              x: "visible",
              a: 41,
              q: "100% 100%",
              b: 60,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "1125",
              dB: "img",
              d: 48,
              k: "div",
              c: 240,
            },
            1138: {
              x: "visible",
              bF: "1129",
              k: "div",
              c: 298,
              d: 391,
              z: 3,
              a: 0,
              bS: 351,
              j: "absolute",
              b: 0,
            },
            1134: {
              cN: "none",
              x: "visible",
              a: 17,
              cA: false,
              b: 17,
              j: "absolute",
              r: "inline",
              c: 23,
              k: "div",
              z: 2,
              d: 23,
              bF: "1130",
              cQ: 1,
              aP: "auto",
              bY: 1,
              bZ: 180,
              bX: false,
              cR: 1,
              cV: [],
            },
            1146: {
              h: "976",
              p: "no-repeat",
              x: "visible",
              a: 2,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "1145",
              dB: "img",
              d: 21,
              k: "div",
              cQ: 1,
              c: 762,
              cR: 1,
            },
            1158: {
              cN: "none",
              x: "hidden",
              bS: 31,
              a: 1,
              b: 461,
              j: "absolute",
              r: "inline",
              z: 6,
              k: "div",
              c: 319,
              d: 63,
              aK: 30,
              e: 0,
              aP: "auto",
              aL: 30,
            },
            1130: {
              x: "visible",
              bS: 383,
              a: -11,
              b: 291,
              j: "absolute",
              bF: "1129",
              z: 6,
              r: "inline",
              k: "div",
              d: 61,
              c: 320,
              cQ: 0.7,
              e: 0,
              cR: 0.7,
            },
            1142: {
              cN: "none",
              x: "hidden",
              bS: 18,
              a: 11,
              b: 31,
              j: "absolute",
              aJ: 30,
              z: 5,
              r: "inline",
              k: "div",
              d: 391,
              aK: 30,
              aI: 30,
              e: 1,
              c: 298,
              aP: "auto",
              aL: 30,
            },
            1154: {
              x: "visible",
              tY: 0.62222222,
              a: 34,
              b: 0,
              j: "absolute",
              bF: "1153",
              c: 119,
              k: "div",
              z: 2,
              d: 135,
              bY: 1,
              cA: false,
              bX: false,
              bZ: 180,
              cV: [],
              tX: 0.45378151,
            },
            1166: {
              x: "visible",
              bF: "1165",
              k: "div",
              c: 298,
              d: 391,
              z: 1,
              a: 0,
              bS: 415,
              j: "absolute",
              b: 0,
            },
            1150: {
              h: "993",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "1148",
              z: 6,
              dB: "img",
              d: 302,
              k: "div",
              cQ: 1,
              e: 0,
              c: 685,
              cR: 1,
            },
            1162: {
              h: "976",
              p: "no-repeat",
              x: "visible",
              a: 2,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "1161",
              dB: "img",
              d: 21,
              k: "div",
              cQ: 1,
              c: 762,
              cR: 1,
            },
            1127: {
              h: "980",
              p: "no-repeat",
              x: "visible",
              a: 91,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "1125",
              b: 0,
              d: 61,
              k: "div",
              c: 138,
            },
            1139: {
              c: 41,
              d: 41,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#000",
              L: "Solid",
              M: 0,
              bF: "1138",
              N: 0,
              A: "#004997",
              x: "visible",
              j: "absolute",
              B: "#004997",
              P: 0,
              O: 0,
              C: "#004997",
              z: 3,
              aJ: "50%",
              D: "#004997",
              aK: "50%",
              k: "div",
              aI: "50%",
              a: 173,
              aL: "50%",
              b: 382,
            },
            1123: {
              c: 318,
              bS: 287,
              d: 56,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#00FDFF",
              L: "Solid",
              aP: "pointer",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 1,
              O: 1,
              C: "#D8DDE4",
              z: 50,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "750" },
                  { p: 4, h: "747" },
                ],
              },
              k: "div",
              a: 0,
              b: 422,
            },
            1135: {
              h: "62",
              p: "no-repeat",
              x: "visible",
              a: 32,
              q: "100% 100%",
              b: -2,
              j: "absolute",
              r: "inline",
              bF: "1134",
              z: 4,
              dB: "img",
              d: 17,
              k: "div",
              aY: 0,
              cQ: 1,
              c: 13,
              cR: 1,
            },
            1147: {
              h: "1044",
              p: "no-repeat",
              x: "visible",
              a: -113,
              q: "100% 100%",
              b: 13,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "1143",
              dB: "img",
              d: 347,
              k: "div",
              cQ: 1,
              c: 503,
              cR: 1,
            },
            1159: {
              x: "visible",
              bF: "1158",
              k: "div",
              c: 320,
              d: 62,
              z: 7,
              a: 0,
              bS: 383,
              j: "absolute",
              b: 1,
            },
            1131: {
              aU: 8,
              G: "#FFF",
              c: 38,
              aV: 8,
              r: "inline",
              d: 9,
              s: "Montserrat",
              X: 0,
              t: 11,
              Y: 4,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "700",
              i: "distance",
              w: "300 m",
              bF: "1130",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 3,
              aS: 8,
              cN: "none",
              E: 0.337862,
              aT: 8,
              a: 56,
              b: 15,
            },
            1143: {
              x: "visible",
              bF: "1142",
              k: "div",
              c: 298,
              d: 391,
              z: 5,
              a: 0,
              bS: 447,
              j: "absolute",
              b: 0,
            },
            1155: {
              p: "no-repeat",
              b: 2,
              c: 119,
              q: "100% 100%",
              d: 135,
              r: "inline",
              f: 0,
              dO: 0,
              h: "990",
              dP: 0,
              bF: "1154",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 3,
              tX: 0.27731092,
              a: -2,
              dD: 0,
              tY: 0.48148148,
            },
            1151: {
              h: "993",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "1148",
              z: 5,
              dB: "img",
              d: 302,
              k: "div",
              cQ: 1,
              e: 0,
              c: 685,
              cR: 1,
            },
            1163: {
              h: "1003",
              p: "no-repeat",
              x: "visible",
              a: 16,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "1160",
              b: 34,
              d: 17,
              k: "div",
              c: 167,
            },
            1128: {
              x: "hidden",
              k: "div",
              c: 298,
              d: 391,
              z: 12,
              r: "inline",
              a: 11,
              bS: 23,
              j: "absolute",
              b: 31,
            },
            1124: {
              c: 318,
              bS: 319,
              d: 478,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#0433FF",
              L: "Solid",
              aP: "pointer",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 1,
              O: 1,
              C: "#D8DDE4",
              z: 49,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "749" },
                  { p: 4, h: "9" },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            1136: {
              h: "978",
              p: "no-repeat",
              x: "visible",
              a: 35,
              q: "100% 100%",
              bS: 383,
              j: "absolute",
              bF: "1129",
              r: "inline",
              b: 230,
              z: 7,
              d: 57,
              dB: "img",
              cQ: 0.8,
              e: 0,
              k: "div",
              c: 230,
              cR: 0.8,
            },
            1148: {
              x: "visible",
              cA: false,
              a: -11,
              b: -125,
              j: "absolute",
              bF: "1143",
              c: 685,
              k: "div",
              bY: 1,
              d: 302,
              z: 2,
              bX: false,
              bZ: 180,
              cV: [],
            },
            1132: {
              aU: 8,
              G: "#FFF",
              c: 154,
              aV: 8,
              r: "inline",
              d: 18,
              s: "Futura,Verdana,sans-serif",
              X: 0,
              t: 10,
              Y: 12,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "normal",
              i: "address",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">Mi\u0119dzyzdroje, \nUl. Gryfa Pomorskiego 25\n</div>',
              bF: "1130",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 4,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 105,
              b: 6,
            },
            1144: {
              c: 320,
              d: 165,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#D10007",
              L: "Solid",
              M: 0,
              bF: "1143",
              N: 0,
              A: "#004997",
              x: "visible",
              j: "absolute",
              B: "#004997",
              P: 0,
              O: 0,
              C: "#004997",
              z: 8,
              k: "div",
              D: "#004997",
              a: -11,
              b: 228,
            },
            1156: {
              h: "988",
              p: "no-repeat",
              x: "visible",
              a: -196,
              q: "100% 100%",
              b: -71,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "1153",
              dB: "img",
              d: 400,
              k: "div",
              cQ: 1,
              c: 580,
              cR: 1,
            },
            1140: {
              c: 21,
              d: 21,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#000",
              L: "Solid",
              M: 0,
              bF: "1138",
              N: 0,
              A: "#004997",
              x: "visible",
              j: "absolute",
              B: "#004997",
              P: 0,
              O: 0,
              C: "#004997",
              z: 1,
              aJ: "50%",
              D: "#004997",
              aK: "50%",
              k: "div",
              aI: "50%",
              a: 17,
              aL: "50%",
              b: 269,
            },
            1152: {
              x: "visible",
              k: "div",
              c: 580,
              d: 400,
              z: 5,
              r: "inline",
              a: -161,
              j: "absolute",
              bF: "1143",
              b: 7,
            },
            1164: {
              c: 200,
              d: 38,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#D10007",
              L: "Solid",
              M: 0,
              bF: "1160",
              N: 0,
              A: "#004997",
              x: "visible",
              j: "absolute",
              B: "#004997",
              P: 0,
              O: 0,
              C: "#004997",
              z: 1,
              k: "div",
              D: "#004997",
              a: 0,
              b: 24,
            },
            1160: {
              x: "hidden",
              k: "div",
              c: 199,
              d: 62,
              z: 1,
              a: 60,
              j: "absolute",
              bF: "1159",
              b: 0,
            },
            1129: {
              x: "visible",
              b: 0,
              k: "div",
              c: 298,
              d: 391,
              z: 7,
              r: "inline",
              a: 0,
              bS: 351,
              j: "absolute",
              bF: "1128",
            },
            1125: {
              x: "visible",
              k: "div",
              c: 320,
              d: 109,
              z: 45,
              r: "inline",
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            1137: {
              h: "986",
              p: "no-repeat",
              x: "visible",
              a: 31,
              q: "100% 100%",
              b: 342,
              j: "absolute",
              r: "inline",
              bF: "1129",
              z: 4,
              dB: "img",
              d: 36,
              k: "div",
              cQ: 1,
              e: 0,
              c: 236,
              cR: 1,
            },
            1149: {
              h: "993",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "1148",
              z: 7,
              dB: "img",
              d: 302,
              k: "div",
              cQ: 1,
              e: 0,
              c: 685,
              cR: 1,
            },
            1133: {
              c: 240,
              d: 38,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#000",
              L: "Solid",
              M: 0,
              bF: "1130",
              N: 0,
              A: "#004997",
              x: "visible",
              j: "absolute",
              B: "#004997",
              P: 0,
              O: 0,
              C: "#004997",
              z: 1,
              aJ: 30,
              D: "#004997",
              aK: 30,
              k: "div",
              aI: 30,
              a: 40,
              aL: 30,
              b: 5,
            },
            1145: {
              x: "visible",
              cA: false,
              a: -5,
              b: 208,
              j: "absolute",
              bF: "1143",
              c: 762,
              k: "div",
              bY: 1,
              d: 21,
              z: 9,
              bX: false,
              bZ: 180,
              cV: [],
            },
            1157: {
              c: 320,
              d: 480,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#7BA5D3",
              L: "Solid",
              M: 0,
              bF: "1143",
              N: 0,
              A: "#004997",
              x: "visible",
              j: "absolute",
              B: "#004997",
              P: 0,
              O: 0,
              C: "#004997",
              z: 1,
              k: "div",
              D: "#004997",
              a: 0,
              b: -31,
            },
            1141: {
              c: 41,
              d: 41,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#000",
              L: "Solid",
              M: 0,
              bF: "1138",
              N: 0,
              A: "#004997",
              x: "visible",
              j: "absolute",
              B: "#004997",
              P: 0,
              O: 0,
              C: "#004997",
              z: 2,
              aJ: "50%",
              D: "#004997",
              aK: "50%",
              k: "div",
              aI: "50%",
              a: 262,
              aL: "50%",
              b: 248,
            },
            1153: {
              x: "visible",
              tY: 0.67,
              a: 196,
              b: 71,
              j: "absolute",
              bF: "1152",
              c: 188,
              k: "div",
              z: 1,
              d: 144,
              f: 0,
              tX: 0.5,
            },
            1165: {
              x: "hidden",
              aI: 30,
              a: 11,
              b: 31,
              bS: 18,
              aJ: 30,
              z: 7,
              k: "div",
              j: "absolute",
              d: 391,
              aK: 0,
              c: 298,
              aL: 0,
            },
            1161: {
              x: "visible",
              a: -130,
              cA: false,
              b: 7,
              j: "absolute",
              bF: "1160",
              c: 762,
              k: "div",
              z: 3,
              d: 21,
              bY: 1,
              cQ: 0.7,
              bX: false,
              bZ: 180,
              cV: [],
              cR: 0.7,
            },
          },
        },
      ],
      {},
      h,
      {
        y: { p: 0, q: [[0, 0, 0.445, 0.05, 0.55, 0.95, 1, 1]] },
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
        h: { p: 0, q: [[0, 0, 0.175, 0.885, 0.32, 1.25, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
