//	HYPE.documents["Medex_postbeeotic_320x480adaptive_June26"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/Medex",
      f = "Medex_postbeeotic_320x480adaptive_June26",
      g = "medexpostbeeotic320x480adaptivejune26_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "gotomap",
        source:
          "function(hypeDocument, element, event) {\t\twindow.gotomap();\t\n\t\n}",
        identifier: "118",
      },
      {
        name: "action1",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action1();\n}",
        identifier: "904",
      },
      {
        name: "action2",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action2();\n}",
        identifier: "1188",
      },
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\t\n\t\twindow.gotosite();\t\n}",
        identifier: "1189",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        10: { p: 1, n: "splash.png", g: "1191", t: "@1x" },
        2: { p: 1, n: "logo.svg", g: "606", t: "image/svg+xml" },
        "-2": { n: "blank.gif" },
        3: { p: 1, n: "logo_2.svg", g: "1070", t: "image/svg+xml" },
        11: { p: 1, n: "ice_.png", g: "1193", t: "@1x" },
        4: { p: 1, n: "promo_sticker.svg", g: "1072", t: "image/svg+xml" },
        5: { p: 1, n: "btn_text.svg", g: "608", t: "image/svg+xml" },
        12: { p: 1, n: "dis_1.svg", g: "1078", t: "image/svg+xml" },
        6: { p: 1, n: "powder.png", g: "1126", t: "@1x" },
        13: { p: 1, n: "hand_.png", g: "1068", t: "@1x" },
        7: { p: 1, n: "powder_.png", g: "1131", t: "@1x" },
        "-1": { n: "PIE.htc" },
        0: { p: 1, n: "icon_white.svg", g: "754", t: "image/svg+xml" },
        8: { p: 1, n: "image_1_glass.png", g: "1076", t: "@1x" },
        1: { p: 1, n: "bg_.jpg", g: "980", t: "@1x" },
        9: { p: 1, n: "image_2.png", g: "1074", t: "@1x" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "SCENE", o: "1", X: [0] }],
      [
        {
          o: "3",
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#00293F",
          L: [],
          bY: 1,
          d: 320,
          U: {
            1225: { V: { "Main Timeline": "1262" }, W: "1262", n: "btn_bg" },
            1231: { V: { "Main Timeline": "1263" }, W: "1263", n: "icon" },
            1222: { V: { "Main Timeline": "1261" }, W: "1261", n: "pulse" },
          },
          T: {
            1177: {
              q: false,
              z: 9,
              i: "1177",
              n: "sticker",
              a: [
                { f: "p", y: 0, z: 1, i: "e", e: 0, s: 1, o: "1246" },
                { f: "p", y: 0, z: 1, i: "cQ", e: 0.6, s: 1, o: "1246" },
                { f: "p", y: 0, z: 1, i: "cR", e: 0.6, s: 1, o: "1246" },
                { f: "c", y: 1, z: 0.05, i: "a", e: 38, s: 221, o: "1246" },
                { f: "c", y: 1, z: 0.05, i: "b", e: 18, s: 0, o: "1246" },
                { f: "h", y: 1, z: 0.05, i: "cQ", e: 0.6, s: 0.6, o: "1246" },
                { f: "c", y: 1, z: 0.05, i: "e", e: 0, s: 0, o: "1246" },
                { f: "h", y: 1, z: 0.05, i: "cR", e: 0.6, s: 0.6, o: "1246" },
                { f: "c", y: 1.05, z: 2.21, i: "b", e: 18, s: 18, o: "1246" },
                { f: "c", y: 1.05, z: 2.21, i: "a", e: 38, s: 38, o: "1246" },
                { f: "h", y: 1.05, z: 0.25, i: "cR", e: 1, s: 0.6, o: "1246" },
                { f: "c", y: 1.05, z: 0.25, i: "e", e: 1, s: 0, o: "1246" },
                { f: "h", y: 1.05, z: 0.25, i: "cQ", e: 1, s: 0.6, o: "1246" },
                { f: "p", y: 2, z: 1, i: "e", e: 1, s: 1, o: "1246" },
                { f: "p", y: 2, z: 1, i: "cQ", e: 1, s: 1, o: "1246" },
                { f: "p", y: 2, z: 1, i: "cR", e: 1, s: 1, o: "1246" },
                { f: "p", y: 3, z: 0.26, i: "cR", e: 0.6, s: 1, o: "1246" },
                { f: "p", y: 3, z: 0.26, i: "e", e: 0, s: 1, o: "1246" },
                { f: "p", y: 3, z: 0.26, i: "cQ", e: 0.6, s: 1, o: "1246" },
                { f: "c", y: 3.26, z: 0.04, i: "b", e: 110, s: 18, o: "1246" },
                { f: "c", y: 3.26, z: 0.04, i: "a", e: 160, s: 38, o: "1246" },
                {
                  f: "h",
                  y: 3.26,
                  z: 0.04,
                  i: "cR",
                  e: 0.6,
                  s: 0.6,
                  o: "1246",
                },
                {
                  f: "h",
                  y: 3.26,
                  z: 0.04,
                  i: "cQ",
                  e: 0.6,
                  s: 0.6,
                  o: "1246",
                },
                { f: "c", y: 3.26, z: 0.04, i: "e", e: 0, s: 0, o: "1246" },
                { f: "c", y: 4, z: 2.22, i: "b", e: 110, s: 110, o: "1246" },
                { f: "c", y: 4, z: 2.22, i: "a", e: 160, s: 160, o: "1246" },
                { f: "c", y: 4, z: 0.2, i: "e", e: 1, s: 0, o: "1246" },
                { f: "h", y: 4, z: 0.2, i: "cQ", e: 1, s: 0.6, o: "1246" },
                { f: "h", y: 4, z: 0.2, i: "cR", e: 1, s: 0.6, o: "1246" },
                { f: "p", y: 4.2, z: 1.04, i: "e", e: 1, s: 1, o: "1246" },
                { f: "p", y: 4.2, z: 1.04, i: "cQ", e: 1, s: 1, o: "1246" },
                { f: "p", y: 4.2, z: 1.04, i: "cR", e: 1, s: 1, o: "1246" },
                { f: "p", y: 5.24, z: 0.28, i: "cR", e: 0.6, s: 1, o: "1246" },
                { f: "p", y: 5.24, z: 0.28, i: "cQ", e: 0.6, s: 1, o: "1246" },
                { f: "p", y: 5.24, z: 0.28, i: "e", e: 0, s: 1, o: "1246" },
                { f: "c", y: 6.22, z: 0.04, i: "a", e: 221, s: 160, o: "1246" },
                { f: "c", y: 6.22, z: 0.04, i: "b", e: 0, s: 110, o: "1246" },
                {
                  f: "h",
                  y: 6.22,
                  z: 0.04,
                  i: "cR",
                  e: 0.6,
                  s: 0.6,
                  o: "1246",
                },
                {
                  f: "h",
                  y: 6.22,
                  z: 0.04,
                  i: "cQ",
                  e: 0.6,
                  s: 0.6,
                  o: "1246",
                },
                { f: "c", y: 6.22, z: 0.04, i: "e", e: 0, s: 0, o: "1246" },
                { y: 6.26, i: "a", s: 221, z: 0, o: "1246", f: "c" },
                { y: 6.26, i: "b", s: 0, z: 0, o: "1246", f: "c" },
                { f: "c", y: 6.26, z: 1.04, i: "e", e: 1, s: 0, o: "1246" },
                { f: "h", y: 6.26, z: 1.04, i: "cR", e: 1, s: 0.6, o: "1246" },
                { f: "h", y: 6.26, z: 1.04, i: "cQ", e: 1, s: 0.6, o: "1246" },
                { y: 8, i: "cQ", s: 1, z: 0, o: "1246", f: "p" },
                { y: 8, i: "cR", s: 1, z: 0, o: "1246", f: "p" },
                { y: 8, i: "e", s: 1, z: 0, o: "1246", f: "p" },
                {
                  f: "c",
                  p: 2,
                  y: 9,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1177", p: 3, z: false, symbolOid: "2" }] },
                  o: "1177",
                },
              ],
              f: 30,
              b: [],
            },
            1261: {
              c: "1222",
              q: false,
              z: 3,
              i: "1261",
              a: [
                { f: "c", y: 0, z: 0.15, i: "cQ", e: 1.05, s: 1, o: "1223" },
                { f: "c", y: 0, z: 0.15, i: "cR", e: 1.05, s: 1, o: "1223" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 1.05, o: "1223" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 1.05, o: "1223" },
                { f: "c", y: 1, z: 1, i: "cR", e: 1, s: 1, o: "1223" },
                { f: "c", y: 1, z: 1, i: "cQ", e: 1, s: 1, o: "1223" },
                { f: "c", y: 2, z: 0.15, i: "cR", e: 1.05, s: 1, o: "1223" },
                { f: "c", y: 2, z: 0.15, i: "cQ", e: 1.05, s: 1, o: "1223" },
                { f: "c", y: 2.15, z: 0.15, i: "cQ", e: 1, s: 1.05, o: "1223" },
                { f: "c", y: 2.15, z: 0.15, i: "cR", e: 1, s: 1.05, o: "1223" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1261", p: 3, z: false, symbolOid: "1116" }] },
                  o: "1261",
                },
                { y: 3, i: "cQ", s: 1, z: 0, o: "1223", f: "c" },
                { y: 3, i: "cR", s: 1, z: 0, o: "1223", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1262",
                },
              ],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 6,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { y: 0, i: "cY", s: "0", z: 0, o: "1235", f: "c" },
                { f: "q", y: 0, z: 1, i: "e", e: 1, s: 0, o: "1221" },
                { f: "q", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "1221" },
                { f: "q", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "1221" },
                { f: "c", y: 0, z: 1, i: "a", e: 15, s: 29, o: "1237" },
                { f: "p", y: 0, z: 1, i: "f", e: 0, s: 25, o: "1255" },
                { y: 0, i: "cY", s: "0", z: 0, o: "1238", f: "c" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "1237" },
                { f: "q", y: 0, z: 2.13, i: "cQ", e: 1, s: 1.1, o: "1241" },
                { f: "q", y: 0, z: 2.13, i: "cR", e: 1, s: 1.1, o: "1241" },
                {
                  f: "c",
                  y: 0.16,
                  z: 1.14,
                  i: "cQ",
                  e: 0.9,
                  s: 0.6,
                  o: "1256",
                },
                {
                  f: "c",
                  y: 0.16,
                  z: 1.14,
                  i: "cR",
                  e: 1.5,
                  s: 0.24,
                  o: "1256",
                },
                { f: "c", y: 1, z: 2, i: "b", e: 140, s: 118, o: "1256" },
                { f: "c", y: 1, z: 2, i: "a", e: 15, s: 15, o: "1237" },
                { f: "c", y: 1, z: 2, i: "f", e: 0, s: 0, o: "1255" },
                { f: "c", y: 1, z: 2, i: "e", e: 0, s: 1, o: "1256" },
                { y: 1, i: "e", s: 1, z: 0, o: "1221", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "1221", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "1221", f: "c" },
                { f: "c", y: 1, z: 2, i: "e", e: 1, s: 1, o: "1237" },
                { y: 2, i: "cR", s: 1.5, z: 0, o: "1256", f: "c" },
                { y: 2, i: "cQ", s: 0.9, z: 0, o: "1256", f: "c" },
                { y: 2.13, i: "cQ", s: 1, z: 0, o: "1241", f: "c" },
                { y: 2.13, i: "cR", s: 1, z: 0, o: "1241", f: "c" },
                { y: 3, i: "b", s: 140, z: 0, o: "1256", f: "c" },
                { f: "p", y: 3, z: 1, i: "f", e: 25, s: 0, o: "1255" },
                { f: "c", y: 3, z: 1, i: "a", e: 112, s: 15, o: "1237" },
                { f: "c", y: 3, z: 1, i: "e", e: 0, s: 1, o: "1255" },
                { y: 3, i: "e", s: 0, z: 0, o: "1256", f: "c" },
                { f: "q", y: 3, z: 1, i: "e", e: 0, s: 1, o: "1237" },
                { f: "q", y: 3.15, z: 1, i: "a", e: 0, s: 221, o: "1250" },
                { f: "c", y: 3.15, z: 1, i: "e", e: 1, s: 0, o: "1250" },
                { f: "c", y: 3.24, z: 0.06, i: "e", e: 1, s: 0, o: "1245" },
                { f: "j", y: 4, z: 0.12, i: "b", e: 44, s: -2, o: "1245" },
                { f: "q", y: 4, z: 0.22, i: "f", e: 0, s: 180, o: "1249" },
                { f: "q", y: 4, z: 0.23, i: "b", e: 140, s: 124, o: "1249" },
                { f: "q", y: 4, z: 0.22, i: "a", e: 14, s: 56, o: "1249" },
                { y: 4, i: "f", s: 25, z: 0, o: "1255", f: "p" },
                { y: 4, i: "a", s: 112, z: 0, o: "1237", f: "c" },
                { f: "h", y: 4, z: 1, i: "cR", e: 1, s: 0.6, o: "1246" },
                { f: "h", y: 4, z: 1, i: "cQ", e: 1, s: 0.6, o: "1246" },
                { f: "q", y: 4, z: 0.11, i: "e", e: 1, s: 0, o: "1249" },
                { f: "l", y: 4, z: 0.12, i: "e", e: 0, s: 1, o: "1245" },
                { f: "c", y: 4, z: 1, i: "e", e: 1, s: 0, o: "1246" },
                { f: "c", y: 4, z: 0.15, i: "e", e: 1, s: 0, o: "1227" },
                { y: 4, i: "e", s: 0, z: 0, o: "1255", f: "c" },
                { y: 4, i: "e", s: 0, z: 0, o: "1237", f: "c" },
                { f: "c", y: 4.07, z: 0.02, i: "e", e: 1, s: 0, o: "1247" },
                { f: "c", y: 4.09, z: 0.14, i: "b", e: 35, s: 42, o: "1247" },
                { f: "w", y: 4.09, z: 0.14, i: "cQ", e: 1, s: 0.6, o: "1248" },
                { f: "w", y: 4.09, z: 0.14, i: "cR", e: 1, s: 0.6, o: "1248" },
                { f: "c", y: 4.09, z: 0.12, i: "e", e: 1, s: 1, o: "1247" },
                { f: "q", y: 4.11, z: 0.23, i: "b", e: 130, s: 114, o: "1244" },
                { f: "q", y: 4.11, z: 0.22, i: "f", e: 0, s: 180, o: "1244" },
                { f: "q", y: 4.11, z: 0.22, i: "a", e: 8, s: 50, o: "1244" },
                { f: "q", y: 4.11, z: 0.11, i: "e", e: 1, s: 0, o: "1244" },
                { y: 4.11, i: "e", s: 1, z: 0, o: "1249", f: "l" },
                { y: 4.12, i: "b", s: 44, z: 0, o: "1245", f: "c" },
                { y: 4.12, i: "e", s: 0, z: 0, o: "1245", f: "c" },
                { y: 4.15, i: "a", s: 0, z: 0, o: "1250", f: "c" },
                { y: 4.15, i: "e", s: 1, z: 0, o: "1250", f: "c" },
                { y: 4.15, i: "e", s: 1, z: 0, o: "1227", f: "c" },
                { f: "c", y: 4.21, z: 0.07, i: "e", e: 0, s: 1, o: "1247" },
                { y: 4.22, i: "f", s: 0, z: 0, o: "1249", f: "c" },
                { y: 4.22, i: "a", s: 14, z: 0, o: "1249", f: "c" },
                { y: 4.22, i: "e", s: 1, z: 0, o: "1244", f: "l" },
                { y: 4.23, i: "b", s: 35, z: 0, o: "1247", f: "c" },
                { y: 4.23, i: "cR", s: 1, z: 0, o: "1248", f: "c" },
                { y: 4.23, i: "cQ", s: 1, z: 0, o: "1248", f: "c" },
                { y: 4.23, i: "b", s: 140, z: 0, o: "1249", f: "c" },
                { y: 4.28, i: "e", s: 0, z: 0, o: "1247", f: "c" },
                { y: 5, i: "cR", s: 1, z: 0, o: "1246", f: "c" },
                { y: 5, i: "cQ", s: 1, z: 0, o: "1246", f: "c" },
                { y: 5, i: "e", s: 1, z: 0, o: "1246", f: "c" },
                { y: 5.03, i: "f", s: 0, z: 0, o: "1244", f: "c" },
                { y: 5.03, i: "a", s: 8, z: 0, o: "1244", f: "c" },
                { y: 5.04, i: "b", s: 130, z: 0, o: "1244", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 6,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1177", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
              ],
              f: 30,
              b: [
                {
                  D: 3.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1263",
                },
                {
                  D: 3,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 1,
                  b: "1261",
                },
              ],
            },
            1262: {
              c: "1225",
              q: false,
              z: 3,
              i: "1262",
              a: [
                {
                  f: "c",
                  y: 0,
                  z: 1,
                  i: "g",
                  e: "#679C68",
                  s: "#FFCB05",
                  o: "1226",
                },
                {
                  f: "c",
                  y: 1,
                  z: 1,
                  i: "g",
                  e: "#679C68",
                  s: "#679C68",
                  o: "1226",
                },
                {
                  f: "c",
                  y: 2,
                  z: 1,
                  i: "g",
                  e: "#FFCB05",
                  s: "#679C68",
                  o: "1226",
                },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1262", p: 3, z: false, symbolOid: "1083" }] },
                  o: "1262",
                },
                { y: 3, i: "g", s: "#FFCB05", z: 0, o: "1226", f: "h" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            1263: {
              c: "1231",
              q: false,
              z: 3.15,
              i: "1263",
              a: [
                { f: "y", y: 0, z: 1.15, i: "aY", e: 360, s: 0, o: "1232" },
                { y: 1.15, i: "aY", s: 360, z: 0, o: "1232", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1263", p: 3, z: false, symbolOid: "609" }] },
                  o: "1263",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "1241",
            "1260",
            "1255",
            "1238",
            "1251",
            "1220",
            "1236",
            "1242",
            "1254",
            "1253",
            "1239",
            "1240",
            "1252",
            "1259",
            "1243",
            "1245",
            "1256",
            "1258",
            "1257",
            "1246",
            "1237",
            "1250",
            "1248",
            "1247",
            "1244",
            "1249",
            "1227",
            "1228",
            "1226",
            "1225",
            "1223",
            "1222",
            "1224",
            "1221",
            "1229",
            "1234",
            "1235",
            "1230",
            "1219",
            "1218",
            "1231",
            "1232",
            "1233",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            1228: {
              h: "1070",
              p: "no-repeat",
              x: "visible",
              a: 114,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "1220",
              b: 350,
              d: 28,
              k: "div",
              c: 86,
            },
            1224: {
              h: "608",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: 9,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "1223",
              dB: "img",
              d: 11,
              k: "div",
              cQ: 1,
              c: 101,
              cR: 1,
            },
            1236: {
              x: "visible",
              k: "div",
              c: 318,
              d: 480,
              z: 18,
              a: 1,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            1248: {
              h: "1191",
              p: "no-repeat",
              tY: 1,
              a: 0,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "1247",
              b: 0,
              z: 1,
              d: 42,
              dB: "img",
              cQ: 0.6,
              e: 1,
              k: "div",
              c: 95,
              cR: 0.6,
              tX: 0.51,
            },
            1220: {
              x: "visible",
              k: "div",
              c: 318,
              d: 480,
              z: 21,
              a: 1,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            1232: {
              h: "754",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: 2,
              j: "absolute",
              r: "inline",
              bF: "1231",
              z: 4,
              dB: "img",
              d: 35,
              k: "div",
              aY: 0,
              cQ: 1,
              c: 28,
              cR: 1,
            },
            1244: {
              p: "no-repeat",
              c: 62,
              q: "100% 100%",
              d: 46,
              r: "inline",
              e: 0,
              gg: "1",
              f: 180,
              h: "1193",
              bF: "1243",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 5,
              Q: 2,
              R: "#B3B3B3",
              S: 0,
              a: 50,
              T: 1,
              b: 114,
            },
            1256: {
              x: "visible",
              tY: 0.14,
              a: -19,
              b: 118,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "1255",
              k: "div",
              d: 91,
              c: 62,
              cQ: 0.6,
              e: 1,
              cR: 0.24,
              tX: 0.63,
            },
            1240: {
              c: 320,
              bS: 63,
              d: 470,
              r: "inline",
              e: 1,
              gg: "1",
              bF: "1239",
              aI: 10,
              j: "absolute",
              x: "hidden",
              k: "div",
              aJ: 10,
              Q: 10,
              z: 1,
              aK: 60,
              R: "rgba(0, 0, 0, 0.152)",
              S: 0,
              a: 0,
              aL: 60,
              T: 0,
              b: 10,
            },
            1252: {
              h: "606",
              p: "no-repeat",
              x: "visible",
              a: 100.805,
              q: "100% 100%",
              b: 36,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "1251",
              dB: "img",
              d: 38,
              k: "div",
              cQ: 1,
              c: 114,
              cR: 1,
            },
            1260: {
              h: "1068",
              p: "no-repeat",
              x: "visible",
              tY: 0.12,
              q: "100% 100%",
              a: 16,
              j: "absolute",
              r: "inline",
              bF: "1255",
              b: -28,
              z: 4,
              d: 169,
              dB: "img",
              cQ: 1,
              k: "div",
              c: 224,
              f: 0,
              cR: 1,
              tX: 0.88,
            },
            1229: {
              cN: "none",
              x: "visible",
              bS: 31,
              a: 0,
              b: 417,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 25,
              d: 63,
              aP: "auto",
              e: 1,
            },
            1225: {
              x: "visible",
              cA: false,
              a: 0,
              b: 0,
              j: "absolute",
              bF: "1223",
              c: 116,
              k: "div",
              bY: 1,
              d: 30,
              z: 1,
              bX: false,
              bZ: 180,
              cV: [],
            },
            1237: {
              h: "1076",
              p: "no-repeat",
              x: "visible",
              a: 29,
              q: "100% 100%",
              b: 102,
              j: "absolute",
              r: "inline",
              bF: "1236",
              z: 1,
              dB: "img",
              d: 273,
              k: "div",
              cQ: 1,
              e: 0,
              c: 414,
              cR: 1,
            },
            1249: {
              p: "no-repeat",
              c: 62,
              q: "100% 100%",
              d: 46,
              r: "inline",
              e: 0,
              gg: "1",
              f: 180,
              h: "1193",
              bF: "1243",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 7,
              Q: 2,
              R: "#B3B3B3",
              S: 0,
              a: 56,
              T: 1,
              b: 124,
            },
            1221: {
              Q: 7,
              x: "visible",
              bS: 383,
              R: "rgba(0, 0, 0, 0.095)",
              a: 109,
              j: "absolute",
              bF: "1220",
              r: "inline",
              T: 0,
              b: 399,
              d: 11,
              z: 1,
              S: 0,
              e: 0,
              cQ: 0.8,
              k: "div",
              c: 99,
              cR: 0.8,
              gg: "1",
            },
            1233: {
              aU: 8,
              G: "#FFF",
              c: 100,
              aV: 8,
              r: "inline",
              d: 9,
              s: "Montserrat",
              t: 16,
              Y: 4,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "700",
              i: "distance",
              w: "300 m",
              bF: "1230",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 2,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 48,
              b: 31,
            },
            1245: {
              h: "1193",
              p: "no-repeat",
              x: "visible",
              a: 70,
              q: "100% 100%",
              b: -2,
              j: "absolute",
              r: "inline",
              z: 10,
              bF: "1243",
              dB: "img",
              d: 46,
              k: "div",
              c: 62,
              e: 0,
            },
            1257: {
              h: "1126",
              p: "no-repeat",
              x: "visible",
              tY: 0.33,
              q: "100% 100%",
              a: 23,
              j: "absolute",
              r: "inline",
              bF: "1256",
              b: -7,
              z: 2,
              d: 66,
              dB: "img",
              k: "div",
              bL: 3.45588235,
              c: 20.5,
              tX: 0.54,
            },
            1241: {
              h: "980",
              p: "no-repeat",
              x: "visible",
              a: -138,
              q: "100% 100%",
              b: -66,
              j: "absolute",
              r: "inline",
              bS: 447,
              bF: "1240",
              z: 2,
              d: 510,
              dB: "img",
              cQ: 1.1,
              k: "div",
              c: 595,
              cR: 1.1,
            },
            1253: {
              x: "visible",
              k: "div",
              c: 319,
              d: 480,
              z: 5,
              a: 1,
              bS: 63,
              j: "absolute",
              b: 0,
            },
            1218: {
              x: "hidden",
              b: 427,
              k: "div",
              aL: 15,
              c: 320,
              d: 53,
              z: 22,
              a: 0,
              bS: 31,
              j: "absolute",
              aK: 15,
            },
            1226: {
              c: 116,
              bS: 319,
              d: 30,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#FFCB05",
              L: "Solid",
              M: 0,
              bF: "1225",
              N: 0,
              A: "#ECECEC",
              j: "absolute",
              x: "visible",
              B: "#ECECEC",
              P: 0,
              O: 0,
              C: "#ECECEC",
              z: 3,
              aJ: 30,
              D: "#ECECEC",
              aK: 30,
              k: "div",
              aI: 30,
              a: 0,
              aL: 30,
              b: 0,
            },
            1238: {
              c: 318,
              bS: 311,
              d: 425,
              r: "inline",
              cY: "0",
              e: 0,
              J: "Solid",
              I: "Solid",
              K: "Solid",
              g: "#00F900",
              L: "Solid",
              aP: "pointer",
              M: 1,
              w: "",
              N: 1,
              A: "#B3B3B3",
              j: "absolute",
              x: "visible",
              B: "#B3B3B3",
              P: 1,
              O: 1,
              C: "#B3B3B3",
              z: 75,
              dB: "button",
              D: "#B3B3B3",
              aA: {
                a: [
                  { p: 4, h: "118" },
                  { p: 4, h: "1188" },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            1222: {
              x: "visible",
              cA: false,
              a: -9,
              b: -10,
              j: "absolute",
              bF: "1221",
              c: 116,
              k: "div",
              bY: 1,
              d: 30,
              z: 2,
              bX: false,
              bZ: 180,
              cV: [],
            },
            1234: {
              aU: 8,
              G: "#FFF",
              c: 211,
              aV: 8,
              r: "inline",
              d: 28,
              s: "Montserrat",
              X: 0,
              t: 10,
              Y: 12,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "500",
              i: "address",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">LEKARNA ILIRSKA BISTRICA\nGregor\u010di\u010deva cesta 8 6250 Ilirska Bistrica\n</div>',
              bF: "1230",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 3,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 48,
              b: -3,
            },
            1246: {
              h: "1072",
              p: "no-repeat",
              x: "visible",
              a: 221,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "1243",
              z: 9,
              dB: "img",
              d: 87,
              k: "div",
              cQ: 0.6,
              e: 0,
              c: 77,
              cR: 0.6,
            },
            1258: {
              x: "hidden",
              tY: 0.5,
              a: 9,
              b: 0,
              j: "absolute",
              r: "inline",
              z: 1,
              k: "div",
              bF: "1256",
              d: 110,
              c: 50,
              e: 0.65707721,
              tX: 0.5,
            },
            1230: {
              x: "visible",
              bF: "1229",
              k: "div",
              c: 320,
              d: 52,
              z: 4,
              a: 0,
              bS: 383,
              j: "absolute",
              b: 10,
            },
            1242: {
              aD: {
                a: [{ b: "640", p: 8, z: false, symbolOid: "2", J: true }],
              },
              x: "hidden",
              a: 0,
              bS: 383,
              b: 0,
              j: "absolute",
              z: 17,
              k: "div",
              c: 320,
              d: 480,
              cQ: 1,
              aC: {
                a: [
                  {
                    b: "kTimelineDefaultIdentifier",
                    p: 8,
                    z: true,
                    symbolOid: "2",
                    J: false,
                  },
                ],
              },
              cR: 1,
            },
            1254: {
              x: "visible",
              a: 2,
              bS: 375,
              b: 3,
              j: "absolute",
              bF: "1253",
              z: 2,
              k: "div",
              c: 315,
              d: 477,
              cQ: 1,
              cR: 1,
            },
            1250: {
              h: "1074",
              p: "no-repeat",
              x: "visible",
              a: 221,
              q: "100% 100%",
              b: 7,
              j: "absolute",
              r: "inline",
              z: 8,
              bF: "1243",
              dB: "img",
              d: 216.159,
              k: "div",
              c: 320,
              e: 0,
            },
            1219: {
              c: 320,
              bS: 319,
              d: 53,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#4E2C1D",
              L: "Solid",
              M: 0,
              bF: "1218",
              N: 0,
              A: "#ECECEC",
              j: "absolute",
              x: "visible",
              B: "#ECECEC",
              P: 0,
              O: 0,
              C: "#ECECEC",
              z: 1,
              k: "div",
              D: "#ECECEC",
              aK: 0,
              a: 0,
              aL: 0,
              b: 0,
            },
            1227: {
              h: "1078",
              p: "no-repeat",
              x: "visible",
              a: 29,
              q: "100% 100%",
              b: 297,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "1220",
              dB: "img",
              d: 40,
              k: "div",
              c: 255,
              e: 0,
            },
            1239: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 3,
              r: "inline",
              a: 0,
              bS: 55,
              j: "absolute",
              b: 0,
            },
            1223: {
              x: "visible",
              cQ: 1,
              k: "div",
              cR: 1,
              c: 116,
              d: 30,
              z: 3,
              a: 0,
              bF: "1222",
              j: "absolute",
              b: 0,
            },
            1235: {
              c: 318,
              bS: 287,
              d: 51,
              r: "inline",
              cY: "0",
              e: 0,
              J: "Solid",
              I: "Solid",
              K: "Solid",
              g: "#00FDFF",
              L: "Solid",
              aP: "pointer",
              M: 1,
              w: "",
              N: 1,
              A: "#B3B3B3",
              j: "absolute",
              x: "visible",
              B: "#B3B3B3",
              P: 1,
              O: 1,
              C: "#B3B3B3",
              z: 74,
              dB: "button",
              D: "#B3B3B3",
              aA: {
                a: [
                  { p: 4, h: "118" },
                  { p: 4, h: "904" },
                ],
              },
              k: "div",
              a: 0,
              b: 427,
            },
            1247: {
              x: "visible",
              k: "div",
              c: 95,
              d: 42,
              z: 4,
              e: 0,
              a: 56,
              j: "absolute",
              bF: "1243",
              b: 42,
            },
            1259: {
              h: "1131",
              p: "no-repeat",
              x: "visible",
              tY: 0.5,
              q: "100% 100%",
              b: -30,
              a: -38,
              r: "inline",
              j: "absolute",
              bF: "1258",
              z: 1,
              d: 165,
              dB: "img",
              k: "div",
              c: 125,
              tX: 0.5,
            },
            1231: {
              cN: "none",
              x: "visible",
              a: 11,
              cA: false,
              b: 8,
              j: "absolute",
              r: "inline",
              c: 43,
              k: "div",
              z: 1,
              d: 38,
              bF: "1230",
              cQ: 1,
              aP: "auto",
              bY: 1,
              bZ: 180,
              bX: false,
              cR: 1,
              cV: [],
            },
            1243: {
              x: "visible",
              k: "div",
              c: 320,
              d: 292,
              z: 15,
              r: "inline",
              a: -2,
              j: "absolute",
              bF: "1242",
              b: 89,
            },
            1255: {
              x: "visible",
              tY: 0.09,
              a: 182,
              b: -36,
              j: "absolute",
              bF: "1254",
              c: 183,
              k: "div",
              z: 1,
              d: 174.5,
              e: 1,
              f: 25,
              tX: 0.89,
            },
            1251: {
              x: "visible",
              k: "div",
              c: 320,
              d: 74,
              z: 27,
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
          },
        },
      ],
      {},
      h,
      {
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        y: { p: 0, q: [[0, 0, 0.445, 0.05, 0.55, 0.95, 1, 1]] },
        l: { p: 0, q: [[0, 0, 0.755, 0.05, 0.855, 0.06, 1, 1]] },
        h: { p: 0, q: [[0, 0, 0.175, 0.885, 0.32, 1.25, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
        w: { p: 0, q: [[0, 0, 0.77, 0, 0.175, 1, 1, 1]] },
        j: { p: 0, q: [[0, 0, 0.55, 0.085, 0.68, 0.53, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
