//	HYPE.documents["La_Roche_Posay_320x480_Tiner_Woman_adaptive copy"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/LaRochePosayWoman",
      f = "La_Roche_Posay_320x480_Tiner_Woman_adaptive copy",
      g = "larocheposay320x480tinerwomanadaptivecopy_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/larocheposay320x480tinerwomanadaptivecopy_hype_generated_script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "blendmodes",
        source:
          "function(hypeDocument, element, event) {\t\n\tvar blendmodes = ['color', 'color-burn', 'color-dodge', 'darken', 'difference', 'exclusion', 'hard-light', 'hue', 'lighten', 'luminosity', 'multiply', 'normal', 'overlay', 'saturation', 'screen', 'soft-light'];\n\twhile (blendmodes.length) {\n\t\tvar blendmode = blendmodes.pop();\n\t\tvar nodes = element.querySelectorAll('.blendmode-'+blendmode);\n\t\tfor (i = 0; i < nodes.length; ++i) {\n\t\t\tnodes[i].parentNode.style.mixBlendMode = blendmode;\n\t\t}\n\t}\n}",
        identifier: "7",
      },
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotosite();\n\n}",
        identifier: "39",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        "-2": { n: "blank.gif" },
        18: { p: 1, n: "Mask%20group.png", g: "185", t: "@1x" },
        10: { p: 1, n: "t3_2.svg", g: "28", t: "image/svg+xml" },
        11: { p: 1, n: "t_3_3.svg", g: "211", t: "image/svg+xml" },
        0: { p: 1, n: "logo_.svg", g: "16", t: "image/svg+xml" },
        12: { p: 1, n: "t2_1.svg", g: "34", t: "image/svg+xml" },
        1: { p: 1, n: "bg_sun.jpg", g: "22", t: "@1x" },
        2: { p: 1, n: "BUBBLES.jpg", g: "20", t: "@1x" },
        13: { p: 1, n: "t2_2.svg", g: "32", t: "image/svg+xml" },
        3: { p: 1, n: "logos.svg", g: "188", t: "image/svg+xml" },
        14: { p: 1, n: "hand_.png", g: "196", o: true, t: "@1x" },
        4: { p: 1, n: "dis.svg", g: "18", t: "image/svg+xml" },
        5: { p: 1, n: "buble_.png", g: "194", o: true, t: "@1x" },
        15: { p: 1, n: "hand__2x.png", g: "196", o: true, t: "@2x" },
        6: { p: 1, n: "buble__2x.png", g: "194", o: true, t: "@2x" },
        16: { p: 1, n: "t4.svg", g: "221", t: "image/svg+xml" },
        "-1": { n: "PIE.htc" },
        7: { p: 1, n: "t1_1.svg", g: "192", t: "image/svg+xml" },
        8: { p: 1, n: "t1_2.svg", g: "190", t: "image/svg+xml" },
        17: {
          n: "lrp-suncare-uvair_studioai_texturedropper.mp4",
          g: "228",
          t: "video/mp4",
        },
        9: { p: 1, n: "t3_1.svg", g: "30", t: "image/svg+xml" },
      },
      l,
      [
        "<style>\n    @font-face {\n        font-family: 'GothamProBold';\n        src:url('${Fonts}/futuratot-bol-webfont.ttf') format('truetype'),\n    }\n</style>",
        "<style>\n    @font-face {\n        font-family: 'Gotham';\n        src: url('${Fonts}/futuratot-bol-webfont.eot?#iefix') format('embedded-opentype'),\n                }\n</style>",
      ],
      e,
      [{ n: "Untitled Scene", o: "1", X: [0] }],
      [
        {
          o: "3",
          A: { a: [{ p: 4, h: "7" }] },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: { 230: { V: { "Main Timeline": "268" }, W: "268", n: "Symbol" } },
          T: {
            153: {
              q: false,
              z: 6,
              i: "153",
              n: "pulse",
              a: [
                {
                  f: "c",
                  p: 2,
                  y: 6,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "153", p: 3, z: false, symbolOid: "2" }] },
                  o: "153",
                },
              ],
              f: 30,
              b: [],
            },
            268: {
              b: [],
              c: "230",
              q: false,
              z: 5.03,
              i: "268",
              n: "Main Timeline",
              a: [{ y: 0, p: 1, i: "Video Track", z: 5.03, o: "254", f: "c" }],
              s: "230",
              f: 30,
            },
            kTimelineDefaultIdentifier: {
              j: {
                3: [
                  [387, 275, 387, 275, 366, 221, 321, 249],
                  [321, 249, 247, 295, 160, 196, 160, 196],
                ],
                1: [[214.25, 311, 214.25, 311, 214, 311, 214, 311]],
                2: [
                  [214, 311, 214, 311, 282, 333, 321, 324],
                  [321, 324, 368, 315, 387, 275, 387, 275],
                ],
                0: [
                  [223, 422, 223, 422, 241, 400, 235, 379],
                  [235, 379, 229, 358, 197, 353, 197, 340],
                  [197, 340, 197, 319, 214, 311, 214, 311],
                ],
              },
              q: false,
              z: 18.14,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "262" },
                { f: "c", y: 0, z: 1, i: "a", e: 20, s: -270, o: "262" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "262" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "252" },
                { f: "p", y: 0, z: 1, i: "b", e: 42, s: 131, o: "252" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "241" },
                { f: "c", y: 0, z: 2.12, i: "e", e: 1, s: 0, o: "253" },
                { f: "c", y: 0, z: 2.12, i: "cQ", e: 0.6, s: 0.4, o: "253" },
                { f: "c", y: 0, z: 2.12, i: "cR", e: 0.6, s: 0.4, o: "253" },
                {
                  o: "253",
                  y: 0,
                  z: 2.12,
                  i: "a",
                  e: 102.75,
                  a: "0",
                  f: "p",
                  s: 111.75,
                },
                {
                  o: "253",
                  y: 0,
                  z: 2.12,
                  i: "b",
                  e: 180,
                  a: "0",
                  f: "p",
                  s: 291,
                },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "262" },
                { y: 0, i: "b", s: 73, z: 0, o: "262", f: "c" },
                {
                  f: "c",
                  y: 0,
                  z: 1.16,
                  i: "cQ",
                  e: 1.05047211,
                  s: 0.85047211,
                  o: "238",
                },
                {
                  f: "c",
                  y: 0,
                  z: 1.16,
                  i: "cR",
                  e: 1.05047211,
                  s: 0.85047211,
                  o: "238",
                },
                { f: "c", y: 0, z: 1.16, i: "a", e: 84, s: 320, o: "238" },
                { f: "c", y: 0, z: 1, i: "e", e: 1, s: 0, o: "240" },
                { f: "p", y: 0, z: 1.16, i: "b", e: 158, s: 158, o: "238" },
                { f: "c", y: 0, z: 1.16, i: "e", e: 1, s: 0, o: "238" },
                { f: "c", y: 1, z: 2.17, i: "e", e: 1, s: 1, o: "241" },
                { f: "c", y: 1, z: 2, i: "cQ", e: 1, s: 1, o: "262" },
                { f: "c", y: 1, z: 2, i: "cR", e: 1, s: 1, o: "262" },
                { f: "c", y: 1, z: 2, i: "a", e: 20, s: 20, o: "262" },
                { y: 1, i: "b", s: 42, z: 0, o: "252", f: "c" },
                { f: "c", y: 1, z: 2.17, i: "e", e: 1, s: 1, o: "252" },
                { f: "c", y: 1, z: 1, i: "e", e: 1, s: 0, o: "247" },
                { f: "c", y: 1, z: 2, i: "e", e: 1, s: 1, o: "262" },
                { f: "c", y: 1, z: 2.17, i: "e", e: 1, s: 1, o: "240" },
                {
                  f: "c",
                  y: 1.16,
                  z: 1.22,
                  i: "cQ",
                  e: 1.05047211,
                  s: 1.05047211,
                  o: "238",
                },
                {
                  f: "c",
                  y: 1.16,
                  z: 1.22,
                  i: "cR",
                  e: 1.05047211,
                  s: 1.05047211,
                  o: "238",
                },
                { f: "c", y: 1.16, z: 1.22, i: "a", e: 84, s: 84, o: "238" },
                { f: "c", y: 1.16, z: 1.22, i: "b", e: 158, s: 158, o: "238" },
                { f: "c", y: 1.16, z: 1.22, i: "e", e: 1, s: 1, o: "238" },
                { f: "c", y: 2, z: 2.11, i: "e", e: 1, s: 1, o: "247" },
                { f: "c", y: 2.12, z: 2.1, i: "cQ", e: 0.6, s: 0.6, o: "253" },
                { f: "c", y: 2.12, z: 2.1, i: "cR", e: 0.6, s: 0.6, o: "253" },
                {
                  o: "253",
                  y: 2.12,
                  z: 1.05,
                  i: "a",
                  e: 102.75,
                  a: "1",
                  f: "c",
                  s: 103,
                },
                {
                  o: "253",
                  y: 2.12,
                  z: 1.05,
                  i: "b",
                  e: 180,
                  a: "1",
                  f: "c",
                  s: 180,
                },
                { f: "c", y: 2.12, z: 1.05, i: "e", e: 1, s: 1, o: "253" },
                { f: "c", y: 3, z: 1.08, i: "cQ", e: 0.8, s: 1, o: "262" },
                { f: "c", y: 3, z: 1.08, i: "cR", e: 0.8, s: 1, o: "262" },
                { f: "c", y: 3, z: 1.08, i: "a", e: 144, s: 20, o: "262" },
                { f: "c", y: 3, z: 1.08, i: "e", e: 0, s: 1, o: "262" },
                {
                  f: "c",
                  y: 3.08,
                  z: 1.08,
                  i: "cQ",
                  e: 1.05047211,
                  s: 1.05047211,
                  o: "238",
                },
                {
                  f: "c",
                  y: 3.08,
                  z: 1.08,
                  i: "cR",
                  e: 1.05047211,
                  s: 1.05047211,
                  o: "238",
                },
                { f: "c", y: 3.08, z: 1.08, i: "a", e: 340, s: 84, o: "238" },
                { f: "c", y: 3.08, z: 1.08, i: "b", e: 158, s: 158, o: "238" },
                { f: "c", y: 3.08, z: 1.08, i: "e", e: 0, s: 1, o: "238" },
                { f: "c", y: 3.17, z: 2, i: "e", e: 1, s: 0, o: "257" },
                { f: "c", y: 3.17, z: 1, i: "e", e: 0, s: 1, o: "241" },
                {
                  o: "253",
                  y: 3.17,
                  z: 1.05,
                  i: "b",
                  e: 144,
                  a: "2",
                  f: "c",
                  s: 180,
                },
                {
                  o: "253",
                  y: 3.17,
                  z: 1.05,
                  i: "a",
                  e: 275.75,
                  a: "2",
                  f: "c",
                  s: 102.75,
                },
                { f: "q", y: 3.17, z: 2, i: "cR", e: 1, s: 1.3, o: "257" },
                { f: "q", y: 3.17, z: 2, i: "cQ", e: 1, s: 1.3, o: "257" },
                { f: "c", y: 3.17, z: 2, i: "e", e: 0, s: 1, o: "252" },
                { f: "c", y: 3.17, z: 1.05, i: "e", e: 0, s: 1, o: "253" },
                { f: "c", y: 3.17, z: 1, i: "e", e: 0, s: 1, o: "240" },
                { f: "c", y: 3.27, z: 1, i: "e", e: 1, s: 0, o: "242" },
                { y: 4.08, i: "cQ", s: 0.8, z: 0, o: "262", f: "c" },
                { y: 4.08, i: "cR", s: 0.8, z: 0, o: "262", f: "c" },
                { y: 4.08, i: "a", s: 144, z: 0, o: "262", f: "c" },
                { y: 4.08, i: "e", s: 0, z: 0, o: "262", f: "c" },
                { f: "c", y: 4.11, z: 1.08, i: "b", e: -32, s: -32, o: "266" },
                { f: "c", y: 4.11, z: 1.08, i: "cR", e: 1, s: 0.8, o: "266" },
                { f: "c", y: 4.11, z: 1.08, i: "a", e: 29, s: -204, o: "266" },
                { f: "c", y: 4.11, z: 1.08, i: "cQ", e: 1, s: 0.8, o: "266" },
                { f: "c", y: 4.11, z: 1.08, i: "e", e: 1, s: 0, o: "266" },
                { f: "c", y: 4.11, z: 1, i: "e", e: 0, s: 1, o: "247" },
                { y: 4.16, i: "b", s: 158, z: 0, o: "238", f: "c" },
                { y: 4.16, i: "cQ", s: 1.05047211, z: 0, o: "238", f: "c" },
                { y: 4.16, i: "cR", s: 1.05047211, z: 0, o: "238", f: "c" },
                { y: 4.16, i: "a", s: 340, z: 0, o: "238", f: "c" },
                { y: 4.16, i: "e", s: 0, z: 0, o: "238", f: "c" },
                { y: 4.17, i: "e", s: 0, z: 0, o: "241", f: "c" },
                { y: 4.17, i: "e", s: 0, z: 0, o: "240", f: "c" },
                { f: "c", y: 4.19, z: 1.08, i: "b", e: 35, s: 35, o: "267" },
                { f: "c", y: 4.19, z: 1.08, i: "cR", e: 1, s: 0.8, o: "267" },
                { f: "c", y: 4.19, z: 1.08, i: "a", e: 28, s: 301, o: "267" },
                { f: "c", y: 4.19, z: 1.08, i: "cQ", e: 1, s: 0.8, o: "267" },
                { f: "c", y: 4.19, z: 1.08, i: "e", e: 1, s: 0, o: "267" },
                { y: 4.22, i: "b", s: 144, z: 0, o: "253", f: "c" },
                { f: "q", y: 4.22, z: 2.01, i: "cR", e: 0.9, s: 0.6, o: "253" },
                { f: "q", y: 4.22, z: 2.01, i: "cQ", e: 0.9, s: 0.6, o: "253" },
                { y: 4.22, i: "a", s: 275.75, z: 0, o: "253", f: "c" },
                {
                  o: "253",
                  y: 4.22,
                  z: 2.01,
                  i: "b",
                  e: 65,
                  a: "3",
                  f: "q",
                  s: 144,
                },
                {
                  o: "253",
                  y: 4.22,
                  z: 2.01,
                  i: "a",
                  e: 48.75,
                  a: "3",
                  f: "q",
                  s: 275.75,
                },
                { f: "c", y: 4.22, z: 0, i: "e", e: 0, s: 0, o: "253" },
                { f: "q", y: 4.22, z: 2.01, i: "e", e: 1, s: 0, o: "253" },
                { y: 4.27, i: "e", s: 1, z: 0, o: "242", f: "c" },
                { y: 5.11, i: "e", s: 0, z: 0, o: "247", f: "c" },
                { f: "c", y: 5.17, z: 11.13, i: "e", e: 1, s: 1, o: "257" },
                { y: 5.17, i: "cR", s: 1, z: 0, o: "257", f: "c" },
                { y: 5.17, i: "cQ", s: 1, z: 0, o: "257", f: "c" },
                { y: 5.17, i: "e", s: 0, z: 0, o: "252", f: "c" },
                { y: 5.19, i: "b", s: -32, z: 0, o: "266", f: "c" },
                { y: 5.19, i: "a", s: 29, z: 0, o: "266", f: "c" },
                { f: "c", y: 5.19, z: 2, i: "cR", e: 1, s: 1, o: "266" },
                { f: "c", y: 5.19, z: 2, i: "cQ", e: 1, s: 1, o: "266" },
                { f: "c", y: 5.19, z: 2, i: "e", e: 1, s: 1, o: "266" },
                { y: 5.27, i: "b", s: 35, z: 0, o: "267", f: "c" },
                { f: "c", y: 5.27, z: 2.02, i: "cR", e: 1, s: 1, o: "267" },
                { y: 5.27, i: "a", s: 28, z: 0, o: "267", f: "c" },
                { f: "c", y: 5.27, z: 2.02, i: "cQ", e: 1, s: 1, o: "267" },
                { f: "c", y: 5.27, z: 2.02, i: "e", e: 1, s: 1, o: "267" },
                { y: 6.23, i: "b", s: 65, z: 0, o: "253", f: "c" },
                { y: 6.23, i: "cR", s: 0.9, z: 0, o: "253", f: "c" },
                { y: 6.23, i: "cQ", s: 0.9, z: 0, o: "253", f: "c" },
                { y: 6.23, i: "a", s: 48.75, z: 0, o: "253", f: "c" },
                { f: "c", y: 6.23, z: 0.16, i: "e", e: 1, s: 1, o: "253" },
                { f: "c", y: 7.09, z: 1.21, i: "e", e: 0, s: 1, o: "253" },
                { f: "v", y: 7.19, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "266" },
                { f: "v", y: 7.19, z: 1.1, i: "cR", e: 0.8, s: 1, o: "266" },
                { f: "c", y: 7.19, z: 1.1, i: "e", e: 0, s: 1, o: "266" },
                { f: "c", y: 7.2, z: 2, i: "e", e: 1, s: 0, o: "258" },
                { f: "q", y: 7.2, z: 2, i: "cQ", e: 1, s: 1.3, o: "258" },
                { f: "q", y: 7.2, z: 2, i: "cR", e: 1, s: 1.3, o: "258" },
                {
                  f: "h",
                  y: 7.29,
                  z: 1.2,
                  i: "cQ",
                  e: 1,
                  s: 0.79846006,
                  o: "263",
                },
                {
                  f: "h",
                  y: 7.29,
                  z: 1.2,
                  i: "cR",
                  e: 1,
                  s: 0.79846006,
                  o: "263",
                },
                { f: "v", y: 7.29, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "267" },
                { f: "v", y: 7.29, z: 1.1, i: "cR", e: 0.8, s: 1, o: "267" },
                { f: "c", y: 7.29, z: 1.2, i: "e", e: 1, s: 0, o: "263" },
                { f: "c", y: 7.29, z: 1.1, i: "e", e: 0, s: 1, o: "267" },
                { f: "q", y: 8.19, z: 3.02, i: "b", e: -108, s: -54, o: "255" },
                {
                  f: "h",
                  y: 8.19,
                  z: 1.2,
                  i: "cQ",
                  e: 1,
                  s: 0.79887806,
                  o: "244",
                },
                {
                  f: "h",
                  y: 8.19,
                  z: 1.2,
                  i: "cR",
                  e: 1,
                  s: 0.79887806,
                  o: "244",
                },
                { f: "q", y: 8.19, z: 1.25, i: "e", e: 1, s: 0, o: "255" },
                { f: "c", y: 8.19, z: 1.2, i: "e", e: 1, s: 0, o: "244" },
                { y: 8.29, i: "cQ", s: 0.8, z: 0, o: "266", f: "c" },
                { y: 8.29, i: "cR", s: 0.8, z: 0, o: "266", f: "c" },
                { y: 8.29, i: "e", s: 0, z: 0, o: "266", f: "c" },
                { y: 9, i: "e", s: 0, z: 0, o: "253", f: "c" },
                {
                  f: "h",
                  y: 9.05,
                  z: 1.2,
                  i: "cR",
                  e: 1,
                  s: 0.79453182,
                  o: "245",
                },
                {
                  f: "h",
                  y: 9.05,
                  z: 1.2,
                  i: "cQ",
                  e: 1,
                  s: 0.79453182,
                  o: "245",
                },
                { f: "c", y: 9.05, z: 1.2, i: "e", e: 1, s: 0, o: "245" },
                { y: 9.09, i: "cQ", s: 0.8, z: 0, o: "267", f: "c" },
                { y: 9.09, i: "cR", s: 0.8, z: 0, o: "267", f: "c" },
                { y: 9.09, i: "e", s: 0, z: 0, o: "267", f: "c" },
                { f: "c", y: 9.19, z: 2.02, i: "cQ", e: 1, s: 1, o: "263" },
                { f: "c", y: 9.19, z: 2.02, i: "cR", e: 1, s: 1, o: "263" },
                { f: "c", y: 9.19, z: 2.02, i: "e", e: 1, s: 1, o: "263" },
                { y: 9.2, i: "e", s: 1, z: 0, o: "258", f: "c" },
                { y: 9.2, i: "cQ", s: 1, z: 0, o: "258", f: "c" },
                { y: 9.2, i: "cR", s: 1, z: 0, o: "258", f: "c" },
                { f: "c", y: 10.09, z: 1.21, i: "cQ", e: 1, s: 1, o: "244" },
                { f: "c", y: 10.09, z: 1.21, i: "cR", e: 1, s: 1, o: "244" },
                { f: "c", y: 10.09, z: 1.21, i: "e", e: 1, s: 1, o: "244" },
                { f: "c", y: 10.14, z: 1.23, i: "e", e: 1, s: 1, o: "255" },
                { f: "c", y: 10.25, z: 1.21, i: "cR", e: 1, s: 1, o: "245" },
                { f: "c", y: 10.25, z: 1.21, i: "cQ", e: 1, s: 1, o: "245" },
                { f: "c", y: 10.25, z: 1.21, i: "e", e: 1, s: 1, o: "245" },
                {
                  f: "c",
                  y: 11.21,
                  z: 0.17,
                  i: "b",
                  e: -108,
                  s: -108,
                  o: "255",
                },
                { f: "v", y: 11.21, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "263" },
                { f: "v", y: 11.21, z: 1.1, i: "cR", e: 0.8, s: 1, o: "263" },
                { f: "c", y: 11.21, z: 1.1, i: "e", e: 0, s: 1, o: "263" },
                {
                  f: "v",
                  y: 12,
                  z: 1.1,
                  i: "cR",
                  e: 0.80434623,
                  s: 1,
                  o: "244",
                },
                {
                  f: "v",
                  y: 12,
                  z: 1.1,
                  i: "cQ",
                  e: 0.80434623,
                  s: 1,
                  o: "244",
                },
                { f: "c", y: 12, z: 1.1, i: "e", e: 0, s: 1, o: "244" },
                { f: "c", y: 12.07, z: 1.05, i: "e", e: 0, s: 1, o: "255" },
                {
                  f: "w",
                  y: 12.08,
                  z: 2.07,
                  i: "b",
                  e: -54,
                  s: -108,
                  o: "255",
                },
                { f: "v", y: 12.16, z: 1.1, i: "cR", e: 0.8, s: 1, o: "245" },
                { f: "v", y: 12.16, z: 1.1, i: "cQ", e: 0.8, s: 1, o: "245" },
                { f: "c", y: 12.16, z: 1.1, i: "e", e: 0, s: 1, o: "245" },
                { y: 13.01, i: "cQ", s: 0.8, z: 0, o: "263", f: "c" },
                { y: 13.01, i: "cR", s: 0.8, z: 0, o: "263", f: "c" },
                { y: 13.01, i: "e", s: 0, z: 0, o: "263", f: "c" },
                { f: "c", y: 13.1, z: 1.2, i: "e", e: 1, s: 0, o: "230" },
                { f: "c", y: 13.1, z: 1.15, i: "e", e: 1, s: 0, o: "265" },
                { f: "c", y: 13.1, z: 1.15, i: "b", e: -21, s: 17, o: "265" },
                { f: "c", y: 13.1, z: 1.15, i: "cQ", e: 1, s: 0.7, o: "265" },
                { f: "c", y: 13.1, z: 1.15, i: "cR", e: 1, s: 0.7, o: "265" },
                { y: 13.1, i: "cQ", s: 0.80434623, z: 0, o: "244", f: "c" },
                { y: 13.1, i: "cR", s: 0.80434623, z: 0, o: "244", f: "c" },
                { y: 13.1, i: "e", s: 0, z: 0, o: "244", f: "c" },
                { y: 13.12, i: "e", s: 0, z: 0, o: "255", f: "c" },
                { y: 13.26, i: "cR", s: 0.8, z: 0, o: "245", f: "c" },
                { y: 13.26, i: "cQ", s: 0.8, z: 0, o: "245", f: "c" },
                { y: 13.26, i: "e", s: 0, z: 0, o: "245", f: "c" },
                { y: 14.15, i: "b", s: -54, z: 0, o: "255", f: "q" },
                { f: "c", y: 14.25, z: 2.05, i: "e", e: 1, s: 1, o: "265" },
                { y: 14.25, i: "b", s: -21, z: 0, o: "265", f: "c" },
                { y: 14.25, i: "cQ", s: 1, z: 0, o: "265", f: "c" },
                { y: 14.25, i: "cR", s: 1, z: 0, o: "265", f: "c" },
                { f: "c", y: 15, z: 2, i: "e", e: 1, s: 1, o: "230" },
                { f: "c", y: 17, z: 1.14, i: "e", e: 0, s: 1, o: "265" },
                { f: "c", y: 17, z: 1.14, i: "e", e: 0, s: 1, o: "230" },
                { f: "c", y: 17, z: 1.14, i: "e", e: 0, s: 1, o: "257" },
                {
                  f: "c",
                  p: 2,
                  y: 18.11,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      {
                        b: "kTimelineDefaultIdentifier",
                        p: 3,
                        z: false,
                        symbolOid: "2",
                      },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 18.14, i: "e", s: 0, z: 0, o: "265", f: "c" },
                { y: 18.14, i: "e", s: 0, z: 0, o: "230", f: "c" },
                { y: 18.14, i: "e", s: 0, z: 0, o: "257", f: "c" },
              ],
              f: 30,
              b: [
                {
                  D: 5.03,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 13.1,
                  b: "268",
                },
              ],
            },
          },
          bZ: 180,
          O: [
            "241",
            "254",
            "230",
            "255",
            "257",
            "258",
            "260",
            "248",
            "236",
            "261",
            "240",
            "239",
            "251",
            "250",
            "249",
            "259",
            "256",
            "242",
            "252",
            "263",
            "237",
            "262",
            "238",
            "253",
            "244",
            "266",
            "264",
            "243",
            "246",
            "245",
            "265",
            "247",
            "267",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            239: {
              x: "visible",
              k: "div",
              c: 320,
              d: 129,
              z: 29,
              r: "inline",
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            250: {
              x: "visible",
              bF: "249",
              k: "div",
              c: 318,
              d: 480,
              z: 10,
              a: 0,
              bS: 127,
              j: "absolute",
              b: 1,
            },
            258: {
              h: "22",
              p: "no-repeat",
              x: "visible",
              a: -9,
              q: "100% 100%",
              b: -15,
              j: "absolute",
              r: "inline",
              cP: "blendmode-soft-light",
              bF: "256",
              z: 3,
              d: 507,
              dB: "img",
              cQ: 1.3,
              e: 0,
              k: "div",
              c: 338,
              cR: 1.3,
            },
            245: {
              h: "211",
              p: "no-repeat",
              x: "visible",
              a: 200,
              q: "100% 100%",
              b: 1,
              j: "absolute",
              r: "inline",
              bF: "243",
              z: 6,
              dB: "img",
              d: 7,
              k: "div",
              cQ: 0.79453182,
              e: 0,
              c: 98,
              cR: 0.79453182,
            },
            264: {
              x: "visible",
              k: "div",
              c: 320,
              d: 107,
              z: 24,
              r: "inline",
              a: 0,
              bS: 350,
              j: "absolute",
              b: 373,
            },
            251: {
              x: "visible",
              bF: "250",
              k: "div",
              c: 318,
              d: 480,
              z: 1,
              a: 0,
              bS: 447,
              j: "absolute",
              b: 0,
            },
            259: {
              c: 320,
              bS: 319,
              d: 480,
              I: "None",
              e: 0.85,
              J: "None",
              K: "None",
              L: "None",
              M: 0,
              bF: "256",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              l: 0,
              D: "#D8DDE4",
              m: "#51B1E6",
              k: "div",
              n: "#007CC1",
              a: 0,
              b: 0,
            },
            246: {
              x: "visible",
              k: "div",
              c: 320,
              d: 107,
              z: 22,
              r: "inline",
              a: 0,
              bS: 351,
              j: "absolute",
              b: 373,
            },
            265: {
              h: "221",
              p: "no-repeat",
              x: "visible",
              a: 21,
              q: "100% 100%",
              b: 17,
              j: "absolute",
              r: "inline",
              bF: "264",
              z: 10,
              dB: "img",
              d: 94,
              k: "div",
              cQ: 0.7,
              e: 0,
              c: 200,
              cR: 0.7,
            },
            252: {
              h: "185",
              p: "no-repeat",
              x: "visible",
              a: -336,
              q: "100% 100%",
              bS: 191,
              j: "absolute",
              bF: "251",
              r: "inline",
              b: 131,
              z: 1,
              d: 471,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 700,
              cR: 1,
            },
            247: {
              h: "18",
              p: "no-repeat",
              x: "visible",
              a: 72,
              q: "100% 100%",
              b: 34,
              j: "absolute",
              r: "inline",
              bF: "246",
              z: 2,
              dB: "img",
              d: 53,
              k: "div",
              cQ: 1,
              e: 0,
              c: 241,
              cR: 1,
            },
            266: {
              p: "no-repeat",
              c: 168,
              q: "100% 100%",
              d: 55,
              r: "inline",
              cQ: 0.8,
              s: "GothamProBold",
              e: 0,
              cR: 0.8,
              u: "normal",
              h: "34",
              v: "normal",
              w: "",
              bF: "264",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 13,
              a: -204,
              b: -32,
            },
            253: {
              h: "194",
              p: "no-repeat",
              tY: 0.5,
              a: 111.75,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "249",
              b: 291,
              z: 12,
              d: 262,
              dB: "img",
              cQ: 0.4,
              e: 0,
              k: "div",
              c: 222.5,
              cR: 0.4,
              tX: 0.5,
            },
            240: {
              h: "188",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 2,
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "239",
              dB: "img",
              d: 55,
              k: "div",
              c: 320,
              e: 0,
            },
            248: {
              c: 320,
              bS: 319,
              d: 480,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              k: "div",
              O: 1,
              C: "#D8DDE4",
              z: 38,
              P: 1,
              D: "#D8DDE4",
              a: -1,
              b: -1,
            },
            267: {
              h: "32",
              p: "no-repeat",
              x: "visible",
              a: 301,
              q: "100% 100%",
              b: 35,
              j: "absolute",
              r: "inline",
              bF: "264",
              z: 12,
              dB: "img",
              d: 12,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 263,
              cR: 0.8,
            },
            254: {
              aR: "0",
              x: "visible",
              bE: "228",
              a: 0,
              b: 0,
              j: "absolute",
              bF: "230",
              z: 11,
              aO: false,
              k: "video",
              d: 603,
              c: 340,
              aQ: "0",
              aH: "1",
            },
            241: {
              c: 952,
              d: 166,
              r: "inline",
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#FFF",
              L: "Solid",
              M: 0,
              bF: "239",
              N: 0,
              A: "#D8DDE4",
              x: "visible",
              j: "absolute",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 5,
              k: "div",
              D: "#D8DDE4",
              a: -316,
              b: -105,
            },
            249: {
              x: "visible",
              bS: 383,
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              z: 18,
              k: "div",
              c: 320,
              d: 480,
              cQ: 1,
              e: 1,
              cR: 1,
            },
            260: {
              c: 320,
              bS: 319,
              d: 480,
              I: "None",
              e: 0,
              J: "None",
              K: "None",
              g: "#E8EBED",
              L: "None",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 39,
              dB: "button",
              D: "#D8DDE4",
              aA: { a: [{ p: 4, h: "39" }] },
              k: "div",
              a: 0,
              b: 0,
            },
            236: {
              x: "visible",
              k: "div",
              c: 320,
              d: 145,
              z: 31,
              r: "inline",
              a: 0,
              bS: 371,
              j: "absolute",
              b: 0,
            },
            255: {
              h: "196",
              p: "no-repeat",
              x: "visible",
              a: -42,
              q: "100% 100%",
              b: -54,
              j: "absolute",
              r: "inline",
              bF: "249",
              z: 13,
              dB: "img",
              d: 595,
              k: "div",
              cQ: 1,
              e: 0,
              c: 403,
              cR: 1,
            },
            242: {
              h: "16",
              p: "no-repeat",
              x: "visible",
              a: 106,
              q: "100% 100%",
              b: 15,
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "239",
              dB: "img",
              d: 29,
              k: "div",
              c: 110,
              e: 0,
            },
            261: {
              x: "visible",
              k: "div",
              c: 320,
              d: 145,
              z: 30,
              r: "inline",
              a: 0,
              bS: 374,
              j: "absolute",
              b: 0,
            },
            237: {
              x: "visible",
              a: -273,
              bS: 356,
              b: 65,
              j: "absolute",
              bF: "236",
              z: 2,
              k: "div",
              c: 303,
              d: 83,
              cQ: 0.8,
              e: 0,
              cR: 0.8,
            },
            256: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 1,
              a: 0,
              bS: 447,
              j: "absolute",
              b: 0,
            },
            243: {
              x: "visible",
              k: "div",
              c: 320,
              d: 107,
              z: 23,
              r: "inline",
              a: 0,
              bS: 347,
              j: "absolute",
              b: 373,
            },
            262: {
              h: "192",
              p: "no-repeat",
              x: "visible",
              a: -270,
              q: "100% 100%",
              b: 73,
              j: "absolute",
              r: "inline",
              bF: "261",
              z: 4,
              dB: "img",
              d: 63,
              k: "div",
              cQ: 0.8,
              e: 0,
              c: 244,
              cR: 0.8,
            },
            230: {
              cS: true,
              x: "visible",
              a: -11,
              cA: false,
              b: -61,
              j: "absolute",
              bF: "249",
              c: 340,
              k: "div",
              z: 11,
              cL: "230",
              d: 603,
              bY: 1,
              e: 0,
              bZ: 180,
              cM: true,
              bX: false,
              cK: { a: [{ p: 3, b: "268", z: false }] },
              cV: [],
            },
            238: {
              h: "190",
              p: "no-repeat",
              x: "visible",
              a: 320,
              q: "100% 100%",
              b: 158,
              j: "absolute",
              r: "inline",
              bF: "236",
              z: 3,
              dB: "img",
              d: 61,
              k: "div",
              cQ: 0.85047211,
              e: 0,
              c: 189,
              cR: 0.85047211,
            },
            257: {
              h: "20",
              p: "no-repeat",
              x: "visible",
              a: -10,
              q: "100% 100%",
              b: -15,
              j: "absolute",
              r: "inline",
              cP: "blendmode-luminosity",
              bF: "256",
              z: 4,
              d: 509,
              dB: "img",
              cQ: 1.3,
              e: 0,
              k: "div",
              c: 339,
              cR: 1.3,
            },
            244: {
              h: "28",
              p: "no-repeat",
              x: "visible",
              a: 187,
              q: "100% 100%",
              b: -69,
              j: "absolute",
              r: "inline",
              bF: "243",
              z: 7,
              dB: "img",
              d: 30,
              k: "div",
              cQ: 0.79887806,
              e: 0,
              c: 111,
              cR: 0.79887806,
            },
            263: {
              h: "30",
              p: "no-repeat",
              x: "visible",
              a: 17,
              q: "100% 100%",
              b: 63,
              j: "absolute",
              r: "inline",
              bF: "261",
              z: 2,
              dB: "img",
              d: 57,
              k: "div",
              cQ: 0.79846006,
              e: 0,
              c: 249,
              cR: 0.79846006,
            },
          },
        },
      ],
      { 230: ["254"] },
      h,
      {
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        w: { p: 0, q: [[0, 0, 0.77, 0, 0.175, 1, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
        h: { p: 0, q: [[0, 0, 0.175, 0.885, 0.32, 1.25, 1, 1]] },
        v: { p: 0, q: [[0, 0, 0.455, 0.03, 0.515, 0.955, 1, 1]] },
      },
      null,
      false,
      true,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
