//	HYPE.documents["McDonalds_g_o_a_t_rich_media_geo_320x480_adaptive copy 3"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l =
        "../resources/McDonalds",
      f = "McDonalds_g_o_a_t_rich_media_geo_320x480_adaptive copy 3",
      g = "mcdonaldsgoatrichmediageo320x480adaptivecopy3_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/mcdonaldsgoatrichmediageo320x480adaptivecopy3_hype_generated_script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotosite();\n}",
        identifier: "9",
      },
      {
        name: "gotomap",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotomap();\n\n}",
        identifier: "747",
      },
      {
        name: "action1",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action1(); \n}",
        identifier: "749",
      },
      {
        name: "action2",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action2(); \n\t\n}",
        identifier: "750",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        "-2": { n: "blank.gif" },
        18: { p: 1, n: "1euro.png", g: "676", t: "@1x" },
        10: { p: 1, n: "a%202.png", g: "624", t: "@1x" },
        19: { p: 1, n: "products_2.png", g: "729", t: "@1x" },
        11: { p: 1, n: "icon_.svg", g: "62", t: "image/svg+xml" },
        0: { p: 1, n: "bg_.jpg", g: "563", t: "@1x" },
        12: { p: 1, n: "top_claim.png", g: "664", t: "@1x" },
        1: { p: 1, n: "button_.svg", g: "217", t: "image/svg+xml" },
        2: { p: 1, n: "toast%202.png", g: "604", t: "@1x" },
        13: { p: 1, n: "text_2.png", g: "666", t: "@1x" },
        3: { p: 1, n: "t%202.png", g: "606", t: "@1x" },
        14: { p: 1, n: "text_1.png", g: "668", t: "@1x" },
        4: { p: 1, n: "star_.png", g: "608", t: "@1x" },
        5: { p: 1, n: "o%202.png", g: "614", t: "@1x" },
        15: { p: 1, n: "price_2.png", g: "670", t: "@1x" },
        6: { p: 1, n: "logo_m.svg", g: "616", t: "image/svg+xml" },
        16: { p: 1, n: "price_1.png", g: "672", t: "@1x" },
        7: { p: 1, n: "g%202.png", g: "618", t: "@1x" },
        "-1": { n: "PIE.htc" },
        8: { p: 1, n: "fries%202.png", g: "620", t: "@1x" },
        17: { p: 1, n: "frame_.png", g: "674", t: "@1x" },
        9: { p: 1, n: "cookie%202.png", g: "622", t: "@1x" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "Untitled Scene", o: "548", X: [0] }],
      [
        {
          o: "550",
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: { 758: { V: { "Main Timeline": "803" }, W: "803", n: "icon" } },
          T: {
            597: {
              q: false,
              z: 2,
              i: "597",
              n: "button_",
              a: [
                {
                  f: "h",
                  y: 0,
                  z: 0.1,
                  i: "cR",
                  e: 0.9844078,
                  s: 1.0844078,
                  o: "801",
                },
                {
                  f: "h",
                  y: 0,
                  z: 0.1,
                  i: "cQ",
                  e: 0.9844078,
                  s: 1.0844078,
                  o: "801",
                },
                {
                  f: "c",
                  y: 0.1,
                  z: 0.1,
                  i: "cR",
                  e: 1.0844078,
                  s: 0.9844078,
                  o: "801",
                },
                {
                  f: "c",
                  y: 0.1,
                  z: 0.1,
                  i: "cQ",
                  e: 1.0844078,
                  s: 0.9844078,
                  o: "801",
                },
                { y: 0.2, i: "cR", s: 1.0844078, z: 0, o: "801", f: "c" },
                { y: 0.2, i: "cQ", s: 1.0844078, z: 0, o: "801", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "597", p: 3, z: false, symbolOid: "549" }] },
                  o: "597",
                },
              ],
              f: 30,
              b: [],
            },
            803: {
              c: "758",
              q: false,
              z: 3.15,
              i: "803",
              a: [
                { f: "y", y: 0, z: 1.15, i: "aY", e: 360, s: 0, o: "759" },
                { y: 1.15, i: "aY", s: 360, z: 0, o: "759", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "803", p: 3, z: false, symbolOid: "609" }] },
                  o: "803",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 8.15,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "w", y: 0, z: 0.15, i: "b", e: 0, s: 432, o: "753" },
                { f: "c", y: 0, z: 0.05, i: "e", e: 1, s: 0, o: "753" },
                { f: "h", y: 0, z: 0.15, i: "cQ", e: 1, s: 0.8, o: "753" },
                { f: "h", y: 0, z: 0.15, i: "cR", e: 1, s: 0.8, o: "753" },
                { f: "q", y: 0, z: 0.15, i: "b", e: 417, s: 461, o: "757" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 1, s: 0, o: "757" },
                { y: 0.05, i: "e", s: 1, z: 0, o: "753", f: "c" },
                { f: "h", y: 0.09, z: 0.07, i: "cR", e: 1, s: 1.75, o: "777" },
                { f: "h", y: 0.09, z: 0.07, i: "cQ", e: 1, s: 1.75, o: "777" },
                { f: "c", y: 0.09, z: 0.04, i: "e", e: 1, s: 0, o: "777" },
                { f: "c", y: 0.09, z: 0.01, i: "e", e: 1, s: 0, o: "800" },
                { y: 0.1, i: "e", s: 1, z: 0, o: "800", f: "c" },
                { f: "c", y: 0.13, z: 0.04, i: "e", e: 1, s: 0, o: "782" },
                { y: 0.13, i: "e", s: 1, z: 0, o: "777", f: "c" },
                { y: 0.15, i: "cQ", s: 1, z: 0, o: "753", f: "c" },
                { y: 0.15, i: "cR", s: 1, z: 0, o: "753", f: "c" },
                { y: 0.15, i: "b", s: 0, z: 0, o: "753", f: "c" },
                { y: 0.15, i: "b", s: 417, z: 0, o: "757", f: "c" },
                { y: 0.15, i: "e", s: 1, z: 0, o: "757", f: "c" },
                { f: "h", y: 0.16, z: 0.07, i: "cQ", e: 1, s: 1.75, o: "776" },
                { f: "h", y: 0.16, z: 0.07, i: "cR", e: 1, s: 1.75, o: "776" },
                { y: 0.16, i: "cR", s: 1, z: 0, o: "777", f: "c" },
                { y: 0.16, i: "cQ", s: 1, z: 0, o: "777", f: "c" },
                { f: "c", y: 0.16, z: 0.04, i: "e", e: 1, s: 0, o: "776" },
                { y: 0.17, i: "e", s: 1, z: 0, o: "782", f: "c" },
                { f: "c", y: 0.18, z: 0.04, i: "e", e: 1, s: 0, o: "785" },
                { f: "c", y: 0.19, z: 0.01, i: "e", e: 1, s: 0, o: "799" },
                { y: 0.2, i: "e", s: 1, z: 0, o: "776", f: "c" },
                { y: 0.2, i: "e", s: 1, z: 0, o: "799", f: "c" },
                { y: 0.22, i: "e", s: 1, z: 0, o: "785", f: "c" },
                { f: "h", y: 0.23, z: 0.07, i: "cQ", e: 1, s: 1.75, o: "775" },
                { f: "h", y: 0.23, z: 0.07, i: "cR", e: 1, s: 1.75, o: "775" },
                { y: 0.23, i: "cQ", s: 1, z: 0, o: "776", f: "c" },
                { y: 0.23, i: "cR", s: 1, z: 0, o: "776", f: "c" },
                { f: "c", y: 0.23, z: 0.04, i: "e", e: 1, s: 0, o: "783" },
                { f: "c", y: 0.23, z: 0.03, i: "e", e: 1, s: 0, o: "775" },
                { y: 0.26, i: "e", s: 1, z: 0, o: "775", f: "c" },
                { y: 0.27, i: "e", s: 1, z: 0, o: "783", f: "c" },
                { f: "c", y: 0.28, z: 0.04, i: "e", e: 1, s: 0, o: "784" },
                { f: "c", y: 0.28, z: 0.01, i: "e", e: 1, s: 0, o: "798" },
                { y: 0.29, i: "e", s: 1, z: 0, o: "798", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "775", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "775", f: "c" },
                { y: 1.02, i: "e", s: 1, z: 0, o: "784", f: "c" },
                { f: "c", y: 1.05, z: 0.01, i: "e", e: 1, s: 0, o: "797" },
                { y: 1.06, i: "e", s: 1, z: 0, o: "797", f: "c" },
                { f: "c", y: 1.07, z: 0.06, i: "e", e: 1, s: 0, o: "764" },
                { f: "c", y: 1.12, z: 0.06, i: "e", e: 1, s: 0, o: "802" },
                { y: 1.13, i: "e", s: 1, z: 0, o: "764", f: "c" },
                { y: 1.18, i: "e", s: 1, z: 0, o: "802", f: "c" },
                {
                  f: "h",
                  y: 1.23,
                  z: 0.07,
                  i: "cR",
                  e: 1.0844078,
                  s: 0.9844078,
                  o: "801",
                },
                {
                  f: "h",
                  y: 1.23,
                  z: 0.07,
                  i: "cQ",
                  e: 1.0844078,
                  s: 0.9844078,
                  o: "801",
                },
                { f: "e", y: 1.23, z: 0.07, i: "e", e: 1, s: 0, o: "801" },
                { f: "c", y: 2, z: 0.22, i: "a", e: 2, s: 5, o: "774" },
                { f: "w", y: 2, z: 0.22, i: "b", e: 39, s: 95, o: "774" },
                { f: "h", y: 2, z: 0.22, i: "cR", e: 0.8, s: 1, o: "774" },
                { f: "h", y: 2, z: 0.22, i: "cQ", e: 0.8, s: 1, o: "774" },
                { y: 2, i: "cR", s: 1.0844078, z: 0, o: "801", f: "c" },
                { y: 2, i: "cQ", s: 1.0844078, z: 0, o: "801", f: "c" },
                { y: 2, i: "e", s: 1, z: 0, o: "801", f: "c" },
                { f: "c", y: 2.03, z: 0.16, i: "b", e: 0, s: 77, o: "796" },
                { f: "h", y: 2.03, z: 0.16, i: "cR", e: 0.83, s: 1, o: "796" },
                { f: "h", y: 2.03, z: 0.16, i: "cQ", e: 0.83, s: 1, o: "796" },
                { f: "w", y: 2.04, z: 0.22, i: "b", e: 2, s: 173, o: "778" },
                { f: "w", y: 2.04, z: 0.22, i: "b", e: 1, s: 102, o: "770" },
                { f: "w", y: 2.04, z: 0.22, i: "b", e: -134, s: 37, o: "791" },
                { f: "w", y: 2.04, z: 0.22, i: "b", e: 1, s: 102, o: "789" },
                { f: "w", y: 2.04, z: 0.22, i: "cR", e: 1, s: 0.9, o: "770" },
                { f: "w", y: 2.04, z: 0.22, i: "cQ", e: 1, s: 0.9, o: "770" },
                { f: "w", y: 2.04, z: 0.22, i: "cR", e: 1.1, s: 0.9, o: "791" },
                { f: "w", y: 2.04, z: 0.22, i: "cQ", e: 1.1, s: 0.9, o: "791" },
                { f: "w", y: 2.04, z: 0.22, i: "cR", e: 1, s: 0.9, o: "789" },
                { f: "w", y: 2.04, z: 0.22, i: "cQ", e: 1, s: 0.9, o: "789" },
                { f: "w", y: 2.04, z: 0.22, i: "cR", e: 1.1, s: 0.9, o: "778" },
                { f: "w", y: 2.04, z: 0.22, i: "cQ", e: 1.1, s: 0.9, o: "778" },
                { f: "c", y: 2.04, z: 0.22, i: "e", e: 1, s: 0, o: "778" },
                { f: "c", y: 2.04, z: 0.22, i: "e", e: 1, s: 0, o: "770" },
                { f: "c", y: 2.04, z: 0.22, i: "e", e: 1, s: 0, o: "791" },
                { f: "c", y: 2.04, z: 0.22, i: "e", e: 1, s: 0, o: "789" },
                { f: "c", y: 2.06, z: 0.23, i: "b", e: 0, s: 77, o: "781" },
                { f: "h", y: 2.06, z: 0.23, i: "cR", e: 0.83, s: 1, o: "781" },
                { f: "h", y: 2.06, z: 0.23, i: "cQ", e: 0.83, s: 1, o: "781" },
                { y: 2.19, i: "b", s: 0, z: 0, o: "796", f: "c" },
                { y: 2.19, i: "cR", s: 0.83, z: 0, o: "796", f: "c" },
                { y: 2.19, i: "cQ", s: 0.83, z: 0, o: "796", f: "c" },
                { y: 2.22, i: "a", s: 2, z: 0, o: "774", f: "c" },
                { y: 2.22, i: "b", s: 39, z: 0, o: "774", f: "c" },
                { y: 2.22, i: "cR", s: 0.8, z: 0, o: "774", f: "c" },
                { y: 2.22, i: "cQ", s: 0.8, z: 0, o: "774", f: "c" },
                { y: 2.26, i: "b", s: 2, z: 0, o: "778", f: "c" },
                { y: 2.26, i: "b", s: 1, z: 0, o: "770", f: "c" },
                { y: 2.26, i: "b", s: -134, z: 0, o: "791", f: "c" },
                { y: 2.26, i: "b", s: 1, z: 0, o: "789", f: "c" },
                { y: 2.26, i: "cQ", s: 1.1, z: 0, o: "778", f: "c" },
                { y: 2.26, i: "cR", s: 1.1, z: 0, o: "778", f: "c" },
                { y: 2.26, i: "cR", s: 1, z: 0, o: "770", f: "c" },
                { y: 2.26, i: "cQ", s: 1, z: 0, o: "770", f: "c" },
                { y: 2.26, i: "cR", s: 1.1, z: 0, o: "791", f: "c" },
                { y: 2.26, i: "cQ", s: 1.1, z: 0, o: "791", f: "c" },
                { y: 2.26, i: "cR", s: 1, z: 0, o: "789", f: "c" },
                { y: 2.26, i: "cQ", s: 1, z: 0, o: "789", f: "c" },
                { y: 2.26, i: "e", s: 1, z: 0, o: "778", f: "c" },
                { y: 2.26, i: "e", s: 1, z: 0, o: "770", f: "c" },
                { y: 2.26, i: "e", s: 1, z: 0, o: "791", f: "c" },
                { y: 2.26, i: "e", s: 1, z: 0, o: "789", f: "c" },
                { y: 2.29, i: "b", s: 0, z: 0, o: "781", f: "c" },
                { f: "q", y: 2.29, z: 0.09, i: "cQ", e: 1, s: 1.3, o: "772" },
                { f: "q", y: 2.29, z: 0.09, i: "cR", e: 1, s: 1.3, o: "772" },
                { f: "q", y: 2.29, z: 0.16, i: "cQ", e: 1, s: 1.3, o: "773" },
                { f: "q", y: 2.29, z: 0.16, i: "cR", e: 1, s: 1.3, o: "773" },
                { f: "q", y: 2.29, z: 0.16, i: "cQ", e: 1, s: 1.3, o: "790" },
                { f: "q", y: 2.29, z: 0.16, i: "cR", e: 1, s: 1.3, o: "790" },
                { y: 2.29, i: "cR", s: 0.83, z: 0, o: "781", f: "c" },
                { y: 2.29, i: "cQ", s: 0.83, z: 0, o: "781", f: "c" },
                { f: "c", y: 2.29, z: 0.09, i: "e", e: 1, s: 0, o: "772" },
                { f: "c", y: 2.29, z: 0.16, i: "e", e: 1, s: 0, o: "773" },
                { f: "c", y: 2.29, z: 0.16, i: "e", e: 1, s: 0, o: "790" },
                { f: "q", y: 3.08, z: 0.09, i: "cR", e: 1, s: 1.3, o: "769" },
                { f: "q", y: 3.08, z: 0.09, i: "cQ", e: 1, s: 1.3, o: "769" },
                { y: 3.08, i: "cQ", s: 1, z: 0, o: "772", f: "c" },
                { y: 3.08, i: "cR", s: 1, z: 0, o: "772", f: "c" },
                { f: "c", y: 3.08, z: 0.09, i: "e", e: 1, s: 0, o: "769" },
                { y: 3.08, i: "e", s: 1, z: 0, o: "772", f: "c" },
                { f: "q", y: 3.15, z: 0.1, i: "cQ", e: 1, s: 1.3, o: "771" },
                { f: "q", y: 3.15, z: 0.1, i: "cR", e: 1, s: 1.3, o: "771" },
                { y: 3.15, i: "cQ", s: 1, z: 0, o: "773", f: "c" },
                { y: 3.15, i: "cR", s: 1, z: 0, o: "773", f: "c" },
                { y: 3.15, i: "cQ", s: 1, z: 0, o: "790", f: "c" },
                { y: 3.15, i: "cR", s: 1, z: 0, o: "790", f: "c" },
                { f: "c", y: 3.15, z: 0.1, i: "e", e: 1, s: 0, o: "771" },
                { f: "c", y: 3.15, z: 0.21, i: "e", e: 1, s: 0, o: "768" },
                { f: "c", y: 3.15, z: 0.21, i: "e", e: 1, s: 0, o: "767" },
                { y: 3.15, i: "e", s: 1, z: 0, o: "773", f: "c" },
                { y: 3.15, i: "e", s: 1, z: 0, o: "790", f: "c" },
                { y: 3.17, i: "cR", s: 1, z: 0, o: "769", f: "c" },
                { y: 3.17, i: "cQ", s: 1, z: 0, o: "769", f: "c" },
                { y: 3.17, i: "e", s: 1, z: 0, o: "769", f: "c" },
                { y: 3.25, i: "cQ", s: 1, z: 0, o: "771", f: "c" },
                { y: 3.25, i: "cR", s: 1, z: 0, o: "771", f: "c" },
                { y: 3.25, i: "e", s: 1, z: 0, o: "771", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 4.15,
                  i: "ActionHandler",
                  e: {
                    a: [
                      {
                        i: 4.33333349,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "549",
                      },
                    ],
                  },
                  s: { a: [{ b: "597", p: 3, z: false, symbolOid: "549" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 4.06, i: "e", s: 1, z: 0, o: "768", f: "c" },
                { y: 4.06, i: "e", s: 1, z: 0, o: "767", f: "c" },
                { f: "k", y: 4.28, z: 0.15, i: "aY", e: -90, s: 0, o: "766" },
                { f: "k", y: 4.28, z: 0.15, i: "aY", e: -90, s: 0, o: "781" },
                { f: "k", y: 4.28, z: 0.15, i: "a", e: -16, s: 14, o: "781" },
                { f: "q", y: 5.13, z: 0.15, i: "aY", e: 0, s: 90, o: "787" },
                { f: "q", y: 5.13, z: 0.15, i: "aY", e: 0, s: 90, o: "796" },
                { f: "q", y: 5.13, z: 0.15, i: "a", e: 14, s: 16, o: "796" },
                { f: "c", y: 5.13, z: 0, i: "aY", e: 90, s: -90, o: "766" },
                { f: "c", y: 5.13, z: 0, i: "a", e: 16, s: -16, o: "781" },
                { f: "c", y: 5.13, z: 0, i: "aY", e: 90, s: -90, o: "781" },
                { f: "q", y: 5.13, z: 1.26, i: "a", e: 16, s: 16, o: "781" },
                { f: "q", y: 5.13, z: 1.26, i: "aY", e: 90, s: 90, o: "766" },
                { f: "q", y: 5.13, z: 1.26, i: "aY", e: 90, s: 90, o: "781" },
                { f: "c", y: 5.13, z: 0, i: "e", e: -0.0, s: 1, o: "766" },
                { f: "c", y: 5.13, z: 0, i: "e", e: 0, s: 1, o: "781" },
                { f: "q", y: 5.13, z: 0.01, i: "e", e: 1, s: -0.0, o: "787" },
                { f: "q", y: 5.13, z: 0.01, i: "e", e: 1, s: 0, o: "796" },
                {
                  f: "c",
                  y: 5.13,
                  z: 1.26,
                  i: "e",
                  e: -0.0,
                  s: -0.0,
                  o: "766",
                },
                { f: "c", y: 5.13, z: 1.26, i: "e", e: 0, s: 0, o: "781" },
                { f: "c", y: 5.14, z: 1.24, i: "e", e: 1, s: 1, o: "787" },
                { f: "c", y: 5.14, z: 1.24, i: "e", e: 1, s: 1, o: "796" },
                { f: "c", y: 5.28, z: 0.26, i: "a", e: 14, s: 14, o: "796" },
                { f: "c", y: 5.28, z: 0.26, i: "aY", e: 0, s: 0, o: "787" },
                { f: "k", y: 5.28, z: 0.26, i: "aY", e: 0, s: 0, o: "796" },
                { f: "k", y: 6.24, z: 0.14, i: "a", e: 0, s: 0, o: "787" },
                { f: "k", y: 6.24, z: 0.14, i: "a", e: -16, s: 14, o: "796" },
                { f: "k", y: 6.24, z: 0.15, i: "aY", e: -90, s: 0, o: "787" },
                { f: "k", y: 6.24, z: 0.15, i: "aY", e: -90, s: 0, o: "796" },
                { y: 7.08, i: "a", s: 0, z: 0, o: "787", f: "c" },
                { y: 7.08, i: "a", s: -16, z: 0, o: "796", f: "c" },
                { f: "c", y: 7.08, z: 0.01, i: "e", e: 0, s: 1, o: "787" },
                { f: "c", y: 7.08, z: 0.01, i: "e", e: 0, s: 1, o: "796" },
                { f: "q", y: 7.09, z: 0.15, i: "a", e: 14, s: 16, o: "781" },
                { f: "q", y: 7.09, z: 0.15, i: "aY", e: 0, s: 90, o: "781" },
                { f: "q", y: 7.09, z: 0.14, i: "aY", e: 0, s: 90, o: "766" },
                { y: 7.09, i: "aY", s: -90, z: 0, o: "787", f: "c" },
                { y: 7.09, i: "aY", s: -90, z: 0, o: "796", f: "c" },
                { f: "q", y: 7.09, z: 0, i: "e", e: 1, s: 0, o: "781" },
                { f: "q", y: 7.09, z: 0, i: "e", e: 1, s: -0.0, o: "766" },
                { y: 7.09, i: "e", s: 1, z: 0, o: "781", f: "c" },
                { y: 7.09, i: "e", s: 1, z: 0, o: "766", f: "c" },
                { y: 7.09, i: "e", s: 0, z: 0, o: "787", f: "c" },
                { y: 7.09, i: "e", s: 0, z: 0, o: "796", f: "c" },
                { y: 7.23, i: "aY", s: 0, z: 0, o: "766", f: "c" },
                { y: 7.24, i: "a", s: 14, z: 0, o: "781", f: "c" },
                { y: 7.24, i: "aY", s: 0, z: 0, o: "781", f: "k" },
                {
                  f: "c",
                  p: 2,
                  y: 8.15,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      {
                        i: 4.66666651,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "549",
                      },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
              ],
              f: 30,
              b: [
                {
                  D: 3.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "803",
                },
              ],
            },
          },
          bZ: 180,
          O: [
            "791",
            "754",
            "752",
            "755",
            "763",
            "753",
            "764",
            "786",
            "765",
            "800",
            "796",
            "782",
            "781",
            "799",
            "785",
            "798",
            "783",
            "797",
            "784",
            "792",
            "780",
            "793",
            "789",
            "787",
            "770",
            "766",
            "779",
            "778",
            "790",
            "773",
            "775",
            "774",
            "794",
            "772",
            "769",
            "777",
            "776",
            "771",
            "788",
            "795",
            "768",
            "767",
            "802",
            "756",
            "801",
            "751",
            "760",
            "757",
            "762",
            "759",
            "758",
            "761",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            795: {
              h: "670",
              p: "no-repeat",
              x: "visible",
              a: 215,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 11,
              bF: "787",
              b: 235,
              d: 50,
              k: "div",
              c: 68.6667,
            },
            763: {
              cN: "none",
              x: "visible",
              bS: 383,
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 4,
              d: 480,
              aP: "auto",
              e: 1,
            },
            782: {
              h: "618",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "781",
              dB: "img",
              d: 53.3333,
              k: "div",
              c: 83.3333,
              e: 0,
            },
            758: {
              cN: "none",
              x: "visible",
              a: 11,
              cA: false,
              b: 20,
              j: "absolute",
              r: "inline",
              c: 23,
              k: "div",
              z: 6,
              d: 23,
              bF: "757",
              cQ: 0.9,
              aP: "auto",
              bY: 1,
              bZ: 180,
              bX: false,
              cR: 0.9,
              cV: [],
            },
            777: {
              h: "604",
              p: "no-repeat",
              x: "visible",
              a: 77,
              q: "100% 100%",
              b: 42,
              j: "absolute",
              r: "inline",
              bF: "774",
              z: 1,
              dB: "img",
              d: 103,
              k: "div",
              cQ: 1.75,
              e: 0,
              c: 227,
              cR: 1.75,
            },
            796: {
              x: "visible",
              a: 16,
              b: 77,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "786",
              k: "div",
              d: 53.3333,
              c: 270.333,
              cQ: 1,
              aY: 90,
              e: 0,
              cR: 1,
            },
            764: {
              h: "608",
              p: "no-repeat",
              x: "visible",
              a: 274,
              q: "100% 100%",
              b: 8,
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "763",
              dB: "img",
              d: 39,
              k: "div",
              c: 34,
              e: 0,
            },
            783: {
              h: "624",
              p: "no-repeat",
              x: "visible",
              a: 137,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "781",
              dB: "img",
              d: 52,
              k: "div",
              c: 84.6667,
              e: 0,
            },
            751: {
              c: 318,
              bS: 287,
              d: 56,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#00FDFF",
              L: "Solid",
              aP: "pointer",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 1,
              O: 1,
              C: "#D8DDE4",
              z: 35,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "747" },
                  { p: 4, h: "750" },
                ],
              },
              k: "div",
              a: 0,
              b: 422,
            },
            759: {
              h: "62",
              p: "no-repeat",
              x: "visible",
              a: 2,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "758",
              z: 4,
              dB: "img",
              d: 38,
              k: "div",
              aY: 0,
              cQ: 1,
              c: 29,
              cR: 1,
            },
            770: {
              h: "674",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 102,
              j: "absolute",
              r: "inline",
              bF: "766",
              z: 6,
              dB: "img",
              d: 296,
              k: "div",
              cQ: 0.9,
              e: 0,
              c: 297,
              cR: 0.9,
            },
            778: {
              x: "hidden",
              a: 4,
              b: 173,
              j: "absolute",
              r: "inline",
              z: 1,
              k: "div",
              bF: "766",
              d: 282,
              c: 290,
              cQ: 0.9,
              e: 0,
              cR: 0.9,
            },
            797: {
              h: "606",
              p: "no-repeat",
              x: "visible",
              a: 199,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "796",
              dB: "img",
              d: 52,
              k: "div",
              c: 71.3333,
              e: 0,
            },
            765: {
              x: "visible",
              k: "div",
              c: 297,
              d: 338,
              z: 1,
              a: 11,
              j: "absolute",
              bF: "763",
              b: 23,
            },
            784: {
              h: "606",
              p: "no-repeat",
              x: "visible",
              a: 199,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "781",
              dB: "img",
              d: 52,
              k: "div",
              c: 71.3333,
              e: 0,
            },
            752: {
              c: 318,
              bS: 319,
              d: 478,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#0433FF",
              L: "Solid",
              aP: "pointer",
              M: 1,
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 1,
              O: 1,
              C: "#D8DDE4",
              z: 34,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "9" },
                  { p: 4, h: "749" },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            771: {
              h: "676",
              p: "no-repeat",
              x: "visible",
              a: 154,
              q: "100% 100%",
              b: 182,
              j: "absolute",
              r: "inline",
              bF: "766",
              z: 3,
              dB: "img",
              d: 30,
              k: "div",
              cQ: 1.3,
              e: 0,
              c: 30,
              cR: 1.3,
            },
            779: {
              c: 281,
              d: 271,
              r: "inline",
              I: "Solid",
              e: 1,
              J: "Solid",
              cQ: 0.9,
              K: "Solid",
              cR: 0.9,
              g: "#FFF",
              L: "Solid",
              M: 0,
              bF: "778",
              N: 0,
              j: "absolute",
              x: "visible",
              O: 0,
              B: "#004997",
              P: 0,
              A: "#004997",
              C: "#004997",
              z: 1,
              aJ: 10,
              D: "#004997",
              aK: 10,
              k: "div",
              aI: 10,
              a: 4,
              aL: 10,
              b: 5,
            },
            790: {
              h: "664",
              p: "no-repeat",
              x: "visible",
              a: -2,
              q: "100% 100%",
              b: 15,
              j: "absolute",
              r: "inline",
              bF: "787",
              z: 12,
              dB: "img",
              d: 48.3333,
              k: "div",
              cQ: 1.3,
              e: 0,
              c: 204,
              cR: 1.3,
            },
            798: {
              h: "624",
              p: "no-repeat",
              x: "visible",
              a: 137,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "796",
              dB: "img",
              d: 52,
              k: "div",
              c: 84.6667,
              e: 0,
            },
            766: {
              x: "visible",
              a: 0,
              aI: 30,
              b: 42,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "765",
              aJ: 30,
              d: 296,
              aK: 30,
              aY: 0,
              e: 1,
              k: "div",
              c: 297,
              aL: 30,
            },
            785: {
              h: "614",
              p: "no-repeat",
              x: "visible",
              a: 68,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "781",
              dB: "img",
              d: 53.3333,
              k: "div",
              c: 84.6667,
              e: 0,
            },
            753: {
              x: "hidden",
              a: 0,
              bS: 18,
              b: 432,
              j: "absolute",
              z: 0,
              k: "div",
              c: 320,
              d: 480,
              aK: 30,
              cQ: 0.8,
              e: 0,
              aL: 30,
              cR: 0.8,
            },
            772: {
              h: "676",
              p: "no-repeat",
              x: "visible",
              a: 26,
              q: "100% 100%",
              b: 70,
              j: "absolute",
              r: "inline",
              bF: "766",
              z: 5,
              dB: "img",
              d: 30,
              k: "div",
              cQ: 1.3,
              e: 0,
              c: 30,
              cR: 1.3,
            },
            791: {
              x: "visible",
              a: 0,
              b: 37,
              j: "absolute",
              r: "inline",
              z: 1,
              k: "div",
              bF: "787",
              d: 296,
              c: 297,
              cQ: 0.9,
              e: 0,
              cR: 0.9,
            },
            799: {
              h: "614",
              p: "no-repeat",
              x: "visible",
              a: 68,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "796",
              dB: "img",
              d: 53.3333,
              k: "div",
              c: 84.6667,
              e: 0,
            },
            767: {
              h: "672",
              p: "no-repeat",
              x: "visible",
              a: 68,
              q: "100% 100%",
              b: 242,
              j: "absolute",
              r: "inline",
              z: 8,
              bF: "766",
              dB: "img",
              d: 37,
              k: "div",
              c: 204.667,
              e: 0,
            },
            786: {
              x: "visible",
              k: "div",
              c: 297,
              d: 338,
              z: 2,
              a: 11,
              j: "absolute",
              bF: "763",
              b: 23,
            },
            754: {
              w: "",
              h: "563",
              p: "no-repeat",
              x: "visible",
              a: -11,
              q: "100% 100%",
              bS: 447,
              j: "absolute",
              bF: "753",
              r: "inline",
              b: -16,
              z: 1,
              d: 512,
              dB: "img",
              cQ: 1,
              k: "div",
              c: 341,
              cR: 1,
            },
            800: {
              h: "618",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "796",
              dB: "img",
              d: 53.3333,
              k: "div",
              c: 83.3333,
              e: 0,
            },
            773: {
              h: "664",
              p: "no-repeat",
              x: "visible",
              a: -2,
              q: "100% 100%",
              b: 15,
              j: "absolute",
              r: "inline",
              bF: "766",
              z: 9,
              dB: "img",
              d: 48.3333,
              k: "div",
              cQ: 1.3,
              e: 0,
              c: 204,
              cR: 1.3,
            },
            792: {
              h: "674",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 101,
              j: "absolute",
              r: "inline",
              bF: "791",
              z: 2,
              dB: "img",
              d: 296,
              k: "div",
              cQ: 0.9,
              e: 0,
              c: 297,
              cR: 0.9,
            },
            760: {
              c: 319,
              d: 57,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#FFBD02",
              L: "Solid",
              aP: "auto",
              M: 0,
              bF: "757",
              N: 0,
              A: "#004997",
              x: "visible",
              j: "absolute",
              B: "#004997",
              P: 0,
              O: 0,
              C: "#004997",
              z: 5,
              k: "div",
              D: "#004997",
              aK: 20,
              cN: "none",
              a: 0,
              aL: 20,
              b: 6,
            },
            768: {
              h: "668",
              p: "no-repeat",
              x: "visible",
              a: 26,
              q: "100% 100%",
              b: 240,
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "766",
              dB: "img",
              d: 39.3333,
              k: "div",
              c: 144.667,
              e: 0,
            },
            787: {
              x: "visible",
              a: 0,
              aI: 30,
              b: 42,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "786",
              aJ: 30,
              d: 296,
              aK: 30,
              aY: 90,
              e: -0.0,
              k: "div",
              c: 297,
              aL: 30,
            },
            755: {
              cN: "none",
              x: "visible",
              bS: 351,
              a: 0,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 32,
              d: 480,
              aP: "auto",
              e: 1,
            },
            801: {
              h: "217",
              p: "no-repeat",
              x: "visible",
              a: 76,
              q: "100% 100%",
              bS: 127,
              j: "absolute",
              bF: "763",
              r: "inline",
              b: 370,
              z: 5,
              d: 42,
              dB: "img",
              cQ: 0.9844078,
              e: 0,
              k: "div",
              c: 167,
              cR: 0.9844078,
            },
            774: {
              x: "visible",
              a: 5,
              b: 95,
              j: "absolute",
              r: "inline",
              c: 304,
              k: "div",
              z: 2,
              d: 208.333,
              bF: "766",
              cQ: 1,
              cR: 1,
            },
            793: {
              c: 281,
              d: 280,
              r: "inline",
              I: "Solid",
              e: 1,
              J: "Solid",
              cQ: 0.9,
              K: "Solid",
              cR: 0.9,
              g: "#FFF",
              L: "Solid",
              M: 0,
              bF: "791",
              N: 0,
              j: "absolute",
              x: "visible",
              O: 0,
              B: "#004997",
              P: 0,
              A: "#004997",
              C: "#004997",
              z: 1,
              aJ: 10,
              D: "#004997",
              aK: 10,
              k: "div",
              aI: 10,
              a: 10,
              aL: 10,
              b: 129,
            },
            761: {
              aU: 8,
              G: "#000",
              c: 97,
              aV: 8,
              r: "inline",
              d: 9,
              s: "Montserrat",
              t: 16,
              Y: 7,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "700",
              i: "distance",
              w: "300 m",
              bF: "757",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 7,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 47,
              b: 37,
            },
            769: {
              h: "676",
              p: "no-repeat",
              x: "visible",
              a: 192,
              q: "100% 100%",
              b: 79,
              j: "absolute",
              r: "inline",
              bF: "766",
              z: 4,
              dB: "img",
              d: 30,
              k: "div",
              cQ: 1.3,
              e: 0,
              c: 30,
              cR: 1.3,
            },
            780: {
              h: "674",
              p: "no-repeat",
              x: "visible",
              a: -7,
              q: "100% 100%",
              b: -35,
              j: "absolute",
              r: "inline",
              bF: "778",
              z: 2,
              dB: "img",
              d: 296,
              k: "div",
              cQ: 0.9,
              e: 0,
              c: 297,
              cR: 0.9,
            },
            788: {
              h: "666",
              p: "no-repeat",
              x: "visible",
              a: 15,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 10,
              bF: "787",
              b: 235,
              d: 52,
              k: "div",
              c: 187,
            },
            756: {
              cN: "none",
              h: "616",
              p: "no-repeat",
              x: "visible",
              a: 190,
              q: "100% 100%",
              b: 355,
              j: "absolute",
              r: "inline",
              bF: "755",
              z: 4,
              dB: "img",
              d: 198,
              k: "div",
              cQ: 0.2,
              e: 1,
              c: 198,
              aP: "auto",
              cR: 0.2,
            },
            802: {
              h: "608",
              p: "no-repeat",
              x: "visible",
              a: 9,
              q: "100% 100%",
              b: 344,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "763",
              dB: "img",
              d: 47,
              k: "div",
              c: 40.6667,
              e: 0,
            },
            775: {
              h: "620",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "774",
              z: 3,
              dB: "img",
              d: 135,
              k: "div",
              cQ: 1.75,
              e: 0,
              c: 118,
              cR: 1.75,
            },
            794: {
              h: "729",
              p: "no-repeat",
              x: "visible",
              a: 28,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "787",
              b: 57,
              d: 165,
              k: "div",
              c: 220.667,
            },
            762: {
              aU: 8,
              G: "#000",
              c: 190,
              aV: 8,
              r: "inline",
              d: 28,
              s: "Montserrat",
              X: 0,
              t: 10,
              Y: 12,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "500",
              i: "address",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">Nemunas, Kaunas, Karaliaus Mindaugo pr. 18, LT- 44295\n</div>',
              bF: "757",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 8,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 47,
              b: 6,
            },
            781: {
              x: "visible",
              a: 14,
              b: 77,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "765",
              k: "div",
              d: 53.3333,
              c: 270.333,
              cQ: 1,
              aY: 0,
              e: 1,
              cR: 1,
            },
            789: {
              h: "674",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 102,
              j: "absolute",
              r: "inline",
              bF: "787",
              z: 7,
              dB: "img",
              d: 296,
              k: "div",
              cQ: 0.9,
              e: 0,
              c: 297,
              cR: 0.9,
            },
            757: {
              cN: "none",
              x: "visible",
              a: 1,
              b: 461,
              j: "absolute",
              r: "inline",
              c: 319,
              k: "div",
              z: 3,
              d: 63,
              bF: "755",
              aP: "auto",
              e: 0,
            },
            776: {
              h: "622",
              p: "no-repeat",
              x: "visible",
              a: 22,
              q: "100% 100%",
              b: 120,
              j: "absolute",
              r: "inline",
              bF: "774",
              z: 2,
              dB: "img",
              d: 88.3333,
              k: "div",
              cQ: 1.75,
              e: 0,
              c: 244,
              cR: 1.75,
            },
          },
        },
      ],
      {},
      h,
      {
        k: { p: 0, q: [[0, 0, 0.895, 0.03, 0.685, 0.22, 1, 1]] },
        w: { p: 0, q: [[0, 0, 0.77, 0, 0.175, 1, 1, 1]] },
        y: { p: 0, q: [[0, 0, 0.445, 0.05, 0.55, 0.95, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
        h: { p: 0, q: [[0, 0, 0.175, 0.885, 0.32, 1.25, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
