//	HYPE.documents["CH_Janki_rich_live_HR_320x480_adaptive_MRAID__"]

(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/CH_Janki",
      f = "CH_Janki_rich_live_HR_320x480_adaptive_MRAID__",
      g = "chjankirichlivehr320x480adaptivemraid_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "Action1",
        source:
          "function(hypeDocument, element, event) {\t\n\t\n\twindow.action();\n\t\t\n\n}",
        identifier: "87",
      },
      {
        name: "GoToSite",
        source:
          "function(hypeDocument, element, event) {\t\n\t\t\t\n\twindow.gotosite();\n\t\n\n}",
        identifier: "88",
      },
      {
        name: "Click",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.click();\n\t\n}",
        identifier: "141",
      },
      {
        name: "sound",
        source:
          'function(hypeDocument, element, event) {\t\n\tvar video = hypeDocument.getElementById("videom");\n\tvar krest = hypeDocument.getElementById("krestm");\n\tvar on = hypeDocument.getElementById("onm");\n\t\n\t\n\tif (video.muted) {\n\t\tvideo.muted = false;\n\t\tkrest.style.display = "none";\n\t\ton.style.display = "block";\n\t\tregisterUnMuteEvent();\n\t} else {\n\t\tvideo.muted = true;\n\t\tkrest.style.display = "block";\n\t\ton.style.display = "none";\n\t\tregisterMuteEvent();\n\t}\n\t\n\treturn false;\n\t\t\t\n}',
        identifier: "142",
      },
      {
        name: "blendmodes",
        source:
          "function(hypeDocument, element, event) {\t\n\tvar blendmodes = ['color', 'color-burn', 'color-dodge', 'darken', 'difference', 'exclusion', 'hard-light', 'hue', 'lighten', 'luminosity', 'multiply', 'normal', 'overlay', 'saturation', 'screen', 'soft-light'];\n\twhile (blendmodes.length) {\n\t\tvar blendmode = blendmodes.pop();\n\t\tvar nodes = element.querySelectorAll('.blendmode-'+blendmode);\n\t\tfor (i = 0; i < nodes.length; ++i) {\n\t\t\tnodes[i].parentNode.style.mixBlendMode = blendmode;\n\t\t}\n\t}\n}",
        identifier: "303",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        7: { p: 1, n: "bubbles_3-ezgif.com-optimize.gif", g: "411", t: "@1x" },
        3: { p: 1, n: "bg_mask.png", g: "285", t: "@1x" },
        "-2": { n: "blank.gif" },
        4: { p: 1, n: "crane_1.png", g: "306", t: "@1x" },
        0: { p: 1, n: "icon_w.svg", g: "125", t: "image/svg+xml" },
        5: { p: 1, n: "headline_summer.png", g: "310", t: "@1x" },
        1: { p: 1, n: "CH_logo.svg", g: "308", t: "image/svg+xml" },
        6: { p: 1, n: "gift.png", g: "343", t: "@1x" },
        2: { p: 1, n: "crane.png", g: "277", t: "@1x" },
        "-1": { n: "PIE.htc" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "Untitled Scene", o: "1", X: [0] }],
      [
        {
          o: "3",
          A: { a: [{ p: 4, h: "303" }] },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FCFFFF",
          L: [],
          bY: 1,
          d: 320,
          U: { 451: { V: { "Main Timeline": "507" }, W: "507", n: "icon" } },
          T: {
            433: {
              q: false,
              z: 3,
              i: "433",
              n: "crane",
              a: [
                { f: "p", y: 0, z: 0.17, i: "b", e: -51, s: -172, o: "501" },
                { f: "c", y: 0.17, z: 0.19, i: "b", e: -51, s: -51, o: "501" },
                { f: "p", y: 1.06, z: 0.08, i: "f", e: -5, s: 0, o: "501" },
                { f: "p", y: 1.06, z: 1.09, i: "b", e: -172, s: -51, o: "501" },
                { f: "b", y: 1.14, z: 0.07, i: "f", e: 5, s: -5, o: "501" },
                { f: "b", y: 1.21, z: 0.03, i: "f", e: 0, s: 5, o: "501" },
                { y: 1.24, i: "f", s: 0, z: 0, o: "501", f: "p" },
                { y: 2.15, i: "b", s: -172, z: 0, o: "501", f: "p" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "433", p: 3, z: false, symbolOid: "2" }] },
                  o: "433",
                },
              ],
              f: 30,
              b: [],
            },
            507: {
              c: "451",
              q: false,
              z: 3.15,
              i: "507",
              a: [
                { f: "y", y: 0, z: 1.15, i: "aY", e: 360, s: 0, o: "452" },
                { y: 1.15, i: "aY", s: 360, z: 0, o: "452", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "507", p: 3, z: false, symbolOid: "609" }] },
                  o: "507",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            434: {
              q: false,
              z: 2,
              i: "434",
              n: "pulse",
              a: [
                { f: "c", y: 0, z: 0.15, i: "cQ", e: 1.05, s: 1, o: "459" },
                { f: "c", y: 0, z: 0.15, i: "cR", e: 1.05, s: 1, o: "459" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1.05, s: 1, o: "465" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1.05, s: 1, o: "465" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 1.05, o: "459" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 1.05, o: "459" },
                { f: "c", y: 1, z: 0.15, i: "cR", e: 1, s: 1.05, o: "465" },
                { f: "c", y: 1, z: 0.15, i: "cQ", e: 1, s: 1.05, o: "465" },
                { y: 1, i: "cR", s: 1, z: 0, o: "459", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "459", f: "c" },
                { y: 1.15, i: "cQ", s: 1, z: 0, o: "465", f: "c" },
                { y: 1.15, i: "cR", s: 1, z: 0, o: "465", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "434", p: 3, z: false, symbolOid: "2" }] },
                  o: "434",
                },
              ],
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              q: false,
              z: 10.15,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "c", y: 0, z: 0.23, i: "a", e: 0, s: 5, o: "449" },
                { f: "c", y: 0, z: 0.23, i: "e", e: 1, s: 0, o: "449" },
                { f: "c", y: 0, z: 0.23, i: "b", e: 418, s: 488, o: "449" },
                { f: "c", y: 0, z: 0.23, i: "a", e: 8, s: 13, o: "468" },
                { f: "c", y: 0, z: 0.23, i: "b", e: 418, s: 488, o: "468" },
                { f: "c", y: 0, z: 0.23, i: "e", e: 1, s: 0, o: "468" },
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 1.15,
                  i: "ActionHandler",
                  e: { a: [{}] },
                  s: {
                    a: [
                      { b: "433", p: 3, z: false, symbolOid: "2" },
                      { b: "441", p: 3, z: false, symbolOid: "2" },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 0.15, z: 0.07, i: "e", e: 1, s: 0, o: "489" },
                { f: "44", y: 0.15, z: 1, i: "bR", e: -65, s: 0, o: "471" },
                { f: "c", y: 0.15, z: 1, i: "cQ", e: 1.1, s: 1, o: "471" },
                { f: "c", y: 0.15, z: 1, i: "cR", e: 1.1, s: 1, o: "471" },
                { f: "c", y: 0.15, z: 1, i: "b", e: 330, s: 201, o: "471" },
                { f: "44", y: 0.15, z: 1, i: "bR", e: 65, s: 0, o: "479" },
                { f: "c", y: 0.15, z: 1, i: "cQ", e: 1.1, s: 1, o: "479" },
                { f: "c", y: 0.15, z: 1, i: "cR", e: 1.1, s: 1, o: "479" },
                { f: "c", y: 0.15, z: 1, i: "b", e: -120, s: 0, o: "479" },
                { f: "p", y: 0.15, z: 1, i: "cR", e: 1, s: 0.9, o: "455" },
                { f: "p", y: 0.15, z: 1, i: "cQ", e: 1, s: 0.9, o: "455" },
                { f: "c", y: 0.15, z: 1, i: "e", e: 1, s: 0, o: "455" },
                { f: "44", y: 0.15, z: 1, i: "bR", e: -65, s: 0, o: "492" },
                { f: "c", y: 0.15, z: 1, i: "cQ", e: 1.1, s: 1, o: "492" },
                { f: "c", y: 0.15, z: 1, i: "cR", e: 1.1, s: 1, o: "492" },
                { f: "c", y: 0.15, z: 1, i: "b", e: 330, s: 201, o: "492" },
                { f: "c", y: 0.22, z: 0.23, i: "e", e: 1, s: 1, o: "489" },
                { y: 0.23, i: "a", s: 0, z: 0, o: "449", f: "c" },
                { y: 0.23, i: "e", s: 1, z: 0, o: "449", f: "c" },
                { y: 0.23, i: "b", s: 418, z: 0, o: "449", f: "c" },
                { y: 0.23, i: "a", s: 8, z: 0, o: "468", f: "c" },
                { y: 0.23, i: "b", s: 418, z: 0, o: "468", f: "c" },
                { y: 0.23, i: "e", s: 1, z: 0, o: "468", f: "c" },
                { f: "c", y: 1.05, z: 0.1, i: "e", e: 0, s: 1, o: "470" },
                { f: "c", y: 1.05, z: 0.1, i: "e", e: 0, s: 1, o: "491" },
                { y: 1.15, i: "e", s: 0, z: 0, o: "470", f: "c" },
                { y: 1.15, i: "bR", s: -65, z: 0, o: "471", f: "c" },
                { y: 1.15, i: "cQ", s: 1.1, z: 0, o: "471", f: "c" },
                { y: 1.15, i: "cR", s: 1.1, z: 0, o: "471", f: "c" },
                { y: 1.15, i: "b", s: 330, z: 0, o: "471", f: "c" },
                { y: 1.15, i: "bR", s: 65, z: 0, o: "479", f: "c" },
                { y: 1.15, i: "cQ", s: 1.1, z: 0, o: "479", f: "c" },
                { y: 1.15, i: "cR", s: 1.1, z: 0, o: "479", f: "c" },
                { y: 1.15, i: "b", s: -120, z: 0, o: "479", f: "c" },
                { y: 1.15, i: "cR", s: 1, z: 0, o: "455", f: "c" },
                { y: 1.15, i: "cQ", s: 1, z: 0, o: "455", f: "c" },
                { y: 1.15, i: "e", s: 1, z: 0, o: "455", f: "c" },
                { y: 1.15, i: "e", s: 0, z: 0, o: "491", f: "c" },
                { y: 1.15, i: "bR", s: -65, z: 0, o: "492", f: "c" },
                { y: 1.15, i: "cQ", s: 1.1, z: 0, o: "492", f: "c" },
                { y: 1.15, i: "cR", s: 1.1, z: 0, o: "492", f: "c" },
                { y: 1.15, i: "b", s: 330, z: 0, o: "492", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 1.15,
                  z: 9,
                  i: "ActionHandler",
                  e: {
                    a: [
                      {
                        i: 4.5666666,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                      { p: 0 },
                    ],
                  },
                  s: { a: [{ b: "434", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 1.15, z: 0.24, i: "e", e: 0, s: 1, o: "489" },
                { y: 2.09, i: "e", s: 0, z: 0, o: "489", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 10.15,
                  z: 0,
                  i: "ActionHandler",
                  s: {
                    a: [
                      {
                        i: 4.5666666,
                        b: "kTimelineDefaultIdentifier",
                        p: 9,
                        symbolOid: "2",
                      },
                      { p: 0 },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
              ],
              f: 30,
              b: [
                {
                  D: 3.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "507",
                },
              ],
            },
            441: {
              q: false,
              z: 1,
              i: "441",
              n: "flash",
              a: [
                { f: "c", y: 0, z: 1, i: "a", e: 264, s: -7, o: "504" },
                { f: "c", y: 0, z: 1, i: "a", e: 264, s: -7, o: "502" },
                { f: "c", y: 0, z: 0.05, i: "e", e: 1, s: 0, o: "505" },
                { f: "c", y: 0, z: 0.05, i: "e", e: 1, s: 0, o: "503" },
                { f: "c", y: 0.05, z: 0.18, i: "e", e: 1, s: 1, o: "503" },
                { f: "c", y: 0.05, z: 0.18, i: "e", e: 1, s: 1, o: "505" },
                { f: "c", y: 0.23, z: 0.07, i: "e", e: 0, s: 1, o: "505" },
                { f: "c", y: 0.23, z: 0.07, i: "e", e: 0, s: 1, o: "503" },
                { y: 1, i: "a", s: 264, z: 0, o: "504", f: "c" },
                { y: 1, i: "a", s: 264, z: 0, o: "502", f: "c" },
                { y: 1, i: "e", s: 0, z: 0, o: "505", f: "c" },
                { y: 1, i: "e", s: 0, z: 0, o: "503", f: "c" },
              ],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "501",
            "462",
            "494",
            "472",
            "484",
            "461",
            "493",
            "478",
            "483",
            "466",
            "456",
            "463",
            "489",
            "467",
            "495",
            "473",
            "485",
            "496",
            "491",
            "474",
            "486",
            "479",
            "470",
            "455",
            "458",
            "497",
            "475",
            "487",
            "460",
            "490",
            "459",
            "503",
            "505",
            "504",
            "502",
            "500",
            "498",
            "477",
            "482",
            "480",
            "476",
            "499",
            "506",
            "481",
            "492",
            "471",
            "457",
            "464",
            "465",
            "488",
            "469",
            "450",
            "449",
            "468",
            "454",
            "451",
            "452",
            "453",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            470: {
              x: "hidden",
              bS: 55,
              a: 8,
              b: 9,
              j: "absolute",
              aJ: 20,
              z: 17,
              r: "inline",
              k: "div",
              d: 402,
              aK: 100,
              aI: 20,
              e: 1,
              c: 304,
              aL: 20,
            },
            449: {
              cN: "none",
              x: "visible",
              bS: 31,
              a: 5,
              b: 488,
              j: "absolute",
              r: "inline",
              c: 320,
              k: "div",
              z: 3,
              d: 62,
              aP: "auto",
              e: 0,
            },
            456: {
              x: "visible",
              bF: "455",
              k: "div",
              c: 328,
              d: 411,
              z: 4,
              a: -16,
              bS: 287,
              j: "absolute",
              b: -9,
            },
            463: {
              c: 328,
              bS: 319,
              d: 480,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 0,
              bF: "455",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 2,
              l: 180,
              D: "#D8DDE4",
              m: "#D34374",
              k: "div",
              n: "#115F6C",
              a: -16,
              b: -9,
            },
            499: {
              b: 16,
              z: 1,
              K: "Solid",
              c: 230,
              L: "Solid",
              d: 32,
              gg: "0",
              M: 0,
              e: 0.59361213,
              cQ: 1.4,
              N: 0,
              O: 0,
              cR: 1.4,
              g: "#FFF",
              P: 0,
              bF: "498",
              Q: 0,
              R: "#FFF",
              j: "absolute",
              S: 0,
              k: "div",
              aI: "50%",
              T: 0,
              aJ: "50%",
              aK: "50%",
              aL: "50%",
              A: "#D8DDE4",
              B: "#D8DDE4",
              bL: 12,
              C: "#D8DDE4",
              D: "#D8DDE4",
              x: "visible",
              I: "Solid",
              a: 34,
              J: "Solid",
            },
            471: {
              bR: 0,
              x: "hidden",
              a: 0,
              bS: 351,
              b: 201,
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "470",
              k: "div",
              d: 201,
              c: 304,
              cQ: 1,
              cR: 1,
            },
            457: {
              c: 328,
              bS: 311,
              d: 97,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 0,
              bF: "456",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              l: 180,
              D: "#D8DDE4",
              m: "rgba(211, 67, 116, 0.000)",
              k: "div",
              n: "#115F6C",
              a: 0,
              b: 314,
            },
            464: {
              x: "visible",
              bF: "455",
              k: "div",
              c: 306,
              d: 68,
              z: 5,
              a: -1,
              bS: 343,
              j: "absolute",
              b: 334,
            },
            465: {
              h: "343",
              p: "no-repeat",
              x: "visible",
              a: 30,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "464",
              dB: "img",
              d: 39,
              k: "div",
              cQ: 1,
              c: 246.333,
              cR: 1,
            },
            472: {
              c: 484,
              cP: "blendmode-screen",
              bS: 383,
              d: 607,
              r: "inline",
              e: 0.5,
              gg: "1",
              bF: "471",
              aI: 60,
              j: "absolute",
              x: "visible",
              k: "div",
              aJ: 60,
              Q: 10,
              z: 2,
              aK: 60,
              R: "rgba(0, 0, 0, 0.152)",
              S: 0,
              a: -90,
              aL: 60,
              T: 0,
              b: -273,
            },
            500: {
              h: "310",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "498",
              b: 0,
              d: 67,
              k: "div",
              c: 298,
            },
            458: {
              x: "visible",
              bF: "455",
              k: "div",
              c: 304,
              d: 92,
              z: 9,
              a: 0,
              bS: 343,
              j: "absolute",
              b: 25,
            },
            466: {
              c: 328,
              bS: 311,
              d: 158,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 0,
              bF: "455",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 8,
              l: 0,
              D: "#D8DDE4",
              m: "rgba(211, 67, 116, 0.000)",
              k: "div",
              n: "#D34374",
              a: -16,
              b: -9,
            },
            473: {
              h: "306",
              p: "no-repeat",
              x: "visible",
              a: 53,
              q: "100% 100%",
              b: 74,
              j: "absolute",
              r: "inline",
              z: 9,
              bF: "472",
              dB: "img",
              d: 388,
              k: "div",
              cQ: 1,
              c: 369,
              cR: 1,
            },
            501: {
              h: "277",
              p: "no-repeat",
              x: "visible",
              a: 150,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 8,
              bF: "461",
              b: -266,
              d: 429,
              k: "div",
              c: 182.66666667,
              f: 0,
            },
            480: {
              x: "visible",
              b: 172,
              k: "div",
              c: 305,
              d: 110,
              z: 4,
              r: "inline",
              a: -1,
              bS: 343,
              j: "absolute",
              bF: "479",
            },
            459: {
              h: "310",
              p: "no-repeat",
              x: "visible",
              a: 21,
              q: "100% 100%",
              b: 31,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "458",
              dB: "img",
              d: 61,
              k: "div",
              cQ: 1,
              c: 272,
              cR: 1,
            },
            467: {
              c: 320,
              bS: 311,
              d: 411,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#EC008C",
              L: "Solid",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 10,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "87" },
                  { p: 4, h: "88" },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            474: {
              x: "visible",
              bF: "471",
              k: "div",
              c: 305,
              d: 55,
              z: 3,
              a: 0,
              bS: 375,
              j: "absolute",
              b: -201,
            },
            481: {
              b: 16,
              z: 1,
              K: "Solid",
              c: 230,
              L: "Solid",
              d: 32,
              gg: "0",
              M: 0,
              e: 0.59361213,
              cQ: 1.4,
              N: 0,
              O: 0,
              cR: 1.4,
              g: "#FFF",
              P: 0,
              bF: "480",
              Q: 0,
              R: "#FFF",
              j: "absolute",
              S: 0,
              k: "div",
              aI: "50%",
              T: 0,
              aJ: "50%",
              aK: "50%",
              aL: "50%",
              A: "#D8DDE4",
              B: "#D8DDE4",
              bL: 12,
              C: "#D8DDE4",
              D: "#D8DDE4",
              x: "visible",
              I: "Solid",
              a: 34,
              J: "Solid",
            },
            502: {
              bI: 3,
              x: "hidden",
              bS: 343,
              bJ: 1.93143382,
              a: -7,
              j: "absolute",
              bF: "479",
              r: "inline",
              bK: 1,
              b: 172,
              d: 110,
              z: 5,
              k: "div",
              bL: 6.26378676,
              e: 1,
              c: 16,
              f: 19,
            },
            468: {
              cN: "none",
              x: "hidden",
              bS: 31,
              a: 13,
              b: 488,
              j: "absolute",
              r: "inline",
              z: 1,
              k: "div",
              c: 304,
              d: 62,
              aK: 30,
              e: 0,
              aP: "auto",
              aL: 30,
            },
            475: {
              h: "308",
              p: "no-repeat",
              x: "visible",
              a: 63,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "474",
              b: 24,
              d: 24,
              k: "div",
              c: 188,
            },
            482: {
              h: "310",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "480",
              b: 0,
              d: 67,
              k: "div",
              c: 298,
            },
            503: {
              h: "310",
              p: "no-repeat",
              x: "visible",
              a: -103,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "502",
              dB: "img",
              d: 67,
              k: "div",
              c: 298,
              e: 0,
            },
            490: {
              h: "411",
              p: "no-repeat",
              x: "visible",
              a: 5,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "489",
              b: 43,
              d: 320,
              k: "div",
              c: 320,
            },
            469: {
              c: 320,
              bS: 319,
              d: 69,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#115F6C",
              L: "Solid",
              M: 0,
              bF: "468",
              N: 0,
              A: "#ECECEC",
              j: "absolute",
              x: "visible",
              B: "#ECECEC",
              P: 0,
              O: 0,
              C: "#ECECEC",
              z: 1,
              k: "div",
              D: "#ECECEC",
              aK: 0,
              a: -8,
              aL: 0,
              b: -7,
            },
            476: {
              bI: 3,
              x: "hidden",
              a: 102,
              bJ: 1.93143382,
              b: -29,
              bS: 343,
              bF: "471",
              z: 4,
              k: "div",
              j: "absolute",
              d: 110,
              c: 16,
              bL: 6.26378676,
              f: 19,
            },
            483: {
              c: 328,
              bS: 319,
              d: 480,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 0,
              bF: "479",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              l: 0,
              D: "#D8DDE4",
              m: "#D34374",
              k: "div",
              n: "#11BBD4",
              a: -16,
              b: -9,
            },
            504: {
              bI: 11,
              x: "visible",
              bS: 343,
              bJ: 1.46047794,
              b: -29,
              j: "absolute",
              bF: "471",
              z: 5,
              bK: 1,
              a: -7,
              d: 110,
              k: "div",
              c: 305,
              e: 1,
            },
            484: {
              c: 484,
              cP: "blendmode-screen",
              bS: 383,
              d: 607,
              r: "inline",
              e: 0.5,
              gg: "1",
              bF: "479",
              aI: 60,
              j: "absolute",
              x: "visible",
              k: "div",
              aJ: 60,
              Q: 10,
              z: 2,
              aK: 60,
              R: "rgba(0, 0, 0, 0.152)",
              S: 0,
              a: -90,
              aL: 60,
              T: 0,
              b: -72,
            },
            491: {
              x: "hidden",
              bS: 55,
              a: 8,
              b: 9,
              j: "absolute",
              aJ: 20,
              z: 21,
              r: "inline",
              k: "div",
              d: 402,
              aK: 100,
              aI: 20,
              e: 1,
              c: 304,
              aL: 20,
            },
            477: {
              h: "310",
              p: "no-repeat",
              x: "visible",
              a: -103,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "476",
              b: 0,
              d: 67,
              k: "div",
              c: 298,
            },
            505: {
              h: "310",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "504",
              dB: "img",
              d: 67,
              k: "div",
              c: 298,
              e: 0,
            },
            478: {
              c: 328,
              bS: 319,
              d: 480,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 0,
              bF: "471",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              l: 0,
              D: "#D8DDE4",
              m: "#D34374",
              k: "div",
              n: "#11BBD4",
              a: -16,
              b: -210,
            },
            485: {
              h: "306",
              p: "no-repeat",
              x: "visible",
              a: 53,
              q: "100% 100%",
              b: 74,
              j: "absolute",
              r: "inline",
              z: 9,
              bF: "484",
              dB: "img",
              d: 388,
              k: "div",
              cQ: 1,
              c: 369,
              cR: 1,
            },
            492: {
              bR: 0,
              x: "hidden",
              a: 0,
              bS: 351,
              b: 201,
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "491",
              k: "div",
              d: 201,
              c: 304,
              cQ: 1,
              cR: 1,
            },
            450: {
              cN: "none",
              x: "visible",
              a: 0,
              bS: 383,
              b: 0,
              j: "absolute",
              bF: "449",
              c: 320,
              k: "div",
              z: 4,
              d: 62,
              aP: "auto",
            },
            506: {
              b: 16,
              z: 1,
              K: "Solid",
              c: 230,
              L: "Solid",
              d: 32,
              gg: "0",
              M: 0,
              e: 0.59361213,
              cQ: 1.4,
              N: 0,
              O: 0,
              cR: 1.4,
              g: "#FFF",
              P: 0,
              bF: "476",
              Q: 0,
              R: "#FFF",
              j: "absolute",
              S: 0,
              k: "div",
              aI: "50%",
              T: 0,
              aJ: "50%",
              aK: "50%",
              aL: "50%",
              A: "#D8DDE4",
              B: "#D8DDE4",
              r: "inline",
              bL: 12,
              C: "#D8DDE4",
              D: "#D8DDE4",
              x: "visible",
              I: "Solid",
              a: -69,
              J: "Solid",
            },
            479: {
              bR: 0,
              x: "hidden",
              a: 0,
              bS: 375,
              b: 0,
              j: "absolute",
              r: "inline",
              z: 4,
              bF: "470",
              k: "div",
              d: 201,
              c: 304,
              cQ: 1,
              cR: 1,
            },
            486: {
              x: "visible",
              bF: "479",
              k: "div",
              c: 305,
              d: 55,
              z: 3,
              a: 0,
              bS: 375,
              j: "absolute",
              b: 0,
            },
            493: {
              c: 328,
              bS: 319,
              d: 480,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 0,
              bF: "492",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              O: 0,
              P: 0,
              C: "#D8DDE4",
              z: 1,
              l: 0,
              D: "#D8DDE4",
              m: "#D34374",
              k: "div",
              n: "#11BBD4",
              a: -16,
              b: -210,
            },
            451: {
              cN: "none",
              x: "visible",
              a: 11,
              cA: false,
              b: 15,
              j: "absolute",
              r: "inline",
              c: 43,
              k: "div",
              z: 5,
              d: 38,
              bF: "450",
              cQ: 1,
              aP: "auto",
              bY: 1,
              bZ: 180,
              bX: false,
              cR: 1,
              cV: [],
            },
            487: {
              h: "308",
              p: "no-repeat",
              x: "visible",
              a: 63,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "486",
              b: 24,
              d: 24,
              k: "div",
              c: 188,
            },
            452: {
              h: "125",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: 2,
              j: "absolute",
              r: "inline",
              bF: "451",
              z: 5,
              dB: "img",
              d: 35,
              k: "div",
              aY: 0,
              cQ: 1,
              c: 28,
              cR: 1,
            },
            494: {
              c: 484,
              cP: "blendmode-screen",
              bS: 383,
              d: 607,
              r: "inline",
              e: 0.5,
              gg: "1",
              bF: "492",
              aI: 60,
              j: "absolute",
              x: "visible",
              k: "div",
              aJ: 60,
              Q: 10,
              z: 2,
              aK: 60,
              R: "rgba(0, 0, 0, 0.152)",
              S: 0,
              a: -90,
              aL: 60,
              T: 0,
              b: -273,
            },
            488: {
              c: 320,
              bS: 287,
              d: 69,
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#EC008C",
              L: "Solid",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 11,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "87" },
                  { p: 4, h: "88" },
                ],
              },
              k: "div",
              a: 0,
              b: 411,
            },
            453: {
              aU: 8,
              G: "#FFF",
              c: 100,
              aV: 8,
              r: "inline",
              d: 9,
              s: "Montserrat",
              t: 24,
              Y: 4,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "700",
              w: "300 m",
              bF: "450",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 6,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 48,
              b: 31,
            },
            460: {
              h: "308",
              p: "no-repeat",
              x: "visible",
              a: 63,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "458",
              b: 0,
              d: 24,
              k: "div",
              c: 188,
            },
            495: {
              h: "306",
              p: "no-repeat",
              x: "visible",
              a: 53,
              q: "100% 100%",
              b: 74,
              j: "absolute",
              r: "inline",
              z: 9,
              bF: "494",
              dB: "img",
              d: 388,
              k: "div",
              cQ: 1,
              c: 369,
              cR: 1,
            },
            489: {
              x: "visible",
              bS: 447,
              a: 0,
              b: 0,
              j: "absolute",
              cY: "0",
              c: 320,
              k: "div",
              z: 20,
              d: 480,
              r: "inline",
              e: 0,
            },
            454: {
              aU: 8,
              G: "#FFF",
              c: 204,
              aV: 8,
              r: "inline",
              d: 28,
              s: "Montserrat",
              X: 0,
              t: 12,
              Y: 15,
              u: "normal",
              Z: "break-word",
              aP: "auto",
              v: "500",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">ul. Mszczonowska 3, 05-090 Janki\n</div>',
              bF: "450",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 7,
              aS: 8,
              cN: "none",
              aT: 8,
              a: 48,
              b: 0,
            },
            461: {
              c: 484,
              bS: 383,
              d: 607,
              r: "inline",
              e: 1,
              gg: "1",
              bF: "455",
              aI: 60,
              j: "absolute",
              x: "visible",
              k: "div",
              aJ: 60,
              Q: 10,
              z: 3,
              aK: 60,
              R: "rgba(0, 0, 0, 0.152)",
              S: 0,
              a: -90,
              aL: 60,
              T: 0,
              b: -72,
            },
            496: {
              x: "visible",
              bF: "492",
              k: "div",
              c: 305,
              d: 55,
              z: 3,
              a: 0,
              bS: 375,
              j: "absolute",
              b: -201,
            },
            497: {
              h: "308",
              p: "no-repeat",
              x: "visible",
              a: 63,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "496",
              b: 24,
              d: 24,
              k: "div",
              c: 188,
            },
            455: {
              x: "hidden",
              a: 8,
              bS: 55,
              b: 9,
              j: "absolute",
              r: "inline",
              z: 12,
              aJ: 20,
              k: "div",
              d: 402,
              aK: 100,
              cQ: 0.9,
              e: 0,
              aI: 20,
              c: 304,
              aL: 20,
              cR: 0.9,
            },
            462: {
              h: "285",
              p: "no-repeat",
              x: "visible",
              a: -167,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "461",
              b: -96,
              d: 739,
              k: "div",
              c: 809,
            },
            498: {
              x: "visible",
              bF: "492",
              k: "div",
              c: 305,
              d: 110,
              z: 4,
              a: -1,
              bS: 343,
              j: "absolute",
              b: -29,
            },
          },
        },
      ],
      {},
      h,
      {
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        y: { p: 0, q: [[0, 0, 0.445, 0.05, 0.55, 0.95, 1, 1]] },
        44: { p: 0, q: [[0, 0, 0.8209, 0, 0.515, 0.955, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
