(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/Superbet",
      f = "Superbet_rich_live_320x480adaptive_June26 copy",
      g = "superbetrichlive320x480adaptivejune26copy_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\t\n\t\twindow.gotosite();\t\n}",
        identifier: "1189",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        "-2": { n: "blank.gif" },
        18: { p: 1, n: "bg.jpg", g: "980", t: "@1x" },
        10: { p: 1, n: "LIGHTNING1.png", g: "1329", t: "@1x" },
        11: { p: 1, n: "LIGHTNING2.png", g: "1327", t: "@1x" },
        0: { p: 1, n: "CTA_b.svg", g: "1220", t: "image/svg+xml" },
        12: { p: 1, n: "rocket_smoke.png", g: "1241", t: "@1x" },
        1: { p: 1, n: "logo.svg", g: "606", t: "image/svg+xml" },
        2: { p: 1, n: "headline.svg", g: "1221", t: "image/svg+xml" },
        13: { p: 1, n: "smoke_1.png", g: "1339", t: "@1x" },
        3: { p: 1, n: "booster.svg", g: "1223", t: "image/svg+xml" },
        14: { p: 1, n: "rocket.png", g: "1261", t: "@1x" },
        4: { p: 1, n: "CTA_y.svg", g: "1226", t: "image/svg+xml" },
        5: { p: 1, n: "cta_t_w.svg", g: "1228", t: "image/svg+xml" },
        15: { p: 1, n: "left.png", g: "1344", t: "@1x" },
        6: { p: 1, n: "cta_t_b.svg", g: "1230", t: "image/svg+xml" },
        16: { p: 1, n: "right.png", g: "1345", t: "@1x" },
        "-1": { n: "PIE.htc" },
        7: { p: 1, n: "coin.svg", g: "1250", t: "image/svg+xml" },
        8: { p: 1, n: "50.svg", g: "1252", t: "image/svg+xml" },
        17: { p: 1, n: "bottom.png", g: "1346", t: "@1x" },
        9: { p: 1, n: "dis.svg", g: "1321", t: "image/svg+xml" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "SCENE", o: "1", X: [0] }],
      [
        {
          o: "3",
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#00FDFF",
          L: [],
          bY: 1,
          d: 320,
          U: {
            1393: { V: { "Main Timeline": "1421" }, W: "1421", n: "coins" },
            1407: { V: { "Main Timeline": "1424" }, W: "1424", n: "lightning" },
            1379: {
              V: { "Main Timeline": "1420" },
              W: "1420",
              n: "color_change",
            },
            1377: { V: { "Main Timeline": "1419" }, W: "1419", n: "btn" },
            1401: { V: { "Main Timeline": "1423" }, W: "1423", n: "rocket" },
            1397: { V: { "Main Timeline": "1422" }, W: "1422", n: "coin" },
          },
          T: {
            1423: {
              c: "1401",
              q: false,
              z: 2,
              i: "1423",
              a: [
                { f: "c", y: 0, z: 1, i: "b", e: 29, s: 0, o: "1402" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 1.2, o: "1405" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 0.8, s: 1, o: "1406" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1, s: 1.4, o: "1406" },
                { f: "c", y: 0.29, z: 0.06, i: "e", e: 1, s: 0, o: "1405" },
                { f: "c", y: 0.29, z: 0.06, i: "e", e: 1, s: 0, o: "1406" },
                {
                  f: "c",
                  y: 1,
                  z: 0.15,
                  i: "d",
                  e: 217.826,
                  s: 217.826,
                  o: "1405",
                },
                { f: "c", y: 1, z: 0.15, i: "cQ", e: 0.8, s: 1, o: "1405" },
                { f: "c", y: 1, z: 1, i: "b", e: 0, s: 29, o: "1402" },
                { f: "c", y: 1, z: 0.15, i: "cR", e: 1.2, s: 1, o: "1405" },
                { f: "c", y: 1, z: 1, i: "cQ", e: 1, s: 0.8, o: "1406" },
                { f: "c", y: 1, z: 1, i: "cR", e: 1.4, s: 1, o: "1406" },
                { f: "c", y: 1.05, z: 0, i: "e", e: 1, s: 1, o: "1406" },
                { f: "c", y: 1.05, z: 0.1, i: "e", e: 1, s: 1, o: "1405" },
                { f: "c", y: 1.05, z: 0.25, i: "e", e: 0, s: 1, o: "1406" },
                { y: 1.15, i: "d", s: 217.826, z: 0, o: "1405", f: "c" },
                { y: 1.15, i: "cQ", s: 0.8, z: 0, o: "1405", f: "c" },
                { y: 1.15, i: "cR", s: 1.2, z: 0, o: "1405", f: "c" },
                { f: "c", y: 1.15, z: 0.15, i: "e", e: 0, s: 1, o: "1405" },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1423", p: 3, z: false, symbolOid: "1263" }] },
                  o: "1423",
                },
                { y: 2, i: "b", s: 0, z: 0, o: "1402", f: "c" },
                { y: 2, i: "cQ", s: 1, z: 0, o: "1406", f: "c" },
                { y: 2, i: "cR", s: 1.4, z: 0, o: "1406", f: "c" },
                { y: 2, i: "e", s: 0, z: 0, o: "1406", f: "c" },
                { y: 2, i: "e", s: 0, z: 0, o: "1405", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [
                {
                  D: 1,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1424",
                },
              ],
            },
            1420: {
              c: "1379",
              q: false,
              z: 2,
              i: "1420",
              a: [
                {
                  f: "i",
                  y: 0,
                  z: 0.12,
                  i: "g",
                  e: "#FFE200",
                  s: "#181020",
                  o: "1382",
                },
                { f: "c", y: 0, z: 0.12, i: "e", e: 0, s: 1, o: "1381" },
                { f: "c", y: 0.12, z: 0.18, i: "e", e: 0, s: 0, o: "1381" },
                {
                  f: "c",
                  y: 0.12,
                  z: 0.18,
                  i: "g",
                  e: "#FFE200",
                  s: "#FFE200",
                  o: "1382",
                },
                {
                  f: "c",
                  y: 1,
                  z: 0.12,
                  i: "g",
                  e: "#181020",
                  s: "#FFE200",
                  o: "1382",
                },
                { f: "c", y: 1, z: 0.12, i: "e", e: 1, s: 0, o: "1381" },
                { y: 1.12, i: "g", s: "#181020", z: 0, o: "1382", f: "i" },
                { y: 1.12, i: "e", s: 1, z: 0, o: "1381", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1420", p: 3, z: false, symbolOid: "1276" }] },
                  o: "1420",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            1424: {
              c: "1407",
              q: false,
              z: 1,
              i: "1424",
              a: [
                { f: "c", y: 0, z: 0.15, i: "d", e: 35, s: 0, o: "1410" },
                { f: "c", y: 0, z: 0.11, i: "cY", e: "1", s: "0", o: "1410" },
                { f: "c", y: 0, z: 0.16, i: "cY", e: "1", s: "0", o: "1408" },
                { f: "c", y: 0.08, z: 0.15, i: "d", e: 26, s: 0, o: "1408" },
                {
                  f: "c",
                  y: 0.11,
                  z: 0.04,
                  i: "cY",
                  e: "0",
                  s: "1",
                  o: "1410",
                },
                { y: 0.15, i: "d", s: 35, z: 0, o: "1410", f: "c" },
                { y: 0.15, i: "cY", s: "0", z: 0, o: "1410", f: "c" },
                {
                  f: "c",
                  y: 0.16,
                  z: 0.07,
                  i: "cY",
                  e: "0",
                  s: "1",
                  o: "1408",
                },
                { y: 0.23, i: "d", s: 26, z: 0, o: "1408", f: "c" },
                { y: 0.23, i: "cY", s: "0", z: 0, o: "1408", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 1,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1424", p: 3, z: false, symbolOid: "1333" }] },
                  o: "1424",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            1369: {
              q: false,
              z: 24,
              i: "1369",
              n: "bg_",
              a: [
                { f: "b", y: 0, z: 24, i: "b", e: -146, s: -300, o: "1416" },
                { f: "b", y: 0, z: 24, i: "a", e: -277, s: 225, o: "1415" },
                { f: "b", y: 0, z: 24, i: "b", e: -146, s: -300, o: "1415" },
                { f: "b", y: 20, z: 2, i: "e", e: 1, s: -1, o: "1416" },
                { f: "b", y: 22, z: 2, i: "e", e: 0, s: 1, o: "1416" },
                { y: 24, i: "a", s: 225, z: 0, o: "1416", f: "b" },
                {
                  f: "c",
                  p: 2,
                  y: 24,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1369", p: 3, z: false, symbolOid: "2" }] },
                  o: "1369",
                },
                { y: 24, i: "a", s: -277, z: 0, o: "1415", f: "c" },
                { y: 24, i: "b", s: -146, z: 0, o: "1415", f: "c" },
                { y: 24, i: "b", s: -146, z: 0, o: "1416", f: "c" },
                { y: 24, i: "e", s: 0, z: 0, o: "1416", f: "c" },
              ],
              f: 30,
              b: [],
            },
            1421: {
              c: "1393",
              q: false,
              z: 2,
              i: "1421",
              a: [
                { f: "c", y: 0, z: 1, i: "b", e: 20, s: 0, o: "1394" },
                { f: "c", y: 0, z: 1.1, i: "b", e: 71, s: 85, o: "1396" },
                { f: "c", y: 0, z: 1, i: "b", e: 89, s: 85, o: "1395" },
                { f: "c", y: 1, z: 1, i: "b", e: 0, s: 20, o: "1394" },
                { f: "c", y: 1, z: 1, i: "b", e: 85, s: 89, o: "1395" },
                { f: "c", y: 1.1, z: 0.2, i: "b", e: 85, s: 71, o: "1396" },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1421", p: 3, z: false, symbolOid: "1270" }] },
                  o: "1421",
                },
                { y: 2, i: "b", s: 0, z: 0, o: "1394", f: "c" },
                { y: 2, i: "b", s: 85, z: 0, o: "1396", f: "c" },
                { y: 2, i: "b", s: 85, z: 0, o: "1395", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              j: {
                0: [
                  [-49, 463, -49, 463, 103, 435, 165, 354],
                  [165, 354, 244, 251, 164, 125, 164, 125],
                ],
              },
              q: false,
              z: 3.16,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { f: "q", y: 0, z: 1, i: "e", e: 1, s: 0, o: "1376" },
                { f: "q", y: 0, z: 1, i: "cQ", e: 1, s: 0.8, o: "1376" },
                { f: "q", y: 0, z: 1, i: "cR", e: 1, s: 0.8, o: "1376" },
                { y: 0, i: "cY", s: "0", z: 0, o: "1417", f: "c" },
                { f: "q", y: 0, z: 0.21, i: "b", e: 0, s: 42, o: "1386" },
                { y: 0, i: "a", s: 1, z: 0, o: "1390", f: "c" },
                { f: "c", y: 0, z: 0.12, i: "e", e: 1, s: 0, o: "1389" },
                { y: 0, i: "b", s: 0, z: 0, o: "1390", f: "c" },
                { f: "c", y: 0, z: 1.06, i: "cQ", e: 1, s: 1, o: "1389" },
                { f: "c", y: 0, z: 1.06, i: "cR", e: 1, s: 1, o: "1389" },
                { f: "c", y: 0, z: 1.03, i: "cQ", e: 1, s: 1, o: "1387" },
                { f: "c", y: 0, z: 1.03, i: "cR", e: 1, s: 1, o: "1387" },
                {
                  f: "c",
                  p: 2,
                  y: 0.05,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1369", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "c", y: 0.05, z: 0.11, i: "e", e: 1, s: 0, o: "1387" },
                { f: "c", y: 0.09, z: 0.12, i: "e", e: 1, s: 0, o: "1388" },
                { y: 0.12, i: "e", s: 1, z: 0, o: "1389", f: "c" },
                {
                  o: "1392",
                  y: 0.16,
                  z: 1.04,
                  i: "a",
                  e: 51,
                  a: "0",
                  f: "p",
                  s: -162,
                },
                {
                  o: "1392",
                  y: 0.16,
                  z: 1.04,
                  i: "b",
                  e: -21.5,
                  a: "0",
                  f: "p",
                  s: 316.5,
                },
                { f: "v", y: 0.16, z: 1.04, i: "cQ", e: 0.85, s: 1, o: "1392" },
                { f: "v", y: 0.16, z: 1.04, i: "cR", e: 0.85, s: 1, o: "1392" },
                { f: "c", y: 0.16, z: 0.15, i: "e", e: 1, s: 0, o: "1392" },
                { y: 0.16, i: "e", s: 1, z: 0, o: "1387", f: "c" },
                { y: 0.21, i: "b", s: 0, z: 0, o: "1386", f: "c" },
                { y: 0.21, i: "e", s: 1, z: 0, o: "1388", f: "c" },
                { y: 1, i: "cR", s: 1, z: 0, o: "1376", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "1376", f: "c" },
                { y: 1, i: "e", s: 1, z: 0, o: "1376", f: "c" },
                { f: "p", y: 1.01, z: 0.15, i: "a", e: 24, s: 24, o: "1388" },
                { f: "p", y: 1.01, z: 0.15, i: "b", e: 290, s: 169, o: "1388" },
                { y: 1.01, i: "e", s: 1, z: 0, o: "1392", f: "c" },
                { f: "p", y: 1.03, z: 0.15, i: "a", e: 6, s: 52, o: "1387" },
                { f: "p", y: 1.03, z: 0.15, i: "b", e: 216, s: 119, o: "1387" },
                { f: "c", y: 1.03, z: 0.15, i: "cQ", e: 0.9, s: 1, o: "1387" },
                { f: "c", y: 1.03, z: 0.15, i: "cR", e: 0.9, s: 1, o: "1387" },
                {
                  f: "p",
                  y: 1.06,
                  z: 0.15,
                  i: "a",
                  e: -3.195,
                  s: 58.805,
                  o: "1389",
                },
                { f: "p", y: 1.06, z: 0.15, i: "b", e: 177, s: 74, o: "1389" },
                { f: "c", y: 1.06, z: 0.15, i: "cQ", e: 0.7, s: 1, o: "1389" },
                { f: "c", y: 1.06, z: 0.15, i: "cR", e: 0.7, s: 1, o: "1389" },
                { f: "c", y: 1.06, z: 0.14, i: "e", e: 1, s: 0, o: "1393" },
                { y: 1.16, i: "a", s: 24, z: 0, o: "1388", f: "c" },
                { y: 1.16, i: "b", s: 290, z: 0, o: "1388", f: "c" },
                { f: "c", y: 1.16, z: 0.14, i: "e", e: 1, s: 0, o: "1397" },
                { y: 1.18, i: "a", s: 6, z: 0, o: "1387", f: "c" },
                { y: 1.18, i: "cQ", s: 0.9, z: 0, o: "1387", f: "c" },
                { y: 1.18, i: "cR", s: 0.9, z: 0, o: "1387", f: "c" },
                { y: 1.18, i: "b", s: 216, z: 0, o: "1387", f: "c" },
                { y: 1.2, i: "a", s: 51, z: 0, o: "1392", f: "c" },
                { y: 1.2, i: "cQ", s: 0.85, z: 0, o: "1392", f: "c" },
                { y: 1.2, i: "cR", s: 0.85, z: 0, o: "1392", f: "c" },
                { y: 1.2, i: "b", s: -21.5, z: 0, o: "1392", f: "c" },
                { y: 1.2, i: "e", s: 1, z: 0, o: "1393", f: "c" },
                { y: 1.21, i: "a", s: -3.195, z: 0, o: "1389", f: "c" },
                { y: 1.21, i: "cQ", s: 0.7, z: 0, o: "1389", f: "c" },
                { y: 1.21, i: "cR", s: 0.7, z: 0, o: "1389", f: "c" },
                { y: 1.21, i: "b", s: 177, z: 0, o: "1389", f: "c" },
                { f: "c", y: 2, z: 0.15, i: "e", e: 1, s: 0, o: "1385" },
                { y: 2, i: "e", s: 1, z: 0, o: "1397", f: "c" },
                { y: 2.15, i: "e", s: 1, z: 0, o: "1385", f: "c" },
              ],
              f: 30,
              b: [
                {
                  D: 2,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1423",
                },
                {
                  D: 2,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 1,
                  b: "1419",
                },
                {
                  D: 2,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 1.06,
                  b: "1421",
                },
                {
                  D: 2,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 1.16,
                  b: "1422",
                },
              ],
            },
            1422: {
              c: "1397",
              q: false,
              z: 2,
              i: "1422",
              a: [
                { f: "c", y: 0, z: 1, i: "f", e: 45, s: 0, o: "1400" },
                { f: "c", y: 0, z: 1, i: "cQ", e: 1.05, s: 1, o: "1400" },
                { f: "c", y: 0, z: 1, i: "cR", e: 1.05, s: 1, o: "1400" },
                { f: "c", y: 0.15, z: 0.08, i: "cR", e: 1.05, s: 1, o: "1399" },
                { f: "c", y: 0.15, z: 0.08, i: "cQ", e: 1.05, s: 1, o: "1399" },
                { f: "c", y: 0.23, z: 1.07, i: "cQ", e: 1, s: 1.05, o: "1399" },
                { f: "c", y: 0.23, z: 1.07, i: "cR", e: 1, s: 1.05, o: "1399" },
                { f: "c", y: 1, z: 1, i: "f", e: 0, s: 45, o: "1400" },
                { f: "c", y: 1, z: 1, i: "cR", e: 1, s: 1.05, o: "1400" },
                { f: "c", y: 1, z: 1, i: "cQ", e: 1, s: 1.05, o: "1400" },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1422", p: 3, z: false, symbolOid: "1256" }] },
                  o: "1422",
                },
                { y: 2, i: "f", s: 0, z: 0, o: "1400", f: "c" },
                { y: 2, i: "cR", s: 1, z: 0, o: "1399", f: "c" },
                { y: 2, i: "cQ", s: 1, z: 0, o: "1399", f: "c" },
                { y: 2, i: "cR", s: 1, z: 0, o: "1400", f: "c" },
                { y: 2, i: "cQ", s: 1, z: 0, o: "1400", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            1419: {
              c: "1377",
              q: false,
              z: 2,
              i: "1419",
              a: [
                { f: "c", y: 0, z: 0.08, i: "cR", e: 1.05, s: 1, o: "1378" },
                { f: "c", y: 0, z: 0.08, i: "cQ", e: 1.05, s: 1, o: "1378" },
                { f: "c", y: 0.08, z: 0.07, i: "cR", e: 1, s: 1.05, o: "1378" },
                { f: "c", y: 0.08, z: 0.07, i: "cQ", e: 1, s: 1.05, o: "1378" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 1, o: "1378" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 1, o: "1378" },
                { f: "c", y: 1, z: 0.08, i: "cR", e: 1.05, s: 1, o: "1378" },
                { f: "c", y: 1, z: 0.08, i: "cQ", e: 1.05, s: 1, o: "1378" },
                { f: "c", y: 1.08, z: 0.07, i: "cR", e: 1, s: 1.05, o: "1378" },
                { f: "c", y: 1.08, z: 0.07, i: "cQ", e: 1, s: 1.05, o: "1378" },
                { y: 1.15, i: "cR", s: 1, z: 0, o: "1378", f: "c" },
                { y: 1.15, i: "cQ", s: 1, z: 0, o: "1378", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "1419", p: 3, z: false, symbolOid: "1234" }] },
                  o: "1419",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [
                {
                  D: 2,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "1420",
                },
              ],
            },
          },
          bZ: 180,
          O: [
            "1416",
            "1415",
            "1417",
            "1390",
            "1375",
            "1412",
            "1391",
            "1418",
            "1386",
            "1414",
            "1413",
            "1389",
            "1387",
            "1388",
            "1407",
            "1411",
            "1406",
            "1403",
            "1402",
            "1401",
            "1392",
            "1400",
            "1398",
            "1397",
            "1393",
            "1394",
            "1409",
            "1410",
            "1399",
            "1408",
            "1385",
            "1405",
            "1395",
            "1396",
            "1404",
            "1382",
            "1383",
            "1380",
            "1379",
            "1378",
            "1377",
            "1376",
            "1381",
            "1384",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            1377: {
              x: "visible",
              cA: false,
              a: 0,
              b: 0,
              j: "absolute",
              bF: "1376",
              c: 186,
              k: "div",
              bY: 1,
              d: 40,
              z: 1,
              bX: false,
              bZ: 180,
              cV: [],
            },
            1389: {
              h: "606",
              p: "no-repeat",
              x: "visible",
              a: 58.805,
              q: "100% 100%",
              b: 74,
              j: "absolute",
              r: "inline",
              bF: "1386",
              z: 5,
              dB: "img",
              d: 37,
              k: "div",
              cQ: 1,
              e: 0,
              c: 202,
              cR: 1,
            },
            1408: {
              x: "hidden",
              cY: "0",
              k: "div",
              c: 36,
              d: 0,
              z: 5,
              a: 51,
              bF: "1407",
              j: "absolute",
              b: 102,
            },
            1385: {
              h: "1321",
              p: "no-repeat",
              x: "visible",
              a: 18,
              q: "100% 100%",
              b: 387,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "1375",
              dB: "img",
              d: 39,
              k: "div",
              c: 281,
              e: 0,
            },
            1397: {
              x: "visible",
              a: 59,
              cA: false,
              b: -1,
              j: "absolute",
              bF: "1392",
              c: 125,
              k: "div",
              bY: 1,
              d: 125,
              z: 1,
              bX: false,
              e: 0,
              bZ: 180,
              cV: [],
            },
            1404: {
              x: "visible",
              tY: 0.07,
              a: -1,
              b: 123,
              j: "absolute",
              bF: "1402",
              z: 4,
              k: "div",
              c: 266,
              d: 155,
              cQ: 1,
              cR: 1,
              tX: 0.72,
            },
            1381: {
              h: "1228",
              p: "no-repeat",
              x: "visible",
              a: 53,
              q: "100% 100%",
              b: 15,
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "1379",
              dB: "img",
              d: 10,
              k: "div",
              c: 80,
              e: 1,
            },
            1393: {
              x: "visible",
              a: -3,
              cA: false,
              b: 24,
              j: "absolute",
              bF: "1392",
              c: 231,
              k: "div",
              bY: 1,
              d: 186,
              z: 2,
              bX: false,
              e: 0,
              bZ: 180,
              cV: [],
            },
            1400: {
              h: "1250",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "1398",
              dB: "img",
              d: 125,
              k: "div",
              cQ: 1,
              c: 125,
              f: 0,
              cR: 1,
            },
            1412: {
              aD: {
                a: [{ b: "640", p: 8, z: false, symbolOid: "2", J: true }],
              },
              x: "hidden",
              a: 0,
              bS: 383,
              b: 0,
              j: "absolute",
              z: 16,
              k: "div",
              c: 320,
              d: 480,
              cQ: 1,
              aC: {
                a: [
                  {
                    b: "kTimelineDefaultIdentifier",
                    p: 8,
                    z: true,
                    symbolOid: "2",
                    J: false,
                  },
                ],
              },
              cR: 1,
            },
            1416: {
              p: "no-repeat",
              b: -300,
              c: 417,
              q: "100% 100%",
              bS: 319,
              d: 548,
              r: "inline",
              cY: "0",
              e: -1,
              cQ: 5.1,
              f: -9,
              cR: 5.1,
              h: "980",
              aY: 0,
              bF: "1414",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 4,
              tX: 0.45,
              a: -277,
              tY: 0.5,
            },
            1378: {
              x: "visible",
              cQ: 1,
              k: "div",
              cR: 1,
              c: 186,
              d: 40,
              z: 2,
              a: 0,
              bF: "1377",
              j: "absolute",
              b: 0,
            },
            1409: {
              h: "1327",
              p: "no-repeat",
              x: "visible",
              a: -51,
              q: "100% 100%",
              b: -55,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "1408",
              dB: "img",
              d: 136,
              k: "div",
              cQ: 0.3,
              c: 132,
              cR: 0.3,
            },
            1386: {
              x: "visible",
              b: 42,
              k: "div",
              c: 320,
              d: 232,
              z: 27,
              r: "inline",
              e: 1,
              bS: 375,
              j: "absolute",
              a: 0,
            },
            1398: {
              x: "visible",
              k: "div",
              c: 125,
              d: 125,
              z: 2,
              a: 0,
              j: "absolute",
              bF: "1397",
              b: 0,
            },
            1405: {
              h: "1339",
              p: "no-repeat",
              tY: 0.26,
              a: 1,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "1404",
              b: -39,
              z: 2,
              d: 217.826,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 286,
              cR: 1.2,
              tX: 0.65,
            },
            1382: {
              p: "no-repeat",
              c: 184,
              q: "100% 100%",
              d: 39,
              I: "None",
              J: "None",
              K: "None",
              g: "#181020",
              L: "None",
              M: 0,
              bF: "1379",
              N: 0,
              A: "#C11B80",
              j: "absolute",
              x: "visible",
              B: "#C11B80",
              P: 0,
              O: 0,
              C: "#C11B80",
              z: 4,
              aJ: 30,
              D: "#C11B80",
              aK: 30,
              k: "div",
              aI: 30,
              a: 1,
              aL: 30,
              b: 0,
            },
            1394: {
              h: "1344",
              p: "no-repeat",
              x: "visible",
              a: 59,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 6,
              bF: "1393",
              dB: "img",
              d: 97,
              k: "div",
              cQ: 1,
              c: 62,
              cR: 1,
            },
            1401: {
              x: "visible",
              cA: false,
              a: -41,
              b: -1,
              j: "absolute",
              bF: "1392",
              c: 286,
              k: "div",
              bY: 1,
              d: 307,
              z: 3,
              bX: false,
              bZ: 180,
              cV: [],
            },
            1413: {
              x: "hidden",
              a: 0,
              bS: 63,
              b: 42,
              j: "absolute",
              aJ: 60,
              z: 3,
              k: "div",
              r: "inline",
              d: 417,
              aK: 60,
              aI: 60,
              c: 320,
              aL: 60,
            },
            1390: {
              x: "visible",
              k: "div",
              c: 319,
              d: 480,
              z: 28,
              r: "inline",
              a: 1,
              bS: 63,
              j: "absolute",
              b: 0,
            },
            1417: {
              c: 318,
              bS: 319,
              d: 478,
              r: "inline",
              cY: "0",
              e: 0,
              J: "None",
              I: "None",
              K: "None",
              g: "#00F900",
              L: "None",
              aP: "pointer",
              M: 0,
              w: "",
              N: 0,
              A: "#B3B3B3",
              j: "absolute",
              x: "visible",
              B: "#B3B3B3",
              P: 0,
              O: 0,
              C: "#B3B3B3",
              z: 81,
              dB: "button",
              D: "#B3B3B3",
              aA: { a: [{ p: 4, h: "1189" }] },
              k: "div",
              a: 1,
              b: 1,
            },
            1379: {
              x: "visible",
              cA: false,
              a: 0,
              b: 0,
              j: "absolute",
              bF: "1378",
              c: 186,
              k: "div",
              bY: 1,
              d: 40,
              z: 1,
              bX: false,
              bZ: 180,
              cV: [],
            },
            1375: {
              x: "visible",
              k: "div",
              c: 318,
              d: 480,
              z: 21,
              a: 1,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            1387: {
              h: "1223",
              p: "no-repeat",
              x: "visible",
              a: 52,
              q: "100% 100%",
              b: 119,
              j: "absolute",
              r: "inline",
              bF: "1386",
              z: 4,
              dB: "img",
              d: 34,
              k: "div",
              cQ: 1,
              e: 0,
              c: 215,
              cR: 1,
            },
            1399: {
              h: "1252",
              p: "no-repeat",
              x: "visible",
              a: 22,
              q: "100% 100%",
              b: 43,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "1398",
              dB: "img",
              d: 49,
              k: "div",
              cQ: 1,
              c: 87,
              cR: 1,
            },
            1406: {
              h: "1241",
              p: "no-repeat",
              tY: 0.5,
              a: 11,
              q: "100% 100%",
              x: "visible",
              j: "absolute",
              r: "inline",
              bF: "1404",
              b: -124,
              z: 1,
              d: 279,
              dB: "img",
              cQ: 1,
              e: 0,
              k: "div",
              c: 260,
              cR: 1.4,
              tX: 0.68,
            },
            1383: {
              h: "1220",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "none",
              z: 3,
              bF: "1379",
              b: 0,
              d: 40,
              k: "div",
              c: 186,
            },
            1395: {
              h: "1346",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 85,
              j: "absolute",
              r: "inline",
              z: 7,
              bF: "1393",
              dB: "img",
              d: 101,
              k: "div",
              cQ: 1,
              c: 219,
              cR: 1,
            },
            1402: {
              x: "visible",
              k: "div",
              c: 286,
              d: 307,
              z: 2,
              a: 0,
              j: "absolute",
              bF: "1401",
              b: 0,
            },
            1414: {
              c: 320,
              bS: 447,
              d: 419,
              r: "inline",
              e: 1,
              gg: "1",
              g: "#891114",
              bF: "1413",
              aI: 60,
              j: "absolute",
              x: "visible",
              k: "div",
              aJ: 60,
              Q: 10,
              z: 1,
              aK: 60,
              R: "rgba(0, 0, 0, 0.152)",
              S: 0,
              a: 0,
              aL: 60,
              T: 0,
              b: -2,
            },
            1391: {
              x: "visible",
              bF: "1390",
              k: "div",
              c: 260,
              d: 322,
              z: 3,
              a: 59,
              bS: 371,
              j: "absolute",
              b: 0,
            },
            1418: {
              c: 368,
              d: 419,
              I: "Solid",
              J: "Solid",
              K: "Solid",
              g: "#891114",
              L: "Solid",
              M: 0,
              bF: "1414",
              N: 0,
              A: "#C11B80",
              x: "visible",
              j: "absolute",
              B: "#C11B80",
              P: 0,
              O: 0,
              C: "#C11B80",
              z: 2,
              k: "div",
              D: "#C11B80",
              a: -32,
              b: 0,
            },
            1410: {
              x: "hidden",
              cY: "0",
              k: "div",
              c: 21,
              d: 0,
              z: 7,
              a: 125,
              bF: "1407",
              j: "absolute",
              b: 47,
            },
            1376: {
              x: "visible",
              a: 66,
              b: 438,
              j: "absolute",
              bF: "1375",
              c: 186,
              k: "div",
              z: 2,
              d: 40,
              cQ: 0.8,
              e: 0,
              cR: 0.8,
            },
            1388: {
              h: "1221",
              p: "no-repeat",
              x: "visible",
              a: 24,
              q: "100% 100%",
              b: 169,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "1386",
              dB: "img",
              d: 62,
              k: "div",
              c: 272,
              e: 0,
            },
            1407: {
              x: "visible",
              cA: false,
              a: 112,
              b: -27,
              j: "absolute",
              bF: "1402",
              c: 205,
              k: "div",
              bY: 1,
              d: 183,
              z: 6,
              bX: false,
              bZ: 180,
              cV: [],
            },
            1384: {
              h: "1230",
              p: "no-repeat",
              x: "visible",
              a: 53,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "1379",
              b: 15,
              d: 10,
              k: "div",
              c: 80,
            },
            1396: {
              h: "1345",
              p: "no-repeat",
              x: "visible",
              a: 207,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 5,
              bF: "1393",
              b: 85,
              d: 24,
              k: "div",
              c: 24,
            },
            1403: {
              h: "1261",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "1402",
              dB: "img",
              d: 307,
              k: "div",
              cQ: 1,
              c: 286,
              cR: 1,
            },
            1380: {
              h: "1226",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "none",
              z: 2,
              bF: "1379",
              b: 0,
              d: 40,
              k: "div",
              c: 186,
            },
            1392: {
              x: "visible",
              tY: 0.5,
              a: -162,
              b: 316.5,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "1391",
              k: "div",
              d: 293,
              c: 226,
              cQ: 1,
              e: 0,
              cR: 1,
              tX: 0.5,
            },
            1415: {
              p: "no-repeat",
              b: -300,
              c: 417,
              q: "100% 100%",
              bS: 319,
              d: 548,
              r: "inline",
              e: 1,
              cQ: 5.1,
              f: -9,
              cR: 5.1,
              h: "980",
              aY: 0,
              bF: "1414",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 3,
              tX: 0.45,
              a: 225,
              tY: 0.5,
            },
            1411: {
              h: "1329",
              p: "no-repeat",
              x: "visible",
              a: -56,
              q: "100% 100%",
              b: -47,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "1410",
              dB: "img",
              d: 134,
              k: "div",
              cQ: 0.3,
              c: 136,
              cR: 0.3,
            },
          },
        },
      ],
      {},
      h,
      {
        i: { p: 0, q: [[0, 0, 0.6, -0.28, 0.735, 0.045, 1, 1]] },
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        q: { p: 0, q: [[0, 0, 0.165, 0.84, 0.44, 1, 1, 1]] },
        v: { p: 0, q: [[0, 0, 0.455, 0.03, 0.515, 0.955, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
