(function () {
  (function m() {
    function k(a, b, c, d) {
      var e = !1;
      null == window[a] &&
        (null == window[b]
          ? ((window[b] = []),
            window[b].push(m),
            (a = document.getElementsByTagName("head")[0]),
            (b = document.createElement("script")),
            (e = l),
            false == !0 && (e = ""),
            (b.type = "text/javascript"),
            "" != d &&
              ((b.integrity = d), b.setAttribute("crossorigin", "anonymous")),
            (b.src = e + "/" + c),
            a.appendChild(b))
          : window[b].push(m),
        (e = !0));
      return e;
    }
    var l = "../resources/Lindt_Bunny",
      f = "Lindt_bunny_320x480_adaptive_geo_withPrice",
      g = "lindtbunny320x480adaptivegeowithprice_hype_container";
    if (false == !1)
      try {
        for (
          var c = document.getElementsByTagName("script"), a = 0;
          a < c.length;
          a++
        ) {
          var d = c[a].src,
            b =
              null != d
                ? d.indexOf(
                    "/script.js",
                  )
                : -1;
          if (-1 != b) {
            l = d.substr(0, b);
            break;
          }
        }
      } catch (p) {}
    c =
      null == navigator.userAgentData &&
      navigator.userAgent.match(/MSIE (\d+\.\d+)/);
    c = parseFloat(c && c[1]) || null;
    d =
      !0 == (null != window.HYPE_778F || null != window.HYPE_dtl_778F) ||
      false == !0 ||
      (null != c && 10 > c);
    a = !0 == d ? "HYPE-778.full.min.js" : "HYPE-778.thin.min.js";
    c = !0 == d ? "F" : "T";
    d = d ? "" : "";
    if (
      false == !1 &&
      ((a = k("HYPE_778" + c, "HYPE_dtl_778" + c, a, d)),
      false == !0 &&
        (a =
          a ||
          k("HYPE_w_778", "HYPE_wdtl_778", "HYPE-778.waypoints.min.js", "")),
      false == !0 &&
        (a = a || k("Matter", "HYPE_pdtl_778", "HYPE-778.physics.min.js", "")),
      a)
    )
      return;
    d = window.HYPE.documents;
    if (null != d[f]) {
      b = 1;
      a = f;
      do f = "" + a + "-" + b++;
      while (null != d[f]);
      for (
        var e = document.getElementsByTagName("div"), b = !1, a = 0;
        a < e.length;
        a++
      )
        if (e[a].id == g && null == e[a].getAttribute("HYP_dn")) {
          var b = 1,
            h = g;
          do g = "" + h + "-" + b++;
          while (null != document.getElementById(g));
          e[a].id = g;
          b = !0;
          break;
        }
      if (!1 == b) return;
    }
    b = [];
    b = [
      {
        name: "action1",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action1();\n}",
        identifier: "5",
      },
      {
        name: "action2",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.action2();\n}",
        identifier: "6",
      },
      {
        name: "gotosite",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotosite();\n}",
        identifier: "7",
      },
      {
        name: "gotomap",
        source:
          "function(hypeDocument, element, event) {\t\n\twindow.gotomap();\n}",
        identifier: "8",
      },
      {
        name: "sound123",
        source:
          'function(hypeDocument, element, event) {\t\n\t\t\tvar video123 = hypeDocument.getElementById("video123");\n\tvar krest = hypeDocument.getElementById("krestm");\n\tvar on = hypeDocument.getElementById("onm");\n\t\n\t\n\tif (video123.muted) {\n\t\tvideo123.muted = false;\n\t\tkrest.style.display = "none";\n\t\ton.style.display = "block";\n\t\tregisterUnMuteEvent();\n\t} else {\n\t\tvideo123.muted = true;\n\t\tkrest.style.display = "block";\n\t\ton.style.display = "none";\n\t\tregisterMuteEvent();\n\t}\n\t\n\treturn false;\n\t\n}',
        identifier: "9",
      },
      {
        name: "VolumeUp123",
        source:
          'function(hypeDocument, element, event) {\t\n\t\t\tvar video123 = hypeDocument.getElementById("video123");\n\tvideo123.volume = 0.5;\n\tvideo123.muted = true;\n}',
        identifier: "10",
      },
    ];
    e = {};
    h = {};
    for (a = 0; a < b.length; a++)
      try {
        ((h[b[a].identifier] = b[a].name),
          (e[b[a].name] = eval("(function(){return " + b[a].source + "})();")));
      } catch (n) {
        (window.console && window.console.log(n),
          (e[b[a].name] = function () {}));
      }
    c = new window["HYPE_778" + c](
      f,
      g,
      {
        "-2": { n: "blank.gif" },
        18: { p: 1, n: "biedronce.svg", g: "105", t: "image/svg+xml" },
        10: { p: 1, n: "icon_location.svg", g: "207", t: "image/svg+xml" },
        19: { p: 1, n: "gold_block.svg", g: "276", t: "image/svg+xml" },
        11: { p: 1, n: "headline_PL.svg", g: "209", t: "image/svg+xml" },
        0: { p: 1, n: "white_pin.svg", g: "37", t: "image/svg+xml" },
        12: { p: 1, n: "bunny_bell.png", g: "211", t: "@1x" },
        1: { p: 1, n: "krest.svg", g: "95", t: "image/svg+xml" },
        20: { p: 1, n: "legal_price.svg", g: "277", t: "image/svg+xml" },
        2: { p: 1, n: "on.svg", g: "104", t: "image/svg+xml" },
        13: { p: 1, n: "body_.png", g: "215", t: "@1x" },
        3: { p: 1, n: "mute.svg", g: "110", t: "image/svg+xml" },
        21: { p: 1, n: "red_block.svg", g: "278", t: "image/svg+xml" },
        14: { p: 1, n: "grass_3.png", g: "187", t: "@1x" },
        4: { n: "video_PL.mp4", g: "114", t: "video/mp4" },
        5: { p: 1, n: "bunny_body.png", g: "195", t: "@1x" },
        15: { p: 1, n: "grass_1.png", g: "191", t: "@1x" },
        6: { p: 1, n: "bg_.jpg", g: "199", t: "@1x" },
        16: { p: 1, n: "bunny_eye.png", g: "193", t: "@1x" },
        7: { p: 1, n: "wing_r.png", g: "201", t: "@1x" },
        "-1": { n: "PIE.htc" },
        8: { p: 1, n: "wing_l.png", g: "203", t: "@1x" },
        17: { p: 1, n: "btn_PL.svg", g: "213", t: "image/svg+xml" },
        9: { p: 1, n: "logo_-1.png", g: "205", t: "@1x" },
      },
      l,
      [
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:700&subset=latin' rel='stylesheet' type='text/css'>",
        "<link href='https://fonts.googleapis.com/css?family=Montserrat:500&subset=latin' rel='stylesheet' type='text/css'>",
      ],
      e,
      [{ n: "Main", o: "1", X: [0] }],
      [
        {
          o: "3",
          A: { a: [{ p: 4, h: "10" }] },
          p: "600px",
          a: 100,
          Y: 320,
          Z: 480,
          b: 100,
          cA: false,
          c: "#FFF",
          L: [],
          bY: 1,
          d: 320,
          U: {
            333: { V: { "Main Timeline": "353" }, W: "353", n: "butterfly" },
            323: { V: { "Main Timeline": "351" }, W: "351", n: "butterfly" },
            347: { V: { "Main Timeline": "354" }, W: "354", n: "icon" },
            328: { V: { "Main Timeline": "352" }, W: "352", n: "butterfly" },
          },
          T: {
            353: {
              c: "333",
              q: false,
              z: 0.18,
              i: "353",
              a: [
                { f: "c", y: 0, z: 0.09, i: "aY", e: 50, s: 0, o: "337" },
                { f: "c", y: 0, z: 0.09, i: "aY", e: 44, s: 0, o: "336" },
                { f: "c", y: 0.09, z: 0.09, i: "aY", e: 0, s: 50, o: "337" },
                { f: "c", y: 0.09, z: 0.09, i: "aY", e: 0, s: 44, o: "336" },
                {
                  f: "c",
                  p: 2,
                  y: 0.18,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "353", p: 3, z: false, symbolOid: "266" }] },
                  o: "353",
                },
                { y: 0.18, i: "aY", s: 0, z: 0, o: "337", f: "c" },
                { y: 0.18, i: "aY", s: 0, z: 0, o: "336", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            352: {
              c: "328",
              q: false,
              z: 0.18,
              i: "352",
              a: [
                { f: "c", y: 0, z: 0.09, i: "aY", e: 50, s: 0, o: "332" },
                { f: "c", y: 0, z: 0.09, i: "aY", e: 44, s: 0, o: "331" },
                { f: "c", y: 0.09, z: 0.09, i: "aY", e: 0, s: 50, o: "332" },
                { f: "c", y: 0.09, z: 0.09, i: "aY", e: 0, s: 44, o: "331" },
                {
                  f: "c",
                  p: 2,
                  y: 0.18,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "352", p: 3, z: false, symbolOid: "266" }] },
                  o: "352",
                },
                { y: 0.18, i: "aY", s: 0, z: 0, o: "332", f: "c" },
                { y: 0.18, i: "aY", s: 0, z: 0, o: "331", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            244: {
              q: false,
              z: 2.15,
              i: "244",
              n: "button",
              a: [
                { f: "c", y: 0, z: 0.15, i: "cQ", e: 0.9, s: 1, o: "313" },
                { f: "c", y: 0, z: 0.15, i: "cR", e: 0.9, s: 1, o: "313" },
                { f: "c", y: 0.15, z: 0.15, i: "cQ", e: 1, s: 0.9, o: "313" },
                { f: "c", y: 0.15, z: 0.15, i: "cR", e: 1, s: 0.9, o: "313" },
                { y: 1, i: "cR", s: 1, z: 0, o: "313", f: "c" },
                { y: 1, i: "cQ", s: 1, z: 0, o: "313", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 2.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "244", p: 3, z: false, symbolOid: "2" }] },
                  o: "244",
                },
              ],
              f: 30,
              b: [],
            },
            351: {
              c: "323",
              q: false,
              z: 0.18,
              i: "351",
              a: [
                { f: "c", y: 0, z: 0.09, i: "aY", e: 50, s: 0, o: "327" },
                { f: "c", y: 0, z: 0.09, i: "aY", e: 44, s: 0, o: "326" },
                { f: "c", y: 0.09, z: 0.09, i: "aY", e: 0, s: 50, o: "327" },
                { f: "c", y: 0.09, z: 0.09, i: "aY", e: 0, s: 44, o: "326" },
                {
                  f: "c",
                  p: 2,
                  y: 0.18,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "351", p: 3, z: false, symbolOid: "266" }] },
                  o: "351",
                },
                { y: 0.18, i: "aY", s: 0, z: 0, o: "327", f: "c" },
                { y: 0.18, i: "aY", s: 0, z: 0, o: "326", f: "c" },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            283: {
              q: false,
              z: 8,
              i: "283",
              n: "price",
              a: [
                { f: "p", y: 0, z: 0.15, i: "e", e: 0, s: 1, o: "313" },
                { f: "p", y: 0, z: 0.2, i: "e", e: 1, s: 0, o: "311" },
                { f: "p", y: 0, z: 0.2, i: "e", e: 1, s: 0, o: "310" },
                { f: "p", y: 0, z: 0.2, i: "e", e: 1, s: 0, o: "312" },
                { f: "c", y: 0.15, z: 3.15, i: "e", e: 0, s: 0, o: "313" },
                { f: "c", y: 0.2, z: 3.1, i: "e", e: 1, s: 1, o: "311" },
                { f: "c", y: 0.2, z: 3.1, i: "e", e: 1, s: 1, o: "310" },
                { f: "c", y: 0.2, z: 3.1, i: "e", e: 1, s: 1, o: "312" },
                { f: "c", y: 1.2, z: 0.1, i: "cR", e: 1.1, s: 1, o: "310" },
                { f: "c", y: 1.2, z: 0.1, i: "cQ", e: 1.1, s: 1, o: "310" },
                { f: "c", y: 2, z: 0.1, i: "cR", e: 1, s: 1.1, o: "310" },
                { f: "c", y: 2, z: 0.1, i: "cQ", e: 1, s: 1.1, o: "310" },
                { f: "c", y: 2.1, z: 0.1, i: "cR", e: 1.1, s: 1, o: "311" },
                { f: "c", y: 2.1, z: 0.1, i: "cQ", e: 1.1, s: 1, o: "311" },
                { y: 2.1, i: "cR", s: 1, z: 0, o: "310", f: "c" },
                { y: 2.1, i: "cQ", s: 1, z: 0, o: "310", f: "c" },
                { f: "c", y: 2.2, z: 0.1, i: "cR", e: 1, s: 1.1, o: "311" },
                { f: "c", y: 2.2, z: 0.1, i: "cQ", e: 1, s: 1.1, o: "311" },
                { y: 3, i: "cR", s: 1, z: 0, o: "311", f: "c" },
                { y: 3, i: "cQ", s: 1, z: 0, o: "311", f: "c" },
                { f: "c", y: 4, z: 0.15, i: "e", e: 1, s: 0, o: "313" },
                { f: "c", y: 4, z: 0.15, i: "e", e: 0, s: 1, o: "311" },
                { f: "c", y: 4, z: 0.15, i: "e", e: 0, s: 1, o: "310" },
                { f: "c", y: 4, z: 0.15, i: "e", e: 0, s: 1, o: "312" },
                { y: 4.15, i: "e", s: 1, z: 0, o: "313", f: "c" },
                { y: 4.15, i: "e", s: 0, z: 0, o: "311", f: "c" },
                { y: 4.15, i: "e", s: 0, z: 0, o: "310", f: "c" },
                { y: 4.15, i: "e", s: 0, z: 0, o: "312", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 8,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ i: 0, b: "283", p: 9, symbolOid: "2" }] },
                  o: "283",
                },
              ],
              f: 30,
              b: [],
            },
            kTimelineDefaultIdentifier: {
              j: {
                3: [
                  [208, 302, 208, 302, 185, 258, 144, 261],
                  [144, 261, 106, 263, 88, 306, 88, 306],
                ],
                1: [
                  [281, 345, 281, 345, 261, 308, 270, 239],
                  [270, 239, 276, 191, 306, 160, 311, 102],
                  [311, 102, 316, 49, 281, -23, 281, -23],
                ],
                2: [
                  [194, 363, 194, 363, 171, 302, 180, 233],
                  [180, 233, 186, 185, 176, -20, 176, -20],
                ],
                0: [
                  [28, 351, 28, 351, 57, 316, 49, 247],
                  [49, 247, 43, 198, 25, 173, 15, 115],
                  [15, 115, 5, 55, 56, -28, 56, -28],
                ],
              },
              q: false,
              z: 15.01,
              i: "kTimelineDefaultIdentifier",
              n: "Main Timeline",
              a: [
                { y: 0, p: 1, i: "Video Track", z: 15.01, o: "307", f: "c" },
                { f: "c", y: 0, z: 1, i: "d", e: 400, s: 400, o: "306" },
                { f: "c", y: 0, z: 1, i: "b", e: 0, s: 0, o: "306" },
                { f: "c", y: 0, z: 1, i: "a", e: 50, s: 50, o: "306" },
                { f: "c", y: 0, z: 1, i: "c", e: 220, s: 220, o: "306" },
                { f: "v", y: 0, z: 0.21, i: "e", e: 1, s: 0, o: "341" },
                {
                  f: "c",
                  p: 2,
                  y: 0,
                  z: 4,
                  i: "ActionHandler",
                  e: {
                    a: [
                      { b: "259", p: 3, z: false, symbolOid: "2" },
                      { b: "244", p: 3, z: false, symbolOid: "2" },
                    ],
                  },
                  s: { a: [{ b: "246", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
                { f: "v", y: 0, z: 0.21, i: "b", e: 278, s: 294, o: "341" },
                { f: "c", y: 0, z: 0.15, i: "e", e: 1, s: 0, o: "328" },
                { o: "328", y: 0, z: 2, i: "a", e: 33, a: "0", f: "c", s: 5 },
                {
                  o: "328",
                  y: 0,
                  z: 2,
                  i: "b",
                  e: -50.5,
                  a: "0",
                  f: "c",
                  s: 328.5,
                },
                { f: "v", y: 0.06, z: 0.24, i: "e", e: 1, s: 0, o: "340" },
                { f: "v", y: 0.06, z: 0.24, i: "b", e: 283, s: 299, o: "340" },
                {
                  o: "323",
                  y: 0.1,
                  z: 1.3,
                  i: "a",
                  e: 258,
                  a: "1",
                  f: "c",
                  s: 258,
                },
                { f: "c", y: 0.1, z: 0.15, i: "e", e: 1, s: 0, o: "323" },
                {
                  o: "323",
                  y: 0.1,
                  z: 1.3,
                  i: "b",
                  e: -45.5,
                  a: "1",
                  f: "c",
                  s: 322.5,
                },
                { f: "c", y: 0.15, z: 0.2, i: "e", e: 1, s: 0, o: "319" },
                { y: 0.15, i: "e", s: 1, z: 0, o: "328", f: "c" },
                { y: 0.21, i: "b", s: 278, z: 0, o: "341", f: "c" },
                { y: 0.21, i: "e", s: 1, z: 0, o: "341", f: "c" },
                { y: 0.25, i: "e", s: 1, z: 0, o: "323", f: "c" },
                { f: "c", y: 1, z: 1.15, i: "d", e: 160, s: 413, o: "307" },
                { f: "c", y: 1, z: 1.15, i: "c", e: 284, s: 734, o: "307" },
                { f: "c", y: 1, z: 0.29, i: "d", e: 154, s: 400, o: "306" },
                { f: "c", y: 1, z: 0.29, i: "c", e: 282, s: 220, o: "306" },
                { f: "c", y: 1, z: 1.15, i: "a", e: 0, s: -225, o: "307" },
                { f: "c", y: 1, z: 0.29, i: "a", e: 19, s: 50, o: "306" },
                {
                  o: "333",
                  y: 1,
                  z: 2,
                  i: "a",
                  e: 153,
                  a: "2",
                  f: "c",
                  s: 171,
                },
                { f: "c", y: 1, z: 1.15, i: "b", e: 0, s: -7, o: "307" },
                { f: "c", y: 1, z: 1.2, i: "b", e: 24, s: 0, o: "306" },
                {
                  o: "333",
                  y: 1,
                  z: 2,
                  i: "b",
                  e: -42.5,
                  a: "2",
                  f: "c",
                  s: 340.5,
                },
                { f: "c", y: 1, z: 0.15, i: "e", e: 1, s: 0, o: "333" },
                { y: 1, i: "e", s: 1, z: 0, o: "340", f: "c" },
                { y: 1, i: "b", s: 283, z: 0, o: "340", f: "c" },
                { y: 1.05, i: "e", s: 1, z: 0, o: "319", f: "c" },
                {
                  o: "314",
                  y: 1.1,
                  z: 0.3,
                  i: "a",
                  e: -72,
                  a: "3",
                  f: "c",
                  s: 48,
                },
                {
                  o: "314",
                  y: 1.1,
                  z: 0.3,
                  i: "b",
                  e: 106.56550598,
                  a: "3",
                  f: "c",
                  s: 102.56550598,
                },
                { f: "c", y: 1.1, z: 0.3, i: "e", e: 1, s: 0, o: "314" },
                { y: 1.15, i: "e", s: 1, z: 0, o: "333", f: "c" },
                { y: 1.29, i: "d", s: 154, z: 0, o: "306", f: "c" },
                { y: 1.29, i: "c", s: 282, z: 0, o: "306", f: "c" },
                { y: 1.29, i: "a", s: 19, z: 0, o: "306", f: "c" },
                { y: 2, i: "a", s: 33, z: 0, o: "328", f: "c" },
                { y: 2, i: "b", s: -50.5, z: 0, o: "328", f: "c" },
                { f: "c", y: 2.1, z: 0.15, i: "f", e: 30, s: 0, o: "318" },
                { y: 2.1, i: "a", s: -72, z: 0, o: "314", f: "c" },
                { y: 2.1, i: "a", s: 258, z: 0, o: "323", f: "c" },
                { y: 2.1, i: "b", s: 107, z: 0, o: "314", f: "c" },
                { y: 2.1, i: "e", s: 1, z: 0, o: "314", f: "c" },
                { y: 2.1, i: "b", s: -45.5, z: 0, o: "323", f: "c" },
                { y: 2.15, i: "d", s: 160, z: 0, o: "307", f: "c" },
                { y: 2.15, i: "c", s: 284, z: 0, o: "307", f: "c" },
                { y: 2.15, i: "a", s: 0, z: 0, o: "307", f: "c" },
                { y: 2.15, i: "b", s: 0, z: 0, o: "307", f: "c" },
                { y: 2.2, i: "b", s: 24, z: 0, o: "306", f: "c" },
                { f: "c", y: 2.25, z: 0.08, i: "f", e: 0, s: 30, o: "318" },
                { f: "c", y: 2.25, z: 0.2, i: "e", e: 1, s: 0, o: "320" },
                { f: "c", y: 2.28, z: 0.05, i: "cR", e: 0.5, s: 1, o: "316" },
                { f: "c", y: 2.28, z: 0.05, i: "f", e: -15, s: 0, o: "316" },
                { y: 3, i: "a", s: 153, z: 0, o: "333", f: "c" },
                { y: 3, i: "b", s: -42.5, z: 0, o: "333", f: "c" },
                { f: "c", y: 3.03, z: 0.08, i: "cR", e: 1, s: 0.5, o: "316" },
                { f: "c", y: 3.03, z: 0.08, i: "f", e: 0, s: -15, o: "316" },
                { y: 3.03, i: "f", s: 0, z: 0, o: "318", f: "c" },
                { f: "c", y: 3.05, z: 0.2, i: "e", e: 1, s: 0, o: "321" },
                { y: 3.11, i: "cR", s: 1, z: 0, o: "316", f: "c" },
                { y: 3.11, i: "f", s: 0, z: 0, o: "316", f: "c" },
                { f: "c", y: 3.15, z: 0.2, i: "e", e: 1, s: 0, o: "313" },
                { y: 3.15, i: "e", s: 1, z: 0, o: "320", f: "c" },
                { y: 3.25, i: "e", s: 1, z: 0, o: "321", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 4,
                  z: 3,
                  i: "ActionHandler",
                  e: { a: [{ b: "283", p: 3, z: false, symbolOid: "2" }] },
                  s: {
                    a: [
                      { b: "259", p: 3, z: false, symbolOid: "2" },
                      { b: "244", p: 3, z: false, symbolOid: "2" },
                    ],
                  },
                  o: "kTimelineDefaultIdentifier",
                },
                { y: 4.05, i: "e", s: 1, z: 0, o: "313", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 7,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "283", p: 3, z: false, symbolOid: "2" }] },
                  o: "kTimelineDefaultIdentifier",
                },
              ],
              f: 30,
              b: [
                {
                  D: 1.15,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "354",
                },
                {
                  D: 0.18,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0,
                  b: "352",
                },
                {
                  D: 0.18,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 0.1,
                  b: "351",
                },
                {
                  D: 0.18,
                  H: true,
                  E: true,
                  z: false,
                  F: 0,
                  G: 0,
                  C: 1,
                  b: "353",
                },
              ],
            },
            354: {
              c: "347",
              q: false,
              z: 1.15,
              i: "354",
              a: [
                { f: "y", y: 0, z: 1.03, i: "aY", e: 360, s: 0, o: "348" },
                { y: 1.03, i: "aY", s: 360, z: 0, o: "348", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 1.15,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "354", p: 3, z: false, symbolOid: "220" }] },
                  o: "354",
                },
              ],
              n: "Main Timeline",
              f: 30,
              b: [],
            },
            246: {
              q: false,
              z: 5,
              i: "246",
              n: "geo_change",
              a: [
                { f: "c", y: 1.15, z: 0.15, i: "e", e: 0, s: 1, o: "344" },
                { f: "c", y: 2, z: 0.15, i: "e", e: 1, s: 0, o: "349" },
                { f: "c", y: 2, z: 2, i: "e", e: 0, s: 0, o: "344" },
                { f: "c", y: 2.15, z: 1, i: "e", e: 1, s: 1, o: "349" },
                { f: "c", y: 3.15, z: 0.15, i: "e", e: 0, s: 1, o: "349" },
                { f: "c", y: 4, z: 0.15, i: "e", e: 1, s: 0, o: "344" },
                { y: 4, i: "e", s: 0, z: 0, o: "349", f: "c" },
                { y: 4.15, i: "e", s: 1, z: 0, o: "344", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 5,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ i: 1, b: "246", p: 9, symbolOid: "2" }] },
                  o: "246",
                },
              ],
              f: 30,
              b: [],
            },
            259: {
              q: false,
              z: 3,
              i: "259",
              n: "bunny_idle",
              a: [
                { f: "c", y: 0, z: 0.15, i: "f", e: 48, s: 0, o: "318" },
                { f: "c", y: 0.15, z: 0.15, i: "f", e: 0, s: 48, o: "318" },
                { f: "c", y: 0.27, z: 0.05, i: "cR", e: 0.5, s: 1, o: "316" },
                { f: "c", y: 0.27, z: 0.05, i: "f", e: -15, s: 0, o: "316" },
                { f: "c", y: 1, z: 0.08, i: "f", e: 0, s: 0, o: "318" },
                { f: "c", y: 1.02, z: 0.08, i: "cR", e: 1, s: 0.5, o: "316" },
                { f: "c", y: 1.02, z: 0.08, i: "f", e: 0, s: -15, o: "316" },
                { y: 1.08, i: "f", s: 0, z: 0, o: "318", f: "c" },
                { y: 1.1, i: "cR", s: 1, z: 0, o: "316", f: "c" },
                { y: 1.1, i: "f", s: 0, z: 0, o: "316", f: "c" },
                {
                  f: "c",
                  p: 2,
                  y: 3,
                  z: 0,
                  i: "ActionHandler",
                  s: { a: [{ b: "259", p: 3, z: false, symbolOid: "2" }] },
                  o: "259",
                },
              ],
              f: 30,
              b: [],
            },
          },
          bZ: 180,
          O: [
            "296",
            "332",
            "329",
            "328",
            "327",
            "324",
            "323",
            "337",
            "334",
            "333",
            "330",
            "331",
            "336",
            "325",
            "326",
            "335",
            "297",
            "322",
            "308",
            "339",
            "300",
            "299",
            "295",
            "294",
            "303",
            "307",
            "306",
            "301",
            "304",
            "302",
            "305",
            "316",
            "318",
            "317",
            "315",
            "314",
            "320",
            "321",
            "340",
            "341",
            "310",
            "309",
            "311",
            "313",
            "319",
            "312",
            "298",
            "350",
            "342",
            "338",
            "348",
            "347",
            "343",
            "346",
            "344",
            "349",
            "345",
          ],
          n: "Untitled Layout",
          _: 0,
          v: {
            337: {
              h: "203",
              p: "no-repeat",
              x: "visible",
              tY: 0.7,
              q: "100% 100%",
              a: 1,
              j: "absolute",
              r: "inline",
              bF: "334",
              b: 0,
              z: 2,
              d: 37,
              dB: "img",
              aY: 0,
              k: "div",
              c: 18,
              tX: 0.94,
            },
            344: {
              x: "visible",
              k: "div",
              c: 243,
              d: 48,
              z: 3,
              e: 1,
              a: 38,
              j: "absolute",
              bF: "343",
              b: -4,
            },
            302: {
              h: "104",
              p: "no-repeat",
              x: "visible",
              a: 23,
              q: "100% 100%",
              b: 12,
              j: "absolute",
              bF: "301",
              r: "inline",
              cY: "1",
              z: 7,
              d: 19,
              dB: "img",
              cQ: 0.5,
              e: 0.8,
              k: "div",
              c: 13,
              cR: 0.5,
            },
            338: {
              x: "visible",
              k: "div",
              c: 320,
              d: 73,
              z: 14,
              r: "inline",
              a: 0,
              bS: 18,
              j: "absolute",
              b: 407,
            },
            310: {
              h: "278",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "309",
              z: 1,
              dB: "img",
              d: 45,
              k: "div",
              cQ: 1,
              e: 0,
              c: 60,
              cR: 1,
            },
            345: {
              aU: 8,
              G: "#FFF",
              c: 107,
              aV: 8,
              r: "inline",
              d: 9,
              s: "Montserrat",
              t: 18,
              Y: 8,
              u: "normal",
              Z: "break-word",
              v: "700",
              i: "distance",
              w: "300 m",
              bF: "344",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 1,
              aS: 8,
              aT: 8,
              a: 0,
              b: 23,
            },
            303: {
              c: 90,
              d: 90,
              r: "inline",
              I: "None",
              e: 0.5,
              J: "None",
              cQ: 0.35,
              K: "None",
              cR: 0.35,
              g: "#C29643",
              L: "None",
              M: 0,
              bF: "301",
              N: 0,
              j: "absolute",
              x: "visible",
              O: 0,
              B: "#FFF",
              P: 0,
              A: "#FFF",
              C: "#FFF",
              z: 4,
              aJ: "50%",
              D: "#FFF",
              aK: "50%",
              k: "div",
              aI: "50%",
              a: -22,
              aL: "50%",
              b: -24,
            },
            339: {
              x: "visible",
              b: -406,
              k: "div",
              c: 320,
              d: 479,
              z: 1,
              r: "inline",
              a: 0,
              bS: 383,
              j: "absolute",
              bF: "338",
            },
            304: {
              h: "110",
              p: "no-repeat",
              x: "visible",
              a: 8,
              q: "100% 100%",
              b: 5,
              j: "absolute",
              r: "inline",
              bF: "301",
              z: 5,
              dB: "img",
              d: 31,
              k: "div",
              cQ: 0.5,
              e: 0.8,
              c: 23,
              aP: "pointer",
              cR: 0.5,
              bD: "auto",
            },
            311: {
              h: "276",
              p: "no-repeat",
              x: "visible",
              a: 65,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              bF: "309",
              z: 2,
              dB: "img",
              d: 45,
              k: "div",
              cQ: 1,
              e: 0,
              c: 60,
              cR: 1,
            },
            346: {
              aU: 8,
              G: "#FFF",
              c: 227,
              aV: 8,
              r: "inline",
              d: 9,
              s: "Montserrat",
              X: 0,
              t: 11,
              Y: 11,
              u: "normal",
              Z: "break-word",
              v: "500",
              i: "address",
              w: '<div style="display:flex;align-items: center;width:100%;height:100%;">Z\u0142ota 59, 00-120 Warszawa</div>',
              bF: "344",
              j: "absolute",
              x: "visible",
              k: "div",
              y: "preserve",
              z: 2,
              aS: 8,
              aT: 8,
              a: 0,
              b: 0,
            },
            347: {
              x: "visible",
              cA: false,
              a: 0,
              b: 0,
              j: "absolute",
              bF: "343",
              c: 34,
              k: "div",
              bY: 1,
              d: 41,
              z: 1,
              bX: false,
              bZ: 180,
              cV: [],
            },
            305: {
              h: "95",
              p: "no-repeat",
              x: "visible",
              a: 23,
              q: "100% 100%",
              b: 15,
              j: "absolute",
              r: "inline",
              bF: "301",
              z: 6,
              dB: "img",
              d: 13,
              k: "div",
              cQ: 0.5,
              e: 0.8,
              c: 13,
              aP: "pointer",
              cR: 0.5,
            },
            312: {
              p: "no-repeat",
              c: 114,
              q: "100% 100%",
              d: 7,
              r: "inline",
              e: 0,
              gg: "1",
              h: "277",
              bF: "309",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 3,
              Q: 1,
              R: "rgba(0, 0, 0, 0.800)",
              S: 0,
              a: 6,
              T: 0,
              b: 54,
            },
            348: {
              h: "207",
              p: "no-repeat",
              x: "visible",
              a: 0,
              q: "100% 100%",
              b: 0,
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "347",
              dB: "img",
              d: 41,
              k: "div",
              aY: 0,
              c: 34,
            },
            306: {
              c: 220,
              d: 400,
              I: "Solid",
              cQ: 1,
              J: "Solid",
              K: "Solid",
              cR: 1,
              L: "Solid",
              aP: "auto",
              M: 3,
              bF: "300",
              N: 3,
              A: "#C29643",
              x: "hidden",
              j: "absolute",
              B: "#C29643",
              O: 3,
              P: 3,
              C: "#C29643",
              z: 1,
              aJ: 33,
              D: "#C29643",
              aK: 33,
              k: "div",
              aI: 33,
              cN: "none",
              a: 50,
              aL: 33,
              b: 0,
            },
            313: {
              h: "213",
              p: "no-repeat",
              x: "visible",
              a: 143,
              q: "100% 100%",
              b: 327,
              j: "absolute",
              r: "inline",
              bF: "308",
              z: 7,
              dB: "img",
              d: 34,
              k: "div",
              cQ: 1,
              e: 0,
              c: 155,
              cR: 1,
            },
            320: {
              h: "209",
              p: "no-repeat",
              x: "visible",
              a: 143,
              q: "100% 100%",
              b: 213,
              j: "absolute",
              r: "inline",
              z: 9,
              bF: "308",
              dB: "img",
              d: 12,
              k: "div",
              c: 160,
              e: 0,
            },
            349: {
              h: "105",
              p: "no-repeat",
              x: "visible",
              a: 38,
              q: "100% 100%",
              b: 4,
              j: "absolute",
              r: "inline",
              z: 2,
              bF: "343",
              dB: "img",
              d: 32,
              k: "div",
              c: 298,
              e: 0,
            },
            307: {
              cN: "none",
              dA: "1",
              aR: "1",
              x: "visible",
              bE: "114",
              a: -225,
              b: -7,
              j: "absolute",
              bF: "306",
              z: 1,
              aO: "0",
              k: "video",
              d: 413,
              c: 734,
              cQ: 1,
              aP: "auto",
              cR: 1,
              aQ: "1",
              aH: "1",
            },
            314: {
              x: "visible",
              tY: 0.5,
              a: 48,
              b: 102.566,
              j: "absolute",
              bF: "308",
              z: 2,
              k: "div",
              c: 320,
              d: 398.869,
              bP: "NO",
              cQ: 0.5,
              e: 0,
              f: 0,
              cR: 0.5,
              tX: 0.5,
            },
            321: {
              h: "205",
              p: "no-repeat",
              x: "visible",
              a: 133,
              q: "100% 100%",
              b: 238,
              j: "absolute",
              r: "inline",
              z: 8,
              bF: "308",
              dB: "img",
              d: 83,
              k: "div",
              c: 176,
              e: 0,
            },
            294: {
              c: 320,
              bS: 63,
              d: 480,
              r: "inline",
              I: "Solid",
              J: "Solid",
              K: "Solid",
              L: "Solid",
              M: 3,
              N: 3,
              A: "#C29643",
              j: "absolute",
              x: "hidden",
              B: "#C29643",
              O: 3,
              P: 3,
              C: "#C29643",
              z: 12,
              k: "div",
              D: "#C29643",
              aK: 25,
              a: -3,
              aL: 25,
              b: -2,
            },
            308: {
              x: "visible",
              k: "div",
              c: 320,
              d: 480,
              z: 15,
              r: "inline",
              a: 0,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            315: {
              x: "visible",
              tY: 0.89,
              a: 0,
              b: 0,
              j: "absolute",
              bF: "314",
              c: 320,
              k: "div",
              z: 1,
              d: 398.869,
              f: 0,
              tX: 0.5,
            },
            322: {
              x: "visible",
              k: "div",
              c: 323,
              d: 483,
              z: 17,
              a: 0,
              bS: 383,
              j: "absolute",
              b: 0,
            },
            295: {
              x: "visible",
              b: 0,
              k: "div",
              c: 320,
              d: 482,
              z: 1,
              r: "inline",
              a: 0,
              bS: 447,
              j: "absolute",
              bF: "294",
            },
            323: {
              x: "visible",
              tY: 0.5,
              a: 258,
              b: 322,
              j: "absolute",
              bF: "322",
              c: 46,
              k: "div",
              z: 2,
              d: 45,
              bY: 1,
              cA: false,
              e: 0,
              bZ: 180,
              bX: false,
              cV: [],
              tX: 0.5,
            },
            330: {
              h: "215",
              p: "no-repeat",
              x: "visible",
              a: 18,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "329",
              b: 19,
              d: 10.3333,
              k: "div",
              c: 6.66667,
            },
            309: {
              x: "visible",
              k: "div",
              c: 125,
              d: 61,
              z: 10,
              a: 160,
              j: "absolute",
              bF: "308",
              b: 321,
            },
            316: {
              p: "no-repeat",
              tY: 0.38,
              b: 0,
              q: "100% 100%",
              c: 320,
              d: 398.869,
              r: "inline",
              cQ: 1,
              f: 0,
              gW: 0,
              cR: 1,
              h: "193",
              aY: 0,
              uB: 0,
              bF: "315",
              j: "absolute",
              x: "visible",
              k: "div",
              dB: "img",
              z: 3,
              tX: 0.2,
              a: 0,
              bR: 0,
            },
            296: {
              h: "199",
              p: "no-repeat",
              x: "visible",
              a: -310,
              q: "100% 100%",
              b: -86,
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "295",
              dB: "img",
              d: 667,
              k: "div",
              cQ: 1,
              c: 940,
              cR: 1,
            },
            317: {
              h: "195",
              p: "no-repeat",
              x: "visible",
              a: 0,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 1,
              bF: "315",
              b: 0,
              d: 398.869,
              k: "div",
              c: 320,
            },
            324: {
              x: "visible",
              k: "div",
              c: 50.3333,
              d: 43,
              z: 11,
              r: "inline",
              a: 0,
              j: "absolute",
              bF: "323",
              b: 0,
            },
            331: {
              h: "201",
              p: "no-repeat",
              x: "visible",
              tY: 0.36,
              q: "100% 100%",
              a: 19,
              j: "absolute",
              r: "inline",
              bF: "329",
              b: 17,
              z: 1,
              d: 28,
              dB: "img",
              aY: 0,
              k: "div",
              c: 28.3333,
              f: 0,
              tX: 0,
            },
            297: {
              c: 318,
              bS: 319,
              d: 478,
              r: "inline",
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#E8EBED",
              L: "Solid",
              aP: "pointer",
              M: 1,
              w: "",
              N: 1,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 1,
              O: 1,
              C: "#D8DDE4",
              z: 18,
              dB: "button",
              D: "#D8DDE4",
              aA: {
                a: [
                  { p: 4, h: "6" },
                  { p: 4, h: "7" },
                ],
              },
              k: "div",
              a: 0,
              b: 0,
            },
            318: {
              h: "211",
              p: "no-repeat",
              x: "visible",
              tY: 0.6,
              q: "100% 100%",
              b: 0,
              a: 0,
              r: "inline",
              j: "absolute",
              bF: "315",
              z: 2,
              d: 398.869,
              dB: "img",
              k: "div",
              c: 320,
              f: 0,
              tX: 0.12,
            },
            325: {
              h: "215",
              p: "no-repeat",
              x: "visible",
              a: 18,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "324",
              b: 19,
              d: 10.3333,
              k: "div",
              c: 6.66667,
            },
            332: {
              h: "203",
              p: "no-repeat",
              x: "visible",
              tY: 0.7,
              q: "100% 100%",
              a: 1,
              j: "absolute",
              r: "inline",
              bF: "329",
              b: 0,
              z: 2,
              d: 37,
              dB: "img",
              aY: 0,
              k: "div",
              c: 18,
              tX: 0.94,
            },
            298: {
              c: 320,
              bS: 287,
              d: 80,
              r: "inline",
              I: "Solid",
              e: 0,
              J: "Solid",
              K: "Solid",
              g: "#C29643",
              L: "Solid",
              aP: "pointer",
              M: 0,
              N: 0,
              A: "#C29643",
              j: "absolute",
              x: "visible",
              B: "#C29643",
              P: 0,
              O: 0,
              C: "#C29643",
              z: 22,
              dB: "button",
              D: "#C29643",
              aA: {
                a: [
                  { p: 4, h: "5" },
                  { p: 4, h: "8" },
                ],
              },
              k: "div",
              a: 0,
              b: 401,
            },
            319: {
              h: "191",
              p: "no-repeat",
              x: "visible",
              a: -210,
              q: "100% 100%",
              b: 352.566,
              j: "absolute",
              r: "inline",
              bF: "308",
              z: 3,
              dB: "img",
              d: 134,
              k: "div",
              cQ: 1,
              e: 0,
              c: 865,
              cR: 1,
            },
            326: {
              h: "201",
              p: "no-repeat",
              x: "visible",
              tY: 0.36,
              q: "100% 100%",
              a: 19,
              j: "absolute",
              r: "inline",
              bF: "324",
              b: 17,
              z: 1,
              d: 28,
              dB: "img",
              aY: 0,
              k: "div",
              c: 28.3333,
              f: 0,
              tX: 0,
            },
            333: {
              x: "visible",
              tY: 0.5,
              a: 171,
              b: 340,
              j: "absolute",
              bF: "322",
              z: 1,
              k: "div",
              c: 46,
              d: 45,
              bY: 1,
              cQ: 0.9,
              e: 0,
              bZ: 180,
              cA: false,
              bX: false,
              cR: 0.9,
              cV: [],
              tX: 0.5,
            },
            340: {
              h: "191",
              p: "no-repeat",
              x: "visible",
              a: -274,
              q: "100% 100%",
              b: 299,
              j: "absolute",
              r: "inline",
              bF: "339",
              z: 4,
              dB: "img",
              d: 134,
              k: "div",
              cQ: 1,
              e: 0,
              c: 865,
              cR: 1,
            },
            299: {
              cN: "none",
              x: "visible",
              bS: 383,
              a: -3,
              b: 0,
              j: "absolute",
              r: "inline",
              c: 325,
              k: "div",
              z: 13,
              d: 476,
              aP: "auto",
              e: 1,
            },
            327: {
              h: "203",
              p: "no-repeat",
              x: "visible",
              tY: 0.7,
              q: "100% 100%",
              a: 1,
              j: "absolute",
              r: "inline",
              bF: "324",
              b: 0,
              z: 2,
              d: 37,
              dB: "img",
              aY: 0,
              k: "div",
              c: 18,
              tX: 0.94,
            },
            334: {
              x: "visible",
              k: "div",
              c: 50.3333,
              d: 43,
              z: 11,
              r: "inline",
              a: 0,
              j: "absolute",
              bF: "333",
              b: 0,
            },
            341: {
              h: "187",
              p: "no-repeat",
              x: "visible",
              a: -274,
              q: "100% 100%",
              b: 294,
              j: "absolute",
              r: "inline",
              bF: "339",
              z: 1,
              dB: "img",
              d: 171,
              k: "div",
              cQ: 1,
              e: 0,
              c: 1064,
              cR: 1,
            },
            342: {
              x: "visible",
              k: "div",
              c: 320,
              d: 73,
              z: 16,
              r: "inline",
              a: 0,
              bS: 18,
              j: "absolute",
              b: 407,
            },
            300: {
              cN: "none",
              x: "visible",
              tY: 0.5,
              bS: 119,
              b: 0,
              j: "absolute",
              bF: "299",
              r: "inline",
              a: 0,
              z: 1,
              d: 476,
              k: "div",
              cQ: 1,
              e: 1,
              c: 325,
              aP: "auto",
              cR: 1,
              tX: 0.5,
            },
            328: {
              b: 328.5,
              c: 46,
              d: 45,
              e: 0,
              cQ: 0.8,
              cA: false,
              cR: 0.8,
              aY: 180,
              bF: "322",
              j: "absolute",
              x: "visible",
              k: "div",
              bX: false,
              z: 3,
              cV: [],
              bY: 1,
              tX: 0.5,
              a: 5,
              bZ: 180,
              tY: 0.5,
            },
            335: {
              h: "215",
              p: "no-repeat",
              x: "visible",
              a: 18,
              dB: "img",
              q: "100% 100%",
              j: "absolute",
              r: "inline",
              z: 3,
              bF: "334",
              b: 19,
              d: 10.3333,
              k: "div",
              c: 6.66667,
            },
            336: {
              h: "201",
              p: "no-repeat",
              x: "visible",
              tY: 0.36,
              q: "100% 100%",
              a: 19,
              j: "absolute",
              r: "inline",
              bF: "334",
              b: 17,
              z: 1,
              d: 28,
              dB: "img",
              aY: 0,
              k: "div",
              c: 28.3333,
              f: 0,
              tX: 0,
            },
            343: {
              x: "visible",
              bF: "342",
              k: "div",
              c: 281,
              d: 48,
              z: 8,
              a: 22,
              bS: 383,
              j: "absolute",
              b: 17,
            },
            301: {
              cN: "auto",
              x: "visible",
              bS: 375,
              dB: "button",
              b: 25,
              j: "absolute",
              bF: "300",
              z: 2,
              r: "none",
              a: 226,
              d: 43,
              aA: { a: [{ p: 4, h: "9" }] },
              cQ: 1,
              e: 1,
              k: "div",
              c: 48,
              aP: "pointer",
              cR: 1,
            },
            329: {
              x: "visible",
              k: "div",
              c: 50.3333,
              d: 43,
              z: 11,
              r: "inline",
              a: 0,
              j: "absolute",
              bF: "328",
              b: 0,
            },
            350: {
              c: 320,
              bS: 31,
              d: 73,
              r: "inline",
              I: "None",
              J: "None",
              K: "None",
              g: "#C1994B",
              L: "None",
              M: 0,
              bF: "342",
              N: 0,
              A: "#D8DDE4",
              j: "absolute",
              x: "visible",
              B: "#D8DDE4",
              P: 0,
              O: 0,
              C: "#D8DDE4",
              z: 3,
              k: "div",
              D: "#D8DDE4",
              a: 0,
              b: 0,
            },
          },
        },
      ],
      {},
      h,
      {
        p: { p: 0, q: [[0, 0, 0.25, 0.46, 0.45, 0.94, 1, 1]] },
        v: { p: 0, q: [[0, 0, 0.455, 0.03, 0.515, 0.955, 1, 1]] },
        y: { p: 0, q: [[0, 0, 0.445, 0.05, 0.55, 0.95, 1, 1]] },
      },
      null,
      false,
      false,
      -1,
      true,
      true,
      false,
      true,
      true,
    );
    d[f] = c.API;
    document.getElementById(g).setAttribute("HYP_dn", f);
    c.z_o(this.body);
  })();
})();
